<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ahl-3-12a – 日本語で読む IB数学</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-12b.html" rel="next">
<link href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3d27ed94b0b15b9bda3c32201c09d63a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "一致なし",
    "search-matching-documents-text": "一致した文書",
    "search-copy-link-title": "検索へのリンクをコピー",
    "search-hide-matches-text": "追加の検索結果を非表示",
    "search-more-match-text": "追加の検索結果",
    "search-more-matches-text": "追加の検索結果",
    "search-clear-button-title": "消去",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "検索",
    "search-label": "サーチ"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-LQBB7M9VZ0"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-LQBB7M9VZ0', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"ja"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">日本語で読む IB数学</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="サーチ"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="ナビゲーションを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../ai-sl/index.html" aria-current="page"> 
<span class="menu-text">AI SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ai-hl/index.html"> 
<span class="menu-text">AI HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../glossary-ai.html"> 
<span class="menu-text">英日対訳表（AI）</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/"> 
<span class="menu-text">学習サロン SELF</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-7.html">Topic 3 — Geometry and trigonometry</a></li><li class="breadcrumb-item"><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-12a.html">AHL 3.12a — Kinematics: constant velocity</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IB数学 AI HL</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 1 — Number and algebra</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.9 — Laws of logarithms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.10 — Rational exponents</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.11 — The sum of an infinite geometric sequence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-12a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.12a — Complex numbers in Cartesian form</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-12b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.12b — The complex plane</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.13 — Polar and exponential form</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.14 — Matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.15 — Eigenvalues and eigenvectors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 2 — Functions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/02-functions/ahl-2-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 2.7 — Composite and inverse functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/02-functions/ahl-2-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 2.8 — Transformations of graphs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/02-functions/ahl-2-9a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 2.9a — Half-life, natural log and sinusoidal models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/02-functions/ahl-2-9b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 2.9b — Logistic and piecewise models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/02-functions/ahl-2-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 2.10 — Log–log and semi-log scaling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Topic 3 — Geometry and trigonometry</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.7 — Radian measure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.8 — The unit circle and identities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.9 — Geometric transformations in two dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-10a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.10a — Vectors: the basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-10b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.10b — Magnitude, position and unit vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.11 — Vector equation of a line</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-12a.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">AHL 3.12a — Kinematics: constant velocity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-12b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.12b — Kinematics: variable velocity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-13a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.13a — The scalar product</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-13b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.13b — The vector product</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.14 — Graph theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.15 — Adjacency matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.16 — Tree and cycle algorithms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 4 — Statistics and probability</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.12 — Data collection and χ² categorisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.13 — Non-linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.14 — Linear transformation of a single random variable</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.15 — Linear combinations of normal variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.16 — Confidence intervals for the mean of a normal population</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.17 — The Poisson distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18a — Critical values and critical regions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18b — Tests for a mean, a proportion and ρ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18c — Type I and Type II errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.19 — Transition matrices</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 5 — Calculus</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-9a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.9a — Derivatives of the standard functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-9b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.9b — The chain, product and quotient rules, and related rates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.10 — The second derivative</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-11a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.11a — Standard integrals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-11b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.11b — Integration by inspection and substitution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-12a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.12a — Area enclosed by a curve and the axes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-12b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.12b — Volumes of revolution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.13 — Kinematics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.14 — Setting up a differential equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.15 — Slope fields</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16a — Euler’s method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16b — Euler’s method for coupled systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17a — Phase portraits: real eigenvalues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17b — Phase portraits: complex eigenvalues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.18 — Second order differential equations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">付録</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-sl/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SL の39項目（AI SL）</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../glossary-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">英日対訳表（AI）</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">このページの内容</h2>
   
  <ul>
  <li><a href="#sec-ahl-3-12a" id="toc-sec-ahl-3-12a" class="nav-link active" data-scroll-target="#sec-ahl-3-12a">AHL 3.12a — Kinematics: constant velocity（等速度の運動）</a>
  <ul class="collapse">
  <li><a href="#the-idea" id="toc-the-idea" class="nav-link" data-scroll-target="#the-idea">The idea</a>
  <ul class="collapse">
  <li><a href="#idea" id="toc-idea" class="nav-link" data-scroll-target="#idea">1. <span class="math inline">\(\mathbf{r} = \mathbf{r}_0 + \mathbf{v}t\)</span></a></li>
  <li><a href="#velocity" id="toc-velocity" class="nav-link" data-scroll-target="#velocity">2. <span class="math inline">\(\mathbf{v}\)</span> の長さが speed です</a></li>
  <li><a href="#path" id="toc-path" class="nav-link" data-scroll-target="#path">3. 経路と位置は、別のものです</a></li>
  <li><a href="#cross-vs-collide" id="toc-cross-vs-collide" class="nav-link" data-scroll-target="#cross-vs-collide">4. 「経路が交わる」と「衝突する」は、別のことです</a></li>
  <li><a href="#relative" id="toc-relative" class="nav-link" data-scroll-target="#relative">5. relative position — <span class="math inline">\(\overrightarrow{AB} = \mathbf{r}_B - \mathbf{r}_A\)</span></a></li>
  <li><a href="#collide-test" id="toc-collide-test" class="nav-link" data-scroll-target="#collide-test">6. 衝突の判定は <span class="math inline">\(\overrightarrow{AB} = \mathbf{0}\)</span></a></li>
  <li><a href="#distance" id="toc-distance" class="nav-link" data-scroll-target="#distance">7. <span class="math inline">\(2\)</span> つの距離は <span class="math inline">\(\lvert \overrightarrow{AB} \rvert\)</span> です</a></li>
  <li><a href="#closest" id="toc-closest" class="nav-link" data-scroll-target="#closest">8. 最接近する時刻と距離</a></li>
  <li><a href="#three-d" id="toc-three-d" class="nav-link" data-scroll-target="#three-d">9. <span class="math inline">\(3\)</span> 次元でも、成分が <span class="math inline">\(1\)</span> つ増えるだけです</a></li>
  </ul></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples">Worked examples</a></li>
  <li><a href="#common-errors" id="toc-common-errors" class="nav-link" data-scroll-target="#common-errors">Common errors</a></li>
  <li><a href="#using-your-gdc-ti-nspire-cx-ii" id="toc-using-your-gdc-ti-nspire-cx-ii" class="nav-link" data-scroll-target="#using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</a>
  <ul class="collapse">
  <li><a href="#gdc-position" id="toc-gdc-position" class="nav-link" data-scroll-target="#gdc-position">1. 位置は、代入で出せます</a></li>
  <li><a href="#gdc-store" id="toc-gdc-store" class="nav-link" data-scroll-target="#gdc-store">2. 名前を付けておくと、<span class="math inline">\(t\)</span> を変えるのが楽です</a></li>
  <li><a href="#gdc-linsolve" id="toc-gdc-linsolve" class="nav-link" data-scroll-target="#gdc-linsolve">3. 交点は、連立方程式として</a></li>
  <li><a href="#gdc-graph" id="toc-gdc-graph" class="nav-link" data-scroll-target="#gdc-graph">4. 距離のグラフで、最接近を見る</a></li>
  <li><a href="#gdc-table" id="toc-gdc-table" class="nav-link" data-scroll-target="#gdc-table">5. 表で、近づき方を見る</a></li>
  <li><a href="#gdc-check" id="toc-gdc-check" class="nav-link" data-scroll-target="#gdc-check">6. 検算のしかた</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#syllabus" id="toc-syllabus" class="nav-link" data-scroll-target="#syllabus">参考：シラバスの原文</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-7.html">Topic 3 — Geometry and trigonometry</a></li><li class="breadcrumb-item"><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-12a.html">AHL 3.12a — Kinematics: constant velocity</a></li></ol></nav></header>




<section id="sec-ahl-3-12a" class="level1">
<h1>AHL 3.12a — Kinematics: constant velocity（等速度の運動）</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>What you should be able to do
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(\mathbf{r} = \mathbf{r}_0 + \mathbf{v}t\)</span> の <span class="math inline">\(\mathbf{r}_0\)</span> と <span class="math inline">\(\mathbf{v}\)</span> が何を表すかを言える。</li>
<li>時刻 <span class="math inline">\(t\)</span> を入れて、<strong>position</strong>（位置）を求められる。</li>
<li><strong>speed</strong>（速さ）が <span class="math inline">\(\lvert \mathbf{v} \rvert\)</span> であることを使える。</li>
<li><span class="math inline">\(2\)</span> つの <strong>particle</strong>（粒子・物体）の、<strong>path</strong>（経路）が交わる点を求められる。</li>
<li><strong>経路が交わること</strong>と <strong>collide</strong>（衝突する）ことが別だと説明できる。</li>
<li><strong>relative position</strong>（相対位置）<span class="math inline">\(\overrightarrow{AB} = \mathbf{r}_B - \mathbf{r}_A\)</span> を <span class="math inline">\(t\)</span> の式で書ける。</li>
<li><span class="math inline">\(\overrightarrow{AB} = \mathbf{0}\)</span> になる <span class="math inline">\(t\)</span> があるかで、<strong>衝突を判定</strong>できる。</li>
<li><span class="math inline">\(2\)</span> つの物体の距離を <span class="math inline">\(t\)</span> の式で書き、<strong>最接近の時刻と距離</strong>を求められる。</li>
<li><span class="math inline">\(3\)</span> 次元でも、<strong>成分が <span class="math inline">\(1\)</span> つ増えるだけ</strong>で同じ計算ができる。</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html">AHL 3.11</a> との対応
</div>
</div>
<div class="callout-body-container callout-body">
<p><span id="eq-ahl312a-correspond"><span class="math display">\[
\underbrace{\mathbf{r} = \mathbf{a} + \lambda\mathbf{b}}_{\text{AHL 3.11}} \qquad \longrightarrow \qquad \underbrace{\mathbf{r} = \mathbf{r}_0 + \mathbf{v}t}_{\text{AHL 3.12}}
\tag{1}\]</span></span></p>
<div id="tbl-ahl312a-correspond" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl312a-correspond-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;1: 記号の対応
</figcaption>
<div aria-describedby="tbl-ahl312a-correspond-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">AHL 3.11</th>
<th style="text-align: left;">AHL 3.12</th>
<th style="text-align: left;">変わったこと</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mathbf{a}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{r}_0\)</span></td>
<td style="text-align: left;"><strong><span class="math inline">\(t = 0\)</span> のときの位置</strong>という意味が付いた</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\lambda\)</span></td>
<td style="text-align: left;"><span class="math inline">\(t\)</span></td>
<td style="text-align: left;"><strong>時刻</strong>という意味が付いた</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mathbf{b}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{v}\)</span></td>
<td style="text-align: left;"><strong>速度</strong>という意味が付いた。<strong>長さが速さ</strong>になった</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>式の形は同じですが、意味が付いたぶん、変えられなくなったものがあります</strong>（<a href="#velocity">第2節</a>）。</p>
</div>
</div>
<section id="the-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-idea">The idea</h2>
<section id="idea" class="level3">
<h3 class="anchored" data-anchor-id="idea">1. <span class="math inline">\(\mathbf{r} = \mathbf{r}_0 + \mathbf{v}t\)</span></h3>
<p><strong>constant velocity</strong>（等速度）で動く物体の、時刻 <span class="math inline">\(t\)</span> での位置は</p>
<p><span id="eq-ahl312a-r"><span class="math display">\[
\mathbf{r} = \mathbf{r}_0 + \mathbf{v}t
\tag{2}\]</span></span></p>
<ul>
<li><span class="math inline">\(\mathbf{r}\)</span> … 時刻 <span class="math inline">\(t\)</span> での<strong>位置ベクトル</strong></li>
<li><span class="math inline">\(\mathbf{r}_0\)</span> … <strong><span class="math inline">\(t = 0\)</span> のときの位置</strong></li>
<li><span class="math inline">\(\mathbf{v}\)</span> … <strong>velocity</strong>（速度）。向きと大きさを持つ</li>
</ul>
<p><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html">AHL 3.11</a> の <span class="math inline">\(\mathbf{r} = \mathbf{a} + \lambda\mathbf{b}\)</span> で、<strong><span class="math inline">\(\mathbf{a}\)</span> を <span class="math inline">\(\mathbf{r}_0\)</span>、<span class="math inline">\(\lambda\)</span> を <span class="math inline">\(t\)</span>、<span class="math inline">\(\mathbf{b}\)</span> を <span class="math inline">\(\mathbf{v}\)</span> と書き直しただけ</strong>です（<a href="#eq-ahl312a-correspond" class="quarto-xref">式&nbsp;1</a>、<a href="#tbl-ahl312a-correspond" class="quarto-xref">表&nbsp;1</a>）。</p>
<div id="fig-ahl312a-idea" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl312a-idea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-3-12a-idea.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl312a-idea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;1: Constant velocity: one step of v per unit of time
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl312a-idea" class="quarto-xref">図&nbsp;1</a> の (a) は <span class="math inline">\(\mathbf{r} = \begin{pmatrix} 1 \\ 2 \end{pmatrix} + t\begin{pmatrix} 2 \\ 1 \end{pmatrix}\)</span> です。<span class="math inline">\(t = 0,\ 1,\ 2,\ 3,\ 4\)</span> の位置に点を打ってあります。</p>
<p><strong><span class="math inline">\(1\)</span> 秒ごとに、ちょうど <span class="math inline">\(\mathbf{v}\)</span> だけ進みます。</strong> ですから点は<strong>等間隔</strong>に並びます。これが「等速度」という言葉の中身です。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>問題文から、まず <span class="math inline">\(3\)</span> つを読み取ってください
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong><span class="math inline">\(t = 0\)</span> がいつか。</strong> 「<span class="math inline">\(9\)</span> 時に港を出る」なら、<span class="math inline">\(t\)</span> は <span class="math inline">\(9\)</span> 時からの時間です</li>
<li><strong>単位は何か。</strong> <span class="math inline">\(t\)</span> が秒か時間か、距離が m か km か</li>
<li><strong><span class="math inline">\(t\)</span> の範囲。</strong> ふつう <span class="math inline">\(t \geq 0\)</span> です。<strong>負の <span class="math inline">\(t\)</span> の答えは、意味を持ちません</strong>（<a href="#closest">第8節</a>）</li>
</ol>
<p><strong>この <span class="math inline">\(3\)</span> つを書き出してから計算に入る</strong>と、最後に単位や時刻でつまずきません。</p>
</div>
</div>
</section>
<section id="velocity" class="level3">
<h3 class="anchored" data-anchor-id="velocity">2. <span class="math inline">\(\mathbf{v}\)</span> の長さが speed です</h3>
<p><strong>speed</strong>（速さ）は、velocity の<strong>大きさ</strong>です（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-10b.html#distance">AHL 3.10b 第4節</a>）。</p>
<p><span id="eq-ahl312a-speed"><span class="math display">\[
\text{speed} = \lvert \mathbf{v} \rvert
\tag{3}\]</span></span></p>
<p><span class="math inline">\(\mathbf{v} = \begin{pmatrix} 2 \\ 1 \end{pmatrix}\)</span> なら <span class="math inline">\(\lvert \mathbf{v} \rvert = \sqrt{5} \approx 2.24\)</span> です。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>ここでは、<span class="math inline">\(\mathbf{v}\)</span> を勝手にスカラー倍できません
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#not-unique">AHL 3.11 第3節</a> では、direction vector を何倍しても<strong>同じ直線</strong>でした。</p>
<p><strong>ここは違います。</strong> <a href="#fig-ahl312a-idea" class="quarto-xref">図&nbsp;1</a> の (b) を見てください。<span class="math inline">\(\mathbf{v} = \begin{pmatrix} 2 \\ 1 \end{pmatrix}\)</span> の <span class="math inline">\(P\)</span> と、<span class="math inline">\(\mathbf{v} = \begin{pmatrix} 4 \\ 2 \end{pmatrix}\)</span> の <span class="math inline">\(Q\)</span> は、<strong>同じ道すじを通りますが、速さが <span class="math inline">\(2\)</span> 倍</strong>です。</p>
<p><span class="math inline">\(t = 1\)</span> のとき <span class="math inline">\(P\)</span> は <span class="math inline">\((3,\ 3)\)</span>、<span class="math inline">\(Q\)</span> は <span class="math inline">\((5,\ 4)\)</span> で、<strong>別の場所にいます。</strong></p>
<p><strong><span class="math inline">\(t\)</span> に時刻という意味が付いたので、<span class="math inline">\(\mathbf{v}\)</span> の長さが答えを変えます。</strong></p>
<p><strong><span class="math inline">\(\mathbf{r}_0\)</span> も自由ではありません。</strong> <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#not-unique">AHL 3.11 第3節</a> では <span class="math inline">\(\mathbf{a}\)</span> は直線上のどの点でもよかったのですが、ここでの <span class="math inline">\(\mathbf{r}_0\)</span> は <strong><span class="math inline">\(t = 0\)</span> にその物体が実際にいる点</strong>でなければなりません。</p>
</div>
</div>
<p><span class="math inline">\(t\)</span> 秒間に進む<strong>道のり</strong>は <span class="math inline">\(\lvert \mathbf{v} \rvert t\)</span> です。<strong>等速度なので、道のりと変位の大きさが一致します</strong>（向きが変わらないからです）。</p>
</section>
<section id="path" class="level3">
<h3 class="anchored" data-anchor-id="path">3. 経路と位置は、別のものです</h3>
<ul>
<li><strong>path</strong>（経路）… 物体が通る<strong>線</strong>。等速度なら<strong>直線</strong>です</li>
<li><strong>position</strong>（位置）… <strong>ある時刻での点</strong> <span class="math inline">\(1\)</span> つ</li>
</ul>
<p><strong>経路は <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html">AHL 3.11</a> の直線そのもの</strong>です。ですから <span class="math inline">\(2\)</span> つの物体の<strong>経路が交わる点</strong>は、<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#intersect">AHL 3.11 第9節</a> のやり方で求まります。</p>
<p><strong>ただし <span class="math inline">\(t \geq 0\)</span> なので、実際に通るのは半分（半直線）だけ</strong>です。求めた <span class="math inline">\(\lambda\)</span>、<span class="math inline">\(\mu\)</span> が<strong>両方とも <span class="math inline">\(0\)</span> 以上</strong>なら、その点は本当に <span class="math inline">\(2\)</span> 物体が通る点です。</p>
<p><strong><span class="math inline">\(2\)</span> 直線で別の文字を使うのは、<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#intersect">AHL 3.11 第9節</a> と同じ理由</strong>です。しかもこのページでは、その <span class="math inline">\(2\)</span> つの値には<strong>時刻</strong>という意味があります。</p>
</section>
<section id="cross-vs-collide" class="level3">
<h3 class="anchored" data-anchor-id="cross-vs-collide">4. 「経路が交わる」と「衝突する」は、別のことです</h3>
<p><strong>このページで、いちばん大事なところです。</strong></p>
<div id="fig-ahl312a-cross" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl312a-cross-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-3-12a-cross.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl312a-cross-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;2: Crossing paths, and an actual collision
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl312a-cross" class="quarto-xref">図&nbsp;2</a> の (a) では、<span class="math inline">\(A\)</span> と <span class="math inline">\(B\)</span> の経路が <span class="math inline">\((3,\ 5)\)</span> で交わっています。しかし</p>
<ul>
<li><span class="math inline">\(A\)</span> がそこにいるのは <span class="math inline">\(t = 1\)</span></li>
<li><span class="math inline">\(B\)</span> がそこにいるのは <span class="math inline">\(t = 5\)</span></li>
</ul>
<p><strong><span class="math inline">\(4\)</span> 秒ずれています。ぶつかりません。</strong></p>
<ol start="2" type="a">
<li>では、両方が <span class="math inline">\(t = 1\)</span> に <span class="math inline">\((3,\ 5)\)</span> にいます。<strong>これが collide</strong>（衝突する）です。</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>交点を出しただけでは、答えになりません
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>Do the particles collide?</code> と聞かれたら、<strong>時刻まで確かめてください。</strong></p>
<ul>
<li><strong>経路が交わる</strong> … 場所が同じ。<span class="math inline">\(\lambda\)</span> と <span class="math inline">\(\mu\)</span> は違ってよい</li>
<li><strong>衝突する</strong> … <strong>場所も時刻も同じ</strong>。<span class="math inline">\(\lambda = \mu\)</span> でなければならない</li>
</ul>
<p><code>Do the paths cross?</code> と <code>Do the particles collide?</code> は、<strong>別の問い</strong>です。</p>
</div>
</div>
</section>
<section id="relative" class="level3">
<h3 class="anchored" data-anchor-id="relative">5. relative position — <span class="math inline">\(\overrightarrow{AB} = \mathbf{r}_B - \mathbf{r}_A\)</span></h3>
<p><span id="eq-ahl312a-ab"><span class="math display">\[
\overrightarrow{AB} = \mathbf{r}_B - \mathbf{r}_A
\tag{4}\]</span></span></p>
<p><strong>「ゴールひくスタート」</strong>でした（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-10b.html#ab">AHL 3.10b 第3節</a>）。<span class="math inline">\(A\)</span> から見て <span class="math inline">\(B\)</span> がどこにいるか、を表します。</p>
<p>両方が動いているので、<span class="math inline">\(\overrightarrow{AB}\)</span> は <strong><span class="math inline">\(t\)</span> の式</strong>になります。</p>
<p><span id="eq-ahl312a-abt"><span class="math display">\[
\overrightarrow{AB} = (\mathbf{r}_{0B} - \mathbf{r}_{0A}) + t(\mathbf{v}_B - \mathbf{v}_A)
\tag{5}\]</span></span></p>
<p><strong>これも「はじめの差」＋「<span class="math inline">\(t\)</span> ×（速度の差）」の形</strong>です。<span class="math inline">\(\mathbf{v}_B - \mathbf{v}_A\)</span> を <strong>relative velocity</strong>（相対速度）といいます。</p>
</section>
<section id="collide-test" class="level3">
<h3 class="anchored" data-anchor-id="collide-test">6. 衝突の判定は <span class="math inline">\(\overrightarrow{AB} = \mathbf{0}\)</span></h3>
<p><span class="math inline">\(2\)</span> つが同じ場所にいるということは、その差が <span class="math inline">\(\mathbf{0}\)</span> だということです。</p>
<p><span id="eq-ahl312a-collide"><span class="math display">\[
\text{衝突する} \quad \Longleftrightarrow \quad \overrightarrow{AB} = \mathbf{0} \ \text{となる} \ t \geq 0 \ \text{がある}
\tag{6}\]</span></span></p>
<p><strong>成分ごとに <span class="math inline">\(0\)</span> とおいて、<span class="math inline">\(t\)</span> が全部そろうかを見ます。</strong> <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#on-line">AHL 3.11 第6節</a> の「<span class="math inline">\(1\)</span> つの値が全成分で成り立つか」と、まったく同じ考え方です。<strong><span class="math inline">\(t \geq 0\)</span> でそろえば衝突</strong>です（<a href="#exm-ahl312a-collide" class="quarto-xref">例&nbsp;3</a>）。</p>
<p><span class="math inline">\(\overrightarrow{AB} = \begin{pmatrix} 12-4t \\ -2-2t \end{pmatrix}\)</span> なら</p>
<ul>
<li><span class="math inline">\(1\)</span> つ目 … <span class="math inline">\(12-4t = 0\)</span> から <span class="math inline">\(t = 3\)</span></li>
<li><span class="math inline">\(2\)</span> つ目 … <span class="math inline">\(-2-2t = 0\)</span> から <span class="math inline">\(t = -1\)</span></li>
</ul>
<p><strong>そろいません。しかも <span class="math inline">\(t = -1\)</span> は範囲の外です。</strong> ですから衝突しません（<a href="#exm-ahl312a-cross" class="quarto-xref">例&nbsp;2</a>）。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>いつも <span class="math inline">\(0\)</span> になる成分は、条件になりません
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\overrightarrow{AB}\)</span> のある成分が、<span class="math inline">\(t\)</span> によらず <span class="math inline">\(0\)</span> のことがあります。<span class="math inline">\(2\)</span> つの物体が、その向きにはずっと同じ位置にいる、ということです。</p>
<p><strong>その成分は、はじめから満たされています。</strong> 残りの成分だけで <span class="math inline">\(t\)</span> を決めます（演習 <span class="math inline">\(8\)</span>）。</p>
<p>逆に、<strong><span class="math inline">\(t\)</span> によらず <span class="math inline">\(0\)</span> でない</strong>成分があれば、その時点で<strong>衝突しません</strong>（演習 <span class="math inline">\(10\)</span>）。</p>
</div>
</div>
</section>
<section id="distance" class="level3">
<h3 class="anchored" data-anchor-id="distance">7. <span class="math inline">\(2\)</span> つの距離は <span class="math inline">\(\lvert \overrightarrow{AB} \rvert\)</span> です</h3>
<p>時刻 <span class="math inline">\(t\)</span> での <span class="math inline">\(2\)</span> 物体の距離は</p>
<p><span id="eq-ahl312a-d"><span class="math display">\[
d(t) = \lvert \overrightarrow{AB} \rvert = \sqrt{(\text{成分}_1)^2 + (\text{成分}_2)^2}
\tag{7}\]</span></span></p>
<p><strong>relative velocity（相対速度）<span class="math inline">\(\mathbf{v}_B - \mathbf{v}_A\)</span> が <span class="math inline">\(\mathbf{0}\)</span> でなければ</strong>、<a href="#eq-ahl312a-d" class="quarto-xref">式&nbsp;7</a> の中身は <span class="math inline">\(t\)</span> の <span class="math inline">\(2\)</span> 次式になります。<strong><span class="math inline">\(\sqrt{\ }\)</span> の中を先に整理してください。</strong></p>
<p><strong><span class="math inline">\(\mathbf{v}_B = \mathbf{v}_A\)</span> のときだけ別</strong>で、そのときは <span class="math inline">\(\overrightarrow{AB}\)</span> が <span class="math inline">\(t\)</span> によらず一定になり、中身は定数です（演習 <span class="math inline">\(6\)</span>）。</p>
</section>
<section id="closest" class="level3">
<h3 class="anchored" data-anchor-id="closest">8. 最接近する時刻と距離</h3>
<div id="fig-ahl312a-closest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl312a-closest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-3-12a-closest.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl312a-closest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;3: Two ships, the gap between them, and the graph of that gap
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl312a-closest" class="quarto-xref">図&nbsp;3</a> の (a) は、<span class="math inline">\(A\)</span> が東へ <span class="math inline">\(3\)</span>、<span class="math inline">\(B\)</span> が北へ <span class="math inline">\(4\)</span> で進む様子です。点線は、そのときどきの <span class="math inline">\(A\)</span> と <span class="math inline">\(B\)</span> を結ぶ線分で、その長さが <span class="math inline">\(\lvert \overrightarrow{AB} \rvert\)</span> です。</p>
<p><strong>近づいてから、また離れます。</strong> (b) はその距離 <span class="math inline">\(d\)</span> のグラフです。</p>
<p><strong><span class="math inline">\(5\)</span> つの手順があります。</strong></p>
<p><strong>相対速度が <span class="math inline">\(\mathbf{0}\)</span> でないとき</strong>の手順です。</p>
<div id="tbl-ahl312a-steps" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl312a-steps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;2: 最接近を出す <span class="math inline">\(5\)</span> つの手順
</figcaption>
<div aria-describedby="tbl-ahl312a-steps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">ステップ</th>
<th style="text-align: left;">すること</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(1\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\overrightarrow{AB}\)</span> を <span class="math inline">\(t\)</span> の式で書く（<a href="#eq-ahl312a-abt" class="quarto-xref">式&nbsp;5</a>）</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(2\)</span></td>
<td style="text-align: left;"><span class="math inline">\(d^2\)</span> を計算して、<span class="math inline">\(t\)</span> の <span class="math inline">\(2\)</span> 次式に整理する</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(3\)</span></td>
<td style="text-align: left;"><strong>平方完成</strong>する（または頂点の <span class="math inline">\(t = -\dfrac{b}{2a}\)</span> を使う）</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(4\)</span></td>
<td style="text-align: left;">その <span class="math inline">\(t\)</span> を <span class="math inline">\(d\)</span> に入れる。<strong><span class="math inline">\(d^2\)</span> ではなく <span class="math inline">\(d\)</span> を答える</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(5\)</span></td>
<td style="text-align: left;"><span class="math inline">\(t \geq 0\)</span> になっているかを確かめる</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#fig-ahl312a-closest" class="quarto-xref">図&nbsp;3</a> の例では</p>
<p><span class="math display">\[
d^2 = 25t^2 - 150t + 625 = 25\left((t-3)^2 + 16\right)
\]</span></p>
<p><span class="math display">\[
d = 5\sqrt{(t-3)^2+16}
\]</span></p>
<p><span class="math inline">\((t-3)^2\)</span> が <span class="math inline">\(0\)</span> 以上なので、<strong><span class="math inline">\(t = 3\)</span> のときが最小</strong>で、そのとき <span class="math inline">\(d = 5\sqrt{16} = 20\)</span> です。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span><span class="math inline">\(d^2\)</span> が最小になる <span class="math inline">\(t\)</span> と、<span class="math inline">\(d\)</span> が最小になる <span class="math inline">\(t\)</span> は同じです
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(d \geq 0\)</span> で、<span class="math inline">\(\sqrt{\ }\)</span> は増加する関数なので、<strong><span class="math inline">\(d^2\)</span> を小さくすれば <span class="math inline">\(d\)</span> も小さくなります。</strong></p>
<p>ですから <span class="math inline">\(\sqrt{\ }\)</span> を付けたまま平方完成する必要はなく、<strong><span class="math inline">\(d^2\)</span> で計算して構いません。</strong></p>
<p><strong>ただし、答えるのは <span class="math inline">\(d\)</span> です。</strong> <span class="math inline">\(d^2 = 400\)</span> を答えにしないでください。<span class="math inline">\(400\)</span> km ではなく <span class="math inline">\(20\)</span> km です。</p>
</div>
</div>
</section>
<section id="three-d" class="level3">
<h3 class="anchored" data-anchor-id="three-d">9. <span class="math inline">\(3\)</span> 次元でも、成分が <span class="math inline">\(1\)</span> つ増えるだけです</h3>
<p><span class="math display">\[
\mathbf{r} = \begin{pmatrix} 1 \\ 0 \\ -2 \end{pmatrix} + t\begin{pmatrix} 2 \\ -3 \\ 1 \end{pmatrix}
\]</span></p>
<p>衝突の判定も、<span class="math inline">\(3\)</span> 成分すべてで同じ <span class="math inline">\(t\)</span> が要る、というだけです（<a href="#collide-test">第6節</a>、演習 <span class="math inline">\(8\)</span>）。</p>
<p>距離も <span class="math inline">\(d = \sqrt{(\ )^2+(\ )^2+(\ )^2}\)</span> になるだけで、<strong>平方完成の手順は変わりません。</strong></p>
<p><strong>図はかけなくなりますが、計算はできます</strong>（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#three-d">AHL 3.11 第7節</a>）。</p>
</section>
</section>
<section id="worked-examples" class="level2">
<h2 class="anchored" data-anchor-id="worked-examples">Worked examples</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>問題文は英語です。意味が理解できなかったら、問題文の下の「<strong>日本語訳</strong>」を開いてください。解説は日本語です。</p>
</div>
</div>
</div>
<div id="exm-ahl312a-position" class="theorem example">
<p><span class="theorem-title"><strong>例題 1</strong></span> <span class="q-en">A particle starts at the point <span class="math inline">\((-3,\ 7)\)</span> and moves with constant velocity <span class="math inline">\(\begin{pmatrix} 4 \\ -2 \end{pmatrix}\)</span> m s<span class="math inline">\(^{-1}\)</span>. Time <span class="math inline">\(t\)</span> is measured in seconds from the start.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write down the position vector of the particle at time <span class="math inline">\(t\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the position of the particle after <span class="math inline">\(5\)</span> seconds.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the speed of the particle, giving your answer to <span class="math inline">\(3\)</span> significant figures.</span></p>
<p><strong>(d)</strong> <span class="q-en">Find the time at which the particle crosses the <span class="math inline">\(x\)</span>-axis.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある粒子が点 <span class="math inline">\((-3,\ 7)\)</span> を出発し、一定の速度 <span class="math inline">\(\begin{pmatrix} 4 \\ -2 \end{pmatrix}\)</span> m s<span class="math inline">\(^{-1}\)</span> で動きます。時刻 <span class="math inline">\(t\)</span> は、出発してからの秒数です。</p>
<p><strong>(a)</strong> 時刻 <span class="math inline">\(t\)</span> での位置ベクトルを書きなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(5\)</span> 秒後の位置を求めなさい。</p>
<p><strong>(c)</strong> この粒子の速さを、有効数字 <span class="math inline">\(3\)</span> 桁で求めなさい。</p>
<p><strong>(d)</strong> この粒子が <span class="math inline">\(x\)</span> 軸を横切る時刻を求めなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> <a href="#eq-ahl312a-r" class="quarto-xref">式&nbsp;2</a> にあてはめるだけです。</p>
<p><span class="math display">\[
\mathbf{r} = \begin{pmatrix} -3 \\ 7 \end{pmatrix} + t\begin{pmatrix} 4 \\ -2 \end{pmatrix}
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(t = 5\)</span> を入れます。</p>
<p><span class="math display">\[
\begin{pmatrix} -3 \\ 7 \end{pmatrix} + 5\begin{pmatrix} 4 \\ -2 \end{pmatrix} = \begin{pmatrix} 17 \\ -3 \end{pmatrix}
\]</span></p>
<p><strong>(c)</strong> speed は <span class="math inline">\(\lvert \mathbf{v} \rvert\)</span> です（<a href="#eq-ahl312a-speed" class="quarto-xref">式&nbsp;3</a>）。</p>
<p><span class="math display">\[
\lvert \mathbf{v} \rvert = \sqrt{4^2+(-2)^2} = \sqrt{20} = 2\sqrt{5} \approx 4.47 \ \text{m s}^{-1}
\]</span></p>
<p><strong>(d)</strong> <span class="math inline">\(x\)</span> 軸の上では <span class="math inline">\(y = 0\)</span> です。<strong><span class="math inline">\(y\)</span> 成分だけを見ます。</strong></p>
<p><span class="math display">\[
7 - 2t = 0 \quad \Longrightarrow \quad t = 3.5 \ \text{秒}
\]</span></p>
<p>そのときの位置は <span class="math inline">\(\begin{pmatrix} -3+14 \\ 0 \end{pmatrix} = \begin{pmatrix} 11 \\ 0 \end{pmatrix}\)</span> です。</p>
<p><strong>検算。</strong> (b) の位置と出発点の差が、<span class="math inline">\(5\mathbf{v}\)</span> になるはずです。</p>
<p><span class="math display">\[
\begin{pmatrix} 17 \\ -3 \end{pmatrix} - \begin{pmatrix} -3 \\ 7 \end{pmatrix} = \begin{pmatrix} 20 \\ -10 \end{pmatrix} = 5\begin{pmatrix} 4 \\ -2 \end{pmatrix}
\]</span></p>
<p><span class="math inline">\(5\mathbf{v}\)</span> に戻りました ✓ <strong><span class="math inline">\(7-10 = -3\)</span> を <span class="math inline">\(3\)</span> としていたら、差の <span class="math inline">\(2\)</span> つ目が <span class="math inline">\(-4\)</span> になり、<span class="math inline">\(5\mathbf{v}\)</span> になりません。</strong></p>
<p><strong>検算（(c) について）。</strong> <span class="math inline">\(5\)</span> 秒で進んだ道のりは <span class="math inline">\(5\lvert \mathbf{v} \rvert = 10\sqrt{5} \approx 22.4\)</span> m のはずです。(b) の変位の大きさは <span class="math inline">\(\sqrt{20^2+(-10)^2} = \sqrt{500} = 10\sqrt{5}\)</span> ✓ <strong>等速度なので、この <span class="math inline">\(2\)</span> つは一致します。</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[\mathbf{r} = \begin{pmatrix} -3 \\ 7 \end{pmatrix} + t\begin{pmatrix} 4 \\ -2 \end{pmatrix}\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[\begin{pmatrix} 17 \\ -3 \end{pmatrix}\]</span></p>
<p><strong>(c)</strong> <span class="math display">\[\lvert \mathbf{v} \rvert = \sqrt{4^2+(-2)^2} = 2\sqrt{5} \approx 4.47 \ \text{m s}^{-1}\]</span></p>
<p><strong>(d)</strong> <span class="math display">\[7-2t = 0 \ \Rightarrow \ t = 3.5 \ \text{s}\]</span></p>
</div>
</div>
</div>
<div id="exm-ahl312a-cross" class="theorem example">
<p><span class="theorem-title"><strong>例題 2</strong></span> <span class="q-en">Two particles <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> move with constant velocity. At time <span class="math inline">\(t\)</span> seconds their position vectors, in metres, are</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 1 \\ 2 \end{pmatrix} + t\begin{pmatrix} 2 \\ 3 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 13 \\ 0 \end{pmatrix} + t\begin{pmatrix} -2 \\ 1 \end{pmatrix}
\]</span></p>
<p><strong>(a)</strong> <span class="q-en">Show that the paths of the two particles cross, and find the point where they cross.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the time at which each particle is at that point.</span></p>
<p><strong>(c)</strong> <span class="q-en">Determine whether the particles collide.</span></p>
<p><strong>(d)</strong> <span class="q-en">Explain why the paths crossing does not mean that the particles collide.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの粒子 <span class="math inline">\(A\)</span>、<span class="math inline">\(B\)</span> が一定の速度で動きます。時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは、メートル単位で上のとおりです。</p>
<p><strong>(a)</strong> <span class="math inline">\(2\)</span> つの経路が交わることを示し、交わる点を求めなさい。</p>
<p><strong>(b)</strong> それぞれの粒子が、その点にいる時刻を求めなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(2\)</span> つの粒子が衝突するかどうかを判定しなさい。</p>
<p><strong>(d)</strong> 経路が交わることが、粒子が衝突することを意味しない理由を説明しなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> 経路は直線なので、<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#intersect">AHL 3.11 第9節</a> のやり方です。<strong>文字は <span class="math inline">\(2\)</span> 種類</strong>にします。</p>
<p><span class="math display">\[
\begin{pmatrix} 1+2\lambda \\ 2+3\lambda \end{pmatrix} = \begin{pmatrix} 13-2\mu \\ \mu \end{pmatrix}
\]</span></p>
<p><span class="math display">\[
1+2\lambda = 13-2\mu \quad \Longrightarrow \quad \mu = 6-\lambda
\]</span></p>
<p><span class="math display">\[
2+3\lambda = \mu = 6-\lambda \quad \Longrightarrow \quad 4\lambda = 4, \quad \lambda = 1
\]</span></p>
<p><span class="math inline">\(\lambda = 1\)</span>、<span class="math inline">\(\mu = 5\)</span> です。交わる点は</p>
<p><span class="math display">\[
\begin{pmatrix} 1 \\ 2 \end{pmatrix} + \begin{pmatrix} 2 \\ 3 \end{pmatrix} = \begin{pmatrix} 3 \\ 5 \end{pmatrix}
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(\lambda\)</span> と <span class="math inline">\(\mu\)</span> が、そのまま時刻です。</p>
<ul>
<li><span class="math inline">\(A\)</span> … <span class="math inline">\(t = 1\)</span> 秒</li>
<li><span class="math inline">\(B\)</span> … <span class="math inline">\(t = 5\)</span> 秒</li>
</ul>
<p><strong>(c)</strong> 時刻が違うので、<strong>衝突しません</strong>（<a href="#cross-vs-collide">第4節</a>）。</p>
<p><span class="math inline">\(\overrightarrow{AB}\)</span> でも確かめられます（<a href="#eq-ahl312a-collide" class="quarto-xref">式&nbsp;6</a>）。</p>
<p><span class="math display">\[
\overrightarrow{AB} = \begin{pmatrix} 13-2t \\ t \end{pmatrix} - \begin{pmatrix} 1+2t \\ 2+3t \end{pmatrix} = \begin{pmatrix} 12-4t \\ -2-2t \end{pmatrix}
\]</span></p>
<p><span class="math inline">\(12-4t = 0\)</span> から <span class="math inline">\(t = 3\)</span>、<span class="math inline">\(-2-2t = 0\)</span> から <span class="math inline">\(t = -1\)</span> です。<strong>そろわないので、衝突しません。</strong></p>
<p><strong>(d)</strong> <code>Explain why</code> なので、英語で理由を書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The paths crossing only says that the two straight lines share a point in space; it says nothing about when each particle is there. Here <span class="math inline">\(A\)</span> reaches <span class="math inline">\((3,\ 5)\)</span> at <span class="math inline">\(t = 1\)</span> and <span class="math inline">\(B\)</span> reaches it at <span class="math inline">\(t = 5\)</span>, so <span class="math inline">\(B\)</span> arrives four seconds after <span class="math inline">\(A\)</span> has already gone. A collision needs the same position at the same time, which is why the two parameters must be allowed to differ when finding the crossing point but must be equal for a collision.</em></p>
</div>
<p>（経路が交わるというのは、<span class="math inline">\(2\)</span> 本の直線が空間の中で <span class="math inline">\(1\)</span> 点を共有するというだけのことで、それぞれの粒子がいつそこにいるかについては何も言っていない。ここでは <span class="math inline">\(A\)</span> は <span class="math inline">\(t = 1\)</span> に <span class="math inline">\((3,\ 5)\)</span> に着き、<span class="math inline">\(B\)</span> は <span class="math inline">\(t = 5\)</span> に着くので、<span class="math inline">\(A\)</span> が去ったあと <span class="math inline">\(4\)</span> 秒たってから <span class="math inline">\(B\)</span> が到着する。衝突には、同じ位置に同じ時刻でいることが必要である。だからこそ、交点を求めるときは <span class="math inline">\(2\)</span> つの parameter が違ってよく、衝突のときは等しくなければならない、という意味です。）</p>
<p><strong>検算。</strong> (a) で出した点を、<strong>使っていないほうの式</strong>に入れます。<span class="math inline">\(\mu = 5\)</span> を <span class="math inline">\(\mathbf{r}_B\)</span> に入れると</p>
<p><span class="math display">\[
\begin{pmatrix} 13 \\ 0 \end{pmatrix} + 5\begin{pmatrix} -2 \\ 1 \end{pmatrix} = \begin{pmatrix} 3 \\ 5 \end{pmatrix}
\]</span></p>
<p>同じ点になりました ✓（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#gdc-check">AHL 3.11 の GDC 第6節</a>）</p>
<p><strong>検算（(c) について）。</strong> <span class="math inline">\(t = 1\)</span> での <span class="math inline">\(\overrightarrow{AB}\)</span> を出します。<span class="math inline">\(\begin{pmatrix} 12-4 \\ -2-2 \end{pmatrix} = \begin{pmatrix} 8 \\ -4 \end{pmatrix}\)</span> で、<span class="math inline">\(\mathbf{0}\)</span> ではありません ✓ <strong><span class="math inline">\(A\)</span> が交点にいる時刻でも、<span class="math inline">\(B\)</span> は <span class="math inline">\(x\)</span> 方向に <span class="math inline">\(8\)</span> m、<span class="math inline">\(y\)</span> 方向に <span class="math inline">\(-4\)</span> m ずれたところにいます。</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[1+2\lambda = 13-2\mu, \qquad 2+3\lambda = \mu\]</span> <span class="math display">\[\lambda = 1, \quad \mu = 5, \qquad \text{crossing point } (3,\ 5)\]</span></p>
<p><strong>(b)</strong> <em><span class="math inline">\(A\)</span> is there at <span class="math inline">\(t = 1\)</span>; <span class="math inline">\(B\)</span> is there at <span class="math inline">\(t = 5\)</span>.</em></p>
<p><strong>(c)</strong> <span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 12-4t \\ -2-2t \end{pmatrix}\]</span> <em>The components vanish at <span class="math inline">\(t = 3\)</span> and <span class="math inline">\(t = -1\)</span>, which are different, so the particles do not collide.</em></p>
<p><strong>(d)</strong> <em>Crossing paths give the same position; a collision needs the same position at the same time. Here the arrival times are <span class="math inline">\(t = 1\)</span> and <span class="math inline">\(t = 5\)</span>.</em></p>
</div>
</div>
</div>
<div id="exm-ahl312a-collide" class="theorem example">
<p><span class="theorem-title"><strong>例題 3</strong></span> <span class="q-en">Two particles <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> have position vectors, in metres at time <span class="math inline">\(t\)</span> seconds,</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 1 \\ 2 \end{pmatrix} + t\begin{pmatrix} 2 \\ 3 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 5 \\ 4 \end{pmatrix} + t\begin{pmatrix} -2 \\ 1 \end{pmatrix}
\]</span></p>
<p><strong>(a)</strong> <span class="q-en">Find <span class="math inline">\(\overrightarrow{AB}\)</span> in terms of <span class="math inline">\(t\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Hence show that the particles collide, and state the time.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the position at which they collide.</span></p>
<p><strong>(d)</strong> <span class="q-en">Interpret the vector <span class="math inline">\(\overrightarrow{AB}\)</span> in the context of the two particles.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの粒子 <span class="math inline">\(A\)</span>、<span class="math inline">\(B\)</span> の、時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは、メートル単位で上のとおりです。</p>
<p><strong>(a)</strong> <span class="math inline">\(\overrightarrow{AB}\)</span> を <span class="math inline">\(t\)</span> の式で求めなさい。</p>
<p><strong>(b)</strong> それを使って <span class="math inline">\(2\)</span> つの粒子が衝突することを示し、その時刻を答えなさい。</p>
<p><strong>(c)</strong> 衝突する位置を求めなさい。</p>
<p><strong>(d)</strong> ベクトル <span class="math inline">\(\overrightarrow{AB}\)</span> が、この <span class="math inline">\(2\)</span> 粒子について何を表すかを述べなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> ゴールひくスタートです（<a href="#eq-ahl312a-ab" class="quarto-xref">式&nbsp;4</a>）。</p>
<p><span class="math display">\[
\overrightarrow{AB} = \begin{pmatrix} 5-2t \\ 4+t \end{pmatrix} - \begin{pmatrix} 1+2t \\ 2+3t \end{pmatrix} = \begin{pmatrix} 4-4t \\ 2-2t \end{pmatrix}
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(\overrightarrow{AB} = \mathbf{0}\)</span> となる <span class="math inline">\(t\)</span> を探します（<a href="#eq-ahl312a-collide" class="quarto-xref">式&nbsp;6</a>）。</p>
<p><span class="math display">\[
4-4t = 0 \quad \Longrightarrow \quad t = 1
\]</span></p>
<p><span class="math display">\[
2-2t = 0 \quad \Longrightarrow \quad t = 1
\]</span></p>
<p><strong><span class="math inline">\(2\)</span> つとも <span class="math inline">\(t = 1\)</span> でそろい、<span class="math inline">\(t \geq 0\)</span> も満たします。</strong> ですから <span class="math inline">\(t = 1\)</span> 秒で衝突します。</p>
<p><strong>(c)</strong> どちらかの式に <span class="math inline">\(t = 1\)</span> を入れます。</p>
<p><span class="math display">\[
\begin{pmatrix} 1 \\ 2 \end{pmatrix} + \begin{pmatrix} 2 \\ 3 \end{pmatrix} = \begin{pmatrix} 3 \\ 5 \end{pmatrix}
\]</span></p>
<p><strong>(d)</strong> <code>Interpret</code> なので、<strong><span class="math inline">\(2\)</span> 粒子の言葉</strong>で書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(\overrightarrow{AB}\)</span> is the position of <span class="math inline">\(B\)</span> as seen from <span class="math inline">\(A\)</span> at time <span class="math inline">\(t\)</span>: its components say how far <span class="math inline">\(B\)</span> is from <span class="math inline">\(A\)</span> in the <span class="math inline">\(x\)</span>- and <span class="math inline">\(y\)</span>-directions at that moment. At <span class="math inline">\(t = 0\)</span> it is <span class="math inline">\(\begin{pmatrix} 4 \\ 2 \end{pmatrix}\)</span>, so <span class="math inline">\(B\)</span> starts <span class="math inline">\(4\)</span> m from <span class="math inline">\(A\)</span> in the <span class="math inline">\(x\)</span>-direction and <span class="math inline">\(2\)</span> m in the <span class="math inline">\(y\)</span>-direction. The vector shrinks steadily to <span class="math inline">\(\mathbf{0}\)</span> at <span class="math inline">\(t = 1\)</span>, which is the moment the two particles are in the same place.</em></p>
</div>
<p>（<span class="math inline">\(\overrightarrow{AB}\)</span> は、時刻 <span class="math inline">\(t\)</span> において <span class="math inline">\(A\)</span> から見た <span class="math inline">\(B\)</span> の位置である。その成分は、そのとき <span class="math inline">\(B\)</span> が <span class="math inline">\(A\)</span> から <span class="math inline">\(x\)</span> 方向にいくつ、<span class="math inline">\(y\)</span> 方向にいくつのところにいるかを表す。<span class="math inline">\(t = 0\)</span> では <span class="math inline">\(\begin{pmatrix} 4 \\ 2 \end{pmatrix}\)</span> なので、<span class="math inline">\(B\)</span> は <span class="math inline">\(A\)</span> から <span class="math inline">\(x\)</span> 方向に <span class="math inline">\(4\)</span> m、<span class="math inline">\(y\)</span> 方向に <span class="math inline">\(2\)</span> m のところから始まる。このベクトルはだんだん小さくなり、<span class="math inline">\(t = 1\)</span> で <span class="math inline">\(\mathbf{0}\)</span> になる。それが <span class="math inline">\(2\)</span> 粒子が同じ場所にいる瞬間である、という意味です。）</p>
<p><strong>検算。</strong> (c) を、<strong>もう一方の式</strong>でも出します。</p>
<p><span class="math display">\[
\begin{pmatrix} 5 \\ 4 \end{pmatrix} + \begin{pmatrix} -2 \\ 1 \end{pmatrix} = \begin{pmatrix} 3 \\ 5 \end{pmatrix}
\]</span></p>
<p>同じ点になりました ✓ <strong>どちらか片方だけで出しても、衝突していることの確認にはなりません。</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 4-4t \\ 2-2t \end{pmatrix}\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[4-4t = 0 \ \Rightarrow \ t = 1; \qquad 2-2t = 0 \ \Rightarrow \ t = 1\]</span> <em>Both components vanish at the same time <span class="math inline">\(t = 1\)</span> s, so the particles collide.</em></p>
<p><strong>(c)</strong> <span class="math display">\[\mathbf{r}_A(1) = \begin{pmatrix} 3 \\ 5 \end{pmatrix} = \mathbf{r}_B(1)\]</span></p>
<p><strong>(d)</strong> <em><span class="math inline">\(\overrightarrow{AB}\)</span> is the position of <span class="math inline">\(B\)</span> relative to <span class="math inline">\(A\)</span>; it reaches <span class="math inline">\(\mathbf{0}\)</span> exactly when they meet.</em></p>
</div>
</div>
</div>
<div id="exm-ahl312a-closest" class="theorem example">
<p><span class="theorem-title"><strong>例題 4</strong></span> <span class="q-en">Two ships <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> move with constant velocity. Taking east and north as the positive directions, with distances in kilometres and <span class="math inline">\(t\)</span> in hours,</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 0 \\ 0 \end{pmatrix} + t\begin{pmatrix} 3 \\ 0 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 25 \\ 0 \end{pmatrix} + t\begin{pmatrix} 0 \\ 4 \end{pmatrix}
\]</span></p>
<p><strong>(a)</strong> <span class="q-en">Find <span class="math inline">\(\overrightarrow{AB}\)</span> in terms of <span class="math inline">\(t\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Show that the distance <span class="math inline">\(d\)</span> between the ships satisfies <span class="math inline">\(d = 5\sqrt{(t-3)^2+16}\)</span>.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the time at which the ships are closest, and the least distance between them.</span></p>
<p><strong>(d)</strong> <span class="q-en">Interpret your answers to part (c) in the context of the two ships.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> 隻の船 <span class="math inline">\(A\)</span>、<span class="math inline">\(B\)</span> が一定の速度で進みます。東と北を正の向きとし、距離は km、<span class="math inline">\(t\)</span> は時間の単位で、位置ベクトルは上のとおりです。</p>
<p><strong>(a)</strong> <span class="math inline">\(\overrightarrow{AB}\)</span> を <span class="math inline">\(t\)</span> の式で求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(2\)</span> 隻の距離 <span class="math inline">\(d\)</span> が <span class="math inline">\(d = 5\sqrt{(t-3)^2+16}\)</span> を満たすことを示しなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(2\)</span> 隻が最も近づく時刻と、そのときの距離を求めなさい。</p>
<p><strong>(d)</strong> (c) の答えを、この <span class="math inline">\(2\)</span> 隻の文脈で解釈しなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> <a href="#eq-ahl312a-abt" class="quarto-xref">式&nbsp;5</a> のとおりです。</p>
<p><span class="math display">\[
\overrightarrow{AB} = \begin{pmatrix} 25 \\ 4t \end{pmatrix} - \begin{pmatrix} 3t \\ 0 \end{pmatrix} = \begin{pmatrix} 25-3t \\ 4t \end{pmatrix}
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(\sqrt{\ }\)</span> の中を先に整理します（<a href="#tbl-ahl312a-steps" class="quarto-xref">表&nbsp;2</a> のステップ <span class="math inline">\(2\)</span>）。</p>
<p><span class="math display">\[
d^2 = (25-3t)^2 + (4t)^2 = 625 - 150t + 9t^2 + 16t^2 = 25t^2 - 150t + 625
\]</span></p>
<p><span class="math inline">\(25\)</span> でくくって平方完成します。</p>
<p><span class="math display">\[
d^2 = 25\left(t^2 - 6t + 25\right) = 25\left((t-3)^2 - 9 + 25\right) = 25\left((t-3)^2 + 16\right)
\]</span></p>
<p><span class="math inline">\(d \geq 0\)</span> なので</p>
<p><span class="math display">\[
d = 5\sqrt{(t-3)^2+16}
\]</span></p>
<p><strong>(c)</strong> <span class="math inline">\((t-3)^2 \geq 0\)</span> で、<span class="math inline">\(t = 3\)</span> のときだけ <span class="math inline">\(0\)</span> になります。</p>
<p><span class="math display">\[
t = 3 \ \text{時間}, \qquad d = 5\sqrt{16} = 20 \ \text{km}
\]</span></p>
<p><span class="math inline">\(t = 3 \geq 0\)</span> なので、意味のある答えです（<a href="#tbl-ahl312a-steps" class="quarto-xref">表&nbsp;2</a> のステップ <span class="math inline">\(5\)</span>）。</p>
<p><strong>(d)</strong> <code>Interpret</code> なので、<strong>船の言葉</strong>で書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The ships start <span class="math inline">\(25\)</span> km apart and close on each other for three hours, after which they begin to separate again. The closest they ever come is <span class="math inline">\(20\)</span> km, three hours after the start. They never meet: the least distance is <span class="math inline">\(20\)</span> km, not <span class="math inline">\(0\)</span>, so there is no risk of collision on these courses.</em></p>
</div>
<p>（<span class="math inline">\(2\)</span> 隻は <span class="math inline">\(25\)</span> km 離れて出発し、<span class="math inline">\(3\)</span> 時間のあいだ近づき、そのあとはまた離れていく。もっとも近づくのは出発から <span class="math inline">\(3\)</span> 時間後で、そのときの距離は <span class="math inline">\(20\)</span> km である。<span class="math inline">\(2\)</span> 隻は出会わない。最小の距離が <span class="math inline">\(0\)</span> ではなく <span class="math inline">\(20\)</span> km なので、この進路では衝突の心配はない、という意味です。）</p>
<p><strong>検算。</strong> <span class="math inline">\(t = 3\)</span> での位置を、<strong>直接</strong>出します。</p>
<p><span class="math display">\[
\mathbf{r}_A(3) = \begin{pmatrix} 9 \\ 0 \end{pmatrix}, \qquad \mathbf{r}_B(3) = \begin{pmatrix} 25 \\ 12 \end{pmatrix}
\]</span></p>
<p><span class="math display">\[
\overrightarrow{AB} = \begin{pmatrix} 16 \\ 12 \end{pmatrix}, \qquad \lvert \overrightarrow{AB} \rvert = \sqrt{256+144} = \sqrt{400} = 20
\]</span></p>
<p><span class="math inline">\(20\)</span> km に戻りました ✓ <strong>多くの計算ミスは、これで見つかります。</strong></p>
<p>さらに <span class="math inline">\(t = 1\)</span> でも見ます。<span class="math inline">\(\mathbf{r}_A(1) = \begin{pmatrix} 3 \\ 0 \end{pmatrix}\)</span>、<span class="math inline">\(\mathbf{r}_B(1) = \begin{pmatrix} 25 \\ 4 \end{pmatrix}\)</span> で <span class="math inline">\(\lvert \overrightarrow{AB} \rvert = \sqrt{484+16} = \sqrt{500} \approx 22.4\)</span>、(b) の式でも <span class="math inline">\(5\sqrt{4+16} = 10\sqrt{5} \approx 22.4\)</span> ✓ <strong><span class="math inline">\(-150t\)</span> の項を落として <span class="math inline">\(d^2 = 25(t^2+25)\)</span> としていた場合、<span class="math inline">\(t = 0\)</span> では両方 <span class="math inline">\(25\)</span> で合ってしまいますが、<span class="math inline">\(t = 1\)</span> では <span class="math inline">\(5\sqrt{26} \approx 25.5\)</span> となり、ここで食い違います。</strong></p>
<p><strong>検算（(b) について）。</strong> <span class="math inline">\(t = 0\)</span> を入れます。<span class="math inline">\(d = 5\sqrt{9+16} = 5 \times 5 = 25\)</span> で、これは出発時の距離 <span class="math inline">\(25\)</span> km と一致します ✓</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 25-3t \\ 4t \end{pmatrix}\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[d^2 = (25-3t)^2+(4t)^2 = 25t^2-150t+625 = 25\left((t-3)^2+16\right)\]</span> <span class="math display">\[d = 5\sqrt{(t-3)^2+16}\]</span></p>
<p><strong>(c)</strong> <span class="math display">\[t = 3 \ \text{hours}, \qquad d = 5\sqrt{16} = 20 \ \text{km}\]</span></p>
<p><strong>(d)</strong> <em>The ships are closest three hours after the start, and even then they are <span class="math inline">\(20\)</span> km apart, so they do not meet.</em></p>
</div>
</div>
</div>
</section>
<section id="common-errors" class="level2">
<h2 class="anchored" data-anchor-id="common-errors">Common errors</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(\mathbf{r}_0\)</span> と <span class="math inline">\(\mathbf{v}\)</span> を取りちがえる
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\mathbf{r} = \mathbf{v}t + \mathbf{r}_0\)</span> と書くのは正しいのですが、<strong>中身を入れかえてしまう</strong>誤りです。</p>
<p><strong><span class="math inline">\(t\)</span> が掛かっているほうが速度</strong>です（<a href="#eq-ahl312a-r" class="quarto-xref">式&nbsp;2</a>）。<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#common-errors">AHL 3.11 の Common errors</a> と同じ形の誤りです。</p>
<p><strong>まず <span class="math inline">\(t = 0\)</span> を入れてください。</strong> 出発点が出なければ、入れかえています。<strong>ただし <span class="math inline">\(t = 0\)</span> だけでは足りません。</strong> <span class="math inline">\(t = 1\)</span> も入れて <span class="math inline">\(\mathbf{r}_0 + \mathbf{v}\)</span> になるかまで見てください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>「経路が交わる」を「衝突する」と結論する
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>このページで、いちばん多い誤りです</strong>（<a href="#cross-vs-collide">第4節</a>）。</p>
<p>交点を出したら、<strong>それぞれがそこにいる時刻</strong>まで出してください。時刻が違えば、衝突しません（<a href="#exm-ahl312a-cross" class="quarto-xref">例&nbsp;2</a>）。</p>
<p><code>Do the paths cross?</code> と <code>Do the particles collide?</code> は、別の問いです。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(\overrightarrow{AB}\)</span> を <span class="math inline">\(\mathbf{r}_A - \mathbf{r}_B\)</span> にする
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>行き先が先</strong>です（<a href="#eq-ahl312a-ab" class="quarto-xref">式&nbsp;4</a>）。<span class="math inline">\(\overrightarrow{AB} = \mathbf{r}_B - \mathbf{r}_A\)</span> です。</p>
<p><strong>衝突の判定と距離だけなら、逆でも答えは変わりません。</strong> <span class="math inline">\(\mathbf{0}\)</span> になる <span class="math inline">\(t\)</span> も、長さも同じだからです。</p>
<p><strong>しかし「<span class="math inline">\(A\)</span> から見た <span class="math inline">\(B\)</span> の位置」を聞かれたら、符号がすべて逆になって不正解</strong>です。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(d^2\)</span> の値を、距離として答える
</div>
</div>
<div class="callout-body-container callout-body">
<p>平方完成で <span class="math inline">\(d^2\)</span> の最小値 <span class="math inline">\(400\)</span> が出たとき、<strong><span class="math inline">\(400\)</span> km と答えてしまう</strong>誤りです。</p>
<p><strong>答えるのは <span class="math inline">\(d\)</span> です。</strong> <span class="math inline">\(\sqrt{400} = 20\)</span> km です（<a href="#closest">第8節</a>）。</p>
<p><strong>単位で気づけます。</strong> <span class="math inline">\(d^2\)</span> の単位は km<span class="math inline">\(^2\)</span> で、距離の単位ではありません。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(t &lt; 0\)</span> の答えを採用する
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(t\)</span> は時刻なので、ふつう <span class="math inline">\(t \geq 0\)</span> です。</p>
<p><span class="math inline">\(\overrightarrow{AB} = \mathbf{0}\)</span> を解いて <span class="math inline">\(t = -1\)</span> が出たら、それは「<strong>このまま逆回しにすれば重なる位置関係だった</strong>」というだけで、<strong>衝突ではありません</strong>（<a href="#exm-ahl312a-cross" class="quarto-xref">例&nbsp;2</a>）。</p>
<p><strong>最接近でも同じ</strong>です。頂点が <span class="math inline">\(t &lt; 0\)</span> にあるなら、<span class="math inline">\(t \geq 0\)</span> の範囲では <strong><span class="math inline">\(t = 0\)</span> がいちばん近い</strong>ことになります。</p>
</div>
</div>
</section>
<section id="using-your-gdc-ti-nspire-cx-ii" class="level2">
<h2 class="anchored" data-anchor-id="using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</h2>
<section id="gdc-position" class="level3">
<h3 class="anchored" data-anchor-id="gdc-position">1. 位置は、代入で出せます</h3>
<p><strong>Matrix</strong> として入れて、そのまま計算します（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-10a.html#gdc-enter">AHL 3.10a の GDC 第1節</a>）。</p>
<p><span class="math inline">\(\begin{bmatrix} -3 \\ 7 \end{bmatrix}+5 \times \begin{bmatrix} 4 \\ -2 \end{bmatrix}\)</span></p>
<p><span class="math inline">\(\begin{pmatrix} 17 \\ -3 \end{pmatrix}\)</span> が返ります（<a href="#exm-ahl312a-position" class="quarto-xref">例&nbsp;1</a>）。</p>
</section>
<section id="gdc-store" class="level3">
<h3 class="anchored" data-anchor-id="gdc-store">2. 名前を付けておくと、<span class="math inline">\(t\)</span> を変えるのが楽です</h3>
<ul>
<li><span class="math inline">\(\begin{bmatrix} 1 \\ 2 \end{bmatrix}  \ \to \  ra\)</span></li>
<li><span class="math inline">\(\begin{bmatrix} 2 \\ 3 \end{bmatrix}  \ \to \  va\)</span></li>
<li><span class="math inline">\(\begin{bmatrix} 13 \\ 0 \end{bmatrix}  \ \to \  rb\)</span></li>
<li><span class="math inline">\(\begin{bmatrix} -2 \\ 1 \end{bmatrix}  \ \to \  vb\)</span></li>
</ul>
<p>矢印 <code>→</code> は、<strong><code>ctrl</code> を押してから <code>var</code></strong> です（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-10a.html#gdc-store">AHL 3.10a の GDC 第2節</a>）。</p>
<p>そのあとは <code>ra+1*va</code>、<code>rb+5*vb</code> と打つだけです。</p>
<p><strong><span class="math inline">\(\overrightarrow{AB}\)</span> も <span class="math inline">\(1\)</span> 行で出せます。</strong></p>
<pre><code>(rb+3*vb)-(ra+3*va)</code></pre>
<p><strong><span class="math inline">\(1\)</span> つの問題が終わったら、変数を消しておいてください</strong>（<code>menu → Actions → Clear a-z</code>）。</p>
</section>
<section id="gdc-linsolve" class="level3">
<h3 class="anchored" data-anchor-id="gdc-linsolve">3. 交点は、連立方程式として</h3>
<p><code>menu → Algebra</code> の中の <strong>Solve System of Linear Equations</strong> を使います（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#gdc-linsolve">AHL 3.11 の GDC 第3節</a>）。</p>
<p><a href="#exm-ahl312a-cross" class="quarto-xref">例&nbsp;2</a> なら、変数 <span class="math inline">\(p\)</span>、<span class="math inline">\(q\)</span> として</p>
<pre><code>1+2*p = 13-2*q
2+3*p = q</code></pre>
<p><span class="math inline">\(\{1,\ 5\}\)</span> が返ります。<strong>この <span class="math inline">\(2\)</span> つが、それぞれの到着時刻</strong>です。</p>
<p><strong>値が違うことを、そのまま答えに使ってください。</strong> 電卓は「衝突するか」までは教えてくれません。</p>
</section>
<section id="gdc-graph" class="level3">
<h3 class="anchored" data-anchor-id="gdc-graph">4. 距離のグラフで、最接近を見る</h3>
<p><code>ctrl + doc</code> でページを足して Graphs を開き、<span class="math inline">\(d\)</span> を <span class="math inline">\(x\)</span> の関数として入れます。</p>
<p><span class="math inline">\(f1(x) = \sqrt{\left(25 - 3x\right)^{2} + \left(4x\right)^{2}}\)</span></p>
<p><strong>電卓の変数は <span class="math inline">\(x\)</span> です。</strong> ここでは <span class="math inline">\(x\)</span> が時刻 <span class="math inline">\(t\)</span> のつもりです。</p>
<p><code>menu → Analyze Graph → Minimum</code> で、<span class="math inline">\(x\)</span> の下限と上限を聞かれるので、頂点をはさむように選びます。<span class="math inline">\((3,\ 20)\)</span> が出れば、<a href="#exm-ahl312a-closest" class="quarto-xref">例&nbsp;4</a> と合っています。</p>
<p><strong>これは関数のグラフなので <code>Analyze Graph</code> が使えます。</strong> <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#gdc-graph">AHL 3.11</a> で parametric を使ったときとは違います。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>グラフは見当を付けるためのものです
</div>
</div>
<div class="callout-body-container callout-body">
<p>答案には、<strong>平方完成の過程</strong>を書いてください（<a href="#tbl-ahl312a-steps" class="quarto-xref">表&nbsp;2</a>）。</p>
<p><code>Show that</code> と指定されている問題では、<strong>グラフだけでは点がもらえません。</strong></p>
</div>
</div>
</section>
<section id="gdc-table" class="level3">
<h3 class="anchored" data-anchor-id="gdc-table">5. 表で、近づき方を見る</h3>
<p>グラフのページで <code>ctrl + T</code> を押すと、表が出ます。<span class="math inline">\(x = 0,\ 1,\ 2,\ \ldots\)</span> の <span class="math inline">\(d\)</span> が並ぶので、<strong>どこで折り返すか</strong>が見えます。</p>
<p><a href="#exm-ahl312a-closest" class="quarto-xref">例&nbsp;4</a> なら <span class="math inline">\(25,\ 22.36,\ 20.62,\ 20,\ 20.62,\ 22.36\)</span> と並び、<strong><span class="math inline">\(x = 3\)</span> で折り返している</strong>ことが分かります。</p>
<p><strong>表の刻みは、はじめ <span class="math inline">\(1\)</span> です</strong>（変えられます）。頂点がちょうど整数でないときは、刻みを細かくするか、<a href="#gdc-graph">GDC 第4節</a> の <code>Analyze Graph</code> を使ってください。</p>
</section>
<section id="gdc-check" class="level3">
<h3 class="anchored" data-anchor-id="gdc-check">6. 検算のしかた</h3>
<ul>
<li><strong><span class="math inline">\(t = 0\)</span> を入れる。</strong> 出発点が出るか見る（<a href="#exm-ahl312a-position" class="quarto-xref">例&nbsp;1</a>）</li>
<li><strong>最接近の <span class="math inline">\(t\)</span> での位置を、直接出す。</strong> そこから <span class="math inline">\(\lvert \overrightarrow{AB} \rvert\)</span> を計算して、答えと合うか見る（<a href="#exm-ahl312a-closest" class="quarto-xref">例&nbsp;4</a>）</li>
<li><strong>交点は、使っていないほうの式に入れる</strong>（<a href="#exm-ahl312a-cross" class="quarto-xref">例&nbsp;2</a>）</li>
<li><strong><span class="math inline">\(d\)</span> の式に <span class="math inline">\(t = 0\)</span> を入れる。</strong> はじめの距離に戻るか見る</li>
<li><strong><span class="math inline">\(t \geq 0\)</span> を確かめる</strong></li>
</ul>
<p><span class="math inline">\(2\)</span> つ目がいちばん強い検算です。<strong><span class="math inline">\(t\)</span> を <span class="math inline">\(2\)</span> つ選んで両方で合わせる</strong>と、平方完成で項を落とした誤りまで見つかります（<a href="#exm-ahl312a-closest" class="quarto-xref">例&nbsp;4</a>）。</p>
</section>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>各問題に、折りたたみが <span class="math inline">\(3\)</span> つ付いています。<strong>日本語訳</strong>、<strong>解答例</strong>（答案用紙に書くべきこと。英語です）、<strong>解説</strong>（なぜそうなるか。日本語です）。</p>
<p>まず自分で解いて、次に解答例と見くらべてください。<strong>解説は、合わなかったときだけ開けば十分です。</strong></p>
</div>
</div>
</div>
<div class="exercise-block">
<p><span class="ex-no">1</span> <span class="q-en">A particle starts at <span class="math inline">\((2,\ -5)\)</span> and moves with constant velocity <span class="math inline">\(\begin{pmatrix} -1 \\ 3 \end{pmatrix}\)</span> m s<span class="math inline">\(^{-1}\)</span>. Find its position after <span class="math inline">\(4\)</span> seconds, and its speed to <span class="math inline">\(3\)</span> significant figures.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある粒子が <span class="math inline">\((2,\ -5)\)</span> を出発し、一定の速度 <span class="math inline">\(\begin{pmatrix} -1 \\ 3 \end{pmatrix}\)</span> m s<span class="math inline">\(^{-1}\)</span> で動きます。<span class="math inline">\(4\)</span> 秒後の位置と、速さを有効数字 <span class="math inline">\(3\)</span> 桁で求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[\begin{pmatrix} 2 \\ -5 \end{pmatrix} + 4\begin{pmatrix} -1 \\ 3 \end{pmatrix} = \begin{pmatrix} -2 \\ 7 \end{pmatrix}, \qquad \lvert \mathbf{v} \rvert = \sqrt{(-1)^2+3^2} = \sqrt{10} \approx 3.16 \ \text{m s}^{-1}\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>代入するだけです（<a href="#eq-ahl312a-r" class="quarto-xref">式&nbsp;2</a>）。<strong><span class="math inline">\(-5+12 = 7\)</span></strong> で、符号に注意してください。</p>
<p>速さは <span class="math inline">\(\lvert \mathbf{v} \rvert\)</span> です（<a href="#eq-ahl312a-speed" class="quarto-xref">式&nbsp;3</a>）。<span class="math inline">\(\sqrt{10}\)</span> は整数になりません。</p>
<p><strong>検算。</strong> 変位が <span class="math inline">\(4\mathbf{v}\)</span> になるはずです。<span class="math inline">\(\begin{pmatrix} -2 \\ 7 \end{pmatrix}-\begin{pmatrix} 2 \\ -5 \end{pmatrix} = \begin{pmatrix} -4 \\ 12 \end{pmatrix} = 4\begin{pmatrix} -1 \\ 3 \end{pmatrix}\)</span> ✓ <strong><span class="math inline">\(-5+12\)</span> を <span class="math inline">\(-17\)</span> としていたら、差の <span class="math inline">\(2\)</span> つ目が <span class="math inline">\(-12\)</span> になり、<span class="math inline">\(4\mathbf{v}\)</span> になりません。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">2</span> <span class="q-en">A particle has position vector <span class="math inline">\(\mathbf{r} = \begin{pmatrix} 6 \\ 1 \end{pmatrix} + t\begin{pmatrix} -2 \\ 4 \end{pmatrix}\)</span> at time <span class="math inline">\(t\)</span> seconds. Find the time at which the particle is at the point <span class="math inline">\((0,\ 13)\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある粒子の時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは <span class="math inline">\(\mathbf{r} = \begin{pmatrix} 6 \\ 1 \end{pmatrix} + t\begin{pmatrix} -2 \\ 4 \end{pmatrix}\)</span> です。この粒子が点 <span class="math inline">\((0,\ 13)\)</span> にいる時刻を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[6-2t = 0 \ \Rightarrow \ t = 3; \qquad 1+4(3) = 13 \ \checkmark\]</span></p>
<p><em>The particle is at <span class="math inline">\((0,\ 13)\)</span> when <span class="math inline">\(t = 3\)</span> s.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(1\)</span> 成分から <span class="math inline">\(t\)</span> を求め、<strong>もう一方でも合うことを確かめます</strong>（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#on-line">AHL 3.11 第6節</a> と同じ考え方）。</p>
<p><strong><span class="math inline">\(x\)</span> だけ見て「<span class="math inline">\(t = 3\)</span>」で止めないでください。</strong> <span class="math inline">\(y\)</span> が合わなければ、その点を通っていません。</p>
<p><strong>検算。</strong> <span class="math inline">\(t = 3\)</span> をもとの式に入れ直します。<span class="math inline">\(\begin{pmatrix} 6 \\ 1 \end{pmatrix}+3\begin{pmatrix} -2 \\ 4 \end{pmatrix} = \begin{pmatrix} 0 \\ 13 \end{pmatrix}\)</span> ✓ <strong><span class="math inline">\(1+12\)</span> を <span class="math inline">\(13\)</span> 以外にしていたら、ここで合いません。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">3</span> <span class="q-en">A particle starts at <span class="math inline">\((1,\ 0,\ -2)\)</span> and moves with constant velocity <span class="math inline">\(\begin{pmatrix} 2 \\ -3 \\ 1 \end{pmatrix}\)</span>. Write down its position vector at time <span class="math inline">\(t\)</span>, and find its position when <span class="math inline">\(t = 6\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある粒子が <span class="math inline">\((1,\ 0,\ -2)\)</span> を出発し、一定の速度 <span class="math inline">\(\begin{pmatrix} 2 \\ -3 \\ 1 \end{pmatrix}\)</span> で動きます。時刻 <span class="math inline">\(t\)</span> における位置ベクトルを書き、<span class="math inline">\(t = 6\)</span> のときの位置を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[\mathbf{r} = \begin{pmatrix} 1 \\ 0 \\ -2 \end{pmatrix} + t\begin{pmatrix} 2 \\ -3 \\ 1 \end{pmatrix}, \qquad \mathbf{r}(6) = \begin{pmatrix} 13 \\ -18 \\ 4 \end{pmatrix}\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(3\)</span> 次元でも同じです（<a href="#three-d">第9節</a>）。<strong><span class="math inline">\(3\)</span> つとも <span class="math inline">\(6\)</span> 倍して足します。</strong></p>
<p><span class="math inline">\(-2+6 = 4\)</span> です。<strong><span class="math inline">\(3\)</span> つ目を落とさない</strong>でください。</p>
<p><strong>検算。</strong> 変位が <span class="math inline">\(6\mathbf{v}\)</span> になるはずです。<span class="math inline">\(\begin{pmatrix} 13 \\ -18 \\ 4 \end{pmatrix}-\begin{pmatrix} 1 \\ 0 \\ -2 \end{pmatrix} = \begin{pmatrix} 12 \\ -18 \\ 6 \end{pmatrix} = 6\begin{pmatrix} 2 \\ -3 \\ 1 \end{pmatrix}\)</span> ✓ <strong><span class="math inline">\(3\)</span> つ目を <span class="math inline">\(2\)</span> としていたら、差が <span class="math inline">\(4\)</span> になって <span class="math inline">\(6\mathbf{v}\)</span> に合いません。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">4</span> <span class="q-en">Two particles have position vectors at time <span class="math inline">\(t\)</span> seconds</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 0 \\ 4 \end{pmatrix} + t\begin{pmatrix} 3 \\ -1 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 10 \\ -6 \end{pmatrix} + t\begin{pmatrix} -2 \\ 4 \end{pmatrix}
\]</span></p>
<p><strong>(a)</strong> <span class="q-en">Find <span class="math inline">\(\overrightarrow{AB}\)</span> in terms of <span class="math inline">\(t\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Show that the particles collide, and find the time and the position of the collision.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの粒子の、時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは上のとおりです。</p>
<p><strong>(a)</strong> <span class="math inline">\(\overrightarrow{AB}\)</span> を <span class="math inline">\(t\)</span> の式で求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(2\)</span> つが衝突することを示し、その時刻と位置を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 10-5t \\ -10+5t \end{pmatrix}\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[10-5t = 0 \ \Rightarrow \ t = 2; \qquad -10+5t = 0 \ \Rightarrow \ t = 2\]</span> <span class="math display">\[\mathbf{r}_A(2) = \begin{pmatrix} 6 \\ 2 \end{pmatrix} = \mathbf{r}_B(2)\]</span> <em>The particles collide at <span class="math inline">\((6,\ 2)\)</span> when <span class="math inline">\(t = 2\)</span> s.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\overrightarrow{AB} = \mathbf{r}_B - \mathbf{r}_A\)</span> です（<a href="#eq-ahl312a-ab" class="quarto-xref">式&nbsp;4</a>）。<span class="math inline">\(-6-4 = -10\)</span>、<span class="math inline">\(4-(-1) = 5\)</span> で、<strong>符号を <span class="math inline">\(2\)</span> か所とも間違えない</strong>でください。</p>
<p><span class="math inline">\(2\)</span> 成分とも <span class="math inline">\(t = 2\)</span> でそろい、<span class="math inline">\(t \geq 0\)</span> も満たします（<a href="#eq-ahl312a-collide" class="quarto-xref">式&nbsp;6</a>）。</p>
<p><strong>検算。</strong> <span class="math inline">\(t = 2\)</span> を<strong>両方の式</strong>に入れます。<span class="math inline">\(\begin{pmatrix} 0 \\ 4 \end{pmatrix}+2\begin{pmatrix} 3 \\ -1 \end{pmatrix} = \begin{pmatrix} 6 \\ 2 \end{pmatrix}\)</span>、<span class="math inline">\(\begin{pmatrix} 10 \\ -6 \end{pmatrix}+2\begin{pmatrix} -2 \\ 4 \end{pmatrix} = \begin{pmatrix} 6 \\ 2 \end{pmatrix}\)</span> ✓ <strong>同じ点になりました。片方だけでは、衝突の確認になりません。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">5</span> <span class="q-en">Two particles have position vectors at time <span class="math inline">\(t\)</span> seconds</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 1 \\ 1 \end{pmatrix} + t\begin{pmatrix} 2 \\ 2 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 9 \\ 1 \end{pmatrix} + t\begin{pmatrix} -1 \\ 3 \end{pmatrix}
\]</span></p>
<p><strong>(a)</strong> <span class="q-en">Show that the paths cross, and find the point where they cross.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the time at which each particle is at that point.</span></p>
<p><strong>(c)</strong> <span class="q-en">State, with a reason, whether the particles collide.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの粒子の、時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは上のとおりです。</p>
<p><strong>(a)</strong> <span class="math inline">\(2\)</span> つの経路が交わることを示し、交わる点を求めなさい。</p>
<p><strong>(b)</strong> それぞれの粒子が、その点にいる時刻を求めなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(2\)</span> つが衝突するかどうかを、理由を付けて答えなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[1+2\lambda = 9-\mu, \qquad 1+2\lambda = 1+3\mu\]</span> <span class="math display">\[\lambda = 3, \quad \mu = 2, \qquad \text{crossing point } (7,\ 7)\]</span></p>
<p><strong>(b)</strong> <em><span class="math inline">\(A\)</span> is there at <span class="math inline">\(t = 3\)</span> s; <span class="math inline">\(B\)</span> is there at <span class="math inline">\(t = 2\)</span> s.</em></p>
<p><strong>(c)</strong> <em>No.&nbsp;The particles reach <span class="math inline">\((7,\ 7)\)</span> at different times, so they are never in the same place at the same time.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 経路の交点なので、文字は <span class="math inline">\(2\)</span> 種類です（<a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html#intersect">AHL 3.11 第9節</a>）。<span class="math inline">\(2\)</span> 本目から <span class="math inline">\(2\lambda = 3\mu\)</span>、<span class="math inline">\(1\)</span> 本目に入れて <span class="math inline">\(1+3\mu = 9-\mu\)</span>、つまり <span class="math inline">\(\mu = 2\)</span>、<span class="math inline">\(\lambda = 3\)</span> です。</p>
<p><strong>(b)</strong> <span class="math inline">\(\lambda\)</span> と <span class="math inline">\(\mu\)</span> が、そのまま時刻です。</p>
<p><strong>(c)</strong> <code>State, with a reason</code> なので、<strong>答えと理由の両方</strong>が要ります（<a href="#cross-vs-collide">第4節</a>）。</p>
<p><strong>検算。</strong> <span class="math inline">\(\overrightarrow{AB}\)</span> でも見ます。<span class="math inline">\(\overrightarrow{AB} = \begin{pmatrix} 9-t \\ 1+3t \end{pmatrix}-\begin{pmatrix} 1+2t \\ 1+2t \end{pmatrix} = \begin{pmatrix} 8-3t \\ t \end{pmatrix}\)</span> です。<span class="math inline">\(8-3t = 0\)</span> から <span class="math inline">\(t = \dfrac{8}{3}\)</span>、<span class="math inline">\(2\)</span> つ目の成分は <span class="math inline">\(t\)</span> そのものなので <span class="math inline">\(0\)</span> になるのは <span class="math inline">\(t = 0\)</span> のときだけで、<strong>そろいません</strong> ✗ 衝突しないことが、別の道でも出ました。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>No, the particles do not collide. The paths do share the point <span class="math inline">\((7,\ 7)\)</span>, but <span class="math inline">\(A\)</span> arrives there at <span class="math inline">\(t = 3\)</span> and <span class="math inline">\(B\)</span> at <span class="math inline">\(t = 2\)</span>, so <span class="math inline">\(B\)</span> has already passed through a second before <span class="math inline">\(A\)</span> gets there. Equivalently, <span class="math inline">\(\overrightarrow{AB} = \begin{pmatrix} 8-3t \\ t \end{pmatrix}\)</span> is never the zero vector, since the second component is <span class="math inline">\(0\)</span> only at <span class="math inline">\(t = 0\)</span>, where the first component is <span class="math inline">\(8\)</span>.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">6</span> <span class="q-en">Two particles have position vectors at time <span class="math inline">\(t\)</span> seconds</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 0 \\ 0 \end{pmatrix} + t\begin{pmatrix} 1 \\ 0 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 0 \\ 5 \end{pmatrix} + t\begin{pmatrix} 1 \\ 0 \end{pmatrix}
\]</span></p>
<p><span class="q-en">Find <span class="math inline">\(\overrightarrow{AB}\)</span> in terms of <span class="math inline">\(t\)</span>, and hence find the distance between the particles at time <span class="math inline">\(t\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの粒子の、時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは上のとおりです。</p>
<p><span class="math inline">\(\overrightarrow{AB}\)</span> を <span class="math inline">\(t\)</span> の式で求め、それを使って時刻 <span class="math inline">\(t\)</span> における <span class="math inline">\(2\)</span> 粒子の距離を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 0 \\ 5 \end{pmatrix}, \qquad d = 5\]</span></p>
<p><em>The distance is <span class="math inline">\(5\)</span> for every value of <span class="math inline">\(t\)</span>.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>速度が同じ</strong>なので、相対速度 <span class="math inline">\(\mathbf{v}_B - \mathbf{v}_A\)</span> が <span class="math inline">\(\mathbf{0}\)</span> になります（<a href="#eq-ahl312a-abt" class="quarto-xref">式&nbsp;5</a>）。ですから <span class="math inline">\(\overrightarrow{AB}\)</span> に <span class="math inline">\(t\)</span> が残りません。</p>
<p><strong><span class="math inline">\(2\)</span> 粒子は、ずっと <span class="math inline">\(5\)</span> m 離れたまま平行に進みます。</strong> 最接近を聞かれても、<span class="math inline">\(d^2\)</span> は <span class="math inline">\(t\)</span> の <span class="math inline">\(2\)</span> 次式にならず、定数です。</p>
<p><strong>検算。</strong> <span class="math inline">\(t = 0\)</span>、<span class="math inline">\(t = 1\)</span>、<span class="math inline">\(t = 10\)</span> で位置を出します。<span class="math inline">\(A\)</span> は <span class="math inline">\((0,0)\)</span>、<span class="math inline">\((1,0)\)</span>、<span class="math inline">\((10,0)\)</span>、<span class="math inline">\(B\)</span> は <span class="math inline">\((0,5)\)</span>、<span class="math inline">\((1,5)\)</span>、<span class="math inline">\((10,5)\)</span> です。どの時刻でも <span class="math inline">\(\overrightarrow{AB} = \begin{pmatrix} 0 \\ 5 \end{pmatrix}\)</span> ✓ <strong><span class="math inline">\(t\)</span> が消えたのは計算ミスではありません。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">7</span> <span class="q-en">Two aircraft have position vectors at time <span class="math inline">\(t\)</span> hours, in kilometres,</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 10 \\ 30 \end{pmatrix} + t\begin{pmatrix} 2 \\ 1 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 10 \\ 5 \end{pmatrix} + t\begin{pmatrix} 5 \\ 5 \end{pmatrix}
\]</span></p>
<p><strong>(a)</strong> <span class="q-en">Find <span class="math inline">\(\overrightarrow{AB}\)</span> in terms of <span class="math inline">\(t\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Show that the distance <span class="math inline">\(d\)</span> between them satisfies <span class="math inline">\(d = 5\sqrt{(t-4)^2+9}\)</span>.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the time at which they are closest, and the least distance between them.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> 機の航空機の、時刻 <span class="math inline">\(t\)</span> 時間における位置ベクトルは、km 単位で上のとおりです。</p>
<p><strong>(a)</strong> <span class="math inline">\(\overrightarrow{AB}\)</span> を <span class="math inline">\(t\)</span> の式で求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(2\)</span> 機の距離 <span class="math inline">\(d\)</span> が <span class="math inline">\(d = 5\sqrt{(t-4)^2+9}\)</span> を満たすことを示しなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(2\)</span> 機が最も近づく時刻と、そのときの距離を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 3t \\ -25+4t \end{pmatrix}\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[d^2 = (3t)^2+(4t-25)^2 = 25t^2-200t+625 = 25\left((t-4)^2+9\right)\]</span> <span class="math display">\[d = 5\sqrt{(t-4)^2+9}\]</span></p>
<p><strong>(c)</strong> <span class="math display">\[t = 4 \ \text{hours}, \qquad d = 5\sqrt{9} = 15 \ \text{km}\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><a href="#tbl-ahl312a-steps" class="quarto-xref">表&nbsp;2</a> の <span class="math inline">\(5\)</span> 段そのものです。</p>
<p><strong>(a)</strong> <span class="math inline">\(10-10 = 0\)</span>、<span class="math inline">\(5-30 = -25\)</span>、速度の差は <span class="math inline">\(\begin{pmatrix} 3 \\ 4 \end{pmatrix}\)</span> です。</p>
<p><strong>(b)</strong> <span class="math inline">\(9t^2 + 16t^2 - 200t + 625 = 25t^2-200t+625\)</span> です。<span class="math inline">\(25\)</span> でくくると <span class="math inline">\(25(t^2-8t+25) = 25((t-4)^2-16+25)\)</span> です。</p>
<p><strong>(c)</strong> <span class="math inline">\(t = 4 \geq 0\)</span> なので、意味のある答えです。<strong><span class="math inline">\(d^2 = 225\)</span> ではなく <span class="math inline">\(d = 15\)</span></strong> と答えてください。</p>
<p><strong>検算。</strong> <span class="math inline">\(t = 4\)</span> での位置を直接出します。<span class="math inline">\(\mathbf{r}_A(4) = \begin{pmatrix} 18 \\ 34 \end{pmatrix}\)</span>、<span class="math inline">\(\mathbf{r}_B(4) = \begin{pmatrix} 30 \\ 25 \end{pmatrix}\)</span> で、<span class="math inline">\(\overrightarrow{AB} = \begin{pmatrix} 12 \\ -9 \end{pmatrix}\)</span>、<span class="math inline">\(\lvert \overrightarrow{AB} \rvert = \sqrt{144+81} = 15\)</span> ✓ <strong>平方完成を <span class="math inline">\((t-4)^2+16\)</span> などと間違えていたら、<span class="math inline">\(20\)</span> になって合いません。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">8</span> <span class="q-en">Two particles have position vectors at time <span class="math inline">\(t\)</span> seconds</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix} + t\begin{pmatrix} 1 \\ 0 \\ -1 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 5 \\ 2 \\ -1 \end{pmatrix} + t\begin{pmatrix} -1 \\ 0 \\ 1 \end{pmatrix}
\]</span></p>
<p><span class="q-en">Show that the particles collide, and find the time and the position of the collision.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの粒子の、時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは上のとおりです。</p>
<p><span class="math inline">\(2\)</span> つが衝突することを示し、その時刻と位置を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 4-2t \\ 0 \\ -4+2t \end{pmatrix}\]</span></p>
<p><span class="math display">\[4-2t = 0 \ \Rightarrow \ t = 2; \qquad -4+2t = 0 \ \Rightarrow \ t = 2\]</span></p>
<p><em>The middle component is <span class="math inline">\(0\)</span> for every <span class="math inline">\(t\)</span>, so all three components vanish at <span class="math inline">\(t = 2\)</span> s.</em></p>
<p><span class="math display">\[\mathbf{r}_A(2) = \begin{pmatrix} 3 \\ 2 \\ 1 \end{pmatrix} = \mathbf{r}_B(2)\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(3\)</span> 次元でも手順は同じです（<a href="#three-d">第9節</a>）。</p>
<p><strong><span class="math inline">\(2\)</span> つ目の成分は、<span class="math inline">\(t\)</span> によらず <span class="math inline">\(0\)</span></strong> です。<span class="math inline">\(2\)</span> 粒子は、その向きにはずっと同じところにいます。<strong>この成分は、はじめから満たされています</strong>（<a href="#collide-test">第6節</a> の callout）。</p>
<p>残りの <span class="math inline">\(2\)</span> 成分がどちらも <span class="math inline">\(t = 2\)</span> でそろうので、衝突します。</p>
<p><strong>検算。</strong> <span class="math inline">\(t = 2\)</span> を<strong>両方の式</strong>に入れます。<span class="math inline">\(\begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}+2\begin{pmatrix} 1 \\ 0 \\ -1 \end{pmatrix} = \begin{pmatrix} 3 \\ 2 \\ 1 \end{pmatrix}\)</span>、<span class="math inline">\(\begin{pmatrix} 5 \\ 2 \\ -1 \end{pmatrix}+2\begin{pmatrix} -1 \\ 0 \\ 1 \end{pmatrix} = \begin{pmatrix} 3 \\ 2 \\ 1 \end{pmatrix}\)</span> ✓ <strong><span class="math inline">\(3\)</span> 成分とも一致しました。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">9</span> <span class="q-en">A boat leaves a harbour at <span class="math inline">\(09{:}00\)</span> and travels with constant velocity <span class="math inline">\(\begin{pmatrix} 12 \\ 5 \end{pmatrix}\)</span> km h<span class="math inline">\(^{-1}\)</span>. Take the harbour as the origin, and let <span class="math inline">\(t\)</span> be the number of hours after <span class="math inline">\(09{:}00\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the position of the boat at <span class="math inline">\(11{:}30\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the speed of the boat.</span></p>
<p><strong>(c)</strong> <span class="q-en">Interpret the answer to part (b) in the context of the voyage.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある船が <span class="math inline">\(9\)</span> 時に港を出て、一定の速度 <span class="math inline">\(\begin{pmatrix} 12 \\ 5 \end{pmatrix}\)</span> km h<span class="math inline">\(^{-1}\)</span> で進みます。港を原点とし、<span class="math inline">\(t\)</span> を <span class="math inline">\(9\)</span> 時からの時間数とします。</p>
<p><strong>(a)</strong> <span class="math inline">\(11\)</span> 時 <span class="math inline">\(30\)</span> 分における船の位置を求めなさい。</p>
<p><strong>(b)</strong> この船の速さを求めなさい。</p>
<p><strong>(c)</strong> (b) の答えを、この航海の文脈で解釈しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[t = 2.5: \qquad 2.5\begin{pmatrix} 12 \\ 5 \end{pmatrix} = \begin{pmatrix} 30 \\ 12.5 \end{pmatrix}\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[\lvert \mathbf{v} \rvert = \sqrt{12^2+5^2} = 13 \ \text{km h}^{-1}\]</span></p>
<p><strong>(c)</strong> <em>The boat covers <span class="math inline">\(13\)</span> km of sea every hour, in a fixed direction. After <span class="math inline">\(2.5\)</span> hours it is <span class="math inline">\(2.5 \times 13 = 32.5\)</span> km from the harbour in a straight line.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(9\)</span> 時から <span class="math inline">\(11\)</span> 時 <span class="math inline">\(30\)</span> 分までは <span class="math inline">\(2.5\)</span> 時間です。<strong><span class="math inline">\(t\)</span> の原点を取りちがえない</strong>でください（<a href="#idea">第1節</a> の callout）。</p>
<p><strong>(b)</strong> <span class="math inline">\(\lvert \mathbf{v} \rvert = \sqrt{144+25} = 13\)</span> です。</p>
<p><strong>(c)</strong> <code>Interpret</code> なので、<strong>船の言葉</strong>で書きます。<strong>「<span class="math inline">\(13\)</span> です」だけでは足りません。</strong></p>
<p><strong>検算。</strong> 港からの距離を <span class="math inline">\(2\)</span> 通りで出します。位置から <span class="math inline">\(\sqrt{30^2+12.5^2} = \sqrt{1056.25} = 32.5\)</span> km、速さからは <span class="math inline">\(2.5 \times 13 = 32.5\)</span> km ✓ <strong>等速度なので、この <span class="math inline">\(2\)</span> つは一致します。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The speed <span class="math inline">\(13\ \text{km h}^{-1}\)</span> is how much sea the boat covers each hour, regardless of direction. Because the velocity is constant, the boat travels in a straight line, so after <span class="math inline">\(2.5\)</span> hours it has covered <span class="math inline">\(2.5 \times 13 = 32.5\)</span> km and is exactly <span class="math inline">\(32.5\)</span> km from the harbour. If the boat had changed course, the distance travelled would still be <span class="math inline">\(32.5\)</span> km but the distance from the harbour would be less.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">10</span> <span class="q-en">Two particles have position vectors at time <span class="math inline">\(t\)</span> seconds</span></p>
<p><span class="math display">\[
\mathbf{r}_A = \begin{pmatrix} 2 \\ 1 \end{pmatrix} + t\begin{pmatrix} 1 \\ 3 \end{pmatrix}, \qquad \mathbf{r}_B = \begin{pmatrix} 8 \\ -5 \end{pmatrix} + t\begin{pmatrix} -1 \\ 3 \end{pmatrix}
\]</span></p>
<p><span class="q-en">A student finds that the paths cross at <span class="math inline">\((4,\ 7)\)</span> and concludes that the particles collide there. Identify the error and give the correct conclusion.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの粒子の、時刻 <span class="math inline">\(t\)</span> 秒における位置ベクトルは上のとおりです。</p>
<p>ある生徒が、経路は <span class="math inline">\((4,\ 7)\)</span> で交わると求め、そこで <span class="math inline">\(2\)</span> 粒子が衝突すると結論しました。誤りを指摘し、正しい結論を書きなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>The crossing point is correct, but crossing paths do not imply a collision: the times must agree as well.</em></p>
<p><span class="math display">\[\overrightarrow{AB} = \begin{pmatrix} 6-2t \\ -6 \end{pmatrix}\]</span></p>
<p><em>The second component is <span class="math inline">\(-6\)</span> for every <span class="math inline">\(t\)</span>, so <span class="math inline">\(\overrightarrow{AB}\)</span> is never <span class="math inline">\(\mathbf{0}\)</span> and the particles never collide.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>Identify the error</code> なので、<strong>どこが違うのかを名指し</strong>してから、正しい結論を書きます。</p>
<p><strong>交点 <span class="math inline">\((4,\ 7)\)</span> 自体は合っています。</strong> 誤っているのは、そこから衝突を結論したところです（<a href="#cross-vs-collide">第4節</a>）。</p>
<p><span class="math inline">\(\overrightarrow{AB}\)</span> を見ると、<strong><span class="math inline">\(2\)</span> つ目の成分が <span class="math inline">\(t\)</span> によらず <span class="math inline">\(-6\)</span></strong> です。<span class="math inline">\(0\)</span> になりようがないので、衝突しません（<a href="#collide-test">第6節</a> の callout）。</p>
<p><span class="math inline">\(2\)</span> 粒子は<strong>同じ <span class="math inline">\(y\)</span> 方向の速度 <span class="math inline">\(3\)</span></strong> を持っているので、<span class="math inline">\(y\)</span> 方向の差 <span class="math inline">\(-6\)</span> が縮まりません。</p>
<p><strong>検算。</strong> 時刻でも見ます。<span class="math inline">\(A\)</span> は <span class="math inline">\(2+\lambda = 4\)</span> から <span class="math inline">\(t = 2\)</span>、<span class="math inline">\(B\)</span> は <span class="math inline">\(8-\mu = 4\)</span> から <span class="math inline">\(t = 4\)</span> です。<strong><span class="math inline">\(2\)</span> 秒ずれています</strong> ✓ どちらの道でも「衝突しない」が出ました。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The student’s crossing point is right, but the conclusion is not. Two paths crossing means the two straight lines share a point; a collision needs both particles to be at that point at the same time. Here <span class="math inline">\(A\)</span> reaches <span class="math inline">\((4,\ 7)\)</span> at <span class="math inline">\(t = 2\)</span> and <span class="math inline">\(B\)</span> reaches it at <span class="math inline">\(t = 4\)</span>. More directly, <span class="math inline">\(\overrightarrow{AB} = \mathbf{r}_B - \mathbf{r}_A = \begin{pmatrix} 6-2t \\ -6 \end{pmatrix}\)</span>, whose second component is <span class="math inline">\(-6\)</span> for every <span class="math inline">\(t\)</span>, so <span class="math inline">\(\overrightarrow{AB}\)</span> can never be the zero vector. The particles therefore never collide; they stay <span class="math inline">\(6\)</span> apart in the <span class="math inline">\(y\)</span>-direction because their <span class="math inline">\(y\)</span>-velocities are equal.</em></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="syllabus" class="level2">
<h2 class="anchored" data-anchor-id="syllabus">参考：シラバスの原文</h2>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>クリックすると開きます
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>AHL 3.12 の Content 欄は <span class="math inline">\(2\)</span> 行あります。このページはそのうち <span class="math inline">\(1\)</span> 行目で、次の <span class="math inline">\(2\)</span> 文でできています。</p>
<blockquote class="blockquote">
<p>Vector applications to kinematics. Modelling linear motion with constant velocity in two and three dimensions.</p>
</blockquote>
<p><strong><span class="math inline">\(1\)</span> 行目に対応する Guidance は、次の <span class="math inline">\(3\)</span> 行</strong>です。</p>
<blockquote class="blockquote">
<p>Finding positions, intersections, describing paths, finding times and distances when two objects are closest to each other.</p>
</blockquote>
<blockquote class="blockquote">
<p><span class="math inline">\(\boldsymbol{r} = \boldsymbol{r}_0 + \boldsymbol{v}t\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Relative position of B from A is <span class="math inline">\(\overrightarrow{\text{AB}}\)</span>.</p>
</blockquote>
<p><strong>Guidance の <span class="math inline">\(1\)</span> 行目に、<span class="math inline">\(5\)</span> つのことが並んでいます。</strong> 位置を出す（<a href="#idea">第1節</a>）、交点を出す（<a href="#path">第3節</a>）、経路を述べる（<a href="#path">第3節</a>）、<span class="math inline">\(2\)</span> 物体が最接近する<strong>時刻</strong>と<strong>距離</strong>を出す（<a href="#closest">第8節</a>）。</p>
<p>このページは、この <span class="math inline">\(5\)</span> つに<strong>衝突の判定</strong>（<a href="#cross-vs-collide">第4節</a>〜<a href="#collide-test">第6節</a>）を加えて扱います。</p>
<p><span class="math inline">\(2\)</span> 行目の Content「Motion with variable velocity in two dimensions」は、次のページ <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-12b.html">AHL 3.12b</a> です。</p>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<!--
  Cookie 同意バナーの本文を差しかえるスクリプト。

  Quarto の cookie-consent は termsfeed のライブラリを使っていて、
  lang: ja のおかげで表示は日本語になります。ただし既定の本文が

    「…パーソナライズされたコンテンツやターゲット広告を表示するため…」

  となっていて、広告を出さないこのサイトの実態と合いません。
  ライブラリ側に文面を差しかえる設定が無いので、バナーが出たあとに
  #cc-nb-text の中身だけを書きかえています。

  ★ 文面を変えるときは、下の NB の中身だけを直してください。
  ★ 読み込みは _quarto.yml の format.html.include-after-body です。
-->
<script>
(function () {
  var NB = "このサイトでは、どのページがどれくらい読まれているかを知るために、"
         + "Google アナリティクスの Cookie を使っています。"
         + "広告の配信や、個人を特定する目的には使いません。";

  function fix() {
    var el = document.getElementById("cc-nb-text");
    if (!el) { return false; }
    if (el.textContent !== NB) { el.textContent = NB; }
    return true;
  }

  // バナーはページ読み込みのあとに差し込まれるので、出てくるまで待つ。
  if (!fix()) {
    var mo = new MutationObserver(function () { if (fix()) { mo.disconnect(); } });
    mo.observe(document.body, { childList: true, subtree: true });
    setTimeout(function () { mo.disconnect(); }, 10000);
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "コピーしました");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "コピーしました");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/edusalonself\.github\.io\/ib-math-ai-sl-jp\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-11.html" class="pagination-link" aria-label="AHL 3.11 — Vector equation of a line">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">AHL 3.11 — Vector equation of a line</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-12b.html" class="pagination-link" aria-label="AHL 3.12b — Kinematics: variable velocity">
        <span class="nav-page-text">AHL 3.12b — Kinematics: variable velocity</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 学習サロン SELF</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/">
<p>学習サロン SELF</p>
</a>
  </li>  
</ul>
    <div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie の設定</a></div></div>
    <div class="nav-footer-right">
<p>IB（国際バカロレア機構）とは関係のない独立した教材です</p>
</div>
  </div>
</footer>




</body></html>