<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ahl-4-13 – 日本語で読む IB数学</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" rel="next">
<link href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3d27ed94b0b15b9bda3c32201c09d63a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "一致なし",
    "search-matching-documents-text": "一致した文書",
    "search-copy-link-title": "検索へのリンクをコピー",
    "search-hide-matches-text": "追加の検索結果を非表示",
    "search-more-match-text": "追加の検索結果",
    "search-more-matches-text": "追加の検索結果",
    "search-clear-button-title": "消去",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "検索",
    "search-label": "サーチ"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">日本語で読む IB数学</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="サーチ"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="ナビゲーションを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../ai-sl/index.html"> 
<span class="menu-text">AI SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../glossary-ai.html"> 
<span class="menu-text">英日対訳表（AI）</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../ai-hl/index.html" aria-current="page"> 
<span class="menu-text">AI HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-sl/index.html"> 
<span class="menu-text">AA SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-hl/index.html"> 
<span class="menu-text">AA HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../which-course.html"> 
<span class="menu-text">AI と AA、どちらを取るか</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/"> 
<span class="menu-text">学習サロン SELF</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html">AHL 4.13 — Non-linear regression</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IB数学 AI HL</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 1 — Number and algebra</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.9 — Laws of logarithms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.14 — Matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.15 — Eigenvalues and eigenvectors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 3 — Geometry and trigonometry</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.9 — Geometric transformations in two dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.14 — Graph theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.15 — Adjacency matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.16 — Tree and cycle algorithms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Topic 4 — Statistics and probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.12 — Data collection and χ² categorisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">AHL 4.13 — Non-linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.14 — Linear transformation of a single random variable</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.15 — Linear combinations of normal variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.19 — Transition matrices</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">このページの内容</h2>
   
  <ul>
  <li><a href="#sec-ahl-4-13" id="toc-sec-ahl-4-13" class="nav-link active" data-scroll-target="#sec-ahl-4-13">AHL 4.13 — Non-linear regression（曲線の回帰）</a>
  <ul class="collapse">
  <li><a href="#the-idea" id="toc-the-idea" class="nav-link" data-scroll-target="#the-idea">The idea</a>
  <ul class="collapse">
  <li><a href="#idea" id="toc-idea" class="nav-link" data-scroll-target="#idea">1. 直線で足りないときは、曲線を当てはめます</a></li>
  <li><a href="#models" id="toc-models" class="nav-link" data-scroll-target="#models">2. 試験に出る <span class="math inline">\(6\)</span> つのモデル</a></li>
  <li><a href="#residual" id="toc-residual" class="nav-link" data-scroll-target="#residual">3. residual — モデルと実際のずれ</a></li>
  <li><a href="#ssres" id="toc-ssres" class="nav-link" data-scroll-target="#ssres">4. <span class="math inline">\(SS_{\text{res}}\)</span> — ずれを <span class="math inline">\(1\)</span> つの数にまとめる</a></li>
  <li><a href="#least-squares" id="toc-least-squares" class="nav-link" data-scroll-target="#least-squares">5. 回帰曲線は、<span class="math inline">\(SS_{\text{res}}\)</span> を最小にする曲線です</a></li>
  <li><a href="#r2" id="toc-r2" class="nav-link" data-scroll-target="#r2">6. <span class="math inline">\(R^{2}\)</span> は「説明できた割合」です</a></li>
  <li><a href="#r2-r" id="toc-r2-r" class="nav-link" data-scroll-target="#r2-r">7. 線形モデルでは、<span class="math inline">\(R^{2} = r^{2}\)</span> です</a></li>
  <li><a href="#choosing" id="toc-choosing" class="nav-link" data-scroll-target="#choosing">8. <span class="math inline">\(R^{2}\)</span> だけでモデルを選んではいけません</a></li>
  </ul></li>
  <li><a href="#why-it-works" id="toc-why-it-works" class="nav-link" data-scroll-target="#why-it-works">Why it works</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples">Worked examples</a></li>
  <li><a href="#common-errors" id="toc-common-errors" class="nav-link" data-scroll-target="#common-errors">Common errors</a></li>
  <li><a href="#using-your-gdc-ti-nspire-cx-ii" id="toc-using-your-gdc-ti-nspire-cx-ii" class="nav-link" data-scroll-target="#using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</a>
  <ul class="collapse">
  <li><a href="#gdc-linear" id="toc-gdc-linear" class="nav-link" data-scroll-target="#gdc-linear">1. データを入れて、直線を当てはめる</a></li>
  <li><a href="#gdc-curve" id="toc-gdc-curve" class="nav-link" data-scroll-target="#gdc-curve">2. 曲線を当てはめる</a></li>
  <li><a href="#gdc-radian" id="toc-gdc-radian" class="nav-link" data-scroll-target="#gdc-radian">3. Sinusoidal は Radian で</a></li>
  <li><a href="#gdc-ssres" id="toc-gdc-ssres" class="nav-link" data-scroll-target="#gdc-ssres">4. <span class="math inline">\(SS_{\text{res}}\)</span> は、自分で作ります</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html">AHL 4.13 — Non-linear regression</a></li></ol></nav></header>




<section id="sec-ahl-4-13" class="level1">
<h1>AHL 4.13 — Non-linear regression（曲線の回帰）</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>What you should be able to do
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>散布図を見て、<strong>linear・quadratic・cubic・exponential・power・sine</strong> のどれを当てはめるかを選べる。</li>
<li>電卓で <strong>regression curve</strong>（回帰曲線）を求め、係数を式の形に書ける。</li>
<li><strong>residual</strong>（残差）<span class="math inline">\(y - \hat{y}\)</span> が何かを言い、<strong><span class="math inline">\(SS_{\text{res}}\)</span></strong>（残差平方和）を手で出せる。</li>
<li>回帰曲線が <strong><span class="math inline">\(SS_{\text{res}}\)</span> を最小にする</strong>曲線だと分かる。</li>
<li><strong>coefficient of determination</strong>（決定係数）<span class="math inline">\(R^{2}\)</span> を電卓で出し、<strong>「<span class="math inline">\(y\)</span> のばらつきのうち、モデルで説明できた割合」</strong>として文脈の中で説明できる。</li>
<li>線形モデルでは <span class="math inline">\(R^{2} = r^{2}\)</span> だと分かり、<strong><span class="math inline">\(R^{2}\)</span> だけでモデルを選んではいけない</strong>理由を言える。</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>SL 2.5 と SL 4.4 の続きです
</div>
</div>
<div class="callout-body-container callout-body">
<p>このページは、<span class="math inline">\(2\)</span> つのページの上に立っています。</p>
<div id="tbl-ahl413-place" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-place-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;1: このページの位置
</figcaption>
<div aria-describedby="tbl-ahl413-place-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>ページ</th>
<th>そこでやったこと</th>
<th>ここで足すこと</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="../../ai-sl/02-functions/sl-2-5.html#six-models">SL 2.5</a></td>
<td>モデルに使う関数の<strong>形</strong>（<span class="math inline">\(6\)</span> つ）</td>
<td>その形を、<strong>データに当てはめる</strong></td>
</tr>
<tr class="even">
<td><a href="../../ai-sl/04-statistics-and-probability/sl-4-4.html">SL 4.4</a></td>
<td>データに<strong>直線</strong>を当てはめ、<span class="math inline">\(r\)</span> で測る</td>
<td><strong>曲線</strong>も当てはめ、<strong><span class="math inline">\(R^{2}\)</span></strong> で測る</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>つまり、<strong>SL 4.4 で直線にしかできなかったことを、<span class="math inline">\(6\)</span> つの形すべてに広げる</strong>項目です。曲線の式そのものは SL 2.5 で見たものばかりです（sine のモデルに <span class="math inline">\(c\)</span> が加わる点だけが新しく、<strong>新しい種類の関数は出てきません</strong>）。</p>
<p>なお、この項目にも公式集の欄はありません。式を覚えるより、<strong><span class="math inline">\(R^{2}\)</span> が何を表しているか</strong>を言えるようにするほうが、そのまま点になります。</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>電卓を開きながら、このページを読んでください
</div>
</div>
<div class="callout-body-container callout-body">
<p>シラバスは、この項目について <span class="math inline">\(2\)</span> 回「technology」と書いています。</p>
<blockquote class="blockquote">
<p>Evaluation of least squares regression curves <strong>using technology</strong></p>
<p>Evaluation of <span class="math inline">\(R^{2}\)</span> <strong>using technology</strong></p>
</blockquote>
<p><strong>手で回帰曲線を求める問題は出ません。</strong> 電卓が係数と <span class="math inline">\(R^{2}\)</span> を出してくれます。</p>
<p><strong>問われるのは、その前後です。</strong> どのモデルを選ぶか。出てきた数を、文脈の中でどう説明するか。そして、<strong>その <span class="math inline">\(R^{2}\)</span> をどこまで信じてよいか。</strong></p>
</div>
</div>
<section id="the-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-idea">The idea</h2>
<section id="idea" class="level3">
<h3 class="anchored" data-anchor-id="idea">1. 直線で足りないときは、曲線を当てはめます</h3>
<p><a href="../../ai-sl/04-statistics-and-probability/sl-4-4.html#regression">SL 4.4</a> では、データに<strong>直線</strong>を当てはめました。</p>
<p>しかし、現実のデータは直線に並ぶとはかぎりません。</p>
<ul>
<li>値段を上げていくと、利益は途中まで増えて、そのあと減る——<strong>山の形</strong></li>
<li>車の価値は、毎年<strong>一定の割合で</strong>減る——<strong>下がり方がだんだんゆるくなる形</strong></li>
<li><span class="math inline">\(1\)</span> 年の日照時間は、毎年同じように<strong>くり返す</strong>——<strong>波の形</strong></li>
</ul>
<p>こういうデータに直線を引いても、意味のある予測はできません。<strong>同じ手順で、曲線を当てはめる</strong>——それがこの項目です。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>やることの順番は、SL 4.4 と同じです
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(1\)</span>. 散布図をかいて、<strong>形を見る</strong></p>
<p><span class="math inline">\(2\)</span>. その形のモデルを選び、<strong>電卓で係数を出す</strong></p>
<p><span class="math inline">\(3\)</span>. 係数の意味を、<strong>文脈の中で言葉にする</strong></p>
<p><span class="math inline">\(4\)</span>. <strong>当てはまり具合</strong>を測る（SL 4.4 は <span class="math inline">\(r\)</span>、ここは <span class="math inline">\(R^{2}\)</span>）</p>
<p>変わるのは <span class="math inline">\(2\)</span> と <span class="math inline">\(4\)</span> だけです。</p>
</div>
</div>
</section>
<section id="models" class="level3">
<h3 class="anchored" data-anchor-id="models">2. 試験に出る <span class="math inline">\(6\)</span> つのモデル</h3>
<p>シラバスが名指ししています。</p>
<blockquote class="blockquote">
<p>In examinations, questions may be asked on <strong>linear, quadratic, cubic, exponential, power and sine</strong> functions.</p>
</blockquote>
<div id="fig-ahl413-shapes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl413-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-13-shapes.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl413-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;1: The six model shapes
</figcaption>
</figure>
</div>
<p>形そのものは <a href="../../ai-sl/02-functions/sl-2-5.html#six-models">SL 2.5</a> で見たものです。ここでは、<strong>どれを選ぶか</strong>と、<strong>電卓のどのメニューを使うか</strong>を並べておきます。</p>
<div id="tbl-ahl413-models" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;2: <span class="math inline">\(6\)</span> つのモデルと、電卓のメニュー
</figcaption>
<div aria-describedby="tbl-ahl413-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>モデル</th>
<th>式</th>
<th>選ぶ目印</th>
<th>電卓のメニュー</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>linear</strong></td>
<td><span class="math inline">\(y = ax + b\)</span></td>
<td>まっすぐ並んでいる</td>
<td><code>Linear Regression (mx+b)</code></td>
</tr>
<tr class="even">
<td><strong>quadratic</strong></td>
<td><span class="math inline">\(y = ax^{2} + bx + c\)</span></td>
<td><strong>山が <span class="math inline">\(1\)</span> つ</strong>、または谷が <span class="math inline">\(1\)</span> つ</td>
<td><code>Quadratic Regression</code></td>
</tr>
<tr class="odd">
<td><strong>cubic</strong></td>
<td><span class="math inline">\(y = ax^{3} + bx^{2} + cx + d\)</span></td>
<td><strong>S 字</strong>になることがあり、quadratic より複雑に曲がる</td>
<td><code>Cubic Regression</code></td>
</tr>
<tr class="even">
<td><strong>exponential</strong></td>
<td><span class="math inline">\(y = k a^{x}\)</span></td>
<td>一定の<strong>割合</strong>で増える／減る</td>
<td><code>Exponential Regression</code></td>
</tr>
<tr class="odd">
<td><strong>power</strong></td>
<td><span class="math inline">\(y = a x^{n}\)</span></td>
<td><span class="math inline">\(x\)</span> を一定倍すると、<span class="math inline">\(y\)</span> も一定の倍率で変わる</td>
<td><code>Power Regression</code></td>
</tr>
<tr class="even">
<td><strong>sine</strong></td>
<td><span class="math inline">\(y = a\sin(bx + c) + d\)</span></td>
<td><strong>くり返す</strong></td>
<td><code>Sinusoidal Regression</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>形を見るのは、散布図です。<span class="math inline">\(R^{2}\)</span> ではありません
</div>
</div>
<div class="callout-body-container callout-body">
<p>モデルを選ぶ順番を取りちがえないでください。</p>
<p><span class="math display">\[
\text{散布図をかく} \ \to \ \text{形を選ぶ} \ \to \ \text{電卓で当てはめる} \ \to \ R^{2} \text{で測る}
\]</span></p>
<p><strong><span class="math inline">\(6\)</span> つ全部を試して、<span class="math inline">\(R^{2}\)</span> がいちばん大きいものを選ぶ</strong>——これは、この項目がいちばん避けたい進め方です（<a href="#choosing">第8節</a>）。</p>
<p>まず<strong>目で見て、文脈で考えて</strong>ください。「毎年一定の割合で減る」と問題文にあれば、それは exponential です。</p>
<p>同じ割合を掛け続ける増え方は、<a href="../../ai-sl/01-number-and-algebra/sl-1-3.html">SL 1.3 の geometric sequence</a> そのものです。<span class="math inline">\(y = ka^{x}\)</span> の <span class="math inline">\(a\)</span> が、公比にあたります。</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>power と exponential は、別のものです
</div>
</div>
<div class="callout-body-container callout-body">
<p>どちらも曲がった増え方をしますが、<strong><span class="math inline">\(x\)</span> の場所が違います。</strong></p>
<p><span class="math display">\[
\underbrace{y = ax^{n}}_{\text{power：$x$ が}\textbf{底}} \qquad \text{と} \qquad \underbrace{y = ka^{x}}_{\text{exponential：$x$ が}\textbf{指数}}
\]</span></p>
<p>exponential は「<strong><span class="math inline">\(1\)</span> 増えるごとに <span class="math inline">\(a\)</span> 倍</strong>」、power は「<strong><span class="math inline">\(2\)</span> 倍になると <span class="math inline">\(2^{n}\)</span> 倍</strong>」です。<a href="#tbl-ahl413-models" class="quarto-xref">表&nbsp;2</a> の power の目印は、この <span class="math inline">\(2\)</span> 行目のことを言っています。<span class="math inline">\(x\)</span> が何倍になったかで <span class="math inline">\(y\)</span> の倍率が決まり、<strong><span class="math inline">\(x\)</span> がどこから始まったかには関係しません。</strong> 問題文が「毎年 <span class="math inline">\(15\%\)</span> 減る」と言えば exponential、「長さの平方根に比例する」と言えば power です。</p>
<p>（power は <a href="../../ai-sl/02-functions/sl-2-5.html#variation">SL 2.5 の direct / inverse variation</a> と同じ形 <span class="math inline">\(y = ax^{n}\)</span> です。SL では <span class="math inline">\(n\)</span> が整数でしたが、この項目では <span class="math inline">\(n\)</span> が整数でなくても構いません。）</p>
</div>
</div>
</section>
<section id="residual" class="level3">
<h3 class="anchored" data-anchor-id="residual">3. residual — モデルと実際のずれ</h3>
<p>当てはまり具合を測るには、まず<strong>ずれ</strong>を数にします。</p>
<p><strong>residual</strong>（残差）は、<strong>実際の値 <span class="math inline">\(-\)</span> モデルの値</strong>です。</p>
<p><span id="eq-ahl413-residual"><span class="math display">\[
\text{residual} = y - \hat{y}
\tag{1}\]</span></span></p>
<p><span class="math inline">\(\hat{y}\)</span>（「<span class="math inline">\(y\)</span> ハット」）は、<strong>モデルが予測する値</strong>を表す記号です。</p>
<div id="fig-ahl413-residuals" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl413-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-13-residuals.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl413-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;2: Residuals are the vertical gaps
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl413-residuals" class="quarto-xref">図&nbsp;2</a> の左を見てください。<span class="math inline">\(5\)</span> 個の点に、モデル <span class="math inline">\(\hat{y} = 2x + 1\)</span> を当てはめてあります。</p>
<div id="tbl-ahl413-residual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;3: residual を出す
</figcaption>
<div aria-describedby="tbl-ahl413-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
<th><span class="math inline">\(5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y\)</span>（実際）</td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(8\)</span></td>
<td><span class="math inline">\(9\)</span></td>
<td><span class="math inline">\(10\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat{y}\)</span>（モデル）</td>
<td><span class="math inline">\(3\)</span></td>
<td><span class="math inline">\(5\)</span></td>
<td><span class="math inline">\(7\)</span></td>
<td><span class="math inline">\(9\)</span></td>
<td><span class="math inline">\(11\)</span></td>
</tr>
<tr class="odd">
<td>residual</td>
<td><span class="math inline">\(+1\)</span></td>
<td><span class="math inline">\(-1\)</span></td>
<td><span class="math inline">\(+1\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(-1\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>residual は「たて」のずれです
</div>
</div>
<div class="callout-body-container callout-body">
<p>点から曲線への<strong>いちばん近い距離</strong>ではありません。<strong>同じ <span class="math inline">\(x\)</span> のところで、上下にどれだけ離れているか</strong>です。</p>
<p><a href="#fig-ahl413-residuals" class="quarto-xref">図&nbsp;2</a> の赤い線は、すべて<strong>たて向き</strong>に引いてあります。</p>
</div>
</div>
<p><strong>モデルが上にあれば residual は負、下にあれば正</strong>です。点がモデルの上下に散らばっていれば、正と負が混ざります。</p>
</section>
<section id="ssres" class="level3">
<h3 class="anchored" data-anchor-id="ssres">4. <span class="math inline">\(SS_{\text{res}}\)</span> — ずれを <span class="math inline">\(1\)</span> つの数にまとめる</h3>
<p>residual は点の数だけあります。これを <strong><span class="math inline">\(1\)</span> つの数</strong>にまとめたのが <strong>sum of square residuals</strong>（残差平方和）です。</p>
<p><span id="eq-ahl413-ssres"><span class="math display">\[
SS_{\text{res}} = \sum (y - \hat{y})^{2}
\tag{2}\]</span></span></p>
<p><a href="#fig-ahl413-residuals" class="quarto-xref">図&nbsp;2</a> の右のとおり、<a href="#tbl-ahl413-residual" class="quarto-xref">表&nbsp;3</a> では</p>
<p><span class="math display">\[
SS_{\text{res}} = 1^{2} + (-1)^{2} + 1^{2} + 0^{2} + (-1)^{2} = 4
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>なぜ、<span class="math inline">\(2\)</span> 乗するのか
</div>
</div>
<div class="callout-body-container callout-body">
<p>そのまま足すと、<strong>正のずれと負のずれが打ち消し合います。</strong> <a href="#tbl-ahl413-residual" class="quarto-xref">表&nbsp;3</a> では <span class="math inline">\(1 + (-1) + 1 + 0 + (-1) = 0\)</span> になり、ずれの大きさが消えてしまいました。打ち消し方は場合によりますが、<strong>足し算のままでは「ずれの大きさ」を測れない</strong>という点は変わりません。</p>
<p><span class="math inline">\(2\)</span> 乗すれば、符号が消えます。<strong>ずれが大きいほど <span class="math inline">\(SS_{\text{res}}\)</span> が大きくなる</strong>、という性質だけが残ります。</p>
<p><span class="math display">\[
SS_{\text{res}} \text{が小さい} \quad \Longleftrightarrow \quad \text{モデルがデータに近い}
\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(SS_{\text{res}}\)</span> の大きさだけでは、比べられません
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(SS_{\text{res}} = 4\)</span> は小さいでしょうか。<strong>それだけでは決まりません。</strong></p>
<ul>
<li><span class="math inline">\(y\)</span> の単位が円なら、<span class="math inline">\(SS_{\text{res}}\)</span> は「円<span class="math inline">\(^{2}\)</span>」の桁になります。単位を変えれば数も変わります</li>
<li>データの個数が増えれば、項が増えるので <span class="math inline">\(SS_{\text{res}}\)</span> も大きくなります</li>
</ul>
<p>比べてよいのは、<strong>同じデータに、別のモデルを当てはめたとき</strong>だけです。そこが <span class="math inline">\(SS_{\text{res}}\)</span> の使いどころです。</p>
<p><strong>単位にもデータの数にも左右されない測り方</strong>が、次の <span class="math inline">\(R^{2}\)</span> です。</p>
</div>
</div>
</section>
<section id="least-squares" class="level3">
<h3 class="anchored" data-anchor-id="least-squares">5. 回帰曲線は、<span class="math inline">\(SS_{\text{res}}\)</span> を最小にする曲線です</h3>
<p>シラバスの言葉は <strong>least squares regression curves</strong> です。「least squares」——<strong>平方（square）の和が最小（least）</strong>、つまり</p>
<p><strong><span class="math inline">\(SS_{\text{res}}\)</span> がいちばん小さくなるように、係数を決める。</strong> これが、電卓の中で起きていることです。</p>
<p><a href="#tbl-ahl413-residual" class="quarto-xref">表&nbsp;3</a> のデータに、電卓で直線を当てはめると</p>
<p><span class="math display">\[
\hat{y} = 1.7x + 1.9
\]</span></p>
<p>が出ます。この直線の <span class="math inline">\(SS_{\text{res}}\)</span> は <strong><span class="math inline">\(3.1\)</span></strong> で、さっきの <span class="math inline">\(\hat{y} = 2x+1\)</span> の <span class="math inline">\(4\)</span> より小さくなっています。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>どんな直線を持ってきても、<span class="math inline">\(3.1\)</span> より小さくはなりません
</div>
</div>
<div class="callout-body-container callout-body">
<p>それが「least squares」の意味です。<strong><span class="math inline">\(y = 1.7x + 1.9\)</span> は、この <span class="math inline">\(5\)</span> 点に対していちばん <span class="math inline">\(SS_{\text{res}}\)</span> が小さい直線</strong>です。</p>
<p>同じことが、linear・quadratic・cubic について成り立ちます。<code>Quadratic Regression</code> を選べば、電卓は<strong><span class="math inline">\(SS_{\text{res}}\)</span> が最小になる放物線</strong>を返します。</p>
<p>（exponential と power では、電卓は<strong>両辺の <span class="math inline">\(\log\)</span> を取って直線に直してから</strong>最小にしています。そのため、<span class="math inline">\(y\)</span> そのものの <span class="math inline">\(SS_{\text{res}}\)</span> が厳密に最小とはかぎりません。試験でこの違いを問われることはありません。）</p>
</div>
</div>
</section>
<section id="r2" class="level3">
<h3 class="anchored" data-anchor-id="r2">6. <span class="math inline">\(R^{2}\)</span> は「説明できた割合」です</h3>
<p><span class="math inline">\(SS_{\text{res}}\)</span> は、単位にもデータの数にも左右されました。そこで、<strong><span class="math inline">\(y\)</span> のばらつき全体と比べます。</strong></p>
<p>まず、モデルを使わずに <span class="math inline">\(y\)</span> のばらつきを測ります。<strong>全部の点が <span class="math inline">\(\bar{y}\)</span> からどれだけ離れているか</strong>です。これを <strong>total sum of squares</strong>（総平方和）<span class="math inline">\(SS_{\text{tot}}\)</span> と書きます。</p>
<p><span id="eq-ahl413-sstot"><span class="math display">\[
SS_{\text{tot}} = \sum (y - \bar{y})^{2}
\tag{3}\]</span></span></p>
<div id="fig-ahl413-r2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl413-r2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-13-r2.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl413-r2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;3: Total spread and unexplained spread
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl413-r2" class="quarto-xref">図&nbsp;3</a> の左が <span class="math inline">\(SS_{\text{tot}} = 32\)</span>、右が <span class="math inline">\(SS_{\text{res}} = 4\)</span> です。</p>
<p><strong><span class="math inline">\(SS_{\text{tot}}\)</span> が「ばらつきの全部」、<span class="math inline">\(SS_{\text{res}}\)</span> が「モデルでは説明できずに残ったぶん」</strong>です。ですから、割合で見ると</p>
<p><span id="eq-ahl413-r2"><span class="math display">\[
R^{2} = 1 - \frac{SS_{\text{res}}}{SS_{\text{tot}}}
\tag{4}\]</span></span></p>
<p><a href="#fig-ahl413-r2" class="quarto-xref">図&nbsp;3</a> の数を入れると</p>
<p><span class="math display">\[
R^{2} = 1 - \frac{4}{32} = 0.875
\]</span></p>
<p>シラバスの言い方は、こうです。</p>
<blockquote class="blockquote">
<p><span class="math inline">\(R^{2}\)</span> gives the <strong>proportion of variability in the second variable accounted for by the chosen model</strong>.</p>
</blockquote>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>答案では、この一文の形で書いてください
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(R^{2} = 0.875\)</span> を、数のまま書いても点になりません。<strong>文脈に戻して</strong>ください。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(R^{2} = 0.875\)</span>, so the model accounts for <span class="math inline">\(87.5\%\)</span> of the variability in <span class="math inline">\(y\)</span>.</em></p>
</div>
<p>（このモデルは、<span class="math inline">\(y\)</span> のばらつきの <span class="math inline">\(87.5\%\)</span> を説明している、という意味です。）</p>
<p><span class="math inline">\(y\)</span> が「利益」なら <em>variability in the profit</em>、「日照時間」なら <em>variability in the number of hours of daylight</em> と、<strong>その問題の言葉に置きかえます。</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span><span class="math inline">\(R^{2}\)</span> は <span class="math inline">\(0\)</span> 以上 <span class="math inline">\(1\)</span> 以下です
</div>
</div>
<div class="callout-body-container callout-body">
<p>電卓に<strong>当てはめさせた</strong>モデル（回帰直線・回帰曲線）についての話です。問題文で与えられただけのモデルなら、<span class="math inline">\(R^{2}\)</span> が負になることもあります。</p>
<ul>
<li><span class="math inline">\(R^{2} = 1\)</span> … <span class="math inline">\(SS_{\text{res}} = 0\)</span>。<strong>全部の点が曲線の上にある</strong></li>
<li><span class="math inline">\(R^{2}\)</span> が <span class="math inline">\(0\)</span> に近い … モデルを使っても、<span class="math inline">\(\bar{y}\)</span> と言うのとほとんど変わらない</li>
</ul>
<p>割合なので、<span class="math inline">\(0.875\)</span> は <span class="math inline">\(87.5\%\)</span> と読み替えられます。<strong>パーセントで書くと、意味が伝わりやすくなります。</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(R^{2} = 1 - \dfrac{SS_{\text{res}}}{SS_{\text{tot}}}\)</span> は、計算させられません
</div>
</div>
<div class="callout-body-container callout-body">
<p>シラバスに、はっきりこう書かれています。</p>
<blockquote class="blockquote">
<p>Awareness that <span class="math inline">\(R^{2} = 1 - \dfrac{SS_{\text{res}}}{SS_{\text{tot}}}\)</span> and hence <span class="math inline">\(=1\)</span> if <span class="math inline">\(SS_{\text{res}} = 0\)</span>, <strong>may enhance understanding but will not be examined</strong>.</p>
</blockquote>
<p><strong>この式そのものは試験に出ません。</strong> 出るのは、電卓が返した <span class="math inline">\(R^{2}\)</span> を<strong>読んで、文脈で説明すること</strong>です。</p>
<p>ただ、意味を知っておくと <span class="math inline">\(R^{2}\)</span> の説明が書きやすくなります。だからここに置いてあります。</p>
<p><strong>このページの <a href="#exm-ahl413-ssres" class="quarto-xref">例&nbsp;1</a> (b) と演習2・演習8で、この式を使って計算させています。</strong> それは仕組みを分かってもらうためで、<strong>試験でこの形で問われることはありません。</strong></p>
</div>
</div>
</section>
<section id="r2-r" class="level3">
<h3 class="anchored" data-anchor-id="r2-r">7. 線形モデルでは、<span class="math inline">\(R^{2} = r^{2}\)</span> です</h3>
<p>シラバスが名指ししている関係です。</p>
<blockquote class="blockquote">
<p>The connection between the coefficient of determination and the <strong>Pearson’s product moment correlation coefficient</strong> for linear models.</p>
</blockquote>
<p><a href="../../ai-sl/04-statistics-and-probability/sl-4-4.html#pearson-r">SL 4.4</a> の <span class="math inline">\(r\)</span> を <span class="math inline">\(2\)</span> 乗すると、<span class="math inline">\(R^{2}\)</span> になります。</p>
<p><span id="eq-ahl413-r2r"><span class="math display">\[
R^{2} = r^{2} \qquad (\text{linear model のときだけ})
\tag{5}\]</span></span></p>
<p><a href="#tbl-ahl413-residual" class="quarto-xref">表&nbsp;3</a> のデータに、電卓で<strong>回帰直線</strong>を当てはめると <span class="math inline">\(r = 0.950\)</span> です。</p>
<p><span class="math display">\[
r^{2} = 0.950^{2} \approx 0.903
\]</span></p>
<p>これは、その回帰直線 <span class="math inline">\(\hat{y} = 1.7x + 1.9\)</span> の <span class="math inline">\(R^{2}\)</span>（<a href="#least-squares">第5節</a>の <span class="math inline">\(SS_{\text{res}} = 3.1\)</span> から <span class="math inline">\(1 - \frac{3.1}{32} = 0.903\)</span>）と一致します ✓</p>
<p><strong>第6節の <span class="math inline">\(0.875\)</span> とは別の数です。</strong> あちらは <span class="math inline">\(\hat{y} = 2x+1\)</span> という、回帰直線ではないモデルの <span class="math inline">\(R^{2}\)</span> でした。<span class="math inline">\(R^{2} = r^{2}\)</span> が成り立つのは、<strong>回帰直線</strong>についてです。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(r\)</span> には符号があり、<span class="math inline">\(R^{2}\)</span> にはありません
</div>
</div>
<div class="callout-body-container callout-body">
<p>これが、<span class="math inline">\(2\)</span> つの大きな違いです。</p>
<div id="tbl-ahl413-r-r2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-r-r2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;4: <span class="math inline">\(r\)</span> と <span class="math inline">\(R^{2}\)</span>
</figcaption>
<div aria-describedby="tbl-ahl413-r-r2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>値の範囲</th>
<th>分かること</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(r\)</span></strong></td>
<td><span class="math inline">\(-1 \le r \le 1\)</span></td>
<td>強さ<strong>と向き</strong>（正の相関か、負の相関か）</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(R^{2}\)</span></strong></td>
<td><span class="math inline">\(0 \le R^{2} \le 1\)</span></td>
<td>説明できた<strong>割合</strong>だけ</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math inline">\(R^{2} = 0.81\)</span> から <span class="math inline">\(r\)</span> を出そうとすると、<span class="math inline">\(r = 0.9\)</span> か <span class="math inline">\(r = -0.9\)</span> かが<strong>決まりません。</strong> 向きは、散布図か傾きの符号を見て決めます。</p>
<p>そして、<strong><span class="math inline">\(R^{2} = r^{2}\)</span> が使えるのは linear model のときだけ</strong>です。quadratic や sine のモデルに <span class="math inline">\(r\)</span> はありません。</p>
</div>
</div>
</section>
<section id="choosing" class="level3">
<h3 class="anchored" data-anchor-id="choosing">8. <span class="math inline">\(R^{2}\)</span> だけでモデルを選んではいけません</h3>
<p>この項目でいちばん大事な注意です。シラバスが、わざわざ <span class="math inline">\(1\)</span> 行を使って書いています。</p>
<blockquote class="blockquote">
<p>Awareness that many factors affect the validity of a model and <strong>the coefficient of determination, by itself, is not a good way to decide between different models</strong>.</p>
</blockquote>
<p>理由は <span class="math inline">\(2\)</span> つあります。</p>
<section id="nonsense" class="level4">
<h4 class="anchored" data-anchor-id="nonsense">理由1 — 現実にありえない予測をすることがある</h4>
<div id="fig-ahl413-compare" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl413-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-13-compare.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl413-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;4: Two ways a high <span class="math inline">\(R^2\)</span> can mislead
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl413-compare" class="quarto-xref">図&nbsp;4</a> の左は、中古車の価値を <span class="math inline">\(6\)</span> 年ぶん記録したデータです。直線を当てはめると <span class="math inline">\(R^{2} = 0.975\)</span>——<strong>十分に高い値</strong>です。</p>
<p>ところが、この直線で <span class="math inline">\(8\)</span> 年後を予測すると</p>
<p><span class="math display">\[
V = -2240 \ \text{ドル}
\]</span></p>
<p><strong>価値が負になります。</strong> データの範囲では合っていても、外へ出た瞬間に意味を失います（<a href="../../ai-sl/04-statistics-and-probability/sl-4-4.html#extrapolation">SL 4.4 の extrapolation</a>）。</p>
<p>exponential なら <span class="math inline">\(R^{2} = 0.998\)</span> で、しかも<strong>どこまでいっても正</strong>です。文脈に合っているのは、こちらです。</p>
</section>
<section id="more-terms" class="level4">
<h4 class="anchored" data-anchor-id="more-terms">理由2 — 係数を増やせば、<span class="math inline">\(R^{2}\)</span> はいくらでも上げられる</h4>
<p><a href="#fig-ahl413-compare" class="quarto-xref">図&nbsp;4</a> の右は、同じデータに <strong>quadratic と cubic</strong> を当てはめて並べたものです。</p>
<div id="tbl-ahl413-compare" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;5: <span class="math inline">\(R^{2}\)</span> が大きいほうが、よいとはかぎらない
</figcaption>
<div aria-describedby="tbl-ahl413-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>モデル</th>
<th>係数の数</th>
<th><span class="math inline">\(R^{2}\)</span></th>
<th><span class="math inline">\(10\)</span> 年後の予測</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>quadratic</td>
<td><span class="math inline">\(3\)</span> 個</td>
<td><span class="math inline">\(0.99759\)</span></td>
<td><span class="math inline">\(9100\)</span> ドル</td>
</tr>
<tr class="even">
<td><strong>cubic</strong></td>
<td><span class="math inline">\(4\)</span> 個</td>
<td><strong><span class="math inline">\(0.99824\)</span></strong></td>
<td><span class="math inline">\(-7260\)</span> ドル</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>cubic のほうが <span class="math inline">\(R^{2}\)</span> は大きい</strong>のに、<span class="math inline">\(10\)</span> 年後に負の値を出します。<strong>係数が <span class="math inline">\(4\)</span> 個あるぶん、<span class="math inline">\(6\)</span> 個の点に寄り添えている</strong>だけです。差は <span class="math inline">\(0.99759 \to 0.99824\)</span>、<strong><span class="math inline">\(0.001\)</span> 未満</strong>。この差で cubic を選ぶ理由にはなりません。</p>
<p><strong>とはいえ、quadratic もよいモデルではありません。</strong> <a href="#fig-ahl413-compare" class="quarto-xref">図&nbsp;4</a> の右をよく見ると、緑の曲線は <span class="math inline">\(t = 7\)</span> あたりから<strong>上を向いて</strong>います。中古車の価値が <span class="math inline">\(7\)</span> 年目から上がることはありません。<span class="math inline">\(R^{2}\)</span> はどちらも <span class="math inline">\(0.997\)</span> を超えているのに、<strong>どちらも文脈に合っていない</strong>——これが、この節の言いたいことです。合っているのは、<a href="#nonsense">理由1</a>の exponential のほうでした。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>モデルを選ぶときに見るもの
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(R^{2}\)</span> は、<strong>判断材料の <span class="math inline">\(1\)</span> つ</strong>にすぎません。いっしょに見るのは、次の <span class="math inline">\(3\)</span> つです。</p>
<p><span class="math inline">\(1\)</span>. <strong>散布図の形と合っているか。</strong> 曲線が点の並びをなぞっているか、目で見てください。</p>
<p><span class="math inline">\(2\)</span>. <strong>文脈に合っているか。</strong> 価値は負にならない。人数は整数。日照時間はくり返す——<strong>その量の性質</strong>に、モデルが従っているか。</p>
<p><span class="math inline">\(3\)</span>. <strong>データの外でも、まともな値を出すか。</strong> 予測に使うなら、ここが効きます。</p>
<p>答案では、<strong><span class="math inline">\(R^{2}\)</span> の値と、この <span class="math inline">\(3\)</span> つのどれか</strong>を組み合わせて書いてください。「<span class="math inline">\(R^{2}\)</span> が大きいから」だけでは、この項目の問いに答えたことになりません。</p>
</div>
</div>
</section>
</section>
</section>
<section id="why-it-works" class="level2">
<h2 class="anchored" data-anchor-id="why-it-works">Why it works</h2>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>クリックすると開きます
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>ここで説明するのは <span class="math inline">\(2\)</span> つです。<strong><span class="math inline">\(R^{2}\)</span> の式がなぜあの形なのか</strong>と、<strong>なぜ係数を増やすと <span class="math inline">\(R^{2}\)</span> が下がらないのか</strong>。</p>
<p>どちらも試験には出ません（<a href="#r2">第6節</a>）。ただ、<a href="#choosing">第8節</a>の注意が「なぜそうなるのか」は、ここを読むと分かります。</p>
<section id="why-r2" class="level3">
<h3 class="anchored" data-anchor-id="why-r2"><span class="math inline">\(R^{2}\)</span> の式の形</h3>
<p><span class="math inline">\(SS_{\text{tot}}\)</span> は、<strong>モデルを使わなかったとき</strong>のずれです。何も分からなければ、どの <span class="math inline">\(x\)</span> に対しても「たぶん <span class="math inline">\(\bar{y}\)</span> くらい」と答えるしかありません。そのときの <span class="math inline">\(SS_{\text{res}}\)</span> が、ちょうど <span class="math inline">\(SS_{\text{tot}}\)</span> です。</p>
<p><span class="math display">\[
\hat{y} = \bar{y} \ \text{という「モデル」の} \ SS_{\text{res}} \ = \ \sum (y - \bar{y})^{2} = SS_{\text{tot}}
\]</span></p>
<p>ですから</p>
<p><span class="math display">\[
\frac{SS_{\text{res}}}{SS_{\text{tot}}} = \frac{\text{モデルを使っても残ったずれ}}{\text{何もしなかったときのずれ}}
\]</span></p>
<p>これは「<strong>説明できなかった割合</strong>」です。<span class="math inline">\(1\)</span> から引けば「<strong>説明できた割合</strong>」になります。それが <a href="#eq-ahl413-r2" class="quarto-xref">式&nbsp;4</a> の形でした。</p>
<ul>
<li><span class="math inline">\(SS_{\text{res}} = 0\)</span> なら <span class="math inline">\(R^{2} = 1\)</span>。<strong>全部の点が曲線の上</strong></li>
<li><span class="math inline">\(SS_{\text{res}} = SS_{\text{tot}}\)</span> なら <span class="math inline">\(R^{2} = 0\)</span>。<strong><span class="math inline">\(\bar{y}\)</span> と言うのと変わらない</strong></li>
</ul>
</section>
<section id="why-more" class="level3">
<h3 class="anchored" data-anchor-id="why-more">なぜ、係数を増やすと <span class="math inline">\(R^{2}\)</span> が下がらないのか</h3>
<p><a href="#more-terms">第8節</a>で、cubic のほうが quadratic より <span class="math inline">\(R^{2}\)</span> が大きくなりました。偶然ではありません。</p>
<p>quadratic の式 <span class="math inline">\(y = ax^{2} + bx + c\)</span> で、<span class="math inline">\(a = 0\)</span> とすれば <span class="math inline">\(y = bx + c\)</span>——<strong>直線になります。</strong> つまり、</p>
<p><strong>quadratic で選べる曲線の中に、直線が全部入っています。</strong></p>
<p>電卓は <span class="math inline">\(SS_{\text{res}}\)</span> が最小になるものを選ぶので、<strong>quadratic の <span class="math inline">\(SS_{\text{res}}\)</span> が、linear の <span class="math inline">\(SS_{\text{res}}\)</span> より大きくなることはありません。</strong> 同じように、cubic は quadratic を含みます。</p>
<p><span class="math display">\[
SS_{\text{res}}(\text{linear}) \ \ge \ SS_{\text{res}}(\text{quadratic}) \ \ge \ SS_{\text{res}}(\text{cubic})
\]</span></p>
<p><span class="math inline">\(SS_{\text{tot}}\)</span> は同じデータなら変わらないので、<span class="math inline">\(R^{2}\)</span> は<strong>下がることがありません</strong>。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>点が <span class="math inline">\(n\)</span> 個あれば、係数を <span class="math inline">\(n\)</span> 個もつ多項式で<strong>全部の点をぴったり通せます</strong>。そのとき <span class="math inline">\(R^{2} = 1\)</span> です。しかし、それは「モデルが正しい」のではなく「点を丸暗記した」だけです。</p>
<p><strong><span class="math inline">\(R^{2}\)</span> は係数を増やすだけで上げられるので、<span class="math inline">\(R^{2}\)</span> が高いことは、よいモデルであることの証明になりません</strong>——これが<a href="#choosing">第8節</a>の中身です。</p>
</div>
</div>
</div>
</section>
</div>
</div>
</div>
</section>
<section id="worked-examples" class="level2">
<h2 class="anchored" data-anchor-id="worked-examples">Worked examples</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>問題文は英語です。意味が理解できなかったら、問題文の下の「<strong>日本語訳</strong>」を開いてください。解説は日本語です。</p>
</div>
</div>
</div>
<div id="exm-ahl413-ssres" class="theorem example">
<p><span class="theorem-title"><strong>例題 1</strong></span> <span class="q-en">The table shows five data points.</span></p>
<div id="tbl-ahl413-we1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-we1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;6: Five data points
</figcaption>
<div aria-describedby="tbl-ahl413-we1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
<th><span class="math inline">\(5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y\)</span></td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(8\)</span></td>
<td><span class="math inline">\(9\)</span></td>
<td><span class="math inline">\(10\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="q-en">A student proposes the model <span class="math inline">\(\hat{y} = 2x + 1\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the residual for each point, and hence find <span class="math inline">\(SS_{\text{res}}\)</span> for this model.</span></p>
<p><strong>(b)</strong> <span class="q-en">Given that <span class="math inline">\(SS_{\text{tot}} = 32\)</span>, find <span class="math inline">\(R^{2}\)</span> for this model.</span></p>
<p><strong>(c)</strong> <span class="q-en">Use technology to find the equation of the regression line of <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span>, and its value of <span class="math inline">\(SS_{\text{res}}\)</span>.</span></p>
<p><strong>(d)</strong> <span class="q-en">Explain why the value in part (c) is smaller than the value in part (a).</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>表は <span class="math inline">\(5\)</span> 個のデータの組を示しています。</p>
<p>ある生徒が、モデル <span class="math inline">\(\hat{y} = 2x + 1\)</span> を提案しました。</p>
<p><strong>(a)</strong> 各点の残差を求め、それを使ってこのモデルの <span class="math inline">\(SS_{\text{res}}\)</span> を求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(SS_{\text{tot}} = 32\)</span> であるとき、このモデルの <span class="math inline">\(R^{2}\)</span> を求めなさい。</p>
<p><strong>(c)</strong> 電卓を使って、<span class="math inline">\(y\)</span> の <span class="math inline">\(x\)</span> への回帰直線の式と、その <span class="math inline">\(SS_{\text{res}}\)</span> を求めなさい。</p>
<p><strong>(d)</strong> (c) の値が (a) の値より小さくなる理由を説明しなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> まずモデルの値 <span class="math inline">\(\hat{y}\)</span> を出し、実際の <span class="math inline">\(y\)</span> から引きます（<a href="#eq-ahl413-residual" class="quarto-xref">式&nbsp;1</a>）。</p>
<div id="tbl-ahl413-we1a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-we1a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;7: residual の計算
</figcaption>
<div aria-describedby="tbl-ahl413-we1a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
<th><span class="math inline">\(5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y\)</span></td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(8\)</span></td>
<td><span class="math inline">\(9\)</span></td>
<td><span class="math inline">\(10\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat{y} = 2x+1\)</span></td>
<td><span class="math inline">\(3\)</span></td>
<td><span class="math inline">\(5\)</span></td>
<td><span class="math inline">\(7\)</span></td>
<td><span class="math inline">\(9\)</span></td>
<td><span class="math inline">\(11\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(y - \hat{y}\)</span></td>
<td><span class="math inline">\(+1\)</span></td>
<td><span class="math inline">\(-1\)</span></td>
<td><span class="math inline">\(+1\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(-1\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math display">\[
SS_{\text{res}} = 1^{2} + (-1)^{2} + 1^{2} + 0^{2} + (-1)^{2} = 4
\]</span></p>
<p><strong>検算。</strong> <span class="math inline">\(\hat{y}\)</span> に residual を足すと、もとの <span class="math inline">\(y\)</span> にもどります（<span class="math inline">\(3+1=4\)</span>、<span class="math inline">\(5-1=4\)</span>、…）。ここがずれていたら、引き算のどこかが誤りです。</p>
<p><strong>(b)</strong> <a href="#eq-ahl413-r2" class="quarto-xref">式&nbsp;4</a> に入れるだけです。</p>
<p><span class="math display">\[
R^{2} = 1 - \frac{4}{32} = 1 - 0.125 = 0.875
\]</span></p>
<p><strong>(c)</strong> 電卓に <span class="math inline">\(x\)</span> と <span class="math inline">\(y\)</span> を入れて <code>Linear Regression (mx+b)</code> を走らせます（<a href="#gdc-linear">GDC 第1節</a>）。</p>
<p><span class="math display">\[
\hat{y} = 1.7x + 1.9
\]</span></p>
<p>この直線で residual を出し直すと <span class="math inline">\(SS_{\text{res}} = 3.1\)</span> になります。</p>
<p><strong>(d)</strong> <code>Explain why</code> なので、<strong>言葉で理由を書きます。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The regression line is the least squares line: its coefficients are chosen so that <span class="math inline">\(SS_{\text{res}}\)</span> is as small as possible. No other straight line can give a smaller value, so <span class="math inline">\(3.1\)</span> must be less than the <span class="math inline">\(4\)</span> obtained from <span class="math inline">\(\hat{y} = 2x + 1\)</span>.</em></p>
</div>
<p>（回帰直線は <span class="math inline">\(SS_{\text{res}}\)</span> を最小にするように係数が決められているので、ほかのどんな直線よりも小さくなる、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Residuals: <span class="math inline">\(1\)</span>, <span class="math inline">\(-1\)</span>, <span class="math inline">\(1\)</span>, <span class="math inline">\(0\)</span>, <span class="math inline">\(-1\)</span>.</em></p>
<p><span class="math display">\[
SS_{\text{res}} = 1 + 1 + 1 + 0 + 1 = 4
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
R^{2} = 1 - \frac{4}{32} = 0.875
\]</span></p>
<p><strong>(c)</strong> <span class="math inline">\(\hat{y} = 1.7x + 1.9\)</span>, <span class="math inline">\(SS_{\text{res}} = 3.1\)</span></p>
<p><strong>(d)</strong> <em>The regression line minimises <span class="math inline">\(SS_{\text{res}}\)</span>, so no other straight line can give a smaller value than it.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>この例題で、<span class="math inline">\(R^{2} = r^{2}\)</span> も確かめられます
</div>
</div>
<div class="callout-body-container callout-body">
<ol start="3" type="a">
<li>の直線について電卓が返す <span class="math inline">\(r\)</span> は <span class="math inline">\(0.950\)</span> です。</li>
</ol>
<p><span class="math display">\[
r^{2} = 0.950^{2} = 0.903
\]</span></p>
<p>そして (c) の直線の <span class="math inline">\(R^{2}\)</span> も、<span class="math inline">\(1 - \dfrac{3.1}{32} = 0.903\)</span> です ✓（<a href="#r2-r">第7節</a>）</p>
<p><strong>(b) の <span class="math inline">\(0.875\)</span> とは違う値</strong>であることに注意してください。<span class="math inline">\(0.875\)</span> は生徒のモデル <span class="math inline">\(\hat{y} = 2x+1\)</span> のもの、<span class="math inline">\(0.903\)</span> は回帰直線のものです。</p>
</div>
</div>
</div>
<div id="exm-ahl413-quad" class="theorem example">
<p><span class="theorem-title"><strong>例題 2</strong></span> <span class="q-en">A shop records its daily profit <span class="math inline">\(P\)</span>, in dollars, for six different selling prices <span class="math inline">\(x\)</span>, in dollars.</span></p>
<div id="tbl-ahl413-we2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-we2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;8: Selling price and daily profit
</figcaption>
<div aria-describedby="tbl-ahl413-we2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(4\)</span></th>
<th><span class="math inline">\(6\)</span></th>
<th><span class="math inline">\(8\)</span></th>
<th><span class="math inline">\(10\)</span></th>
<th><span class="math inline">\(12\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P\)</span></td>
<td><span class="math inline">\(78\)</span></td>
<td><span class="math inline">\(150\)</span></td>
<td><span class="math inline">\(199\)</span></td>
<td><span class="math inline">\(191\)</span></td>
<td><span class="math inline">\(160\)</span></td>
<td><span class="math inline">\(72\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Explain why a linear model is not appropriate for this data.</span></p>
<p><strong>(b)</strong> <span class="q-en">Use technology to find the quadratic regression model for <span class="math inline">\(P\)</span> in terms of <span class="math inline">\(x\)</span>, giving the coefficients correct to three significant figures.</span></p>
<p><strong>(c)</strong> <span class="q-en">Write down the value of <span class="math inline">\(R^{2}\)</span> and interpret it in context.</span></p>
<p><strong>(d)</strong> <span class="q-en">Use your model to find the selling price that gives the greatest profit.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある店が、<span class="math inline">\(6\)</span> 通りの販売価格 <span class="math inline">\(x\)</span>（ドル）について、<span class="math inline">\(1\)</span> 日の利益 <span class="math inline">\(P\)</span>（ドル）を記録しました。</p>
<p><strong>(a)</strong> このデータに線形モデルが適さない理由を説明しなさい。</p>
<p><strong>(b)</strong> 電卓を使って、<span class="math inline">\(P\)</span> を <span class="math inline">\(x\)</span> で表す二次の回帰モデルを求めなさい。係数は有効数字 <span class="math inline">\(3\)</span> 桁で書きなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(R^{2}\)</span> の値を書き、文脈の中で説明しなさい。</p>
<p><strong>(d)</strong> このモデルを使って、利益が最大になる販売価格を求めなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> 散布図をかくと、<strong>真ん中が高い山の形</strong>になります。値段を上げると、はじめは利益が増えますが、途中から客が減って利益も減るからです。</p>
<p>直線を当てはめても、この山をなぞれません。実際、直線の <span class="math inline">\(R^{2}\)</span> は <span class="math inline">\(0.0000608\)</span>——<strong>ほとんど <span class="math inline">\(0\)</span></strong> です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The profit increases and then decreases, so the points lie on a curve with a single maximum rather than on a straight line. A linear model would not follow this shape.</em></p>
</div>
<p>（利益が増えてから減るので、点は山が <span class="math inline">\(1\)</span> つの曲線の上に並んでいて、直線にはならない、という意味です。）</p>
<p><strong>(b)</strong> <code>Quadratic Regression</code> を走らせます（<a href="#gdc-curve">GDC 第2節</a>）。</p>
<p><span class="math display">\[
P = -5.00x^{2} + 69.9x - 44.2
\]</span></p>
<p><strong>検算。</strong> <span class="math inline">\(a\)</span> が負なので、上に凸の山の形です ✓ (a) で見た散布図と合っています。</p>
<p><strong>(c)</strong> 電卓が <span class="math inline">\(R^{2} = 0.993\)</span> を返します。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(R^{2} = 0.993\)</span>, so the quadratic model accounts for <span class="math inline">\(99.3\%\)</span> of the variability in the daily profit.</em></p>
</div>
<p>（このモデルが <span class="math inline">\(1\)</span> 日の利益のばらつきの <span class="math inline">\(99.3\%\)</span> を説明している、という意味です。<strong>「利益」という言葉を必ず入れてください。</strong>）</p>
<p><strong>(d)</strong> 山の頂点を求めます。電卓のグラフで <code>Maximum</code> を読んでも、頂点の公式を使っても構いません（<a href="../../ai-sl/02-functions/sl-2-4.html">SL 2.4</a>）。</p>
<p><span class="math display">\[
x = -\frac{69.9}{2 \times (-5.00)} = 6.99
\]</span></p>
<p><span class="math display">\[
P(6.99) = 200
\]</span></p>
<p><strong>約 <span class="math inline">\(7\)</span> ドルのとき、利益は約 <span class="math inline">\(200\)</span> ドル</strong>で最大になります。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>The profit rises and then falls, so the data has a single maximum and does not lie on a straight line.</em></p>
<p><strong>(b)</strong> <span class="math display">\[
P = -5.00x^{2} + 69.9x - 44.2
\]</span></p>
<p><strong>(c)</strong> <em><span class="math inline">\(R^{2} = 0.993\)</span>: the model accounts for <span class="math inline">\(99.3\%\)</span> of the variability in the daily profit.</em></p>
<p><strong>(d)</strong> <span class="math display">\[
x = 6.99 \quad \Rightarrow \quad P = 200
\]</span></p>
<p><em>The greatest profit, about <span class="math inline">\(200\)</span> dollars, occurs at a selling price of about <span class="math inline">\(7\)</span> dollars.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>(d) は「価格」を聞かれています
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>the selling price that gives the greatest profit</code> なので、答えは <strong><span class="math inline">\(x = 6.99\)</span></strong>（ドル）です。</p>
<p><span class="math inline">\(P = 200\)</span> だけを書くと、<strong>聞かれたものと違うもの</strong>を答えたことになります。両方書いておくのが確実です。</p>
</div>
</div>
</div>
<div id="exm-ahl413-compare" class="theorem example">
<p><span class="theorem-title"><strong>例題 3</strong></span> <span class="q-en">The value <span class="math inline">\(V\)</span>, in dollars, of a car is recorded each year for six years. The age of the car is <span class="math inline">\(t\)</span> years.</span></p>
<div id="tbl-ahl413-we3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-we3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;9: Age and value of a car
</figcaption>
<div aria-describedby="tbl-ahl413-we3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(t\)</span></th>
<th><span class="math inline">\(0\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
<th><span class="math inline">\(5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(V\)</span></td>
<td><span class="math inline">\(24\,400\)</span></td>
<td><span class="math inline">\(20\,000\)</span></td>
<td><span class="math inline">\(15\,700\)</span></td>
<td><span class="math inline">\(12\,700\)</span></td>
<td><span class="math inline">\(10\,800\)</span></td>
<td><span class="math inline">\(8200\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Find the linear regression model for <span class="math inline">\(V\)</span> in terms of <span class="math inline">\(t\)</span>, and write down its value of <span class="math inline">\(R^{2}\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the exponential regression model for <span class="math inline">\(V\)</span> in terms of <span class="math inline">\(t\)</span>, and write down its value of <span class="math inline">\(R^{2}\)</span>.</span></p>
<p><strong>(c)</strong> <span class="q-en">Use each model to predict the value of the car when <span class="math inline">\(t = 8\)</span>. Comment on your answers.</span></p>
<p><strong>(d)</strong> <span class="q-en">A student fits a cubic model and finds <span class="math inline">\(R^{2} = 0.99824\)</span>, which is greater than the value in part (b). Explain why this does not show that the cubic model is better.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある車の価値 <span class="math inline">\(V\)</span>（ドル）を、<span class="math inline">\(6\)</span> 年間、毎年記録しました。車の年数は <span class="math inline">\(t\)</span> 年です。</p>
<p><strong>(a)</strong> <span class="math inline">\(V\)</span> を <span class="math inline">\(t\)</span> で表す線形の回帰モデルを求め、その <span class="math inline">\(R^{2}\)</span> の値を書きなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(V\)</span> を <span class="math inline">\(t\)</span> で表す指数の回帰モデルを求め、その <span class="math inline">\(R^{2}\)</span> の値を書きなさい。</p>
<p><strong>(c)</strong> それぞれのモデルを使って、<span class="math inline">\(t = 8\)</span> のときの車の価値を予測しなさい。その答えについて述べなさい。</p>
<p><strong>(d)</strong> ある生徒が三次のモデルを当てはめたところ、<span class="math inline">\(R^{2} = 0.99824\)</span> となり、(b) の値より大きくなりました。これによって三次のモデルのほうがよいとは言えない理由を説明しなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> <code>Linear Regression (mx+b)</code> を走らせます。</p>
<p><span class="math display">\[
V = -3190t + 23300, \qquad R^{2} = 0.975
\]</span></p>
<p><strong>(b)</strong> <code>Exponential Regression</code> を走らせます。</p>
<p><span class="math display">\[
V = 24500(0.807)^{t}, \qquad R^{2} = 0.998
\]</span></p>
<p><strong>検算。</strong> <span class="math inline">\(0.807\)</span> は <span class="math inline">\(1\)</span> より小さいので、減っていく形です ✓ 毎年およそ <span class="math inline">\(19\%\)</span> ずつ減る、という意味になります。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>exponential と power では、電卓が表示する <span class="math inline">\(R^{2}\)</span> の桁が、ここと少し違うことがあります。</strong> 多くの機種は、両辺の <span class="math inline">\(\log\)</span> を取って<strong>直線に直してから</strong> <span class="math inline">\(R^{2}\)</span> を計算するからです。ここに書いた <span class="math inline">\(0.998\)</span> は、シラバスの言い方どおり「<strong><span class="math inline">\(V\)</span> のばらつき</strong>のうち説明できた割合」として計算した値です。</p>
<p>答案には、<strong>自分の電卓が表示した値</strong>を書いてください。どちらの出し方でも linear の <span class="math inline">\(0.975\)</span> より大きく、(c) の結論は変わりません。</p>
</div>
</div>
</div>
<p><strong>(c)</strong> <span class="math inline">\(t = 8\)</span> を、それぞれに入れます。</p>
<div id="tbl-ahl413-we3c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-we3c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;10: <span class="math inline">\(8\)</span> 年後の予測
</figcaption>
<div aria-describedby="tbl-ahl413-we3c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>モデル</th>
<th><span class="math inline">\(t = 8\)</span> の予測</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>linear</td>
<td><span class="math inline">\(-2240\)</span> ドル</td>
</tr>
<tr class="even">
<td>exponential</td>
<td><span class="math inline">\(4400\)</span> ドル</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>代入するときは、電卓に入っている丸める前の係数を使ってください。</strong> (a) で書いた <span class="math inline">\(-3190\)</span> と <span class="math inline">\(23300\)</span> をそのまま使うと <span class="math inline">\(-2220\)</span> になり、<span class="math inline">\(3\)</span> 桁目が変わります。答案には <span class="math inline">\(3\)</span> 桁で書き、計算は電卓の値で——これは AI 全体の作法です。</p>
</div>
</div>
</div>
<p><code>Comment on</code> と言われているので、<strong>この <span class="math inline">\(2\)</span> つを比べて、意味を書きます。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The linear model predicts a value of <span class="math inline">\(-2240\)</span> dollars, which is impossible because a car cannot have a negative value. The exponential model predicts <span class="math inline">\(4400\)</span> dollars, which is sensible. The exponential model also has the larger <span class="math inline">\(R^{2}\)</span>, so it is the better model for this data.</em></p>
</div>
<p>（直線は負の値を出すのでありえない、指数のほうは妥当な値で、<span class="math inline">\(R^{2}\)</span> も大きい、という意味です。）</p>
<p><strong>(d)</strong> <code>Explain why</code> です。<a href="#more-terms">第8節</a>の内容を、この場面の言葉で書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>A cubic model has four coefficients, while the exponential model has two, so the cubic can be adjusted to pass closer to only six data points. A larger <span class="math inline">\(R^{2}\)</span> obtained in this way does not show that the model is better. The cubic predicts a negative value a few years later, which is impossible for the value of a car, so the exponential model fits the context better.</em></p>
</div>
<p>（係数が <span class="math inline">\(4\)</span> 個あるので <span class="math inline">\(6\)</span> 個の点に寄り添えるだけで、しかも数年先で負の値を出すからありえない、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(V = -3190t + 23300\)</span>, <span class="math inline">\(R^{2} = 0.975\)</span></p>
<p><strong>(b)</strong> <span class="math inline">\(V = 24500(0.807)^{t}\)</span>, <span class="math inline">\(R^{2} = 0.998\)</span></p>
<p><strong>(c)</strong> <span class="math display">\[
\text{linear: } V(8) = -2240, \qquad \text{exponential: } V(8) = 4400
\]</span></p>
<p><em>The linear model gives a negative value, which is impossible, so the exponential model is the better one.</em></p>
<p><strong>(d)</strong> <em>The cubic has four coefficients against two, so it can be made to pass closer to six points. A larger <span class="math inline">\(R^{2}\)</span> alone does not make it a better model, and it predicts a negative value soon after the data ends.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(R^{2} = 0.975\)</span> を「悪い」と書かない
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="a">
<li>の <span class="math inline">\(0.975\)</span> は、<strong>それ自体は高い値</strong>です。直線がまずいのは、<span class="math inline">\(R^{2}\)</span> が低いからではなく、<strong>データの外で意味を失うから</strong>です（<a href="#nonsense">第8節</a>）。</li>
</ol>
<p><code>Comment on</code> の答案では、<strong>その理由を書いてください。</strong> 「<span class="math inline">\(R^{2}\)</span> が小さいから」は、この問題では正しくありません。</p>
</div>
</div>
</div>
<div id="exm-ahl413-sine" class="theorem example">
<p><span class="theorem-title"><strong>例題 4</strong></span> <span class="q-en">The table shows the number of hours of daylight <span class="math inline">\(D\)</span> on the 15th day of each month <span class="math inline">\(m\)</span> in a certain city, where <span class="math inline">\(m = 1\)</span> is January.</span></p>
<div id="tbl-ahl413-we4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-we4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;11: Hours of daylight
</figcaption>
<div aria-describedby="tbl-ahl413-we4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(m\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
<th><span class="math inline">\(5\)</span></th>
<th><span class="math inline">\(6\)</span></th>
<th><span class="math inline">\(7\)</span></th>
<th><span class="math inline">\(8\)</span></th>
<th><span class="math inline">\(9\)</span></th>
<th><span class="math inline">\(10\)</span></th>
<th><span class="math inline">\(11\)</span></th>
<th><span class="math inline">\(12\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(D\)</span></td>
<td><span class="math inline">\(9.1\)</span></td>
<td><span class="math inline">\(10.2\)</span></td>
<td><span class="math inline">\(11.9\)</span></td>
<td><span class="math inline">\(13.7\)</span></td>
<td><span class="math inline">\(15.2\)</span></td>
<td><span class="math inline">\(15.9\)</span></td>
<td><span class="math inline">\(15.4\)</span></td>
<td><span class="math inline">\(14.0\)</span></td>
<td><span class="math inline">\(12.2\)</span></td>
<td><span class="math inline">\(10.5\)</span></td>
<td><span class="math inline">\(9.3\)</span></td>
<td><span class="math inline">\(8.8\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Explain why a sine model is appropriate for this data.</span></p>
<p><strong>(b)</strong> <span class="q-en">Use technology to find the sinusoidal regression model, giving the coefficients correct to three significant figures.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the period of your model, and comment on its value.</span></p>
<p><strong>(d)</strong> <span class="q-en">Write down the value of <span class="math inline">\(R^{2}\)</span> and interpret it in context.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>表は、ある都市の各月 <span class="math inline">\(m\)</span> の <span class="math inline">\(15\)</span> 日における日照時間 <span class="math inline">\(D\)</span>（時間）を示しています。<span class="math inline">\(m = 1\)</span> が <span class="math inline">\(1\)</span> 月です。</p>
<p><strong>(a)</strong> このデータに正弦のモデルが適している理由を説明しなさい。</p>
<p><strong>(b)</strong> 電卓を使って正弦の回帰モデルを求めなさい。係数は有効数字 <span class="math inline">\(3\)</span> 桁で書きなさい。</p>
<p><strong>(c)</strong> モデルの周期を求め、その値について述べなさい。</p>
<p><strong>(d)</strong> <span class="math inline">\(R^{2}\)</span> の値を書き、文脈の中で説明しなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> 日照時間は、<strong>毎年同じように増えて減ります。</strong> くり返す量なので、sine のモデルが合います（<a href="../../ai-sl/02-functions/sl-2-5.html#sinusoidal">SL 2.5</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The number of hours of daylight increases to a maximum and then decreases, repeating in the same way every year, so a periodic model such as a sine function is appropriate.</em></p>
</div>
<p>（毎年同じようにくり返すので、周期的なモデルが適している、という意味です。）</p>
<p><strong>(b)</strong> <code>Sinusoidal Regression</code> を走らせます（<a href="#gdc-curve">GDC 第2節</a>）。</p>
<p><span class="math display">\[
D = 3.47\sin(0.547m - 1.76) + 12.3
\]</span></p>
<p><strong>検算。</strong> 電卓に入れる前に、<span class="math inline">\(a\)</span> と <span class="math inline">\(d\)</span> を見積もっておくと安心です。</p>
<p><span class="math display">\[
a \approx \frac{15.9 - 8.8}{2} = 3.55, \qquad d \approx \frac{15.9 + 8.8}{2} = 12.35
\]</span></p>
<p>出てきた <span class="math inline">\(3.47\)</span> と <span class="math inline">\(12.3\)</span> に近い値です ✓</p>
<p><strong>(c)</strong> 周期は <span class="math inline">\(\dfrac{2\pi}{b}\)</span> です。<a href="../../ai-sl/02-functions/sl-2-5.html#sinusoidal">SL 2.5</a> では Degree で考えたので <span class="math inline">\(\dfrac{360}{b}\)</span> でした。<strong>同じ式の、角の単位ちがい</strong>です。ここでは電卓が radian で <span class="math inline">\(b\)</span> を返すので、<span class="math inline">\(2\pi\)</span> を使います。</p>
<p><span class="math display">\[
\text{period} = \frac{2\pi}{0.547} = 11.5
\]</span></p>
<p><code>comment on</code> なので、<strong>この数の意味を書きます。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The period is <span class="math inline">\(11.5\)</span> months, which is close to <span class="math inline">\(12\)</span>. This is what we expect, because the pattern of daylight repeats once every year.</em></p>
</div>
<p>（周期が <span class="math inline">\(11.5\)</span> か月で <span class="math inline">\(12\)</span> に近く、<span class="math inline">\(1\)</span> 年でくり返すという事実と合っている、という意味です。）</p>
<p><strong>(d)</strong> 電卓が <span class="math inline">\(R^{2} = 0.999\)</span> を返します。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(R^{2} = 0.999\)</span>, so the model accounts for <span class="math inline">\(99.9\%\)</span> of the variability in the number of hours of daylight.</em></p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>The data repeats in the same way each year, so a periodic (sine) model is appropriate.</em></p>
<p><strong>(b)</strong> <span class="math display">\[
D = 3.47\sin(0.547m - 1.76) + 12.3
\]</span></p>
<p><strong>(c)</strong> <span class="math display">\[
\text{period} = \frac{2\pi}{0.547} = 11.5 \ \text{months}
\]</span></p>
<p><em>This is close to <span class="math inline">\(12\)</span>, as expected for a yearly cycle.</em></p>
<p><strong>(d)</strong> <em><span class="math inline">\(R^{2} = 0.999\)</span>: the model accounts for <span class="math inline">\(99.9\%\)</span> of the variability in the hours of daylight.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>電卓は Radian にしてください
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>Sinusoidal Regression</code> の <span class="math inline">\(b\)</span> と <span class="math inline">\(c\)</span> は、<strong>radian で返ってきます。</strong> 設定が Degree のままだと、周期を出すときに <span class="math inline">\(\dfrac{2\pi}{b}\)</span> が使えません。</p>
<pre><code>ctrl + doc → Document Settings → Angle: Radian</code></pre>
<p><strong>周期が <span class="math inline">\(11.5\)</span> ではなく <span class="math inline">\(0.2\)</span> のような小さい値になったら、設定を疑ってください。</strong> Degree のままだと <span class="math inline">\(b\)</span> が <span class="math inline">\(31.4\)</span> 前後の大きな値で返るので、<span class="math inline">\(\dfrac{2\pi}{b}\)</span> がとても小さくなります。</p>
</div>
</div>
</div>
</section>
<section id="common-errors" class="level2">
<h2 class="anchored" data-anchor-id="common-errors">Common errors</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(R^{2}\)</span> がいちばん大きいモデルを、そのまま選ぶ
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>この項目でいちばん大きな失点です。</strong> シラバスが名指しで注意しています（<a href="#choosing">第8節</a>）。</p>
<p><span class="math inline">\(R^{2}\)</span> は判断材料の <span class="math inline">\(1\)</span> つです。<strong>散布図の形・文脈・データの外での値</strong>もいっしょに見てください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>係数の数を考えずに <span class="math inline">\(R^{2}\)</span> を比べる
</div>
</div>
<div class="callout-body-container callout-body">
<p>cubic は quadratic を、quadratic は linear を含みます。<strong>次数を上げても、<span class="math inline">\(R^{2}\)</span> が下がることはありません</strong>（<a href="#why-more">Why it works</a>）。</p>
<p>「cubic のほうが <span class="math inline">\(R^{2}\)</span> が大きいから cubic」は、理由になっていません。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(R^{2}\)</span> を数のまま書いて終わる
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>interpret</code> や <code>comment on</code> が付いていたら、<strong>「<span class="math inline">\(y\)</span> のばらつきの <span class="math inline">\(\square\%\)</span> を説明している」の形</strong>で、<span class="math inline">\(y\)</span> をその問題の言葉に置きかえて書きます（<a href="#r2">第6節</a>）。</p>
<p>「<span class="math inline">\(R^{2}\)</span> が高いのでよいモデルです」は、解釈になっていません。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(R^{2}\)</span> を「相関の強さ」と書く
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(R^{2}\)</span> は<strong>説明できた割合</strong>です。相関の強さと向きを表すのは <span class="math inline">\(r\)</span> のほうです（<a href="#tbl-ahl413-r-r2" class="quarto-xref">表&nbsp;4</a>）。</p>
<p>そして <span class="math inline">\(r\)</span> が使えるのは <strong>linear model のときだけ</strong>です。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(R^{2}\)</span> から <span class="math inline">\(r\)</span> を出すときに、符号を忘れる
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(R^{2} = 0.81\)</span> なら <span class="math inline">\(r = 0.9\)</span> <strong>または</strong> <span class="math inline">\(r = -0.9\)</span> です。<strong><span class="math inline">\(R^{2}\)</span> からは向きが決まりません</strong>（<a href="#r2-r">第7節</a>）。</p>
<p>散布図か、回帰直線の傾きの符号を見て決めてください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>residual を、点から曲線までの最短距離にする
</div>
</div>
<div class="callout-body-container callout-body">
<p>residual は<strong>たて向き</strong>のずれ <span class="math inline">\(y - \hat{y}\)</span> です（<a href="#residual">第3節</a>）。斜めに測るのではありません。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>residual をそのまま足して、それを <span class="math inline">\(SS_{\text{res}}\)</span> にしてしまう
</div>
</div>
<div class="callout-body-container callout-body">
<p>正と負が打ち消し合ってしまいます。だから <strong><span class="math inline">\(2\)</span> 乗してから足します</strong>（<a href="#ssres">第4節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(SS_{\text{res}}\)</span> を、別のデータどうしで比べる
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(SS_{\text{res}}\)</span> は<strong>単位とデータの個数に左右されます</strong>。比べてよいのは、<strong>同じデータに別のモデルを当てはめたとき</strong>だけです（<a href="#ssres">第4節</a>）。</p>
<p>データが違うものどうしを比べるなら、<span class="math inline">\(R^{2}\)</span> を使ってください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>power と exponential を取りちがえる
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(y = ax^{n}\)</span> が power、<span class="math inline">\(y = ka^{x}\)</span> が exponential です。<strong><span class="math inline">\(x\)</span> が底か指数か</strong>で見分けます（<a href="#models">第2節</a>）。</p>
<p>問題文の「毎年 <span class="math inline">\(\square\%\)</span> ずつ」は exponential、「<span class="math inline">\(\square\)</span> に比例する」は power の合図です。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>sinusoidal regression を Degree のまま走らせる
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(b\)</span> と <span class="math inline">\(c\)</span> が radian で返るので、周期 <span class="math inline">\(\dfrac{2\pi}{b}\)</span> が合わなくなります。<strong>Radian に設定してから</strong>走らせてください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>データの範囲の外まで、そのまま予測する
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(R^{2}\)</span> が高くても、<strong>extrapolation の危険は消えません</strong>（<a href="../../ai-sl/04-statistics-and-probability/sl-4-4.html#extrapolation">SL 4.4</a>）。</p>
<p><a href="#exm-ahl413-compare" class="quarto-xref">例&nbsp;3</a> のように、外へ出た瞬間に意味を失うモデルがあります。</p>
</div>
</div>
</section>
<section id="using-your-gdc-ti-nspire-cx-ii" class="level2">
<h2 class="anchored" data-anchor-id="using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</h2>
<p>この項目は、<strong>電卓が主役</strong>です。手順は SL 4.4 とほとんど同じで、選ぶメニューが増えるだけです。</p>
<section id="gdc-linear" class="level3">
<h3 class="anchored" data-anchor-id="gdc-linear">1. データを入れて、直線を当てはめる</h3>
<p><a href="../../ai-sl/04-statistics-and-probability/sl-4-4.html#gdc-regression">SL 4.4</a> と同じです。Lists &amp; Spreadsheet に <span class="math inline">\(2\)</span> 列を作り、名前を付けます。</p>
<pre><code>menu → Statistics → Stat Calculations → Linear Regression (mx+b)</code></pre>
<p><code>X List</code> と <code>Y List</code> を指定して <code>OK</code>。<code>m</code>、<code>b</code>、<code>r</code>、<code>r²</code> が返ります。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span><code>r²</code> が、この項目の <span class="math inline">\(R^{2}\)</span> です
</div>
</div>
<div class="callout-body-container callout-body">
<p>SL 4.4 では読まなかった行です。<strong>linear model では <span class="math inline">\(R^{2} = r^{2}\)</span></strong> なので、同じものです（<a href="#r2-r">第7節</a>）。</p>
</div>
</div>
</section>
<section id="gdc-curve" class="level3">
<h3 class="anchored" data-anchor-id="gdc-curve">2. 曲線を当てはめる</h3>
<p>同じメニューの下に、<span class="math inline">\(6\)</span> つのモデルが並んでいます。</p>
<pre><code>menu → Statistics → Stat Calculations → Quadratic Regression
                                      → Cubic Regression
                                      → Exponential Regression
                                      → Power Regression
                                      → Sinusoidal Regression</code></pre>
<p>入れるものは linear と同じ（<code>X List</code> と <code>Y List</code>）です。返ってくる係数の名前だけが変わります。</p>
<p><strong>文字は、電卓に合わせてください。</strong> <a href="#models">第2節</a>では exponential を <span class="math inline">\(y = ka^{x}\)</span>、power を <span class="math inline">\(y = ax^{n}\)</span> と書きましたが、電卓はどちらも <code>a</code> と <code>b</code> で返します。<strong>中身は同じ</strong>です。</p>
<div id="tbl-ahl413-gdc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-gdc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;12: 電卓の係数と、答案に書く式
</figcaption>
<div aria-describedby="tbl-ahl413-gdc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>モデル</th>
<th>返る係数</th>
<th>書き直す式</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quadratic</td>
<td><code>a</code>, <code>b</code>, <code>c</code></td>
<td><span class="math inline">\(y = ax^{2} + bx + c\)</span></td>
</tr>
<tr class="even">
<td>Cubic</td>
<td><code>a</code>, <code>b</code>, <code>c</code>, <code>d</code></td>
<td><span class="math inline">\(y = ax^{3} + bx^{2} + cx + d\)</span></td>
</tr>
<tr class="odd">
<td>Exponential</td>
<td><code>a</code>, <code>b</code></td>
<td><span class="math inline">\(y = a b^{x}\)</span></td>
</tr>
<tr class="even">
<td>Power</td>
<td><code>a</code>, <code>b</code></td>
<td><span class="math inline">\(y = a x^{b}\)</span></td>
</tr>
<tr class="odd">
<td>Sinusoidal</td>
<td><code>a</code>, <code>b</code>, <code>c</code>, <code>d</code></td>
<td><span class="math inline">\(y = a\sin(bx + c) + d\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>画面に出ている値を、そのまま写してください
</div>
</div>
<div class="callout-body-container callout-body">
<p>返る値が <code>R²</code> と出るか <code>r²</code> と出るかは、<strong>選んだモデルによって変わります。</strong> どちらでも、答案には <span class="math inline">\(R^{2}\)</span> と書いて構いません。</p>
<p><strong>試験でやることは <span class="math inline">\(1\)</span> つです。画面に出た値を、丸めずに書き写す。</strong> これで答えは合います。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>ここから先は、意味のほうの話です。</strong></p>
<p>多項式のモデルでは、この値は「<strong><span class="math inline">\(y\)</span> のばらつきのうち、モデルで説明できた割合</strong>」です。<a href="#r2">第6節</a>で見たとおりの意味で、シラバスの言い方もこれです。</p>
<p><strong>exponential と power は、事情が違います。</strong> 機種によっては、両辺の <span class="math inline">\(\log\)</span> を取って直線に直したあとの値が表示されます。それは「<strong><span class="math inline">\(\log y\)</span> のばらつきのうち説明できた割合</strong>」であって、<strong><span class="math inline">\(y\)</span> そのものについての <span class="math inline">\(R^{2}\)</span> とは同じ意味になりません。</strong> 値も少しずれます（<a href="#exm-ahl413-compare">例題3</a>の注意）。</p>
<p>ですから、<span class="math inline">\(R^{2}\)</span> の値を<strong>モデルどうしの比較に使うとき</strong>は、<strong>同じ出し方の値どうしで比べてください。</strong> 多項式の <span class="math inline">\(R^{2}\)</span> と、<span class="math inline">\(\log\)</span> スケールの <span class="math inline">\(r^{2}\)</span> を並べても、公平な比較になりません。</p>
<p>これも、<strong><span class="math inline">\(R^{2}\)</span> だけでモデルを選べない理由</strong>の <span class="math inline">\(1\)</span> つです（<a href="#choosing">第8節</a>）。</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>散布図に、当てはめた曲線を重ねる
</div>
</div>
<div class="callout-body-container callout-body">
<p>数だけ見ていると、形が合っているかどうかは分かりません。</p>
<pre><code>ctrl + doc → Add Data &amp; Statistics</code></pre>
<p>で散布図をかき、</p>
<pre><code>menu → Analyze → Regression → Show Quadratic</code></pre>
<p>のように重ねてください。<strong>曲線が点の並びをなぞっているか</strong>を、目で確かめる——<a href="#choosing">第8節</a>の <span class="math inline">\(1\)</span> つ目がこれです。</p>
</div>
</div>
</section>
<section id="gdc-radian" class="level3">
<h3 class="anchored" data-anchor-id="gdc-radian">3. Sinusoidal は Radian で</h3>
<p><code>Sinusoidal Regression</code> を走らせる前に、角の設定を確かめてください。</p>
<pre><code>ctrl + doc → Document Settings → Angle: Radian</code></pre>
<p>Degree のままだと <span class="math inline">\(b\)</span> が別の値で返り、周期 <span class="math inline">\(\dfrac{2\pi}{b}\)</span> が合わなくなります。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>この項目だけ、Radian です
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-9.html">AHL 3.9</a> の変換行列は Degree でした。<strong>設定は文書ごとに保存される</strong>ので、切りかえたら戻すのを忘れないでください。</p>
</div>
</div>
</section>
<section id="gdc-ssres" class="level3">
<h3 class="anchored" data-anchor-id="gdc-ssres">4. <span class="math inline">\(SS_{\text{res}}\)</span> は、自分で作ります</h3>
<p>電卓は <span class="math inline">\(SS_{\text{res}}\)</span> を直接は返しません。<a href="#exm-ahl413-ssres" class="quarto-xref">例&nbsp;1</a> のような問題では、列を足して作ります。</p>
<ul>
<li>列 C … <code>=b[] - (2*a[]+1)</code> のように、<strong>residual</strong> を作る</li>
<li>列 D … <code>=c[]^2</code></li>
</ul>
<p>そして</p>
<pre><code>sum(d[])</code></pre>
<p>で合計します。<strong><span class="math inline">\(5\)</span> 点くらいなら、手で書き出したほうが速い</strong>こともあります。</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>回帰曲線の residual は、電卓が作ってくれます
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>Linear Regression</code> などを走らせたあと、Lists &amp; Spreadsheet に <code>stat.resid</code> という変数ができています。</p>
<p>新しい列に <code>=stat.resid</code> と打てば、residual が並びます。その列を <span class="math inline">\(2\)</span> 乗して足せば <span class="math inline">\(SS_{\text{res}}\)</span> です。</p>
</div>
</div>
</section>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>各問題に、折りたたみが3つ付いています。<strong>日本語訳</strong>、<strong>解答例</strong>（答案用紙に書くべきこと。英語です）、<strong>解説</strong>（なぜそうなるか。日本語です）。</p>
<p>まず自分で解いて、次に解答例と見くらべてください。<strong>解説は、合わなかったときだけ開けば十分です。</strong></p>
</div>
</div>
</div>
<div class="exercise-block">
<p><span class="ex-no">1</span> <span class="q-en">For each of the following situations, state which of the six models would be most appropriate, and give a reason.</span></p>
<p><strong>(a)</strong> <span class="q-en">The population of a town, which grows by about <span class="math inline">\(3\%\)</span> each year.</span></p>
<p><strong>(b)</strong> <span class="q-en">The height of water in a harbour, recorded every hour for two days.</span></p>
<p><strong>(c)</strong> <span class="q-en">The height of a ball thrown upwards, recorded every <span class="math inline">\(0.2\)</span> seconds until it lands.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>次のそれぞれの場面について、<span class="math inline">\(6\)</span> つのモデルのうちどれが最も適切かを述べ、理由を書きなさい。</p>
<p><strong>(a)</strong> 毎年およそ <span class="math inline">\(3\%\)</span> ずつ増える町の人口。</p>
<p><strong>(b)</strong> <span class="math inline">\(2\)</span> 日間、<span class="math inline">\(1\)</span> 時間ごとに記録した港の水位。</p>
<p><strong>(c)</strong> 上向きに投げたボールの高さを、着地するまで <span class="math inline">\(0.2\)</span> 秒ごとに記録したもの。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Exponential, because the population is multiplied by the same factor each year.</em></p>
<p><strong>(b)</strong> <em>Sine, because the tide repeats in the same way roughly twice a day.</em></p>
<p><strong>(c)</strong> <em>Quadratic, because the height rises to a single maximum and then falls.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 「毎年 <span class="math inline">\(3\%\)</span> ずつ」は、<strong>毎年 <span class="math inline">\(1.03\)</span> 倍</strong>という意味です。同じ割合を掛け続けるのが exponential でした（<a href="#models">第2節</a>）。</p>
<p><strong>「毎年 <span class="math inline">\(\square\)</span> 人ずつ増える」だったら linear</strong> です。<strong>掛けるのか、足すのか</strong>を読み分けてください。</p>
<p><strong>(b)</strong> 潮の満ち引きは<strong>くり返し</strong>ます。くり返す量は sine です。</p>
<p><strong>(c)</strong> 上がって、下がる。<strong>山が <span class="math inline">\(1\)</span> つ</strong>なので quadratic です。</p>
<p><code>give a reason</code> なので、<strong>理由を必ず書いてください。</strong> モデルの名前だけでは点になりません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>(a) Exponential, because the population is multiplied by the same factor <span class="math inline">\(1.03\)</span> each year, rather than increased by the same amount.</em></p>
<p><em>(b) Sine, because the water level repeats the same pattern about twice a day.</em></p>
<p><em>(c) Quadratic, because the height rises to a single maximum and then falls back symmetrically.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">2</span> <span class="q-en">The model <span class="math inline">\(\hat{y} = 3x - 2\)</span> is proposed for the following data.</span></p>
<div id="tbl-ahl413-ex2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-ex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;13: Data for question 2
</figcaption>
<div aria-describedby="tbl-ahl413-ex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y\)</span></td>
<td><span class="math inline">\(2\)</span></td>
<td><span class="math inline">\(5\)</span></td>
<td><span class="math inline">\(8\)</span></td>
<td><span class="math inline">\(12\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Find the residual for each point.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find <span class="math inline">\(SS_{\text{res}}\)</span>.</span></p>
<p><strong>(c)</strong> <span class="q-en">Given that <span class="math inline">\(\bar{y} = 6.75\)</span>, find <span class="math inline">\(SS_{\text{tot}}\)</span> and hence <span class="math inline">\(R^{2}\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>次のデータに、モデル <span class="math inline">\(\hat{y} = 3x - 2\)</span> が提案されています。</p>
<p><strong>(a)</strong> 各点の残差を求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(SS_{\text{res}}\)</span> を求めなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(\bar{y} = 6.75\)</span> であるとき、<span class="math inline">\(SS_{\text{tot}}\)</span> を求め、それを使って <span class="math inline">\(R^{2}\)</span> を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em><span class="math inline">\(\hat{y} = 1,\ 4,\ 7,\ 10\)</span>, so the residuals are <span class="math inline">\(1\)</span>, <span class="math inline">\(1\)</span>, <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>.</em></p>
<p><strong>(b)</strong> <span class="math display">\[
SS_{\text{res}} = 1 + 1 + 1 + 4 = 7
\]</span></p>
<p><strong>(c)</strong> <span class="math display">\[
SS_{\text{tot}} = (2-6.75)^{2} + (5-6.75)^{2} + (8-6.75)^{2} + (12-6.75)^{2} = 54.75
\]</span> <span class="math display">\[
R^{2} = 1 - \frac{7}{54.75} = 0.872
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-44-contents" aria-controls="callout-44" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-44" class="callout-44-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(\hat{y}\)</span> を先に全部出してから引くと、間違えにくくなります。</p>
<p><span class="math display">\[
\hat{y} = 1,\ 4,\ 7,\ 10 \quad \Rightarrow \quad y - \hat{y} = 1,\ 1,\ 1,\ 2
\]</span></p>
<p><strong>residual が全部正</strong>です。この場合、モデルは全部の点の<strong>下</strong>を通っています。</p>
<p><strong>(b)</strong> <span class="math inline">\(2\)</span> 乗して足します。<span class="math inline">\(1 + 1 + 1 + 4 = 7\)</span>。</p>
<p><strong>(c)</strong> <span class="math inline">\(SS_{\text{tot}}\)</span> は <span class="math inline">\(\bar{y}\)</span> からのずれの <span class="math inline">\(2\)</span> 乗の合計です（<a href="#eq-ahl413-sstot" class="quarto-xref">式&nbsp;3</a>）。</p>
<p><span class="math display">\[
\begin{aligned}
&amp;(-4.75)^{2} + (-1.75)^{2} + 1.25^{2} + 5.25^{2} \\
&amp;\qquad = 22.5625 + 3.0625 + 1.5625 + 27.5625 = 54.75
\end{aligned}
\]</span></p>
<p><span class="math display">\[
R^{2} = 1 - \frac{7}{54.75} = 0.8721\ldots = 0.872
\]</span></p>
<p><strong>この <span class="math inline">\(R^{2}\)</span> は、回帰直線のものではありません。</strong> 与えられたモデル <span class="math inline">\(\hat{y} = 3x-2\)</span> のものです。回帰直線ならもっと大きくなります（<a href="#least-squares">第5節</a>）。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">3</span> <span class="q-en">A linear regression model is fitted to a set of data and gives <span class="math inline">\(r = -0.84\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write down the value of <span class="math inline">\(R^{2}\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Interpret this value in context, where <span class="math inline">\(y\)</span> is the mass of a chemical remaining, in grams.</span></p>
<p><strong>(c)</strong> <span class="q-en">A different set of data gives <span class="math inline">\(R^{2} = 0.36\)</span> for a linear model. Find the two possible values of <span class="math inline">\(r\)</span>, and explain how you would decide which one applies.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>あるデータに線形の回帰モデルを当てはめたところ、<span class="math inline">\(r = -0.84\)</span> となりました。</p>
<p><strong>(a)</strong> <span class="math inline">\(R^{2}\)</span> の値を書きなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(y\)</span> が残っている薬品の質量（グラム）であるとき、この値を文脈の中で説明しなさい。</p>
<p><strong>(c)</strong> 別のデータでは、線形モデルの <span class="math inline">\(R^{2} = 0.36\)</span> でした。<span class="math inline">\(r\)</span> としてありうる <span class="math inline">\(2\)</span> つの値を求め、どちらが当てはまるかをどう決めるかを説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
R^{2} = (-0.84)^{2} = 0.7056 \approx 0.706
\]</span></p>
<p><strong>(b)</strong> <em>The model accounts for about <span class="math inline">\(70.6\%\)</span> of the variability in the mass of chemical remaining.</em></p>
<p><strong>(c)</strong> <span class="math display">\[
r = \sqrt{0.36} = 0.6 \quad \text{or} \quad r = -0.6
\]</span></p>
<p><em><span class="math inline">\(R^{2}\)</span> does not show the direction of the relationship. Look at the scatter diagram, or at the sign of the gradient of the regression line: a positive gradient gives <span class="math inline">\(r = 0.6\)</span> and a negative gradient gives <span class="math inline">\(r = -0.6\)</span>.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-46-contents" aria-controls="callout-46" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-46" class="callout-46-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> linear model なので <span class="math inline">\(R^{2} = r^{2}\)</span> です（<a href="#eq-ahl413-r2r" class="quarto-xref">式&nbsp;5</a>）。<strong>符号は消えます。</strong></p>
<p><strong>(b)</strong> 「割合」として、<strong>その問題の言葉</strong>で書きます（<a href="#r2">第6節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(R^{2} = 0.706\)</span>, so the linear model accounts for about <span class="math inline">\(70.6\%\)</span> of the variability in the mass of chemical remaining.</em></p>
</div>
<p><strong>(c)</strong> <span class="math inline">\(2\)</span> 乗して <span class="math inline">\(0.36\)</span> になるのは <span class="math inline">\(0.6\)</span> と <span class="math inline">\(-0.6\)</span> です。</p>
<p><code>explain how you would decide</code> なので、<strong>決め方を書きます。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(R^{2}\)</span> does not show the direction of the relationship, so both <span class="math inline">\(0.6\)</span> and <span class="math inline">\(-0.6\)</span> are possible. I would look at the scatter diagram: if it slopes upwards then <span class="math inline">\(r = 0.6\)</span>, and if it slopes downwards then <span class="math inline">\(r = -0.6\)</span>. The sign of the gradient of the regression line gives the same answer.</em></p>
</div>
<p><strong><span class="math inline">\(R^{2}\)</span> からは向きが決まらない</strong>、というのがこの問題の中心です（<a href="#r2-r">第7節</a>）。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">4</span> <span class="q-en">The period <span class="math inline">\(T\)</span>, in seconds, of a pendulum of length <span class="math inline">\(L\)</span> metres is measured.</span></p>
<div id="tbl-ahl413-ex4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-ex4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;14: Length and period of a pendulum
</figcaption>
<div aria-describedby="tbl-ahl413-ex4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(L\)</span></th>
<th><span class="math inline">\(0.2\)</span></th>
<th><span class="math inline">\(0.4\)</span></th>
<th><span class="math inline">\(0.6\)</span></th>
<th><span class="math inline">\(0.8\)</span></th>
<th><span class="math inline">\(1.0\)</span></th>
<th><span class="math inline">\(1.2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(T\)</span></td>
<td><span class="math inline">\(0.90\)</span></td>
<td><span class="math inline">\(1.27\)</span></td>
<td><span class="math inline">\(1.55\)</span></td>
<td><span class="math inline">\(1.80\)</span></td>
<td><span class="math inline">\(2.01\)</span></td>
<td><span class="math inline">\(2.20\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Use technology to find the power regression model for <span class="math inline">\(T\)</span> in terms of <span class="math inline">\(L\)</span>, giving the coefficients correct to three significant figures.</span></p>
<p><strong>(b)</strong> <span class="q-en">Write down the value of <span class="math inline">\(R^{2}\)</span>.</span></p>
<p><strong>(c)</strong> <span class="q-en">Theory predicts that <span class="math inline">\(T\)</span> is proportional to <span class="math inline">\(\sqrt{L}\)</span>. Comment on whether your model supports this.</span></p>
<p><strong>(d)</strong> <span class="q-en">Use your model to predict the period of a pendulum of length <span class="math inline">\(1.5\)</span> metres.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>長さ <span class="math inline">\(L\)</span> メートルの振り子の周期 <span class="math inline">\(T\)</span>（秒）を測定しました。</p>
<p><strong>(a)</strong> 電卓を使って、<span class="math inline">\(T\)</span> を <span class="math inline">\(L\)</span> で表すべき乗の回帰モデルを求めなさい。係数は有効数字 <span class="math inline">\(3\)</span> 桁で書きなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(R^{2}\)</span> の値を書きなさい。</p>
<p><strong>(c)</strong> 理論では、<span class="math inline">\(T\)</span> は <span class="math inline">\(\sqrt{L}\)</span> に比例するとされています。あなたのモデルがこれを支持するかどうかを述べなさい。</p>
<p><strong>(d)</strong> このモデルを使って、長さ <span class="math inline">\(1.5\)</span> メートルの振り子の周期を予測しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
T = 2.01 L^{0.499}
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(R^{2} = 1.00\)</span> （より正確には <span class="math inline">\(0.99995\)</span>）</p>
<p><strong>(c)</strong> <em>The exponent is <span class="math inline">\(0.499\)</span>, which is very close to <span class="math inline">\(0.5\)</span>, and <span class="math inline">\(L^{0.5} = \sqrt{L}\)</span>. So the model does support the theory that <span class="math inline">\(T\)</span> is proportional to <span class="math inline">\(\sqrt{L}\)</span>.</em></p>
<p><strong>(d)</strong> <span class="math display">\[
T = 2.01 \times 1.5^{0.499} = 2.46 \ \text{seconds}
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-48-contents" aria-controls="callout-48" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-48" class="callout-48-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 「<span class="math inline">\(\square\)</span> に比例する」という言い方なので power です（<a href="#models">第2節</a>）。<code>Power Regression</code> を選びます。</p>
<p><strong>(b)</strong> ほとんど <span class="math inline">\(1\)</span> です。<span class="math inline">\(3\)</span> 有効数字では <span class="math inline">\(1.00\)</span> になってしまうので、<strong>電卓の表示をもう少し詳しく書いておく</strong>と丁寧です。</p>
<p><strong>(c)</strong> ここがこの問題の中心です。<span class="math inline">\(\sqrt{L} = L^{0.5}\)</span> ですから、<strong>指数が <span class="math inline">\(0.5\)</span> に近いかどうか</strong>を見ます。</p>
<p><span class="math display">\[
0.499 \approx 0.5 \quad ✓
\]</span></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The model gives an exponent of <span class="math inline">\(0.499\)</span>, which is very close to <span class="math inline">\(0.5\)</span>. Since <span class="math inline">\(L^{0.5} = \sqrt{L}\)</span>, the data supports the theory that <span class="math inline">\(T\)</span> is proportional to <span class="math inline">\(\sqrt{L}\)</span>.</em></p>
</div>
<p><strong>(d)</strong> <span class="math inline">\(L = 1.5\)</span> はデータの範囲（<span class="math inline">\(0.2\)</span> から <span class="math inline">\(1.2\)</span>）の<strong>すぐ外</strong>です。少しだけの外挿なので、ふつうは受け入れられます。<strong>ただし「モデルがこの範囲でも成り立つと仮定して」という一言があると丁寧です。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">5</span> <span class="q-en">A set of data is fitted with three models. The results are shown below.</span></p>
<div id="tbl-ahl413-ex5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-ex5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;15: Three models fitted to the same data
</figcaption>
<div aria-describedby="tbl-ahl413-ex5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>model</th>
<th>number of coefficients</th>
<th><span class="math inline">\(R^{2}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>linear</td>
<td><span class="math inline">\(2\)</span></td>
<td><span class="math inline">\(0.912\)</span></td>
</tr>
<tr class="even">
<td>quadratic</td>
<td><span class="math inline">\(3\)</span></td>
<td><span class="math inline">\(0.968\)</span></td>
</tr>
<tr class="odd">
<td>cubic</td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(0.971\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Explain why the <span class="math inline">\(R^{2}\)</span> values cannot decrease down the table.</span></p>
<p><strong>(b)</strong> <span class="q-en">State one further piece of information you would need before choosing between the quadratic and cubic models.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>あるデータに <span class="math inline">\(3\)</span> つのモデルを当てはめました。結果は表のとおりです。</p>
<p>表の見出しは、<code>model</code> が「モデル」、<code>number of coefficients</code> が「係数の数」です。</p>
<p><strong>(a)</strong> 表を下に見ていくと <span class="math inline">\(R^{2}\)</span> が減ることはない理由を説明しなさい。</p>
<p><strong>(b)</strong> 二次と三次のどちらを選ぶかを決める前に必要な情報を、<span class="math inline">\(1\)</span> つ述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-49-contents" aria-controls="callout-49" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-49" class="callout-49-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Every straight line is also a quadratic with <span class="math inline">\(a = 0\)</span>, and every quadratic is also a cubic with the <span class="math inline">\(x^{3}\)</span> coefficient zero. The regression makes <span class="math inline">\(SS_{\text{res}}\)</span> as small as possible, so allowing an extra coefficient can never make <span class="math inline">\(SS_{\text{res}}\)</span> larger. Since <span class="math inline">\(SS_{\text{tot}}\)</span> is unchanged, <span class="math inline">\(R^{2}\)</span> cannot decrease.</em></p>
<p><strong>(b)</strong> <em>For example: the scatter diagram, to see whether the data actually has the shape of a cubic; or the context, to check whether the predictions of each model are sensible outside the data.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-50-contents" aria-controls="callout-50" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-50" class="callout-50-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <a href="#why-more">Why it works</a> の内容です。要点は「<strong>あとのモデルは、前のモデルを含んでいる</strong>」ことです。</p>
<p><span class="math inline">\(y = ax^{2} + bx + c\)</span> で <span class="math inline">\(a = 0\)</span> とすれば直線になります。ですから、quadratic を当てはめる電卓は、<strong>直線も候補として見たうえで</strong>、いちばん <span class="math inline">\(SS_{\text{res}}\)</span> が小さいものを選んでいます。</p>
<p><span class="math inline">\(SS_{\text{res}}\)</span> が大きくならなければ、<span class="math inline">\(R^{2} = 1 - \dfrac{SS_{\text{res}}}{SS_{\text{tot}}}\)</span> も小さくなりません。<strong>必ず増えるとは限りません</strong>——たとえば点が完全に直線上にあれば、<span class="math inline">\(3\)</span> つとも <span class="math inline">\(R^{2} = 1\)</span> です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Every straight line is a quadratic with <span class="math inline">\(a = 0\)</span>, and every quadratic is a cubic with the <span class="math inline">\(x^{3}\)</span> coefficient zero. The regression chooses the coefficients that make <span class="math inline">\(SS_{\text{res}}\)</span> as small as possible, so allowing one more coefficient can never make <span class="math inline">\(SS_{\text{res}}\)</span> larger. <span class="math inline">\(SS_{\text{tot}}\)</span> is the same for all three, so <span class="math inline">\(R^{2}\)</span> cannot decrease.</em></p>
</div>
<p><strong>(b)</strong> <span class="math inline">\(R^{2}\)</span> の差は <span class="math inline">\(0.968 \to 0.971\)</span> で、<strong>わずか <span class="math inline">\(0.003\)</span></strong> です。係数を <span class="math inline">\(1\)</span> つ増やして、これだけ。</p>
<p><code>one further piece of information</code> なので <span class="math inline">\(1\)</span> つ書けば足ります。散布図でも、文脈でも、外での予測でも構いません（<a href="#choosing">第8節</a>）。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">6</span> <span class="q-en">The number of bacteria <span class="math inline">\(N\)</span> in a culture is recorded every hour for five hours.</span></p>
<div id="tbl-ahl413-ex6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-ex6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;16: Bacteria count
</figcaption>
<div aria-describedby="tbl-ahl413-ex6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(t\)</span> (hours)</th>
<th><span class="math inline">\(0\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
<th><span class="math inline">\(5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(N\)</span></td>
<td><span class="math inline">\(50\)</span></td>
<td><span class="math inline">\(79\)</span></td>
<td><span class="math inline">\(126\)</span></td>
<td><span class="math inline">\(199\)</span></td>
<td><span class="math inline">\(318\)</span></td>
<td><span class="math inline">\(501\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Use technology to find the exponential regression model for <span class="math inline">\(N\)</span> in terms of <span class="math inline">\(t\)</span>, giving the coefficients correct to three significant figures.</span></p>
<p><strong>(b)</strong> <span class="q-en">Write down <span class="math inline">\(R^{2}\)</span>, and interpret it in context.</span></p>
<p><strong>(c)</strong> <span class="q-en">Interpret the value of the base of your model in context.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある培養液の中の細菌の数 <span class="math inline">\(N\)</span> を、<span class="math inline">\(5\)</span> 時間のあいだ <span class="math inline">\(1\)</span> 時間ごとに記録しました。</p>
<p><strong>(a)</strong> 電卓を使って、<span class="math inline">\(N\)</span> を <span class="math inline">\(t\)</span> で表す指数の回帰モデルを求めなさい。係数は有効数字 <span class="math inline">\(3\)</span> 桁で書きなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(R^{2}\)</span> を書き、文脈の中で説明しなさい。</p>
<p><strong>(c)</strong> モデルの底の値を、文脈の中で説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-51-contents" aria-controls="callout-51" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-51" class="callout-51-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
N = 49.9(1.59)^{t}
\]</span></p>
<p><strong>(b)</strong> <em><span class="math inline">\(R^{2} = 1.00\)</span> (to 3 s.f.): the model accounts for almost all of the variability in the number of bacteria.</em></p>
<p><strong>(c)</strong> <em>The base <span class="math inline">\(1.59\)</span> means the number of bacteria is multiplied by about <span class="math inline">\(1.59\)</span> each hour, that is, it increases by about <span class="math inline">\(59\%\)</span> per hour.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-52-contents" aria-controls="callout-52" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-52" class="callout-52-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <code>Exponential Regression</code> を走らせます。<span class="math inline">\(a = 49.9\)</span>、<span class="math inline">\(b = 1.59\)</span> が返ります。</p>
<p><strong>検算。</strong> <span class="math inline">\(t = 0\)</span> のとき <span class="math inline">\(N = 49.9\)</span> で、データの <span class="math inline">\(50\)</span> とほぼ一致します ✓ <strong><span class="math inline">\(a\)</span> は「はじめの数」</strong>です。</p>
<p><strong>(b)</strong> 電卓の <span class="math inline">\(R^{2}\)</span> は <span class="math inline">\(0.99997\)</span> ほどで、有効数字 <span class="math inline">\(3\)</span> 桁だと <span class="math inline">\(1.00\)</span> です。<strong>数のまま書かず、文脈に戻します</strong>（<a href="#r2">第6節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(R^{2} = 1.00\)</span> to three significant figures, so the exponential model accounts for almost all of the variability in the number of bacteria.</em></p>
</div>
<p><span class="math inline">\(1.00\)</span> でも「完全に正しいモデル」という意味ではありません。点が <span class="math inline">\(6\)</span> 個しかないことにも注意してください（<a href="#choosing">第8節</a>）。</p>
<p><strong>(c)</strong> ここが <code>interpret</code> の中身です。底 <span class="math inline">\(1.59\)</span> は「<strong><span class="math inline">\(1\)</span> 時間で <span class="math inline">\(1.59\)</span> 倍</strong>」という意味です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The base is <span class="math inline">\(1.59\)</span>, so the number of bacteria is multiplied by about <span class="math inline">\(1.59\)</span> every hour, an increase of about <span class="math inline">\(59\%\)</span> per hour.</em></p>
</div>
<p><strong>「<span class="math inline">\(1.59\)</span> 倍」と「<span class="math inline">\(59\%\)</span> 増える」は同じこと</strong>です。どちらか一方でも構いませんが、両方書くと確実です（<a href="../../ai-sl/02-functions/sl-2-5.html#growth-decay">SL 2.5</a>）。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">7</span> <span class="q-en">Explain the difference between <span class="math inline">\(SS_{\text{res}}\)</span> and <span class="math inline">\(R^{2}\)</span> as measures of how well a model fits a set of data.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>モデルがデータにどれだけよく当てはまっているかの尺度として、<span class="math inline">\(SS_{\text{res}}\)</span> と <span class="math inline">\(R^{2}\)</span> の違いを説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-53-contents" aria-controls="callout-53" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-53" class="callout-53-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em><span class="math inline">\(SS_{\text{res}}\)</span> is the total of the squared residuals. It depends on the units of <span class="math inline">\(y\)</span> and on how many data points there are, so it can only be used to compare different models fitted to the same data.</em></p>
<p><em><span class="math inline">\(R^{2}\)</span> compares <span class="math inline">\(SS_{\text{res}}\)</span> with the total spread <span class="math inline">\(SS_{\text{tot}}\)</span>, so it is a proportion between <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>. It has no units and can be compared between different sets of data.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-54-contents" aria-controls="callout-54" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-54" class="callout-54-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(2\)</span> つの違いは、<strong>単位があるかどうか</strong>です（<a href="#ssres">第4節</a>、<a href="#r2">第6節</a>）。</p>
<ul>
<li><span class="math inline">\(SS_{\text{res}}\)</span> … <span class="math inline">\(y\)</span> の単位の <span class="math inline">\(2\)</span> 乗。データが増えれば大きくなる</li>
<li><span class="math inline">\(R^{2}\)</span> … 割合。<span class="math inline">\(0\)</span> から <span class="math inline">\(1\)</span> のあいだ</li>
</ul>
<p>ですから、<strong>「<span class="math inline">\(SS_{\text{res}} = 4\)</span> だからよいモデル」とは言えません。</strong> <span class="math inline">\(4\)</span> が大きいのか小さいのかは、<span class="math inline">\(SS_{\text{tot}}\)</span> と比べてはじめて分かります。</p>
<p><code>Explain the difference</code> なので、<strong>両方について書いてください。</strong> 片方だけでは半分です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(SS_{\text{res}}\)</span> is the sum of the squared residuals, so it has the square of the units of <span class="math inline">\(y\)</span> and it grows as more data points are added. It can therefore only be used to compare models fitted to the same data.</em></p>
<p><em><span class="math inline">\(R^{2}\)</span> divides the unexplained spread by the total spread, so it is a proportion with no units, always between <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>. It can be compared across different sets of data.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">8</span> <span class="q-en">A student fits a quadratic model to six data points and obtains <span class="math inline">\(R^{2} = 1\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">State what this tells you about <span class="math inline">\(SS_{\text{res}}\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">The student concludes that the quadratic model must be the correct model for the situation. Comment on this conclusion.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある生徒が <span class="math inline">\(6\)</span> 個のデータの組に二次のモデルを当てはめ、<span class="math inline">\(R^{2} = 1\)</span> を得ました。</p>
<p><strong>(a)</strong> これが <span class="math inline">\(SS_{\text{res}}\)</span> について何を示すかを述べなさい。</p>
<p><strong>(b)</strong> その生徒は、二次のモデルがこの状況の正しいモデルにちがいないと結論しました。この結論について述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-55-contents" aria-controls="callout-55" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-55" class="callout-55-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em><span class="math inline">\(SS_{\text{res}} = 0\)</span>: every data point lies exactly on the curve.</em></p>
<p><strong>(b)</strong> <em>The conclusion is not justified. <span class="math inline">\(R^{2}\)</span> only measures how close the curve is to these six points; it says nothing about whether the model is right for the situation. The model should also be checked against the context, and against data outside the range used to fit it.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-56-contents" aria-controls="callout-56" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-56" class="callout-56-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <a href="#eq-ahl413-r2" class="quarto-xref">式&nbsp;4</a> で <span class="math inline">\(R^{2} = 1\)</span> になるのは <span class="math inline">\(SS_{\text{res}} = 0\)</span> のときだけです。<strong>residual が全部 <span class="math inline">\(0\)</span></strong>、つまり全部の点が曲線の上にあります。</p>
<p><strong>(b)</strong> <code>Comment on</code> なので、<strong>その結論が正しいかどうかと、その理由</strong>を書きます。</p>
<p><span class="math inline">\(R^{2} = 1\)</span> が言っているのは「<strong>この <span class="math inline">\(6\)</span> 点に近い</strong>」ということだけです。点をぴったり通るモデルは、いくらでも作れます（<a href="#why-more">Why it works</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(R^{2} = 1\)</span> only means the curve passes exactly through these six points. It does not show that the model is correct for the situation: the model should also be checked against the context and against data outside the range used to fit it.</em></p>
</div>
<p><strong>「よく当てはまる」と「正しい」は別のことです。</strong> この項目が繰り返し言っているのは、そこです（<a href="#choosing">第8節</a>）。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">9</span> <span class="q-en">A company’s monthly sales <span class="math inline">\(S\)</span>, in thousands, are recorded for eight months. A linear model gives <span class="math inline">\(S = 2.4m + 31\)</span> with <span class="math inline">\(R^{2} = 0.81\)</span>, and a quadratic model gives <span class="math inline">\(R^{2} = 0.94\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write down the value of <span class="math inline">\(r\)</span> for the linear model, given that sales are increasing.</span></p>
<p><strong>(b)</strong> <span class="q-en">The manager wants to predict the sales in month <span class="math inline">\(24\)</span>. Explain why neither model should be trusted for this prediction.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある会社の月間売上 <span class="math inline">\(S\)</span>（千単位）を <span class="math inline">\(8\)</span> か月間記録しました。線形モデルは <span class="math inline">\(S = 2.4m + 31\)</span>、<span class="math inline">\(R^{2} = 0.81\)</span> となり、二次モデルは <span class="math inline">\(R^{2} = 0.94\)</span> となりました。</p>
<p><strong>(a)</strong> 売上が増えていることを使って、線形モデルの <span class="math inline">\(r\)</span> の値を書きなさい。</p>
<p><strong>(b)</strong> 経営者は <span class="math inline">\(24\)</span> か月目の売上を予測したいと考えています。どちらのモデルもこの予測には信頼できない理由を説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-57-contents" aria-controls="callout-57" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-57" class="callout-57-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
r = \sqrt{0.81} = 0.9
\]</span></p>
<p><em>The gradient is positive, so <span class="math inline">\(r = 0.9\)</span> and not <span class="math inline">\(-0.9\)</span>.</em></p>
<p><strong>(b)</strong> <em>Month <span class="math inline">\(24\)</span> is far outside the eight months of data, so both models would be extrapolating well beyond the range in which they were fitted. There is no evidence that the pattern continues, and the quadratic model in particular may turn and give values that make no sense.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-58-contents" aria-controls="callout-58" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-58" class="callout-58-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(R^{2} = 0.81\)</span> から <span class="math inline">\(r = \pm 0.9\)</span>。向きは、<strong>傾き <span class="math inline">\(2.4\)</span> が正</strong>であることから決まります（<a href="#r2-r">第7節</a>）。</p>
<p>問題文の <code>given that sales are increasing</code> が、そのためのヒントです。</p>
<p><strong>(b)</strong> <code>Explain why</code> です。データは <span class="math inline">\(8\)</span> か月ぶんしかなく、<span class="math inline">\(24\)</span> か月目は<strong>その <span class="math inline">\(3\)</span> 倍</strong>先です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Month <span class="math inline">\(24\)</span> is far outside the range of the data, which covers only eight months. Both models would be extrapolating, and there is no evidence that the pattern continues. The quadratic model may also turn downwards and give a negative value.</em></p>
</div>
<p><strong><span class="math inline">\(R^{2}\)</span> が高いことは、外挿の根拠になりません</strong>（<a href="#nonsense">第8節</a>）。ここでも <span class="math inline">\(0.94\)</span> は高い値ですが、<span class="math inline">\(24\)</span> か月目とは関係がありません。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">10</span> <span class="q-en">The table shows the temperature <span class="math inline">\(\theta\)</span>, in degrees Celsius, of a cup of coffee <span class="math inline">\(t\)</span> minutes after it is poured. The room temperature is <span class="math inline">\(20^\circ\)</span>C.</span></p>
<div id="tbl-ahl413-ex10" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl413-ex10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;17: Cooling coffee
</figcaption>
<div aria-describedby="tbl-ahl413-ex10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(t\)</span></th>
<th><span class="math inline">\(0\)</span></th>
<th><span class="math inline">\(5\)</span></th>
<th><span class="math inline">\(10\)</span></th>
<th><span class="math inline">\(15\)</span></th>
<th><span class="math inline">\(20\)</span></th>
<th><span class="math inline">\(25\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\theta\)</span></td>
<td><span class="math inline">\(85\)</span></td>
<td><span class="math inline">\(67\)</span></td>
<td><span class="math inline">\(54\)</span></td>
<td><span class="math inline">\(45\)</span></td>
<td><span class="math inline">\(38\)</span></td>
<td><span class="math inline">\(33\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Use technology to find the exponential regression model for <span class="math inline">\(\theta\)</span> in terms of <span class="math inline">\(t\)</span>, giving the coefficients correct to three significant figures, and write down <span class="math inline">\(R^{2}\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Use your model to predict the temperature after <span class="math inline">\(60\)</span> minutes.</span></p>
<p><strong>(c)</strong> <span class="q-en">Comment on the answer to part (b).</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>表は、コーヒーを注いでから <span class="math inline">\(t\)</span> 分後の温度 <span class="math inline">\(\theta\)</span>（摂氏）を示しています。室温は <span class="math inline">\(20^\circ\)</span>C です。</p>
<p><strong>(a)</strong> 電卓を使って、<span class="math inline">\(\theta\)</span> を <span class="math inline">\(t\)</span> で表す指数の回帰モデルを求めなさい。係数は有効数字 <span class="math inline">\(3\)</span> 桁で書き、<span class="math inline">\(R^{2}\)</span> も書きなさい。</p>
<p><strong>(b)</strong> このモデルを使って、<span class="math inline">\(60\)</span> 分後の温度を予測しなさい。</p>
<p><strong>(c)</strong> (b) の答えについて述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-59-contents" aria-controls="callout-59" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-59" class="callout-59-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\theta = 81.6(0.963)^{t}, \qquad R^{2} = 0.990
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
\theta(60) = 8.45 \ ^\circ\text{C}
\]</span></p>
<p><strong>(c)</strong> <em>This is below the room temperature of <span class="math inline">\(20^\circ\)</span>C, which is impossible: the coffee cannot cool below the temperature of the room. The model fits the data well over the first <span class="math inline">\(25\)</span> minutes but is not valid for <span class="math inline">\(t = 60\)</span>.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-60-contents" aria-controls="callout-60" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-60" class="callout-60-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <code>Exponential Regression</code> を走らせます。<span class="math inline">\(R^{2} = 0.990\)</span> で、<strong>当てはまりはよい</strong>です（電卓の表示は <span class="math inline">\(0.991\)</span> など、少し違うことがあります——<a href="#exm-ahl413-compare">例題3</a>の注意）。</p>
<p><strong>(b)</strong> そのまま代入します。<span class="math inline">\(8.45\ ^\circ\)</span>C。電卓に入っている丸める前の係数を使ってください。</p>
<p><strong>(c)</strong> ここがこの問題の中心です。<strong>室温が <span class="math inline">\(20^\circ\)</span>C</strong> と問題文に書かれています。コーヒーが室温より冷たくなることはありません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The predicted temperature of <span class="math inline">\(8.45^\circ\)</span>C is below the room temperature of <span class="math inline">\(20^\circ\)</span>C, which is impossible. The model fits the data well for the first <span class="math inline">\(25\)</span> minutes, but it is not valid this far outside that range.</em></p>
</div>
<p><strong><span class="math inline">\(R^{2} = 0.990\)</span> でも、こうなります。</strong> モデルが <span class="math inline">\(\theta = ka^{t}\)</span> の形だと、<span class="math inline">\(t\)</span> を大きくすると <span class="math inline">\(0\)</span> に近づいてしまうからです。現実には <span class="math inline">\(20\)</span> に近づきます。</p>
<p><strong>「<span class="math inline">\(R^{2}\)</span> が高い」と「予測に使える」は別のこと</strong>——<a href="#choosing">第8節</a>の <span class="math inline">\(2\)</span> つ目と <span class="math inline">\(3\)</span> つ目が、そのまま出ている問題です。</p>
<p>（<span class="math inline">\(\theta = ka^{t} + 20\)</span> の形なら、この問題も表せます。SL 2.5 の <span class="math inline">\(f(x) = ka^{x} + c\)</span> がその形です。ただし、電卓の <code>Exponential Regression</code> は <span class="math inline">\(c\)</span> を入れられません。）</p>
</div>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "コピーしました");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "コピーしました");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/edusalonself\.github\.io\/ib-math-ai-sl-jp\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html" class="pagination-link" aria-label="AHL 4.12 — Data collection and χ² categorisation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">AHL 4.12 — Data collection and χ² categorisation</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" class="pagination-link" aria-label="AHL 4.14 — Linear transformation of a single random variable">
        <span class="nav-page-text">AHL 4.14 — Linear transformation of a single random variable</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 学習サロン SELF</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/">
<p>学習サロン SELF</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
<p>IB（国際バカロレア機構）とは関係のない独立した教材です</p>
</div>
  </div>
</footer>




</body></html>