<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ahl-4-15 – 日本語で読む IB数学</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html" rel="next">
<link href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3d27ed94b0b15b9bda3c32201c09d63a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "一致なし",
    "search-matching-documents-text": "一致した文書",
    "search-copy-link-title": "検索へのリンクをコピー",
    "search-hide-matches-text": "追加の検索結果を非表示",
    "search-more-match-text": "追加の検索結果",
    "search-more-matches-text": "追加の検索結果",
    "search-clear-button-title": "消去",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "検索",
    "search-label": "サーチ"
  }
}</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"ja"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">日本語で読む IB数学</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="サーチ"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="ナビゲーションを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../ai-sl/index.html"> 
<span class="menu-text">AI SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../glossary-ai.html"> 
<span class="menu-text">英日対訳表（AI）</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../ai-hl/index.html" aria-current="page"> 
<span class="menu-text">AI HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-sl/index.html"> 
<span class="menu-text">AA SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-hl/index.html"> 
<span class="menu-text">AA HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../which-course.html"> 
<span class="menu-text">AI と AA、どちらを取るか</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/"> 
<span class="menu-text">学習サロン SELF</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html">AHL 4.15 — Linear combinations of normal variables</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IB数学 AI HL</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 1 — Number and algebra</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.9 — Laws of logarithms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.14 — Matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.15 — Eigenvalues and eigenvectors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 3 — Geometry and trigonometry</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.9 — Geometric transformations in two dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.14 — Graph theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.15 — Adjacency matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.16 — Tree and cycle algorithms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Topic 4 — Statistics and probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.12 — Data collection and χ² categorisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.13 — Non-linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.14 — Linear transformation of a single random variable</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">AHL 4.15 — Linear combinations of normal variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.16 — Confidence intervals for the mean of a normal population</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.17 — The Poisson distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18a — Critical values and critical regions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18b — Tests for a mean, a proportion and ρ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18c — Type I and Type II errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.19 — Transition matrices</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 5 — Calculus</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.14 — Setting up a differential equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.15 — Slope fields</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16a — Euler’s method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16b — Euler’s method for coupled systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17a — Phase portraits: real eigenvalues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17b — Phase portraits: complex eigenvalues</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">このページの内容</h2>
   
  <ul>
  <li><a href="#sec-ahl-4-15" id="toc-sec-ahl-4-15" class="nav-link active" data-scroll-target="#sec-ahl-4-15">AHL 4.15 — Linear combinations of normal variables（正規分布にしたがう確率変数の一次結合）</a>
  <ul class="collapse">
  <li><a href="#the-idea" id="toc-the-idea" class="nav-link" data-scroll-target="#the-idea">The idea</a>
  <ul class="collapse">
  <li><a href="#idea" id="toc-idea" class="nav-link" data-scroll-target="#idea">1. 平均と分散だけでは、確率は決まりません</a></li>
  <li><a href="#sum" id="toc-sum" class="nav-link" data-scroll-target="#sum">2. 分散を足して、最後に平方根をとります</a></li>
  <li><a href="#steps" id="toc-steps" class="nav-link" data-scroll-target="#steps">3. <span class="math inline">\(3\)</span> ステップの型</a></li>
  <li><a href="#diff" id="toc-diff" class="nav-link" data-scroll-target="#diff">4. 差のときは、平均は引いて、分散は足します</a></li>
  <li><a href="#xbar" id="toc-xbar" class="nav-link" data-scroll-target="#xbar">5. sample mean（標本平均）<span class="math inline">\(\bar{X}\)</span> の分布</a></li>
  <li><a href="#clt" id="toc-clt" class="nav-link" data-scroll-target="#clt">6. Central limit theorem（中心極限定理）</a></li>
  <li><a href="#total" id="toc-total" class="nav-link" data-scroll-target="#total">7. 平均で解いても、合計で解いても同じです</a></li>
  <li><a href="#when" id="toc-when" class="nav-link" data-scroll-target="#when">8. exactly normal と approximately normal</a></li>
  </ul></li>
  <li><a href="#why-it-works" id="toc-why-it-works" class="nav-link" data-scroll-target="#why-it-works">Why it works</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples">Worked examples</a></li>
  <li><a href="#common-errors" id="toc-common-errors" class="nav-link" data-scroll-target="#common-errors">Common errors</a></li>
  <li><a href="#using-your-gdc-ti-nspire-cx-ii" id="toc-using-your-gdc-ti-nspire-cx-ii" class="nav-link" data-scroll-target="#using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</a>
  <ul class="collapse">
  <li><a href="#gdc-normcdf" id="toc-gdc-normcdf" class="nav-link" data-scroll-target="#gdc-normcdf">1. Normal Cdf に入れるのは <span class="math inline">\(\sigma\)</span> です</a></li>
  <li><a href="#gdc-unrounded" id="toc-gdc-unrounded" class="nav-link" data-scroll-target="#gdc-unrounded">2. <span class="math inline">\(\sigma\)</span> は、丸める前の値を使う</a></li>
  <li><a href="#gdc-diff" id="toc-gdc-diff" class="nav-link" data-scroll-target="#gdc-diff">3. 「<span class="math inline">\(A\)</span> が <span class="math inline">\(B\)</span> より大きい」は <span class="math inline">\(1\)</span> 回で済ませる</a></li>
  <li><a href="#gdc-invnorm" id="toc-gdc-invnorm" class="nav-link" data-scroll-target="#gdc-invnorm">4. 逆向きに使うときは Inverse Normal</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html">AHL 4.15 — Linear combinations of normal variables</a></li></ol></nav></header>




<section id="sec-ahl-4-15" class="level1">
<h1>AHL 4.15 — Linear combinations of normal variables（正規分布にしたがう確率変数の一次結合）</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>What you should be able to do
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>独立な normal の和や差が、<strong>やはり normal になる</strong>と言える。</li>
<li>その平均と分散を出して、<span class="math inline">\(N(\mu,\ \sigma^{2})\)</span> の形に書ける。</li>
<li>そこから <strong>normCdf で確率を求められる</strong>。</li>
<li><strong><span class="math inline">\(\bar{X} \sim N\!\left(\mu,\ \dfrac{\sigma^{2}}{n}\right)\)</span></strong> を使い、標本平均の確率を求められる。</li>
<li><strong>central limit theorem</strong>（中心極限定理）が何を言っているかを説明できる。</li>
<li>もとの分布が normal と分からないとき、標本数が十分に大きければ <strong><span class="math inline">\(\bar{X}\)</span> を近似的に normal として扱える</strong>と分かる。</li>
</ul>
</div>
</div>
<p><a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html">AHL 4.14</a> では、独立な確率変数の和について、平均と分散を求めました。しかし、平均と分散だけでは、その確率変数がどのような分布にしたがうかまでは分かりません。</p>
<p>このページでは、もとの確率変数が <strong>normal distribution</strong>（正規分布）にしたがうとき、和・差・標本平均の分布まで求められることを学びます。</p>
<section id="the-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-idea">The idea</h2>
<section id="idea" class="level3">
<h3 class="anchored" data-anchor-id="idea">1. 平均と分散だけでは、確率は決まりません</h3>
<p><a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#combinations">AHL 4.14</a> で、独立な確率変数の和について</p>
<p><span class="math display">\[
E(X_1 + X_2) = E(X_1) + E(X_2), \qquad \text{Var}(X_1 + X_2) = \text{Var}(X_1) + \text{Var}(X_2)
\]</span></p>
<p>を学びました。この <span class="math inline">\(2\)</span> つは、<strong>どんな分布でも</strong>成り立ちます。</p>
<p>ただし、<strong>平均と分散だけでは、確率は一意に決まりません。</strong> 同じ平均・同じ分散をもつ分布は、いくらでもあるからです。確率を計算するには、normal など、<strong>分布の種類も分かっている</strong>必要があります。</p>
<p>たとえば <span class="math inline">\(X \sim N(250,\ 8^{2})\)</span> を <span class="math inline">\(2\)</span> つ足すと、<span class="math inline">\(X_1 + X_2\)</span> の平均は <span class="math inline">\(500\)</span>、分散は <span class="math inline">\(128\)</span> です。この <span class="math inline">\(2\)</span> つの数だけでは、<span class="math inline">\(P(X_1 + X_2 &gt; 510)\)</span> は決まりません。このページが足すのは、その<strong>分布の種類</strong>です。</p>
<section id="lincomb" class="level4">
<h4 class="anchored" data-anchor-id="lincomb">linear combination（一次結合）とは</h4>
<p><span class="math inline">\(X + Y\)</span>、<span class="math inline">\(2X - Y\)</span>、<span class="math inline">\(\dfrac{X_1 + \cdots + X_n}{n}\)</span> のように、確率変数に定数をかけて足し合わせたものを <strong>linear combination</strong>（一次結合）といいます。</p>
<p><strong>「和」「差」「標本平均」は、すべて一次結合の例です。</strong> ですからこのページの <span class="math inline">\(3\)</span> つの話題は、どれも <span class="math inline">\(1\)</span> つの考え方で扱えます。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>独立な normal random variables の linear combination も normal distribution にしたがう
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(X_1,\ \ldots,\ X_n\)</span> が互いに<strong>独立</strong>で、</p>
<p><span class="math display">\[
X_i \sim N(\mu_i,\ \sigma_i^{2})
\]</span></p>
<p>にしたがうとします。このとき</p>
<p><span id="eq-ahl415-main"><span class="math display">\[
Y = a_1X_1 + \cdots + a_nX_n
\tag{1}\]</span></span></p>
<p>とおきます。ここで <span class="math inline">\(Y\)</span> は、<span class="math inline">\(X_1,\ \ldots,\ X_n\)</span> にそれぞれ定数 <span class="math inline">\(a_1,\ \ldots,\ a_n\)</span> をかけて足し合わせて作った、<strong>新しい確率変数</strong>です。</p>
<p>この <span class="math inline">\(Y\)</span> も normal distribution にしたがい、</p>
<p><span id="eq-ahl415-mean"><span class="math display">\[
E(Y) = a_1\mu_1 + \cdots + a_n\mu_n
\tag{2}\]</span></span></p>
<p><span id="eq-ahl415-var"><span class="math display">\[
\text{Var}(Y) = a_1^{2}\sigma_1^{2} + \cdots + a_n^{2}\sigma_n^{2}
\tag{3}\]</span></span></p>
<p>となります。</p>
</div>
</div>
<p><strong>平均では係数をそのまま使いますが、分散では係数を <span class="math inline">\(2\)</span> 乗します。</strong> 引き算でも分散が足し算になるのは、この <span class="math inline">\(2\)</span> 乗によって負の符号が消えるためです。</p>
<p>シラバスの書き方は、こうです。</p>
<blockquote class="blockquote">
<p>A <strong>linear combination of <span class="math inline">\(n\)</span> independent normal random variables is normally distributed.</strong> In particular, <span class="math inline">\(X \sim N(\mu,\ \sigma^{2}) \Rightarrow \bar{X} \sim N\!\left(\mu,\ \frac{\sigma^{2}}{n}\right)\)</span>.</p>
</blockquote>
<p><strong>「normal を入れれば、normal が出てくる」</strong>——これだけです。どんな分布でもこうなるわけではありません（独立な <span class="math inline">\(2\)</span> つの Poisson の和が Poisson になるのは、<a href="../../ai-hl/04-statistics-and-probability/ahl-4-17.html#sum">AHL 4.17</a> の別の規則です）。</p>
</section>
</section>
<section id="sum" class="level3">
<h3 class="anchored" data-anchor-id="sum">2. 分散を足して、最後に平方根をとります</h3>
<p>独立な確率変数を足すときは、<strong>standard deviation（標準偏差）を直接足すのではなく、まず variance（分散）を足します。</strong> 最後に平方根を取って標準偏差へ戻します。</p>
<p><span class="math inline">\(M \sim N(250,\ 8^{2})\)</span> と <span class="math inline">\(S \sim N(180,\ 6^{2})\)</span> が独立なとき、<span class="math inline">\(2\)</span> つの値の合計を表す<strong>新しい確率変数</strong> <span class="math inline">\(M + S\)</span> を考えます。</p>
<div id="fig-ahl415-sum" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl415-sum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-15-sum.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl415-sum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;1: Adding two independent normals gives another normal
</figcaption>
</figure>
</div>
<p><strong>平均（expected value）</strong>は、係数がどちらも <span class="math inline">\(1\)</span> なので足すだけです。</p>
<p><span class="math display">\[
E(M + S) = 250 + 180 = 430
\]</span></p>
<p>次に、<strong>分散（variance）</strong>を求めます。<span class="math inline">\(M\)</span> と <span class="math inline">\(S\)</span> は独立なので、それぞれの分散を足します。</p>
<p><span class="math display">\[
\text{Var}(M + S) = 8^{2} + 6^{2} = 100
\]</span></p>
<p><strong>標準偏差（standard deviation）</strong>は、分散の正の平方根です。</p>
<p><span class="math display">\[
\sigma_{M+S} = \sqrt{100} = 10
\]</span></p>
<p>したがって、<span class="math inline">\(M + S\)</span> がしたがう<strong>分布（distribution）</strong>は</p>
<p><span class="math display">\[
M + S \sim N(430,\ 10^{2})
\]</span></p>
<p>です。ここで、<span class="math inline">\(E\)</span> は平均、<span class="math inline">\(\text{Var}\)</span> は分散、<span class="math inline">\(\sigma\)</span> は標準偏差を表します。</p>
<p><strong><span class="math inline">\(N(\mu,\ \sigma^{2})\)</span> のカッコの <span class="math inline">\(2\)</span> 番目は、分散です。</strong> <span class="math inline">\(10^{2} = 100\)</span> なので <span class="math inline">\(N(430,\ 100)\)</span> と書いても同じ分布ですが、標準偏差の <span class="math inline">\(10\)</span> をそのまま書くのではありません。</p>
<p><a href="#fig-ahl415-sum" class="quarto-xref">図&nbsp;1</a> のとおり、<span class="math inline">\(M\)</span> と <span class="math inline">\(S\)</span> を足して出てくるのも normal distribution です。</p>
<p>平均と分散の求め方は、すでに学習した <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#combinations">AHL 4.14</a> の内容です。また、normal distribution を使った確率の計算は、<a href="../../ai-sl/04-statistics-and-probability/sl-4-9.html">SL 4.9</a> で学習した内容です。<strong>このページで新しく学ぶのは、それらをつなぐ部分</strong>、つまり「独立な normal random variables の linear combination も normal distribution にしたがう」という性質です。</p>
</section>
<section id="steps" class="level3">
<h3 class="anchored" data-anchor-id="steps">3. <span class="math inline">\(3\)</span> ステップの型</h3>
<p>この項目の問題は、ほとんど同じ形をしています。</p>
<div id="tbl-ahl415-steps" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl415-steps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;1: <span class="math inline">\(3\)</span> ステップ
</figcaption>
<div aria-describedby="tbl-ahl415-steps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>手順</th>
<th>やること</th>
<th>使うもの</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td><span class="math inline">\(E(Y)\)</span> を求める（係数はそのまま使う）</td>
<td><a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#combinations">AHL 4.14</a></td>
</tr>
<tr class="even">
<td><strong>2</strong></td>
<td><span class="math inline">\(\text{Var}(Y)\)</span> を求める（係数は <span class="math inline">\(2\)</span> 乗する）</td>
<td><a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#varcomb">AHL 4.14</a></td>
</tr>
<tr class="odd">
<td><strong>3</strong></td>
<td><span class="math inline">\(X_i\)</span> が独立な normal であることを確かめて <span class="math inline">\(Y \sim N(\mu,\ \sigma^{2})\)</span> と書き、<span class="math inline">\(\sigma\)</span> を GDC に入れる（もとが normal でない場合は<a href="#when">第8節</a>）</td>
<td><a href="../../ai-sl/04-statistics-and-probability/sl-4-9.html#normcdf">SL 4.9</a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><code>normCdf</code> に入れるのは、標準偏差です
</div>
</div>
<div class="callout-body-container callout-body">
<p>GDC の <code>normCdf</code> に入力するのは mean（平均）と standard deviation（標準偏差）です。<strong>分散を求めた後、平方根を取るのを忘れないでください。</strong></p>
</div>
</div>
<p><span class="math inline">\(M + S\)</span> の例なら、<span class="math inline">\(E = 430\)</span> → <span class="math inline">\(\text{Var} = 100\)</span> → <span class="math inline">\(M + S \sim N(430,\ 100)\)</span> と書いて、<span class="math inline">\(\sigma = 10\)</span> を <code>normCdf</code> へ、という流れです。</p>
<p><strong><span class="math inline">\(1\)</span> と <span class="math inline">\(2\)</span> は AHL 4.14、<span class="math inline">\(3\)</span> の後半は SL 4.9 です。</strong> このページが新しく足しているのは、手順 <span class="math inline">\(3\)</span> の前半、「normal だと言ってよい」という一歩だけです。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>答案には、<span class="math inline">\(N(\mu,\ \sigma^{2})\)</span> の行を必ず書いてください
</div>
</div>
<div class="callout-body-container callout-body">
<p>電卓に入れる前に、<strong>求めた分布を <span class="math inline">\(1\)</span> 行書く</strong>習慣をつけてください。</p>
<p><em><span class="math inline">\(M + S \sim N(430,\ 100)\)</span></em></p>
<p>ここに点が付きます。そして、<strong>書いておくと <span class="math inline">\(\sigma\)</span> と <span class="math inline">\(\sigma^{2}\)</span> を取りちがえません。</strong> <span class="math inline">\(N\)</span> のカッコの <span class="math inline">\(2\)</span> 番目は<strong>分散</strong>、<code>normCdf</code> に入れるのは<strong>標準偏差</strong>です。</p>
</div>
</div>
</section>
<section id="diff" class="level3">
<h3 class="anchored" data-anchor-id="diff">4. 差のときは、平均は引いて、分散は足します</h3>
<p><span class="math inline">\(X\)</span> と <span class="math inline">\(Y\)</span> が<strong>独立</strong>であるとします。ここで</p>
<p><span class="math display">\[
D = X - Y
\]</span></p>
<p>とおきます。<span class="math inline">\(D\)</span> は、<span class="math inline">\(X\)</span> の値から <span class="math inline">\(Y\)</span> の値を引いて作る、<strong>差を表す新しい確率変数</strong>です。たとえば <span class="math inline">\(X\)</span> が <span class="math inline">\(1\)</span> 回目の測定値、<span class="math inline">\(Y\)</span> が <span class="math inline">\(2\)</span> 回目の測定値なら、<span class="math inline">\(D\)</span> は「<span class="math inline">\(1\)</span> 回目の測定値と <span class="math inline">\(2\)</span> 回目の測定値の差」を表します。</p>
<p><span class="math inline">\(D = X - Y\)</span> は、<span class="math inline">\(Y\)</span> の係数を <span class="math inline">\(-1\)</span> とする linear combination（一次結合）として</p>
<p><span class="math display">\[
D = X + (-1)Y
\]</span></p>
<p>と書けます。</p>
<p>平均（expected value）は、係数をそのまま使うので</p>
<p><span class="math display">\[
E(D) = E(X) - E(Y)
\]</span></p>
<p>となります。一方、分散（variance）は係数を <span class="math inline">\(2\)</span> 乗して使います。<span class="math inline">\(X\)</span> と <span class="math inline">\(Y\)</span> は独立なので</p>
<p><span id="eq-ahl415-diff"><span class="math display">\[
\text{Var}(D) = \text{Var}(X) + (-1)^{2}\text{Var}(Y) = \text{Var}(X) + \text{Var}(Y)
\tag{4}\]</span></span></p>
<p>となります。</p>
<p><strong>したがって、差の平均は引き算ですが、差の分散は足し算です。</strong> 分散が足し算になるのは、係数 <span class="math inline">\(-1\)</span> が <span class="math inline">\(2\)</span> 乗されて <span class="math inline">\((-1)^{2} = 1\)</span> となり、負の符号が消えるためです。この式は、<strong><span class="math inline">\(X\)</span> と <span class="math inline">\(Y\)</span> が独立である場合</strong>に使えます（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#minus">AHL 4.14</a>）。</p>
<section id="which-bigger" class="level4">
<h4 class="anchored" data-anchor-id="which-bigger">「<span class="math inline">\(A\)</span> のほうが大きい確率」は、差で考えます</h4>
<p>「<span class="math inline">\(A\)</span> が <span class="math inline">\(B\)</span> より大きい確率を求めなさい」（<code>Find the probability that A is greater than B</code>）と聞かれたときは、<span class="math inline">\(A\)</span> と <span class="math inline">\(B\)</span> の差を表す<strong>新しい確率変数</strong></p>
<p><span class="math display">\[
D = A - B
\]</span></p>
<p>を考えます。なぜ差を考えるのかというと、次の言いかえができるからです。</p>
<p><span class="math display">\[
A &gt; B \iff A - B &gt; 0 \iff D &gt; 0
\]</span></p>
<p><strong><span class="math inline">\(A\)</span> のほうが大きい</strong>という出来事と、<strong><span class="math inline">\(D\)</span> が正である</strong>という出来事は、まったく同じものです。ですから、確率も</p>
<p><span id="eq-ahl415-dgt0"><span class="math display">\[
P(A &gt; B) = P(A - B &gt; 0) = P(D &gt; 0)
\tag{5}\]</span></span></p>
<p>と書きかえられます。</p>
<p><span class="math inline">\(A\)</span> と <span class="math inline">\(B\)</span> が独立な normal random variables なら、<a href="#lincomb">第1節</a>より <span class="math inline">\(D = A - B\)</span> も normal distribution にしたがいます。ですから、あとは <span class="math inline">\(1\)</span> つの normal distribution の問題です。</p>
<ol type="1">
<li><span class="math inline">\(D\)</span> の平均を求める … <span class="math inline">\(E(D) = E(A) - E(B)\)</span></li>
<li><span class="math inline">\(D\)</span> の分散と標準偏差を求める … <span class="math inline">\(\text{Var}(D) = \text{Var}(A) + \text{Var}(B)\)</span>、<span class="math inline">\(\sigma_D = \sqrt{\text{Var}(D)}\)</span></li>
<li><code>normCdf</code> で <span class="math inline">\(P(D &gt; 0)\)</span> を求める</li>
</ol>
<p><strong><span class="math inline">\(A\)</span> と <span class="math inline">\(B\)</span> の <span class="math inline">\(2\)</span> つの分布を直接見くらべるのではなく、「<span class="math inline">\(A - B\)</span> は <span class="math inline">\(0\)</span> より大きいか」という <span class="math inline">\(1\)</span> つの normal distribution の問題に変える</strong>——これがこの型の考え方です。</p>
</section>
</section>
<section id="xbar" class="level3">
<h3 class="anchored" data-anchor-id="xbar">5. sample mean（標本平均）<span class="math inline">\(\bar{X}\)</span> の分布</h3>
<p>シラバスが <code>In particular</code> と名指ししている、この項目のもう <span class="math inline">\(1\)</span> つの中心です。</p>
<p><strong>sample mean</strong>（標本平均）を <span class="math inline">\(\bar{X}\)</span> と表します。<span class="math inline">\(\bar{X}\)</span> は「エックス・バー」と読みます。</p>
<p><strong>population</strong>（母集団）から、同じ条件で独立に <span class="math inline">\(n\)</span> 個の値を取り出すとします。</p>
<p><span class="math display">\[
X_1,\ X_2,\ \ldots,\ X_n
\]</span></p>
<p>は、<span class="math inline">\(1\)</span> 回目、<span class="math inline">\(2\)</span> 回目、……、<span class="math inline">\(n\)</span> 回目の抽出で得られる値を表す <strong>random variables</strong>（確率変数）です。</p>
<p>たとえば身長を調べる場合、<span class="math inline">\(X_1\)</span> は「<span class="math inline">\(1\)</span> 人目としてランダムに選ばれる人の身長」です。選ぶ前は値が決まっていないので、<span class="math inline">\(X_1\)</span> は <span class="math inline">\(1\)</span> つの数値ではなく random variable であり、実際に測って得られた <span class="math inline">\(168\)</span> cm などの値は <span class="math inline">\(X_1\)</span> の <strong>observed value</strong>（観測値）です。</p>
<p>population が normal distribution <span class="math inline">\(N(\mu,\ \sigma^{2})\)</span> にしたがうなら、各 <span class="math inline">\(X_i\)</span> も同じ分布にしたがいます。</p>
<p><span class="math display">\[
X_i \sim N(\mu,\ \sigma^{2})
\]</span></p>
<p>この <span class="math inline">\(n\)</span> 個の値の平均を表す新しい確率変数が、sample mean <span class="math inline">\(\bar{X}\)</span> です。</p>
<p><span class="math display">\[
\bar{X} = \frac{X_1 + \cdots + X_n}{n} = \frac{1}{n}X_1 + \cdots + \frac{1}{n}X_n
\]</span></p>
<p>したがって、<span class="math inline">\(\bar{X}\)</span> は<strong>各 <span class="math inline">\(X_i\)</span> の係数が <span class="math inline">\(\dfrac{1}{n}\)</span> である linear combination</strong>（一次結合）です。</p>
<p><span class="math inline">\(\bar{X}\)</span> の平均（mean）は</p>
<p><span class="math display">\[
\begin{aligned}
E(\bar{X}) &amp;= \frac{1}{n}\mu + \cdots + \frac{1}{n}\mu \\
&amp;= n\left(\frac{1}{n}\right)\mu \\
&amp;= \mu
\end{aligned}
\]</span></p>
<p>となります。つまり、sample mean <span class="math inline">\(\bar{X}\)</span> の平均は、<strong>population mean</strong>（母平均）<span class="math inline">\(\mu\)</span> と同じです。</p>
<p>次に、分散（variance）では係数を <span class="math inline">\(2\)</span> 乗します。各 <span class="math inline">\(X_i\)</span> は独立で、分散はすべて <span class="math inline">\(\sigma^{2}\)</span> なので</p>
<p><span class="math display">\[
\begin{aligned}
\text{Var}(\bar{X}) &amp;= \left(\frac{1}{n}\right)^{2}\text{Var}(X_1) + \cdots + \left(\frac{1}{n}\right)^{2}\text{Var}(X_n) \\
&amp;= \left(\frac{1}{n}\right)^{2}\sigma^{2} + \cdots + \left(\frac{1}{n}\right)^{2}\sigma^{2} \\
&amp;= n\left(\frac{1}{n}\right)^{2}\sigma^{2} \\
&amp;= n \cdot \frac{1}{n^{2}}\sigma^{2} \\
&amp;= \frac{\sigma^{2}}{n}
\end{aligned}
\]</span></p>
<p>となります。<strong>ここで大事なのは、分散では係数 <span class="math inline">\(\dfrac{1}{n}\)</span> を <span class="math inline">\(2\)</span> 乗することです。</strong> ですから分散は <span class="math inline">\(\dfrac{1}{n}\)</span> 倍ではなく</p>
<p><span class="math display">\[
\boxed{\ \text{Var}(\bar{X}) = \frac{\sigma^{2}}{n}\ }
\]</span></p>
<p>です。したがって、<span class="math inline">\(\bar{X}\)</span> の標準偏差（standard deviation）は</p>
<p><span id="eq-ahl415-sdxbar"><span class="math display">\[
\sigma_{\bar{X}} = \sqrt{\frac{\sigma^{2}}{n}} = \frac{\sigma}{\sqrt{n}}
\tag{6}\]</span></span></p>
<p>となります。</p>
<p>また、独立な normal random variables の linear combination も normal distribution にしたがうため</p>
<p><span id="eq-ahl415-xbar"><span class="math display">\[
\boxed{\ \bar{X} \sim N\!\left(\mu,\ \frac{\sigma^{2}}{n}\right)\ }
\tag{7}\]</span></span></p>
<p>となります。</p>
<p><span class="math inline">\(\bar{X}\)</span> の標準偏差 <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span> を <strong>standard error</strong>（標準誤差）といいます。<span class="math inline">\(n\)</span> が大きいほど standard error は小さくなり、<span class="math inline">\(\bar{X}\)</span> は population mean <span class="math inline">\(\mu\)</span> の近くに集まりやすくなります。<strong>これは、<span class="math inline">\(\bar{X}\)</span> の分布の「広がり」についての性質です。</strong></p>
<p>一方、次に学ぶ <strong>central limit theorem</strong>（中心極限定理）は、<span class="math inline">\(n\)</span> が大きくなると <span class="math inline">\(\bar{X}\)</span> の分布の「<strong>形</strong>」が normal distribution に近づくことを説明します。</p>
<div id="fig-ahl415-xbar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl415-xbar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-15-xbar.svg" class="img-fluid figure-img" style="width:92.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl415-xbar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;2: The distribution of the sample mean for different <span class="math inline">\(n\)</span>
</figcaption>
</figure>
</div>
<section id="narrower" class="level4">
<h4 class="anchored" data-anchor-id="narrower">中心は動かず、幅だけが狭くなります</h4>
<p><a href="#fig-ahl415-xbar" class="quarto-xref">図&nbsp;2</a> を見てください。<span class="math inline">\(4\)</span> つの曲線は、<strong>すべて <span class="math inline">\(\mu = 1000\)</span> を中心</strong>にしています。違うのは幅だけです。</p>
<p>標本の数が増えると、偶然によるばらつきが平均の中で打ち消し合うため、<span class="math inline">\(\bar{X}\)</span> は母平均 <span class="math inline">\(\mu\)</span> の近くに集まりやすくなります（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#cancel">AHL 4.14</a>）。</p>
<p><strong><span class="math inline">\(\sigma / n\)</span> ではありません。</strong> 分散が <span class="math inline">\(\sigma^{2}/n\)</span> なので、平方根をとると分母は <span class="math inline">\(\sqrt{n}\)</span> になります。</p>
<p><span class="math inline">\(\sigma = 12\)</span>、<span class="math inline">\(n = 9\)</span> なら <span class="math inline">\(\sigma_{\bar{X}} = \dfrac{12}{3} = 4\)</span> です。<span class="math inline">\(\dfrac{12}{9}\)</span> ではありません。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>意味は「平均のほうが、当てにできる」ということです
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(1\)</span> 袋の質量は <span class="math inline">\(1000\)</span> g から <span class="math inline">\(20\)</span> g ずれることもあります。しかし <strong><span class="math inline">\(9\)</span> 袋の平均</strong>が <span class="math inline">\(20\)</span> g もずれることは、めったにありません。重い袋と軽い袋が打ち消し合うからです。</p>
<p>これが、標本をたくさんとる理由です。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(\bar{X}\)</span> と、<span class="math inline">\(1\)</span> つの <span class="math inline">\(X\)</span> を取りちがえないでください
</div>
</div>
<div class="callout-body-container callout-body">
<p>問題文が</p>
<ul>
<li><code>the mass of one bag</code> … <span class="math inline">\(X \sim N(1000,\ 12^{2})\)</span>、<span class="math inline">\(\sigma = 12\)</span></li>
<li><code>the mean mass of nine bags</code> … <span class="math inline">\(\bar{X} \sim N(1000,\ 16)\)</span>、<span class="math inline">\(\sigma = 4\)</span></li>
<li><code>the total mass of nine bags</code> … <span class="math inline">\(\sum X \sim N(9000,\ 1296)\)</span>、<span class="math inline">\(\sigma = 36\)</span></li>
</ul>
<p>の <span class="math inline">\(3\)</span> つを区別します。<strong><span class="math inline">\(\sigma\)</span> は <span class="math inline">\(12\)</span>、<span class="math inline">\(4\)</span>、<span class="math inline">\(36\)</span> と全部違います。</strong> 平均のほうは、<code>one</code> と <code>mean</code> が同じ <span class="math inline">\(1000\)</span> で、<code>total</code> だけ <span class="math inline">\(9000\)</span> です。</p>
<p><strong>平均が同じでも <span class="math inline">\(\sigma\)</span> が違う</strong>——<code>one</code> と <code>mean</code> の取りちがえが危ないのは、まさにここです。</p>
<p><code>one</code> なのか <code>mean</code> なのか <code>total</code> なのか——<strong>そこを丸で囲んでから</strong>計算を始めてください。</p>
</div>
</div>
</section>
</section>
<section id="clt" class="level3">
<h3 class="anchored" data-anchor-id="clt">6. Central limit theorem（中心極限定理）</h3>
<p>これまでは、<strong>population（母集団）が normal distribution にしたがう場合</strong>を考えてきました。</p>
<p>しかし、実際のデータの分布は、いつも normal になるとはかぎりません。たとえば待ち時間の分布は、短い値が多く、右側に長く伸びた形になることがあります。</p>
<p>では、もとの分布が normal でない場合、sample mean <span class="math inline">\(\bar{X}\)</span> はどのような分布になるのでしょうか。</p>
<section id="one-vs-mean" class="level4">
<h4 class="anchored" data-anchor-id="one-vs-mean"><span class="math inline">\(1\)</span> 回の測定値と sample mean は、別のものです</h4>
<p>同じ population から独立に取り出した <span class="math inline">\(n\)</span> 個の値を</p>
<p><span class="math display">\[
X_1,\ X_2,\ \ldots,\ X_n
\]</span></p>
<p>とします。<span class="math inline">\(X_i\)</span> は、<span class="math inline">\(i\)</span> 回目の抽出で得られる値を表す random variable（確率変数）です。その sample mean は</p>
<p><span class="math display">\[
\bar{X} = \frac{X_1 + \cdots + X_n}{n}
\]</span></p>
<p>です。</p>
<p>もとの population が normal でなければ、<span class="math inline">\(1\)</span> 回の測定値 <span class="math inline">\(X_i\)</span> の分布も normal ではありません。<strong>しかし、<span class="math inline">\(n\)</span> 個の値から作った sample mean <span class="math inline">\(\bar{X}\)</span> の分布は、<span class="math inline">\(n\)</span> が大きくなるにつれて normal distribution に近づいていきます。</strong></p>
<div id="fig-ahl415-clt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl415-clt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-15-clt.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl415-clt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;3: The central limit theorem in action
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl415-clt" class="quarto-xref">図&nbsp;3</a> のいちばん左は、<strong>normal ではない</strong> population です。右に大きく尾を引いています。その右の <span class="math inline">\(3\)</span> つは、そこから <span class="math inline">\(n\)</span> 個を取り出して平均する、ということをくり返して描いた <span class="math inline">\(\bar{X}\)</span> の分布です。</p>
<ul>
<li><span class="math inline">\(n = 2\)</span> … まだ歪んでいます</li>
<li><span class="math inline">\(n = 10\)</span> … かなり normal に近づいてきました</li>
<li><span class="math inline">\(n = 40\)</span> … <strong>赤い normal の曲線にほぼ重なっています</strong></li>
</ul>
<p>これが <strong>central limit theorem</strong>（中心極限定理、CLT）です。</p>
<blockquote class="blockquote">
<p>同じ population から独立に取り出した標本の sample mean <span class="math inline">\(\bar{X}\)</span> は、sample size <span class="math inline">\(n\)</span> が十分に大きいとき、もとの population が normal でなくても、<strong>approximately normal distribution</strong>（近似的な正規分布）にしたがいます。</p>
</blockquote>
<p>population の平均を <span class="math inline">\(\mu\)</span>、分散を <span class="math inline">\(\sigma^{2}\)</span> とすると</p>
<p><span id="eq-ahl415-clt"><span class="math display">\[
\boxed{\ \bar{X} \approx N\!\left(\mu,\ \frac{\sigma^{2}}{n}\right)\ }
\tag{8}\]</span></span></p>
<p>となります。したがって、<span class="math inline">\(\bar{X}\)</span> の平均、分散、標準偏差は</p>
<p><span class="math display">\[
E(\bar{X}) = \mu
\]</span></p>
<p><span class="math display">\[
\text{Var}(\bar{X}) = \frac{\sigma^{2}}{n}
\]</span></p>
<p><span class="math display">\[
\sigma_{\bar{X}} = \frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>です。この <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span> が、<a href="#xbar">第5節</a>で出てきた <strong>standard error</strong>（標準誤差）です。</p>
<p><strong>平均と分散は、もとが normal でなくてもそのまま</strong>です（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#varcomb">AHL 4.14</a> から出るので、分布の形は関係ありません）。CLT が足してくれるのは、<strong>形が normal に近い</strong>という一点だけです。</p>
</section>
<section id="bigger-n" class="level4">
<h4 class="anchored" data-anchor-id="bigger-n"><span class="math inline">\(n\)</span> が大きくなると、何が起こるのか</h4>
<p><span class="math inline">\(n\)</span> が大きくなると</p>
<p><span class="math display">\[
\frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>は小さくなります。そのため、sample mean <span class="math inline">\(\bar{X}\)</span> は population mean <span class="math inline">\(\mu\)</span> の近くに集まりやすくなります。また、<span class="math inline">\(\bar{X}\)</span> の分布の<strong>形</strong>は、しだいに normal distribution に近づきます。</p>
</section>
<section id="not-data" class="level4">
<h4 class="anchored" data-anchor-id="not-data">CLT は「データが normal になる」とは言っていません</h4>
<p>ここを取りちがえる答案がよくあります。</p>
<p><strong>CLT は、もとのデータ <span class="math inline">\(X_i\)</span> の分布が normal になるという定理ではありません。</strong> normal に近づくのは、何度も標本を取って作った sample mean <span class="math inline">\(\bar{X}\)</span> の分布です。</p>
<p><a href="#fig-ahl415-clt" class="quarto-xref">図&nbsp;3</a> のいちばん左の形は、<span class="math inline">\(n\)</span> をどれだけ大きくしても変わりません。変わるのは、その右の <span class="math inline">\(3\)</span> つのほうです。</p>
</section>
<section id="n30" class="level4">
<h4 class="anchored" data-anchor-id="n30">どのくらいの <span class="math inline">\(n\)</span> が必要ですか</h4>
<p>シラバスは、こう書いています。</p>
<blockquote class="blockquote">
<p>In general, <span class="math inline">\(\bar{X}\)</span> approaches normality for large <span class="math inline">\(n\)</span>, <strong>how large depends upon the distribution from which the sample is taken.</strong> In examinations, <strong><span class="math inline">\(n &gt; 30\)</span> will be considered sufficient.</strong></p>
</blockquote>
<p>試験では、通常</p>
<p><span class="math display">\[
n &gt; 30
\]</span></p>
<p>を「十分に大きい」とする目安が使われます。<strong>ただし、これは数学的な境界ではありません。</strong> 実際に必要な sample size は、もとの分布の形によって変わります。分布の偏りが強い場合や外れ値が多い場合は、より大きな <span class="math inline">\(n\)</span> が必要になることがあります。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>答案での書き方
</div>
</div>
<div class="callout-body-container callout-body">
<p>CLT を使うときは、<strong>normal distribution で近似している理由を <span class="math inline">\(1\)</span> 行書きます。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Since <span class="math inline">\(n = 40 &gt; 30\)</span>, by the central limit theorem, <span class="math inline">\(\bar{X}\)</span> is approximately normal.</em></p>
</div>
<p>（<span class="math inline">\(n = 40 &gt; 30\)</span> なので、中心極限定理により <span class="math inline">\(\bar{X}\)</span> は近似的に正規分布にしたがう、という意味です。）</p>
<p>ここでは、<strong><code>approximately</code>（近似的に）</strong>と書くことが大事です。もとの population が normal だと分かっている場合を除き、exactly normal とは言えません。</p>
</div>
</div>
</section>
</section>
<section id="total" class="level3">
<h3 class="anchored" data-anchor-id="total">7. 平均で解いても、合計で解いても同じです</h3>
<p><span class="math inline">\(40\)</span> 人の待ち時間を調べます。<span class="math inline">\(i\)</span> 人目の待ち時間を <span class="math inline">\(X_i\)</span> とし、<span class="math inline">\(1\)</span> 人あたりの待ち時間について</p>
<p><span class="math display">\[
\mu = 4.2, \qquad \sigma = 2.5
\]</span></p>
<p>とします。<span class="math inline">\(1\)</span> 人分の待ち時間が normal distribution にしたがうとは分かっていません。ここでは、次の確率を求めます。</p>
<blockquote class="blockquote">
<p><span class="math inline">\(40\)</span> 人の平均待ち時間が <span class="math inline">\(4.5\)</span> 分を超える確率</p>
</blockquote>
<section id="by-mean" class="level4">
<h4 class="anchored" data-anchor-id="by-mean">方法1：平均で考える</h4>
<p><span class="math inline">\(40\)</span> 人の sample mean を</p>
<p><span class="math display">\[
\bar{X} = \frac{X_1 + \cdots + X_{40}}{40}
\]</span></p>
<p>とします。<span class="math inline">\(n = 40 &gt; 30\)</span> なので、CLT により</p>
<p><span class="math display">\[
\bar{X} \approx N\!\left(4.2,\ \frac{2.5^{2}}{40}\right) = N(4.2,\ 0.15625)
\]</span></p>
<p>です。したがって、求める確率は <span class="math inline">\(P(\bar{X} &gt; 4.5)\)</span> です。</p>
</section>
<section id="by-total" class="level4">
<h4 class="anchored" data-anchor-id="by-total">方法2：合計で考える</h4>
<p><span class="math inline">\(40\)</span> 人の合計待ち時間を表す新しい確率変数を</p>
<p><span class="math display">\[
T = X_1 + \cdots + X_{40}
\]</span></p>
<p>とします（<span class="math inline">\(\sum X_i\)</span> と書くこともあります）。合計 <span class="math inline">\(T\)</span> の平均は</p>
<p><span class="math display">\[
E(T) = 40 \times 4.2 = 168
\]</span></p>
<p>です。各 <span class="math inline">\(X_i\)</span> は独立なので、合計の分散は</p>
<p><span class="math display">\[
\text{Var}(T) = 40 \times 2.5^{2} = 250
\]</span></p>
<p>となります。また、<span class="math inline">\(T = 40\bar{X}\)</span> なので、<span class="math inline">\(\bar{X}\)</span> が approximately normal なら <span class="math inline">\(T\)</span> も approximately normal です。</p>
<p><span class="math display">\[
T \approx N(168,\ 250)
\]</span></p>
<p>この方法では、<span class="math inline">\(40\)</span> 人の合計が <span class="math inline">\(40 \times 4.5 = 180\)</span> 分を超える確率 <span class="math inline">\(P(T &gt; 180)\)</span> を求めます。</p>
</section>
<section id="same-event" class="level4">
<h4 class="anchored" data-anchor-id="same-event">なぜ <span class="math inline">\(2\)</span> つの確率は同じなのか</h4>
<p><span class="math inline">\(T = 40\bar{X}\)</span> なので</p>
<p><span id="eq-ahl415-same"><span class="math display">\[
\begin{aligned}
\bar{X} &gt; 4.5 &amp;\iff 40\bar{X} &gt; 40 \times 4.5 \\
&amp;\iff T &gt; 180
\end{aligned}
\tag{9}\]</span></span></p>
<p>です。つまり、<strong>「平均待ち時間が <span class="math inline">\(4.5\)</span> 分を超える」ことと「合計待ち時間が <span class="math inline">\(180\)</span> 分を超える」ことは、同じ出来事</strong>です。したがって</p>
<p><span class="math display">\[
\boxed{\ P(\bar{X} &gt; 4.5) = P(T &gt; 180)\ }
\]</span></p>
<p>となります。</p>
<p>平均と合計では数値の尺度が違いますが、表している出来事は同じです。ですから、どちらの分布を使っても同じ確率が得られます。</p>
<div id="tbl-ahl415-total" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl415-total-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;2: 同じことを <span class="math inline">\(2\)</span> 通りに聞く
</figcaption>
<div aria-describedby="tbl-ahl415-total-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>考え方</th>
<th>使う分布</th>
<th>求める確率</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>平均で考える</td>
<td><span class="math inline">\(\bar{X} \approx N\!\left(4.2,\ \dfrac{2.5^{2}}{40}\right)\)</span></td>
<td><span class="math inline">\(P(\bar{X} &gt; 4.5)\)</span></td>
</tr>
<tr class="even">
<td>合計で考える</td>
<td><span class="math inline">\(T \approx N(168,\ 250)\)</span></td>
<td><span class="math inline">\(P(T &gt; 180)\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>問題が平均について聞いているなら平均を使い、合計について聞いているなら合計を使う</strong>のが自然です。わざわざ一方から他方へ変換する必要はありません。</p>
</section>
</section>
<section id="when" class="level3">
<h3 class="anchored" data-anchor-id="when">8. exactly normal と approximately normal</h3>
<p>sample mean <span class="math inline">\(\bar{X}\)</span> が exactly normal になるか approximately normal になるかは、<strong>population の分布</strong>によって決まります。</p>
<div id="tbl-ahl415-when" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl415-when-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;3: exactly か approximately か
</figcaption>
<div aria-describedby="tbl-ahl415-when-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>population の分布</th>
<th>sample mean <span class="math inline">\(\bar{X}\)</span> の分布</th>
<th>sample size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>normal distribution（観測は独立）</td>
<td><strong>exactly normal</strong></td>
<td><span class="math inline">\(n\)</span> の大きさに関係なく使える</td>
</tr>
<tr class="even">
<td>normal とは限らない（観測は独立）</td>
<td><strong>approximately normal</strong></td>
<td><span class="math inline">\(n\)</span> が十分に大きいとき、CLT を使う</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="small-n" class="level4">
<h4 class="anchored" data-anchor-id="small-n">population が normal の場合</h4>
<p>各 <span class="math inline">\(X_i\)</span> が独立で</p>
<p><span class="math display">\[
X_i \sim N(\mu,\ \sigma^{2})
\]</span></p>
<p>なら、独立な normal random variables の linear combination も normal なので</p>
<p><span class="math display">\[
\boxed{\ \bar{X} \sim N\!\left(\mu,\ \frac{\sigma^{2}}{n}\right)\ }
\]</span></p>
<p>です。この場合、<span class="math inline">\(\bar{X}\)</span> は <strong>exactly normal</strong>（正確に正規分布）です。<strong><span class="math inline">\(n\)</span> が小さくても構いません。</strong> <span class="math inline">\(X \sim N(1000,\ 12^{2})\)</span> から <span class="math inline">\(n = 4\)</span> の標本をとるなら、<span class="math inline">\(4 &lt; 30\)</span> でも <span class="math inline">\(\bar{X}\)</span> は exactly normal で、CLT は要りません。</p>
</section>
<section id="approx-case" class="level4">
<h4 class="anchored" data-anchor-id="approx-case">population が normal とは限らない場合</h4>
<p>もとの population が normal でなくても、<span class="math inline">\(n\)</span> が十分に大きければ、CLT により</p>
<p><span class="math display">\[
\boxed{\ \bar{X} \approx N\!\left(\mu,\ \frac{\sigma^{2}}{n}\right)\ }
\]</span></p>
<p>として扱えます。この場合は <strong>approximately normal</strong>（近似的に正規分布）です。</p>
</section>
<section id="flow" class="level4">
<h4 class="anchored" data-anchor-id="flow">最後に確認</h4>
<p>どちらの場合でも、<span class="math inline">\(\bar{X}\)</span> の平均と分散は</p>
<p><span class="math display">\[
E(\bar{X}) = \mu, \qquad \text{Var}(\bar{X}) = \frac{\sigma^{2}}{n}
\]</span></p>
<p>です。違うのは<strong>分布の形</strong>についてで、</p>
<ul>
<li>population が normal なら、<span class="math inline">\(\bar{X}\)</span> は <strong>exactly normal</strong></li>
<li>population が normal とは限らなければ、十分に大きな <span class="math inline">\(n\)</span> に対して <strong>approximately normal</strong></li>
</ul>
<p>となります。そして、<strong><span class="math inline">\(n\)</span> が小さく、もとの分布も normal と分からない場合</strong>は、normal と仮定しません。<strong>normal approximation（正規近似）を正当化できない</strong>からです。</p>
<p>なお、CLT は<strong>平均と合計</strong>についての定理です。もとが normal でないとき、<span class="math inline">\(n\)</span> をどれだけ大きくしても、<strong>CLT が <span class="math inline">\(1\)</span> つの値 <span class="math inline">\(X\)</span> を normal にしてくれることはありません</strong>（<a href="#not-data">上</a>）。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>「分布が不明」と「normal ではない」は違います
</div>
</div>
<div class="callout-body-container callout-body">
<p>問題文に「この分布は正規分布ではない」と書いてあれば、normal ではないと分かっています。一方、平均と標準偏差だけが与えられている場合は、<strong>分布が不明</strong>なだけです。normal かもしれませんし、そうでないかもしれません。</p>
<p>上の判断はどちらの場合も同じように使えます。ただし答案では、<strong>問題文に書かれていること以上を断定しない</strong>でください。</p>
</div>
</div>
</section>
</section>
</section>
<section id="why-it-works" class="level2">
<h2 class="anchored" data-anchor-id="why-it-works">Why it works</h2>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>クリックすると開きます
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>ここで説明するのは <span class="math inline">\(2\)</span> つです。<strong>なぜ <span class="math inline">\(\bar{X}\)</span> の分散が <span class="math inline">\(\dfrac{\sigma^{2}}{n}\)</span> になるのか</strong>と、<strong>CLT がなぜ起きるのか</strong>。</p>
<section id="why-xbar" class="level3">
<h3 class="anchored" data-anchor-id="why-xbar"><span class="math inline">\(\bar{X}\)</span> の分散は、4.14 から出ます</h3>
<p><span class="math inline">\(\bar{X}\)</span> は、<span class="math inline">\(n\)</span> 個を足して <span class="math inline">\(n\)</span> で割ったものです。</p>
<p><span class="math display">\[
\bar{X} = \frac{1}{n}\bigl(X_1 + X_2 + \cdots + X_n\bigr)
\]</span></p>
<p>まず、カッコの中の分散を出します。独立なので、<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#varcomb">AHL 4.14</a> から</p>
<p><span class="math display">\[
\text{Var}(X_1 + \cdots + X_n) = \underbrace{\sigma^{2} + \sigma^{2} + \cdots + \sigma^{2}}_{n \text{ 個}} = n\sigma^{2}
\]</span></p>
<p>次に、<span class="math inline">\(\dfrac{1}{n}\)</span> を掛けます。<span class="math inline">\(\text{Var}(aX) = a^{2}\text{Var}(X)\)</span> なので</p>
<p><span class="math display">\[
\text{Var}(\bar{X}) = \left(\frac{1}{n}\right)^{2} \times n\sigma^{2} = \frac{n\sigma^{2}}{n^{2}} = \frac{\sigma^{2}}{n}
\]</span></p>
<p><strong><span class="math inline">\(\dfrac{1}{n^{2}}\)</span> を掛けて、<span class="math inline">\(n\sigma^{2}\)</span> が入ってくる。</strong> その差し引きで <span class="math inline">\(\dfrac{\sigma^{2}}{n}\)</span> が残ります。</p>
<p>平均のほうは、<span class="math inline">\(E(\bar{X}) = \dfrac{1}{n} \times n\mu = \mu\)</span> で、<strong><span class="math inline">\(n\)</span> によらず <span class="math inline">\(\mu\)</span> のまま</strong>です。だから <a href="#fig-ahl415-xbar" class="quarto-xref">図&nbsp;2</a> で中心が動かないのです。</p>
</section>
<section id="why-clt" class="level3">
<h3 class="anchored" data-anchor-id="why-clt">CLT は、打ち消し合いの結果です</h3>
<p>証明は、この課程の範囲を大きく超えます。ただ、<strong>なぜそうなるのか</strong>の見当はつけられます。</p>
<p><span class="math inline">\(\bar{X}\)</span> を作るとき、<span class="math inline">\(n\)</span> 個の値を足しています。歪んだ分布から <span class="math inline">\(1\)</span> 個とれば、その値も歪んだ出方をします。しかし <strong><span class="math inline">\(40\)</span> 個とって足すと、大きく外れた値は、ふつうの値に埋もれて</strong>いきます。</p>
<p><a href="#fig-ahl415-clt" class="quarto-xref">図&nbsp;3</a> の左の分布では、たまに <span class="math inline">\(4\)</span> や <span class="math inline">\(5\)</span> が出ます。<span class="math inline">\(n = 1\)</span> ならそれがそのまま出ますが、<span class="math inline">\(n = 40\)</span> の平均では、<span class="math inline">\(1\)</span> 個の <span class="math inline">\(5\)</span> は <span class="math inline">\(\dfrac{5}{40}\)</span> ぶんしか効きません。<strong><span class="math inline">\(1\)</span> 個の極端な値では、平均を動かせなくなる</strong>のです。</p>
<p>その結果、<span class="math inline">\(\bar{X}\)</span> は「たくさんの小さなずれが積み重なったもの」になります。<strong>そういうものの分布は、平均と標準偏差がきちんと決まる分布からとったかぎり、<span class="math inline">\(n\)</span> が大きくなるにつれて正規分布に近づいていきます</strong>——これが中心極限定理の内容です。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>シラバスは、この定理について</p>
<blockquote class="blockquote">
<p><strong>Online simulations are useful for visualisation.</strong></p>
</blockquote>
<p>と書いています。<a href="#fig-ahl415-clt" class="quarto-xref">図&nbsp;3</a> は、そのシミュレーションを <span class="math inline">\(1\)</span> 枚の図にしたものです。<span class="math inline">\(n\)</span> を自分で動かせるシミュレーションを触ってみると、<span class="math inline">\(n\)</span> をいくつにすれば正規に近づくかが体で分かります。</p>
</div>
</div>
</div>
</section>
</div>
</div>
</div>
</section>
<section id="worked-examples" class="level2">
<h2 class="anchored" data-anchor-id="worked-examples">Worked examples</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>問題文は英語です。意味が理解できなかったら、問題文の下の「<strong>日本語訳</strong>」を開いてください。解説は日本語です。</p>
</div>
</div>
</div>
<div id="exm-ahl415-sum" class="theorem example">
<p><span class="theorem-title"><strong>例題 1</strong></span> <span class="q-en">In a school canteen, the mass of a main dish, in grams, is <span class="math inline">\(M \sim N(250,\ 8^{2})\)</span> and the mass of a side dish is <span class="math inline">\(S \sim N(180,\ 6^{2})\)</span>. The two masses are independent.</span></p>
<p><span class="q-en">A meal consists of one main dish and one side dish. Let <span class="math inline">\(T = M + S\)</span> be the total mass of a meal.</span></p>
<p><strong>(a)</strong> <span class="q-en">State the distribution of <span class="math inline">\(T\)</span>, giving its mean and variance.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find <span class="math inline">\(P(T &gt; 445)\)</span>.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the probability that the total mass of a meal is between <span class="math inline">\(420\)</span> g and <span class="math inline">\(445\)</span> g.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある学校の食堂で、主菜の質量（グラム）は <span class="math inline">\(M \sim N(250,\ 8^{2})\)</span>、副菜の質量は <span class="math inline">\(S \sim N(180,\ 6^{2})\)</span> です。この <span class="math inline">\(2\)</span> つの質量は独立です。</p>
<p><span class="math inline">\(1\)</span> 食は、主菜 <span class="math inline">\(1\)</span> つと副菜 <span class="math inline">\(1\)</span> つからなります。<span class="math inline">\(1\)</span> 食の合計質量を <span class="math inline">\(T = M + S\)</span> とします。</p>
<p><strong>(a)</strong> <span class="math inline">\(T\)</span> の分布を、平均と分散を示して述べなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(P(T &gt; 445)\)</span> を求めなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(1\)</span> 食の合計質量が <span class="math inline">\(420\)</span> g から <span class="math inline">\(445\)</span> g のあいだになる確率を求めなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> <a href="#steps">第3節</a>の <span class="math inline">\(3\)</span> ステップのうち、<span class="math inline">\(1\)</span> と <span class="math inline">\(2\)</span> です。<span class="math inline">\(1\)</span> 食の合計質量を <span class="math inline">\(T = M + S\)</span> とおきます。</p>
<p>平均は、係数をそのまま使います。</p>
<p><span class="math display">\[
E(T) = 250 + 180 = 430
\]</span></p>
<p>分散は、係数を <span class="math inline">\(2\)</span> 乗して足します。ここでは係数がどちらも <span class="math inline">\(1\)</span> なので、<span class="math inline">\(8^{2}\)</span> と <span class="math inline">\(6^{2}\)</span> をそのまま足します。<strong>standard deviation ではなく、variance を足す</strong>ところが要点です。</p>
<p><span class="math display">\[
\text{Var}(T) = 8^{2} + 6^{2} = 64 + 36 = 100
\]</span></p>
<p><span class="math inline">\(M\)</span> も <span class="math inline">\(S\)</span> も normal で、独立なので、<span class="math inline">\(T\)</span> は <strong>exactly normal</strong> です（<a href="#lincomb">第1節</a>）。</p>
<p><span class="math display">\[
T \sim N(430,\ 100)
\]</span></p>
<p><strong>検算。</strong> <span class="math inline">\(\sigma = \sqrt{100} = 10\)</span> です。<span class="math inline">\(8 + 6 = 14\)</span> ではありません（<a href="#sum">第2節</a>）。</p>
<p><strong>(b)</strong> <span class="math inline">\(\sigma = 10\)</span> を <code>normCdf</code> に入れます。<strong><span class="math inline">\(100\)</span> ではありません。</strong></p>
<pre><code>normCdf(445, ∞, 430, 10)</code></pre>
<p><span class="math display">\[
P(T &gt; 445) = 0.0668
\]</span></p>
<p><span class="math inline">\(1\)</span> 食の合計質量が <span class="math inline">\(445\)</span> g を超えるのは、およそ <span class="math inline">\(100\)</span> 食のうち <span class="math inline">\(7\)</span> 食です。</p>
<p><strong>(c)</strong> 両端があるので、<code>normCdf</code> の <span class="math inline">\(2\)</span> か所を埋めるだけです。</p>
<pre><code>normCdf(420, 445, 430, 10)</code></pre>
<p><span class="math display">\[
P(420 &lt; T &lt; 445) = 0.775
\]</span></p>
<p><span class="math inline">\(1\)</span> 食のおよそ <span class="math inline">\(77\%\)</span> が、<span class="math inline">\(420\)</span> g から <span class="math inline">\(445\)</span> g のあいだに入ります。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
E(T) = 250 + 180 = 430
\]</span> <span class="math display">\[
\text{Var}(T) = 8^{2} + 6^{2} = 100
\]</span> <span class="math display">\[
T \sim N(430,\ 100)
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
P(T &gt; 445) = 0.0668
\]</span></p>
<p><strong>(c)</strong> <span class="math display">\[
P(420 &lt; T &lt; 445) = 0.775
\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>補足：<span class="math inline">\(2\)</span> 杯のコーヒーなら、こうなります
</div>
</div>
<div class="callout-body-container callout-body">
<p>ここからは、この問題の解答ではなく、<strong>同じ考え方を別の場面に使う話</strong>です。同じ分布のものを <span class="math inline">\(2\)</span> つ足すこともできます。</p>
<p><span class="math inline">\(X \sim N(250,\ 8^{2})\)</span> のコーヒーを <span class="math inline">\(2\)</span> 杯なら</p>
<p><span class="math display">\[
X_1 + X_2 \sim N(500,\ 128), \qquad \sigma = \sqrt{128} = 11.3
\]</span></p>
<p>で、<span class="math inline">\(P(X_1 + X_2 &gt; 510) = 0.188\)</span> です。</p>
<p><strong>ここで <span class="math inline">\(2X\)</span> としてはいけません。</strong> <span class="math inline">\(2X\)</span> なら分散は <span class="math inline">\(4 \times 64 = 256\)</span>、<span class="math inline">\(\sigma = 16\)</span> になり、<span class="math inline">\(P(2X &gt; 510) = 0.266\)</span> と<strong>別の答え</strong>になります（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#two-x">AHL 4.14</a>）。</p>
<p><span class="math inline">\(2\)</span> 杯あるのか、<span class="math inline">\(1\)</span> 杯を <span class="math inline">\(2\)</span> 倍するのか。<strong>問題文で数えてください。</strong></p>
</div>
</div>
</div>
<div id="exm-ahl415-diff" class="theorem example">
<p><span class="theorem-title"><strong>例題 2</strong></span> <span class="q-en">The lifetime of a battery of brand A, in hours, is <span class="math inline">\(X \sim N(30,\ 4^{2})\)</span>. The lifetime of a battery of brand B is <span class="math inline">\(Y \sim N(27,\ 3^{2})\)</span>. All lifetimes are independent.</span></p>
<p><span class="q-en">One battery of each brand is chosen at random. Let <span class="math inline">\(D = X - Y\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">State the distribution of <span class="math inline">\(D\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the probability that the brand A battery lasts longer than the brand B battery.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the probability that the brand A battery lasts at least <span class="math inline">\(5\)</span> hours longer than the brand B battery.</span></p>
<p><strong>(d)</strong> <span class="q-en">Explain why the standard deviation of <span class="math inline">\(D\)</span> is not <span class="math inline">\(4 - 3 = 1\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ブランド A の電池の寿命（時間）は <span class="math inline">\(X \sim N(30,\ 4^{2})\)</span>、ブランド B の電池の寿命は <span class="math inline">\(Y \sim N(27,\ 3^{2})\)</span> です。すべての寿命は独立です。</p>
<p><code>lifetime</code> は「寿命」、<code>at least</code> は「少なくとも」という意味です。</p>
<p>各ブランドから電池を <span class="math inline">\(1\)</span> 個ずつ無作為に選びます。<span class="math inline">\(D = X - Y\)</span> とします。</p>
<p><strong>(a)</strong> <span class="math inline">\(D\)</span> の分布を述べなさい。</p>
<p><strong>(b)</strong> ブランド A の電池のほうが、ブランド B の電池より長持ちする確率を求めなさい。</p>
<p><strong>(c)</strong> ブランド A の電池が、ブランド B の電池より少なくとも <span class="math inline">\(5\)</span> 時間長持ちする確率を求めなさい。</p>
<p><strong>(d)</strong> <span class="math inline">\(D\)</span> の標準偏差が <span class="math inline">\(4 - 3 = 1\)</span> にならない理由を説明しなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> <span class="math inline">\(D = X - Y = X + (-1)Y\)</span> とおきます。平均は係数をそのまま使い、分散は係数を <span class="math inline">\(2\)</span> 乗します（<a href="#eq-ahl415-diff" class="quarto-xref">式&nbsp;4</a>）。</p>
<p><span class="math display">\[
E(D) = 30 - 27 = 3
\]</span></p>
<p><span class="math display">\[
\text{Var}(D) = 4^{2} + (-1)^{2} \times 3^{2} = 16 + 9 = 25
\]</span></p>
<p><span class="math inline">\(X\)</span> も <span class="math inline">\(Y\)</span> も normal で、独立なので、<span class="math inline">\(D\)</span> は <strong>exactly normal</strong> です。</p>
<p><span class="math display">\[
D \sim N(3,\ 25)
\]</span></p>
<p><span class="math inline">\(N(3,\ 25)\)</span> の <span class="math inline">\(25\)</span> は分散なので、標準偏差は <span class="math inline">\(\sigma = \sqrt{25} = 5\)</span> です。<code>normCdf</code> には <span class="math inline">\(5\)</span> を入れます。</p>
<p><strong>(b)</strong> 「A のほうが長い」は「<span class="math inline">\(D\)</span> が正」ということです（<a href="#eq-ahl415-dgt0" class="quarto-xref">式&nbsp;5</a>）。</p>
<p><span class="math display">\[
P(X &gt; Y) = P(D &gt; 0)
\]</span></p>
<pre><code>normCdf(0, ∞, 3, 5)</code></pre>
<p><span class="math display">\[
P(D &gt; 0) = 0.726
\]</span></p>
<p>ブランド A のほうが長持ちするのは、およそ <span class="math inline">\(73\%\)</span> です。</p>
<p><strong>検算。</strong> <span class="math inline">\(E(D) = 3 &gt; 0\)</span> なので、確率は <span class="math inline">\(0.5\)</span> より大きくなるはずです ✓</p>
<p><strong>(c)</strong> <code>at least 5 hours longer</code> は <span class="math inline">\(D \geq 5\)</span> です。</p>
<pre><code>normCdf(5, ∞, 3, 5)</code></pre>
<p><span class="math display">\[
P(D \geq 5) = 0.345
\]</span></p>
<p><span class="math inline">\(5\)</span> 時間以上長持ちするのは、およそ <span class="math inline">\(34\%\)</span> です。</p>
<p><strong>(d)</strong> 足すのは標準偏差ではなく分散で、しかも<strong>差のときも足します</strong>。<span class="math inline">\(Y\)</span> の係数 <span class="math inline">\(-1\)</span> が <span class="math inline">\(2\)</span> 乗されて <span class="math inline">\(+1\)</span> になるからです。<span class="math inline">\(Y\)</span> を引いても <span class="math inline">\(Y\)</span> のばらつきは消えず、<span class="math inline">\(Y\)</span> がぶれれば <span class="math inline">\(X - Y\)</span> もぶれるので、<span class="math inline">\(2\)</span> つのばらつきは打ち消し合わずに重なります。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Variances add, not standard deviations, and they add for a difference as well: <span class="math inline">\(\text{Var}(D) = 4^{2} + (-1)^{2} \times 3^{2} = 25\)</span>, so the standard deviation is <span class="math inline">\(\sqrt{25} = 5\)</span>. Subtracting <span class="math inline">\(Y\)</span> does not remove the variability of <span class="math inline">\(Y\)</span>.</em></p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
E(D) = 30 - 27 = 3, \qquad \text{Var}(D) = 4^{2} + (-1)^{2} \times 3^{2} = 25
\]</span> <span class="math display">\[
D \sim N(3,\ 25)
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
P(X &gt; Y) = P(D &gt; 0) = 0.726
\]</span></p>
<p><strong>(c)</strong> <span class="math display">\[
P(D \geq 5) = 0.345
\]</span></p>
<p><strong>(d)</strong> <em>Variances add rather than standard deviations, and they add for a difference as well as for a sum: <span class="math inline">\(\text{Var}(D) = 4^{2} + (-1)^{2} \times 3^{2} = 25\)</span>, so <span class="math inline">\(\sigma = 5\)</span>. Subtracting <span class="math inline">\(Y\)</span> does not remove the variability of <span class="math inline">\(Y\)</span>.</em></p>
</div>
</div>
</div>
<div id="exm-ahl415-xbar" class="theorem example">
<p><span class="theorem-title"><strong>例題 3</strong></span> <span class="q-en">The mass of a bag of sugar, in grams, is normally distributed with mean <span class="math inline">\(1000\)</span> and standard deviation <span class="math inline">\(12\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the probability that a randomly chosen bag has a mass less than <span class="math inline">\(995\)</span> g.</span></p>
<p><strong>(b)</strong> <span class="q-en">Nine bags are chosen at random. Find the probability that their mean mass is less than <span class="math inline">\(995\)</span> g.</span></p>
<p><strong>(c)</strong> <span class="q-en">Comment on the difference between your answers to parts (a) and (b).</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>砂糖 <span class="math inline">\(1\)</span> 袋の質量（グラム）は、平均 <span class="math inline">\(1000\)</span>、標準偏差 <span class="math inline">\(12\)</span> の正規分布にしたがいます。</p>
<p><strong>(a)</strong> 無作為に選んだ <span class="math inline">\(1\)</span> 袋の質量が <span class="math inline">\(995\)</span> g 未満である確率を求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(9\)</span> 袋を無作為に選びます。その平均質量が <span class="math inline">\(995\)</span> g 未満である確率を求めなさい。</p>
<p><strong>(c)</strong> (a) と (b) の答えの違いについて述べなさい。</p>
</details>
<hr>
<p><span class="math inline">\(1\)</span> 袋の質量を <span class="math inline">\(X\)</span>、<span class="math inline">\(9\)</span> 袋の標本平均を <span class="math inline">\(\bar{X}\)</span> とします。<strong>この <span class="math inline">\(2\)</span> つを、記号でも区別してください。</strong></p>
<p><strong>(a)</strong> <span class="math inline">\(1\)</span> 袋を選ぶ場合なので、<span class="math inline">\(X \sim N(1000,\ 12^{2}) = N(1000,\ 144)\)</span> をそのまま使います。標準偏差は <span class="math inline">\(\sigma = 12\)</span> です。</p>
<pre><code>normCdf(-∞, 995, 1000, 12)</code></pre>
<p><span class="math display">\[
P(X &lt; 995) = 0.338
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(9\)</span> 袋の<strong>平均</strong>を調べる場合なので <span class="math inline">\(\bar{X}\)</span> です。<span class="math inline">\(9\)</span> 袋は独立で、もとの <span class="math inline">\(X\)</span> が normal なので、<span class="math inline">\(n = 9\)</span> でも <span class="math inline">\(\bar{X}\)</span> は <strong>exactly normal</strong> です（<a href="#eq-ahl415-xbar" class="quarto-xref">式&nbsp;7</a>）。</p>
<p><span class="math display">\[
\bar{X} \sim N\!\left(1000,\ \frac{144}{9}\right) = N(1000,\ 16)
\]</span></p>
<p><span class="math display">\[
\sigma_{\bar{X}} = \frac{12}{\sqrt{9}} = \frac{12}{3} = 4
\]</span></p>
<pre><code>normCdf(-∞, 995, 1000, 4)</code></pre>
<p><span class="math display">\[
P(\bar{X} &lt; 995) = 0.106
\]</span></p>
<p><strong>検算。</strong> <span class="math inline">\(\sigma\)</span> が <span class="math inline">\(12\)</span> から <span class="math inline">\(4\)</span> に<strong>小さく</strong>なったので、確率も小さくなるはずです ✓</p>
<p><strong>(c)</strong> <span class="math inline">\(9\)</span> 袋の平均のほうが、はるかに起こりにくくなっています。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The probability drops from <span class="math inline">\(0.338\)</span> to <span class="math inline">\(0.106\)</span>. For a single bag, one light bag is enough to fall below <span class="math inline">\(995\)</span> g. For the mean of nine bags, a light bag tends to be offset by a heavier one, so the mean falls below <span class="math inline">\(995\)</span> g only if the nine bags are light on average, which is much less likely. The standard deviation of the mean is <span class="math inline">\(12/\sqrt{9} = 4\)</span>, only a third of the standard deviation of a single bag.</em></p>
</div>
<p>（確率は <span class="math inline">\(0.338\)</span> から <span class="math inline">\(0.106\)</span> に下がる。<span class="math inline">\(1\)</span> 袋なら軽い袋 <span class="math inline">\(1\)</span> つで <span class="math inline">\(995\)</span> g を下回るが、<span class="math inline">\(9\)</span> 袋の平均では軽い袋が重い袋で打ち消されるので、<span class="math inline">\(9\)</span> 袋そろって軽いときにしか下回らず、はるかに起こりにくい、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
X \sim N(1000,\ 144), \qquad P(X &lt; 995) = 0.338
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
\bar{X} \sim N\!\left(1000,\ \frac{144}{9}\right) = N(1000,\ 16), \qquad \sigma_{\bar{X}} = 4
\]</span> <span class="math display">\[
P(\bar{X} &lt; 995) = 0.106
\]</span></p>
<p><strong>(c)</strong> <em>The probability is much smaller for the mean of nine bags (<span class="math inline">\(0.106\)</span> against <span class="math inline">\(0.338\)</span>), because the standard deviation of <span class="math inline">\(\bar{X}\)</span> is <span class="math inline">\(12/\sqrt{9} = 4\)</span>, only one third of that of a single bag. Light bags tend to be offset by heavy ones, so the mean of nine bags stays close to <span class="math inline">\(1000\)</span> g.</em></p>
</div>
</div>
</div>
<div id="exm-ahl415-clt" class="theorem example">
<p><span class="theorem-title"><strong>例題 4</strong></span> <span class="q-en">At a service desk, the time taken to serve one customer has mean <span class="math inline">\(4.2\)</span> minutes and standard deviation <span class="math inline">\(2.5\)</span> minutes. The distribution of these times is strongly skewed and is <strong>not</strong> normal. The times are independent.</span></p>
<p><span class="q-en">On one day, <span class="math inline">\(40\)</span> customers are served.</span></p>
<p><strong>(a)</strong> <span class="q-en">Explain why the mean serving time for these <span class="math inline">\(40\)</span> customers can be treated as normally distributed.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the probability that the mean serving time for the <span class="math inline">\(40\)</span> customers is greater than <span class="math inline">\(4.5\)</span> minutes.</span></p>
<p><strong>(c)</strong> <span class="q-en">Show that the probability that the total serving time for the <span class="math inline">\(40\)</span> customers exceeds <span class="math inline">\(180\)</span> minutes is the same as your answer to part (b).</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある受付で、<span class="math inline">\(1\)</span> 人の客に対応する時間は、平均 <span class="math inline">\(4.2\)</span> 分、標準偏差 <span class="math inline">\(2.5\)</span> 分です。この時間の分布は大きく歪んでおり、<strong>正規分布ではありません。</strong> 各時間は独立です。</p>
<p><code>service desk</code> は「受付」、<code>skewed</code> は「歪んだ」、<code>exceeds</code> は「〜を超える」という意味です。</p>
<p>ある日、<span class="math inline">\(40\)</span> 人の客に対応しました。</p>
<p><strong>(a)</strong> この <span class="math inline">\(40\)</span> 人の平均対応時間が、正規分布として扱える理由を説明しなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(40\)</span> 人の平均対応時間が <span class="math inline">\(4.5\)</span> 分を超える確率を求めなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(40\)</span> 人の合計対応時間が <span class="math inline">\(180\)</span> 分を超える確率が、(b) の答えと同じになることを示しなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> もとの分布は normal ではないと書かれています。ですから「独立な normal の一次結合は normal」という結果（<a href="#lincomb">第1節</a>）は使えません。使うのは <strong>central limit theorem</strong> です（<a href="#clt">第6節</a>）。<span class="math inline">\(n = 40\)</span> は十分大きいため、CLT により <span class="math inline">\(\bar{X}\)</span> は <strong>approximately normal</strong> です。「normal である」と断定しないでください。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The sample size is <span class="math inline">\(n = 40\)</span>, which is greater than <span class="math inline">\(30\)</span>, so by the central limit theorem the mean serving time <span class="math inline">\(\bar{X}\)</span> is approximately normally distributed, even though the distribution of individual times is not normal.</em></p>
</div>
<p>（<span class="math inline">\(n = 40 &gt; 30\)</span> なので、個々の時間の分布が normal でなくても、中心極限定理により平均 <span class="math inline">\(\bar{X}\)</span> は近似的に正規分布にしたがう、という意味です。）</p>
<p><strong>(b)</strong> 平均と分散は、もとの分布の形によりません（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#varcomb">AHL 4.14</a>）。</p>
<p><span class="math display">\[
E(\bar{X}) = 4.2, \qquad \text{Var}(\bar{X}) = \frac{2.5^{2}}{40} = \frac{6.25}{40} = 0.15625
\]</span></p>
<p><span class="math inline">\(\bar{X}\)</span> は approximately normal なので、<span class="math inline">\(\bar{X} \sim N(4.2,\ 0.15625)\)</span> と書けます。標準偏差は分散の平方根です。</p>
<p><span class="math display">\[
\sigma_{\bar{X}} = \sqrt{0.15625} = 0.395
\]</span></p>
<pre><code>√(2.5^2/40)  →  ans
normCdf(4.5, ∞, 4.2, ans)</code></pre>
<p><span class="math display">\[
P(\bar{X} &gt; 4.5) = 0.224
\]</span></p>
<p><span class="math inline">\(40\)</span> 人の平均対応時間が <span class="math inline">\(4.5\)</span> 分を超える日は、およそ <span class="math inline">\(22\%\)</span> です。</p>
<p><strong>丸める前の <span class="math inline">\(\sigma\)</span> を使ってください。</strong> <span class="math inline">\(0.395\)</span> で計算しても <span class="math inline">\(3\)</span> 桁目までは同じですが、<code>ans</code> で前の行の値をそのまま呼び出すほうが確実です（<a href="#gdc-unrounded">GDC 第2節</a>）。</p>
<p><strong>(c)</strong> 合計 <span class="math inline">\(\sum X\)</span> で考えます。CLT は平均と合計の両方についての定理なので、合計も <strong>approximately normal</strong> です（<a href="#flow">第8節</a>）。</p>
<p><span class="math display">\[
E\left(\sum X\right) = 40 \times 4.2 = 168, \qquad \text{Var}\left(\sum X\right) = 40 \times 2.5^{2} = 250
\]</span></p>
<p><span class="math display">\[
\sigma = \sqrt{250} = 15.8
\]</span></p>
<pre><code>√250  →  ans
normCdf(180, ∞, 168, ans)</code></pre>
<p><span class="math display">\[
P\left(\sum X &gt; 180\right) = 0.224
\]</span></p>
<p><strong>同じ値になりました。</strong> <span class="math inline">\(180 = 40 \times 4.5\)</span> だからです。「合計が <span class="math inline">\(180\)</span> を超える」と「平均が <span class="math inline">\(4.5\)</span> を超える」は、<strong>言い方が違うだけの同じ出来事</strong>です（<a href="#total">第7節</a>）。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em><span class="math inline">\(n = 40 &gt; 30\)</span>, so by the central limit theorem <span class="math inline">\(\bar{X}\)</span> is approximately normal, even though the underlying distribution is not.</em></p>
<p><strong>(b)</strong> <span class="math display">\[
\bar{X} \sim N\!\left(4.2,\ \frac{2.5^{2}}{40}\right) = N(4.2,\ 0.15625), \qquad \sigma_{\bar{X}} = 0.395
\]</span> <span class="math display">\[
P(\bar{X} &gt; 4.5) = 0.224
\]</span></p>
<p><strong>(c)</strong> <em>By the central limit theorem the total is also approximately normal.</em> <span class="math display">\[
\textstyle\sum X \sim N(168,\ 250), \qquad \sigma = 15.8
\]</span> <span class="math display">\[
\textstyle P\left(\sum X &gt; 180\right) = 0.224
\]</span> <em>This is the same event as <span class="math inline">\(\bar{X} &gt; 4.5\)</span>, since <span class="math inline">\(180 = 40 \times 4.5\)</span>.</em></p>
</div>
</div>
</div>
</section>
<section id="common-errors" class="level2">
<h2 class="anchored" data-anchor-id="common-errors">Common errors</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>標準偏差を直接足してしまう
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<span class="math inline">\(\sigma_{M+S} = 8 + 6 = 14\)</span></p>
<p>足せるのは variance（分散）であって、standard deviation（標準偏差）ではありません（<a href="#sum">第2節</a>）。</p>
<p><strong>正しくは</strong>：<span class="math inline">\(\text{Var}(M+S) = 8^{2} + 6^{2} = 100\)</span>、<span class="math inline">\(\sigma = \sqrt{100} = 10\)</span>。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>差を取るときに、分散まで引いてしまう
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<span class="math inline">\(\text{Var}(X - Y) = 4^{2} - 3^{2} = 7\)</span></p>
<p><span class="math inline">\(Y\)</span> の係数 <span class="math inline">\(-1\)</span> は <span class="math inline">\(2\)</span> 乗されて <span class="math inline">\(+1\)</span> になるので、独立なら分散は<strong>足されます</strong>（<a href="#diff">第4節</a>）。</p>
<p><strong>正しくは</strong>：<span class="math inline">\(\text{Var}(X - Y) = 4^{2} + (-1)^{2} \times 3^{2} = 25\)</span>、<span class="math inline">\(\sigma = 5\)</span>。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(N(\mu,\ \sigma^{2})\)</span> と、GDC の標準偏差を混同する
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<code>normCdf(445, ∞, 430, 100)</code></p>
<p><span class="math inline">\(N(430,\ 100)\)</span> の <span class="math inline">\(100\)</span> は<strong>分散</strong>で、<code>normCdf</code> に入れるのは<strong>標準偏差</strong>です（<a href="#gdc-normcdf">GDC 第1節</a>）。</p>
<p><strong>正しくは</strong>：<code>normCdf(445, ∞, 430, 10)</code>。分散を入れると <span class="math inline">\(0.440\)</span> となり、正しい <span class="math inline">\(0.0668\)</span> とはまったく違う答えになります。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>exactly normal と、CLT による approximately normal を混同する
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：もとが normal なのに「<span class="math inline">\(n &gt; 30\)</span> でないので normal として扱えない」／ CLT を使ったのに「<span class="math inline">\(\bar{X}\)</span> は normal である」と書く</p>
<p>もとが normal なら <span class="math inline">\(n\)</span> によらず exactly normal、CLT から言えるのは approximately normal です（<a href="#when">第8節</a>）。</p>
<p><strong>正しくは</strong>：<em>Since <span class="math inline">\(X\)</span> is normal, <span class="math inline">\(\bar{X}\)</span> is exactly normal for any <span class="math inline">\(n\)</span>.</em> ／ <em>Since <span class="math inline">\(n = 40 &gt; 30\)</span>, by the central limit theorem <span class="math inline">\(\bar{X}\)</span> is approximately normal.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>このページの判断手順
</div>
</div>
<div class="callout-body-container callout-body">
<p>① 求めたい量を、和・差・標本平均として式にする。</p>
<p>② 平均は、係数をそのまま使って計算する。</p>
<p>③ 分散は、係数を <span class="math inline">\(2\)</span> 乗して足す。</p>
<p>④ もとの変数が normal なら <strong>exactly normal</strong>。そうでなくても、標本数が十分大きければ CLT により <strong>approximately normal</strong>。</p>
<p>⑤ 分散の平方根を取り、標準偏差を GDC に入れる。</p>
</div>
</div>
<p><a href="#steps">第3節の <span class="math inline">\(3\)</span> ステップ</a>は<strong>計算の手順</strong>、こちらは<strong>normal と言ってよいかを確かめる手順</strong>です。②③⑤ で計算し、④ で根拠を確かめる、と役割を分けて使ってください。</p>
</section>
<section id="using-your-gdc-ti-nspire-cx-ii" class="level2">
<h2 class="anchored" data-anchor-id="using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</h2>
<p>この項目の電卓操作は、<strong>SL 4.9 とまったく同じ</strong>です。新しい機能は使いません。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>AI HL の公式集は <strong>4.14 の次が 4.17</strong> で、4.15 の欄はありません。<span class="math inline">\(E\)</span> と <span class="math inline">\(\text{Var}\)</span> の式は 4.14 の欄にありますが、<strong>「独立な normal の一次結合は normal」と <span class="math inline">\(\bar{X} \sim N\!\left(\mu,\ \dfrac{\sigma^{2}}{n}\right)\)</span> は印刷されていません。この <span class="math inline">\(2\)</span> つは覚える必要があります。</strong></p>
<p>また、<a href="../../ai-sl/04-statistics-and-probability/sl-4-9.html">SL 4.9</a> で見たとおり、シラバスは</p>
<blockquote class="blockquote">
<p>This does <strong>not</strong> involve transformation to the standardized normal variable <span class="math inline">\(z\)</span>.</p>
</blockquote>
<p>と書いています。<span class="math inline">\(z = \dfrac{x-\mu}{\sigma}\)</span> に直す必要はありません。<strong>求めた <span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> を、そのまま <code>normCdf</code> に入れます。</strong></p>
</div>
</div>
</div>
<section id="gdc-normcdf" class="level3">
<h3 class="anchored" data-anchor-id="gdc-normcdf">1. Normal Cdf に入れるのは <span class="math inline">\(\sigma\)</span> です</h3>
<pre><code>menu → Statistics → Distributions → Normal Cdf</code></pre>
<p>欄は <span class="math inline">\(4\)</span> つです。</p>
<div id="tbl-ahl415-gdc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl415-gdc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;4: Normal Cdf の <span class="math inline">\(4\)</span> 欄
</figcaption>
<div aria-describedby="tbl-ahl415-gdc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>欄</th>
<th>入れるもの</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Lower Bound</code></td>
<td>下の端。なければ <span class="math inline">\(-\infty\)</span></td>
</tr>
<tr class="even">
<td><code>Upper Bound</code></td>
<td>上の端。なければ <span class="math inline">\(\infty\)</span></td>
</tr>
<tr class="odd">
<td><code>μ</code></td>
<td>求めた平均</td>
</tr>
<tr class="even">
<td><code>σ</code></td>
<td>求めた<strong>標準偏差</strong>。分散ではありません</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong><span class="math inline">\(N(430,\ 100)\)</span> の <span class="math inline">\(100\)</span> をそのまま <span class="math inline">\(\sigma\)</span> の欄に入れないでください。</strong> 入れるのは <span class="math inline">\(\sqrt{100} = 10\)</span> です。</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span><span class="math inline">\(\infty\)</span> の入れ方と、<span class="math inline">\(1E99\)</span> という書き方
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\infty\)</span> は<strong>記号パレット</strong>から選びます。TI 公式のガイドでは、handheld で <code>ctrl</code> と <code>k</code> を押すとパレットが開く、と書かれています。<span class="math inline">\(-\infty\)</span> は、負号 <code>(-)</code> を打ってから <span class="math inline">\(\infty\)</span> を選びます。</p>
<p><strong><span class="math inline">\(1E99\)</span> と入れても同じです。</strong> <span class="math inline">\(1E99\)</span> は <span class="math inline">\(1 \times 10^{99}\)</span> という意味で、「事実上の無限大」として使う書き方です（<span class="math inline">\(E\)</span> は電卓の <code>EE</code> キーで出します）。古い教材や TI-84 の解説では、こちらをよく見かけます。</p>
<p><strong>この本では <span class="math inline">\(\infty\)</span> で書きます</strong>（<a href="../../ai-sl/04-statistics-and-probability/sl-4-9.html#infinity">SL 4.9</a>）。</p>
</div>
</div>
</section>
<section id="gdc-unrounded" class="level3">
<h3 class="anchored" data-anchor-id="gdc-unrounded">2. <span class="math inline">\(\sigma\)</span> は、丸める前の値を使う</h3>
<p><span class="math inline">\(\sigma = \sqrt{0.15625} = 0.39528\ldots\)</span> のように<strong>割り切れない</strong>ことがよくあります。</p>
<p>答案には <span class="math inline">\(3\)</span> 桁で書きますが、<strong><code>normCdf</code> には電卓の値をそのまま入れてください。</strong> 前の行の答えは <code>ans</code> で呼び出せます。</p>
<pre><code>√(2.5^2/40)  →  ans
normCdf(4.5, ∞, 4.2, ans)</code></pre>
</section>
<section id="gdc-diff" class="level3">
<h3 class="anchored" data-anchor-id="gdc-diff">3. 「<span class="math inline">\(A\)</span> が <span class="math inline">\(B\)</span> より大きい」は <span class="math inline">\(1\)</span> 回で済ませる</h3>
<p><span class="math inline">\(P(X &gt; Y)\)</span> を、<span class="math inline">\(2\)</span> つの分布を見くらべて出そうとしないでください。<strong><span class="math inline">\(D = X - Y\)</span> を作れば、<code>normCdf</code> <span class="math inline">\(1\)</span> 回</strong>で終わります（<a href="#which-bigger">第4節</a>）。</p>
<pre><code>normCdf(0, ∞, 3, 5)</code></pre>
</section>
<section id="gdc-invnorm" class="level3">
<h3 class="anchored" data-anchor-id="gdc-invnorm">4. 逆向きに使うときは Inverse Normal</h3>
<p>「<span class="math inline">\(P(\bar{X} &gt; k) = 0.05\)</span> となる <span class="math inline">\(k\)</span>」のような問題では、<code>Inverse Normal</code> を使います（<a href="../../ai-sl/04-statistics-and-probability/sl-4-9.html#inverse">SL 4.9</a>）。</p>
<p><strong>入れるのは左からの面積</strong>です。右が <span class="math inline">\(0.05\)</span> なら、<span class="math inline">\(0.95\)</span> を入れます。</p>
<pre><code>invNorm(0.95, 60, 2.5)</code></pre>
<p>たとえばこれは、<span class="math inline">\(N(60,\ 2.5^{2})\)</span> で「上から <span class="math inline">\(5\%\)</span> に入る境目」を求めています。右の面積が <span class="math inline">\(0.05\)</span> なので、入れるのは <span class="math inline">\(0.95\)</span> です。返るのは <span class="math inline">\(64.1\)</span> です。</p>
</section>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>各問題に、折りたたみが3つ付いています。<strong>日本語訳</strong>、<strong>解答例</strong>（答案用紙に書くべきこと。英語です）、<strong>解説</strong>（なぜそうなるか。日本語です）。</p>
<p>まず自分で解いて、次に解答例と見くらべてください。<strong>解説は、合わなかったときだけ開けば十分です。</strong></p>
</div>
</div>
</div>
<div class="exercise-block">
<p><span class="ex-no">1</span> <span class="q-en">The independent random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are such that <span class="math inline">\(X \sim N(50,\ 5^{2})\)</span> and <span class="math inline">\(Y \sim N(30,\ 12^{2})\)</span>. State the distribution of <span class="math inline">\(X + Y\)</span> and the distribution of <span class="math inline">\(X - Y\)</span>, giving the mean and variance of each.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>独立な確率変数 <span class="math inline">\(X\)</span> と <span class="math inline">\(Y\)</span> について、<span class="math inline">\(X \sim N(50,\ 5^{2})\)</span>、<span class="math inline">\(Y \sim N(30,\ 12^{2})\)</span> です。<span class="math inline">\(X+Y\)</span> の分布と <span class="math inline">\(X-Y\)</span> の分布を、それぞれ平均と分散を示して述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
X + Y \sim N(80,\ 169)
\]</span> <span class="math display">\[
X - Y \sim N(20,\ 169)
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>分散は <span class="math inline">\(5^{2} + 12^{2} = 25 + 144 = 169\)</span> です。<strong>和でも差でも同じ</strong>になります（<a href="#diff">第4節</a>）。</p>
<p><span class="math inline">\(\sigma = \sqrt{169} = 13\)</span>。<span class="math inline">\(5 + 12 = 17\)</span> でも <span class="math inline">\(12 - 5 = 7\)</span> でもありません（<a href="#sum">第2節</a>）。</p>
<p>平均だけが <span class="math inline">\(80\)</span> と <span class="math inline">\(20\)</span> で違います。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">2</span> <span class="q-en">Using the random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> from question 1, find <span class="math inline">\(P(X + Y &gt; 95)\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>問題 1 の確率変数 <span class="math inline">\(X\)</span> と <span class="math inline">\(Y\)</span> について、<span class="math inline">\(P(X+Y &gt; 95)\)</span> を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
X + Y \sim N(80,\ 169), \qquad \sigma = 13
\]</span> <span class="math display">\[
P(X + Y &gt; 95) = 0.124
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>問題 1 で出した分布を、そのまま <code>normCdf</code> に入れます。</p>
<pre><code>normCdf(95, ∞, 80, 13)</code></pre>
<p><strong>入れるのは <span class="math inline">\(13\)</span> で、<span class="math inline">\(169\)</span> ではありません</strong>（<a href="#gdc-normcdf">GDC 第1節</a>）。<span class="math inline">\(169\)</span> を入れると <span class="math inline">\(0.465\)</span> という別の答えになります。</p>
<p><strong>検算。</strong> <span class="math inline">\(95\)</span> は平均 <span class="math inline">\(80\)</span> より上なので、確率は <span class="math inline">\(0.5\)</span> より小さくなるはずです ✓</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">3</span> <span class="q-en">The random variable <span class="math inline">\(X\)</span> is normally distributed with mean <span class="math inline">\(20\)</span> and standard deviation <span class="math inline">\(5\)</span>. A random sample of <span class="math inline">\(16\)</span> observations is taken. Find the probability that the sample mean is greater than <span class="math inline">\(21.5\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>確率変数 <span class="math inline">\(X\)</span> は、平均 <span class="math inline">\(20\)</span>、標準偏差 <span class="math inline">\(5\)</span> の正規分布にしたがいます。<span class="math inline">\(16\)</span> 個の観測値からなる無作為標本をとります。標本平均が <span class="math inline">\(21.5\)</span> より大きい確率を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\bar{X} \sim N\!\left(20,\ \frac{25}{16}\right), \qquad \sigma_{\bar{X}} = \frac{5}{\sqrt{16}} = 1.25
\]</span> <span class="math display">\[
P(\bar{X} &gt; 21.5) = 0.115
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(X\)</span> が normal なので、<span class="math inline">\(n = 16\)</span> でも <span class="math inline">\(\bar{X}\)</span> は <strong>exactly normal</strong> です（<a href="#small-n">第8節</a>）。<span class="math inline">\(n\)</span> の大きさは関係ありません。</p>
<p><span class="math inline">\(\sigma_{\bar{X}} = \dfrac{5}{\sqrt{16}} = \dfrac{5}{4} = 1.25\)</span>。<strong><span class="math inline">\(\dfrac{5}{16}\)</span> ではありません</strong>（<a href="#narrower">第5節</a>）。</p>
<pre><code>normCdf(21.5, ∞, 20, 1.25)</code></pre>
<p><strong><span class="math inline">\(1\)</span> つの <span class="math inline">\(X\)</span> なら</strong> <span class="math inline">\(\sigma = 5\)</span> で、<span class="math inline">\(P(X &gt; 21.5)\)</span> は <span class="math inline">\(0.382\)</span> です。標本平均のほうが、ずっと起こりにくくなっています。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">4</span> <span class="q-en">The mass of an empty box, in kg, is <span class="math inline">\(B \sim N(0.4,\ 0.05^{2})\)</span>. The mass of its contents is <span class="math inline">\(C \sim N(2.5,\ 0.2^{2})\)</span>. The two masses are independent.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the mean and standard deviation of the total mass of a filled box.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the probability that a filled box has a mass greater than <span class="math inline">\(3\)</span> kg.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>空の箱の質量（kg）は <span class="math inline">\(B \sim N(0.4,\ 0.05^{2})\)</span> です。中身の質量は <span class="math inline">\(C \sim N(2.5,\ 0.2^{2})\)</span> です。この <span class="math inline">\(2\)</span> つの質量は独立です。</p>
<p><code>filled box</code> は「中身の入った箱」という意味です。</p>
<p><strong>(a)</strong> 中身の入った箱の合計質量の、平均と標準偏差を求めなさい。</p>
<p><strong>(b)</strong> 中身の入った箱の質量が <span class="math inline">\(3\)</span> kg より大きい確率を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
E(B + C) = 0.4 + 2.5 = 2.9 \text{ kg}
\]</span> <span class="math display">\[
\text{Var}(B + C) = 0.05^{2} + 0.2^{2} = 0.0025 + 0.04 = 0.0425
\]</span> <span class="math display">\[
\sigma = \sqrt{0.0425} = 0.206 \text{ kg}
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
B + C \sim N(2.9,\ 0.0425)
\]</span> <span class="math display">\[
P(B + C &gt; 3) = 0.314
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 小数の <span class="math inline">\(2\)</span> 乗になるので、桁に気をつけてください。<span class="math inline">\(0.05^{2} = 0.0025\)</span> です。<span class="math inline">\(0.025\)</span> ではありません。</p>
<p><span class="math inline">\(0.05 + 0.2 = 0.25\)</span> としてしまうと誤りです（<a href="#sum">第2節</a>）。正しくは <span class="math inline">\(0.206\)</span>。</p>
<p><strong>(b)</strong> <span class="math inline">\(\sigma\)</span> は <span class="math inline">\(\sqrt{0.0425} = 0.20615\ldots\)</span> です。<strong>丸める前の値</strong>を <code>normCdf</code> に入れてください（<a href="#gdc-unrounded">GDC 第2節</a>）。</p>
<pre><code>√(0.0425)  →  ans
normCdf(3, ∞, 2.9, ans)</code></pre>
<p><strong>箱のばらつきは、ほとんど効いていません。</strong> <span class="math inline">\(0.05\)</span> に対して中身が <span class="math inline">\(0.2\)</span> なので、<span class="math inline">\(2\)</span> 乗すると <span class="math inline">\(0.0025\)</span> と <span class="math inline">\(0.04\)</span> で <span class="math inline">\(16\)</span> 倍の差があります。<strong>ばらつきの差は、<span class="math inline">\(2\)</span> 乗すると広がります</strong>——<span class="math inline">\(4\)</span> 倍の差が <span class="math inline">\(16\)</span> 倍の差になります。だから小さいほうは、和の中でほとんど効かなくなります。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">5</span> <span class="q-en">The random variable <span class="math inline">\(X\)</span> is normally distributed with standard deviation <span class="math inline">\(\sigma\)</span>. A random sample of <span class="math inline">\(n\)</span> observations is taken. Explain why the standard deviation of the sample mean is <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span> and not <span class="math inline">\(\dfrac{\sigma}{n}\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>確率変数 <span class="math inline">\(X\)</span> は、標準偏差 <span class="math inline">\(\sigma\)</span> の正規分布にしたがいます。<span class="math inline">\(n\)</span> 個の観測値からなる無作為標本をとります。標本平均の標準偏差が <span class="math inline">\(\dfrac{\sigma}{n}\)</span> ではなく <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span> になる理由を説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\bar{X} = \frac{1}{n}(X_1 + \cdots + X_n)
\]</span> <span class="math display">\[
\text{Var}(X_1 + \cdots + X_n) = n\sigma^{2}
\]</span> <span class="math display">\[
\text{Var}(\bar{X}) = \left(\frac{1}{n}\right)^{2} \times n\sigma^{2} = \frac{\sigma^{2}}{n}
\]</span> <span class="math display">\[
\text{sd}(\bar{X}) = \sqrt{\frac{\sigma^{2}}{n}} = \frac{\sigma}{\sqrt{n}}
\]</span></p>
<p><em>The formula <span class="math inline">\(\text{Var}(aX) = a^{2}\text{Var}(X)\)</span> squares the factor <span class="math inline">\(\frac{1}{n}\)</span>, and the <span class="math inline">\(n\)</span> independent variances add to <span class="math inline">\(n\sigma^{2}\)</span>. Taking the square root at the end gives <span class="math inline">\(\sqrt{n}\)</span> in the denominator, not <span class="math inline">\(n\)</span>.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>Explain why</code> なので、<strong>式を並べて、言葉で締めます。</strong></p>
<p>要点は <span class="math inline">\(2\)</span> つです。</p>
<ul>
<li><span class="math inline">\(\dfrac{1}{n}\)</span> は <strong><span class="math inline">\(2\)</span> 乗されて</strong> <span class="math inline">\(\dfrac{1}{n^{2}}\)</span> になる（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#variance">AHL 4.14</a>）</li>
<li><span class="math inline">\(n\)</span> 個の分散が足されて <span class="math inline">\(n\sigma^{2}\)</span> になる（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#varcomb">AHL 4.14</a>）</li>
</ul>
<p><span class="math inline">\(\dfrac{n\sigma^{2}}{n^{2}} = \dfrac{\sigma^{2}}{n}\)</span> で、<strong><span class="math inline">\(n\)</span> が <span class="math inline">\(1\)</span> つ約分されて残ります。</strong></p>
<p>最後に平方根をとるので、分母は <span class="math inline">\(\sqrt{n}\)</span> です（途中式は「Why it works」を開くと出てきます）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Since <span class="math inline">\(\bar{X} = \frac{1}{n}(X_1 + \cdots + X_n)\)</span> and the observations are independent, the variances add to give <span class="math inline">\(n\sigma^{2}\)</span>. Multiplying by <span class="math inline">\(\frac{1}{n}\)</span> multiplies the variance by <span class="math inline">\(\left(\frac{1}{n}\right)^{2}\)</span>, so <span class="math inline">\(\text{Var}(\bar{X}) = \frac{n\sigma^{2}}{n^{2}} = \frac{\sigma^{2}}{n}\)</span>. The standard deviation is the square root of this, which is <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">6</span> <span class="q-en">The number of minutes a train is late has mean <span class="math inline">\(8.4\)</span> and standard deviation <span class="math inline">\(3.6\)</span>. The distribution is not normal. A random sample of <span class="math inline">\(50\)</span> journeys is taken.</span></p>
<p><strong>(a)</strong> <span class="q-en">State, with a reason, why the mean delay for these <span class="math inline">\(50\)</span> journeys can be treated as normally distributed.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find the probability that the mean delay for the <span class="math inline">\(50\)</span> journeys is less than <span class="math inline">\(8\)</span> minutes.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある列車の遅れ（分）は、平均 <span class="math inline">\(8.4\)</span>、標準偏差 <span class="math inline">\(3.6\)</span> です。この分布は正規分布ではありません。<span class="math inline">\(50\)</span> 回の運行からなる無作為標本をとります。</p>
<p><code>journey</code> は「運行」、<code>delay</code> は「遅れ」という意味です。</p>
<p><strong>(a)</strong> この <span class="math inline">\(50\)</span> 回の平均の遅れが正規分布として扱える理由を、根拠を示して述べなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(50\)</span> 回の平均の遅れが <span class="math inline">\(8\)</span> 分未満である確率を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em><span class="math inline">\(n = 50 &gt; 30\)</span>, so by the central limit theorem the mean delay <span class="math inline">\(\bar{X}\)</span> is approximately normally distributed, even though the distribution of individual delays is not normal.</em></p>
<p><strong>(b)</strong> <span class="math display">\[
\bar{X} \sim N\!\left(8.4,\ \frac{3.6^{2}}{50}\right) = N(8.4,\ 0.2592), \qquad \sigma_{\bar{X}} = 0.509
\]</span> <span class="math display">\[
P(\bar{X} &lt; 8) = 0.216
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <code>with a reason</code> なので、<strong><span class="math inline">\(n &gt; 30\)</span> を必ず書いてください。</strong> 「中心極限定理より」だけでは、根拠になりません。</p>
<p><code>approximately</code> も忘れずに（<a href="#n30">第6節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The sample size <span class="math inline">\(n = 50\)</span> is greater than <span class="math inline">\(30\)</span>, so by the central limit theorem <span class="math inline">\(\bar{X}\)</span> is approximately normally distributed, even though the distribution of individual delays is not normal.</em></p>
</div>
<p><strong>(b)</strong> <span class="math inline">\(\text{Var}(\bar{X}) = \dfrac{3.6^{2}}{50} = \dfrac{12.96}{50} = 0.2592\)</span>。<span class="math inline">\(\sigma_{\bar{X}} = 0.50911\ldots\)</span></p>
<pre><code>√(3.6^2/50)  →  ans
normCdf(-∞, 8, 8.4, ans)</code></pre>
<p><strong>もとの分布が正規でなくても、平均と標準偏差はそのまま使えます。</strong> CLT が保証してくれるのは<strong>形</strong>だけで、平均と分散は <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html">AHL 4.14</a> のとおりです。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">7</span> <span class="q-en">For each of the following, state whether the quantity can be treated as normally distributed, and give a reason.</span></p>
<p><strong>(a)</strong> <span class="q-en">The sum of <span class="math inline">\(3\)</span> independent observations from a normal distribution.</span></p>
<p><strong>(b)</strong> <span class="q-en">The mean of <span class="math inline">\(8\)</span> independent observations from a distribution that is strongly skewed.</span></p>
<p><strong>(c)</strong> <span class="q-en">The mean of <span class="math inline">\(60\)</span> independent observations from a distribution that is strongly skewed.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>次のそれぞれについて、正規分布として扱えるかどうかを述べ、理由を書きなさい。</p>
<p><strong>(a)</strong> 正規分布からの、独立な <span class="math inline">\(3\)</span> 個の観測値の合計。</p>
<p><strong>(b)</strong> 大きく歪んだ分布からの、独立な <span class="math inline">\(8\)</span> 個の観測値の平均。</p>
<p><strong>(c)</strong> 大きく歪んだ分布からの、独立な <span class="math inline">\(60\)</span> 個の観測値の平均。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Yes. A linear combination of independent normal variables is itself normal, whatever the sample size, so the sum of <span class="math inline">\(3\)</span> observations is exactly normal.</em></p>
<p><strong>(b)</strong> <em>No.&nbsp;The distribution is strongly skewed and <span class="math inline">\(n = 8\)</span> is not greater than <span class="math inline">\(30\)</span>, so a normal approximation for the mean cannot be justified.</em></p>
<p><strong>(c)</strong> <em>Yes, approximately. Although the underlying distribution is not normal, <span class="math inline">\(n = 60 &gt; 30\)</span>, so by the central limit theorem the mean is approximately normally distributed.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><a href="#when">第8節の表</a>が、そのまま答えになる問題です。</p>
<p><strong>(a)</strong> もとが normal なら、<span class="math inline">\(n\)</span> は関係ありません（<a href="#small-n">第8節</a>）。<span class="math inline">\(3\)</span> 個でも <span class="math inline">\(100\)</span> 個でも normal です。しかも approximately ではなく <strong>exactly normal</strong> です。</p>
<p><strong>(b)</strong> もとが normal でなく、<span class="math inline">\(n\)</span> も小さい。<strong>normal approximation（正規近似）を正当化できません</strong>（<a href="#flow">第8節</a>）。</p>
<p><strong>(c)</strong> もとは normal でないので、CLT に頼ります。<span class="math inline">\(60 &gt; 30\)</span> なので使えます。ただし <strong>approximately normal</strong> です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>(a) Yes — a linear combination of independent normal variables is normal for any <span class="math inline">\(n\)</span>.</em></p>
<p><em>(b) No — the distribution is strongly skewed and <span class="math inline">\(n = 8\)</span> is not greater than <span class="math inline">\(30\)</span>, so a normal approximation for the mean cannot be justified.</em></p>
<p><em>(c) Yes, approximately — the distribution is not normal, but <span class="math inline">\(n = 60 &gt; 30\)</span>, so the central limit theorem applies to the mean.</em></p>
</div>
<p><strong>(a) と (c) で、<code>exactly</code> と <code>approximately</code> を書き分けている</strong>ところを見てください。ここが読まれます（<a href="#when">第8節</a>）。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">8</span> <span class="q-en">The random variable <span class="math inline">\(X\)</span> is normally distributed with mean <span class="math inline">\(10\)</span> and standard deviation <span class="math inline">\(2\)</span>. Let <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_3\)</span> be independent observations of <span class="math inline">\(X\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find <span class="math inline">\(P(3X &gt; 36)\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find <span class="math inline">\(P(X_1 + X_2 + X_3 &gt; 36)\)</span>.</span></p>
<p><strong>(c)</strong> <span class="q-en">Comment on the difference between your two answers.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>確率変数 <span class="math inline">\(X\)</span> は、平均 <span class="math inline">\(10\)</span>、標準偏差 <span class="math inline">\(2\)</span> の正規分布にしたがいます。<span class="math inline">\(X_1\)</span>、<span class="math inline">\(X_2\)</span>、<span class="math inline">\(X_3\)</span> を <span class="math inline">\(X\)</span> の独立な観測値とします。</p>
<p><strong>(a)</strong> <span class="math inline">\(P(3X &gt; 36)\)</span> を求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(P(X_1 + X_2 + X_3 &gt; 36)\)</span> を求めなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(2\)</span> つの答えの違いについて述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
3X \sim N(30,\ 3^{2} \times 4) = N(30,\ 36), \qquad \sigma = 6
\]</span> <span class="math display">\[
P(3X &gt; 36) = 0.159
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
X_1 + X_2 + X_3 \sim N(30,\ 3 \times 4) = N(30,\ 12), \qquad \sigma = 3.46
\]</span> <span class="math display">\[
P(X_1 + X_2 + X_3 &gt; 36) = 0.0416
\]</span></p>
<p><strong>(c)</strong> <em>Both have mean <span class="math inline">\(30\)</span>, but the sum of three separate observations has the smaller variance (<span class="math inline">\(12\)</span> against <span class="math inline">\(36\)</span>), because a high observation can be offset by a low one. Tripling a single observation triples its deviation from the mean, so <span class="math inline">\(3X\)</span> is much more likely to exceed <span class="math inline">\(36\)</span>.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#two-x">AHL 4.14</a> の <span class="math inline">\(2X\)</span> と <span class="math inline">\(X_1+X_2\)</span> を、<strong>確率まで出すところ</strong>まで進めた問題です。</p>
<p><strong>平均はどちらも <span class="math inline">\(30\)</span></strong> です。それでも確率は <span class="math inline">\(0.159\)</span> と <span class="math inline">\(0.0416\)</span> で、<strong><span class="math inline">\(3\)</span> 倍以上違います。</strong></p>
<p><strong>(a)</strong> <span class="math inline">\(\text{Var}(3X) = 3^{2} \times 4 = 36\)</span>。<span class="math inline">\(\sigma = 6\)</span>。</p>
<p><strong>(b)</strong> <span class="math inline">\(\text{Var}(X_1+X_2+X_3) = 4+4+4 = 12\)</span>。<span class="math inline">\(\sigma = \sqrt{12} = 3.4641\ldots\)</span></p>
<p><strong>(c)</strong> <code>Comment on</code> なので、<strong>数を文脈に戻して</strong>書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Both variables have mean <span class="math inline">\(30\)</span>, but <span class="math inline">\(3X\)</span> has standard deviation <span class="math inline">\(6\)</span> while the sum has standard deviation <span class="math inline">\(3.46\)</span>. With three separate observations a high value can be balanced by a low one, so the total stays closer to <span class="math inline">\(30\)</span>. With <span class="math inline">\(3X\)</span> there is only one observation, and its deviation from the mean is tripled, so values far from <span class="math inline">\(30\)</span> are much more likely.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">9</span> <span class="q-en">The mass of a component, in grams, is normally distributed with mean <span class="math inline">\(500\)</span> and standard deviation <span class="math inline">\(20\)</span>. A random sample of <span class="math inline">\(25\)</span> components is taken. Find the value of <span class="math inline">\(k\)</span> such that <span class="math inline">\(P(\bar{X} &gt; k) = 0.05\)</span>.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある部品の質量（グラム）は、平均 <span class="math inline">\(500\)</span>、標準偏差 <span class="math inline">\(20\)</span> の正規分布にしたがいます。<span class="math inline">\(25\)</span> 個の部品からなる無作為標本をとります。<span class="math inline">\(P(\bar{X} &gt; k) = 0.05\)</span> となる <span class="math inline">\(k\)</span> の値を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\bar{X} \sim N\!\left(500,\ \frac{400}{25}\right) = N(500,\ 16), \qquad \sigma_{\bar{X}} = 4
\]</span> <span class="math display">\[
k = 507 \text{ g}
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>まず <span class="math inline">\(\bar{X}\)</span> の分布を出します。<span class="math inline">\(\sigma_{\bar{X}} = \dfrac{20}{\sqrt{25}} = \dfrac{20}{5} = 4\)</span>。</p>
<p>次に <code>Inverse Normal</code> です。求めたいのは「<strong>上側</strong>の面積が <span class="math inline">\(0.05\)</span> になる <span class="math inline">\(k\)</span>」ですが、<strong>電卓に入れるのは左からの面積</strong>です（<a href="#gdc-invnorm">GDC 第4節</a>）。ですから <span class="math inline">\(0.05\)</span> ではなく</p>
<p><span class="math display">\[
1 - 0.05 = 0.95
\]</span></p>
<p>を入れます。<span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> の欄には、<span class="math inline">\(1\)</span> 行目で出した <span class="math inline">\(\bar{X}\)</span> の値（<span class="math inline">\(500\)</span> と <span class="math inline">\(4\)</span>）を入れます。<strong>もとの <span class="math inline">\(\sigma = 20\)</span> ではありません。</strong></p>
<pre><code>invNorm(0.95, 500, 4)</code></pre>
<p><span class="math display">\[
k = 506.579\ldots \approx 507 \text{ g}
\]</span></p>
<p><strong>検算。</strong> <span class="math inline">\(k\)</span> は平均 <span class="math inline">\(500\)</span> より<strong>上</strong>にあるはずです ✓ <span class="math inline">\(0.05\)</span> をそのまま入れると <span class="math inline">\(493\)</span> が返り、平均より下になるので、そこで気づけます。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">10</span> <span class="q-en">The mass of an adult, in kg, is normally distributed with mean <span class="math inline">\(72\)</span> and standard deviation <span class="math inline">\(10\)</span>. A lift has a maximum load of <span class="math inline">\(620\)</span> kg.</span></p>
<p><strong>(a)</strong> <span class="q-en">Eight adults enter the lift. Find the probability that their total mass exceeds the maximum load.</span></p>
<p><strong>(b)</strong> <span class="q-en">A student calculates the answer as <span class="math inline">\(P(8X &gt; 620)\)</span>, where <span class="math inline">\(X \sim N(72,\ 10^{2})\)</span>. Explain why this is not correct.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある大人の体重（kg）は、平均 <span class="math inline">\(72\)</span>、標準偏差 <span class="math inline">\(10\)</span> の正規分布にしたがいます。あるエレベーターの最大積載量は <span class="math inline">\(620\)</span> kg です。</p>
<p><code>lift</code> は「エレベーター」、<code>maximum load</code> は「最大積載量」という意味です。</p>
<p><strong>(a)</strong> <span class="math inline">\(8\)</span> 人の大人がエレベーターに乗ります。合計体重が最大積載量を超える確率を求めなさい。</p>
<p><strong>(b)</strong> ある生徒が、<span class="math inline">\(X \sim N(72,\ 10^{2})\)</span> として答えを <span class="math inline">\(P(8X &gt; 620)\)</span> で計算しました。これが正しくない理由を説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
X_1 + \cdots + X_8 \sim N(8 \times 72,\ 8 \times 100) = N(576,\ 800)
\]</span> <span class="math display">\[
\sigma = \sqrt{800} = 28.3
\]</span> <span class="math display">\[
P(\text{total} &gt; 620) = 0.0599
\]</span></p>
<p><strong>(b)</strong> <em><span class="math inline">\(8X\)</span> represents one adult whose mass is multiplied by <span class="math inline">\(8\)</span>, not eight different adults. It gives <span class="math inline">\(\text{Var}(8X) = 8^{2} \times 100 = 6400\)</span> and <span class="math inline">\(\sigma = 80\)</span>, whereas eight independent adults give <span class="math inline">\(\text{Var} = 8 \times 100 = 800\)</span> and <span class="math inline">\(\sigma = 28.3\)</span>. With eight separate adults a heavy person can be offset by a lighter one, so the total varies much less.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(8\)</span> 人<strong>別々</strong>なので、合計です。</p>
<p><span class="math display">\[
E = 8 \times 72 = 576, \qquad \text{Var} = 8 \times 100 = 800
\]</span></p>
<p><span class="math inline">\(\sigma = \sqrt{800} = 28.284\ldots\)</span></p>
<pre><code>√800  →  ans
normCdf(620, ∞, 576, ans)</code></pre>
<p><span class="math display">\[
P = 0.0599
\]</span></p>
<p><strong>約 <span class="math inline">\(6\%\)</span></strong> です。<span class="math inline">\(8\)</span> 人が乗るたびに、<span class="math inline">\(100\)</span> 回に <span class="math inline">\(6\)</span> 回ほど積載量を超えることになります。</p>
<p><strong>(b)</strong> <code>Explain why</code> なので、<strong>何が違うのかと、結果がどう変わるか</strong>の両方を書きます。</p>
<p><span class="math inline">\(8X\)</span> は「<span class="math inline">\(1\)</span> 人の体重を <span class="math inline">\(8\)</span> 倍したもの」で、<span class="math inline">\(\text{Var} = 64 \times 100 = 6400\)</span>、<span class="math inline">\(\sigma = 80\)</span> になります。正しい <span class="math inline">\(28.3\)</span> の<strong><span class="math inline">\(3\)</span> 倍近く</strong>です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(8X\)</span> models a single adult whose mass is multiplied by <span class="math inline">\(8\)</span>, not eight different adults. Its variance is <span class="math inline">\(8^{2} \times 100 = 6400\)</span>, giving <span class="math inline">\(\sigma = 80\)</span>, whereas eight independent adults give <span class="math inline">\(\text{Var} = 8 \times 100 = 800\)</span> and <span class="math inline">\(\sigma = 28.3\)</span>. Because the eight adults are separate, a heavy person can be offset by a lighter one, so the total mass is much less variable than <span class="math inline">\(8X\)</span> suggests.</em></p>
</div>
<p><strong><span class="math inline">\(2X\)</span> と <span class="math inline">\(X_1+X_2\)</span> の区別</strong>（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#two-x">AHL 4.14</a>）が、そのまま現実の場面に出てくる問題です。</p>
</div>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<!--
  Cookie 同意バナーの本文を差しかえるスクリプト。

  Quarto の cookie-consent は termsfeed のライブラリを使っていて、
  lang: ja のおかげで表示は日本語になります。ただし既定の本文が

    「…パーソナライズされたコンテンツやターゲット広告を表示するため…」

  となっていて、広告を出さないこのサイトの実態と合いません。
  ライブラリ側に文面を差しかえる設定が無いので、バナーが出たあとに
  #cc-nb-text の中身だけを書きかえています。

  ★ 文面を変えるときは、下の NB の中身だけを直してください。
  ★ 読み込みは _quarto.yml の format.html.include-after-body です。
-->
<script>
(function () {
  var NB = "このサイトでは、どのページがどれくらい読まれているかを知るために、"
         + "Google アナリティクスの Cookie を使っています。"
         + "広告の配信や、個人を特定する目的には使いません。";

  function fix() {
    var el = document.getElementById("cc-nb-text");
    if (!el) { return false; }
    if (el.textContent !== NB) { el.textContent = NB; }
    return true;
  }

  // バナーはページ読み込みのあとに差し込まれるので、出てくるまで待つ。
  if (!fix()) {
    var mo = new MutationObserver(function () { if (fix()) { mo.disconnect(); } });
    mo.observe(document.body, { childList: true, subtree: true });
    setTimeout(function () { mo.disconnect(); }, 10000);
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "コピーしました");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "コピーしました");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/edusalonself\.github\.io\/ib-math-ai-sl-jp\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" class="pagination-link" aria-label="AHL 4.14 — Linear transformation of a single random variable">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">AHL 4.14 — Linear transformation of a single random variable</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html" class="pagination-link" aria-label="AHL 4.16 — Confidence intervals for the mean of a normal population">
        <span class="nav-page-text">AHL 4.16 — Confidence intervals for the mean of a normal population</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 学習サロン SELF</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/">
<p>学習サロン SELF</p>
</a>
  </li>  
</ul>
    <div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie の設定</a></div></div>
    <div class="nav-footer-right">
<p>IB（国際バカロレア機構）とは関係のない独立した教材です</p>
</div>
  </div>
</footer>




</body></html>