<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ahl-4-16 – 日本語で読む IB数学</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../ai-hl/04-statistics-and-probability/ahl-4-17.html" rel="next">
<link href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3d27ed94b0b15b9bda3c32201c09d63a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "一致なし",
    "search-matching-documents-text": "一致した文書",
    "search-copy-link-title": "検索へのリンクをコピー",
    "search-hide-matches-text": "追加の検索結果を非表示",
    "search-more-match-text": "追加の検索結果",
    "search-more-matches-text": "追加の検索結果",
    "search-clear-button-title": "消去",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "検索",
    "search-label": "サーチ"
  }
}</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"ja"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">日本語で読む IB数学</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="サーチ"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="ナビゲーションを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../ai-sl/index.html"> 
<span class="menu-text">AI SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../glossary-ai.html"> 
<span class="menu-text">英日対訳表（AI）</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../ai-hl/index.html" aria-current="page"> 
<span class="menu-text">AI HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-sl/index.html"> 
<span class="menu-text">AA SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-hl/index.html"> 
<span class="menu-text">AA HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../which-course.html"> 
<span class="menu-text">AI と AA、どちらを取るか</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/"> 
<span class="menu-text">学習サロン SELF</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html">AHL 4.16 — Confidence intervals for the mean of a normal population</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IB数学 AI HL</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 1 — Number and algebra</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.9 — Laws of logarithms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.14 — Matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.15 — Eigenvalues and eigenvectors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 3 — Geometry and trigonometry</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.9 — Geometric transformations in two dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.14 — Graph theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.15 — Adjacency matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.16 — Tree and cycle algorithms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Topic 4 — Statistics and probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.12 — Data collection and χ² categorisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.13 — Non-linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.14 — Linear transformation of a single random variable</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.15 — Linear combinations of normal variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">AHL 4.16 — Confidence intervals for the mean of a normal population</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.17 — The Poisson distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18a — Critical values and critical regions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18b — Tests for a mean, a proportion and ρ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18c — Type I and Type II errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.19 — Transition matrices</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 5 — Calculus</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.14 — Setting up a differential equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.15 — Slope fields</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16a — Euler’s method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16b — Euler’s method for coupled systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17a — Phase portraits: real eigenvalues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17b — Phase portraits: complex eigenvalues</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">このページの内容</h2>
   
  <ul>
  <li><a href="#sec-ahl-4-16" id="toc-sec-ahl-4-16" class="nav-link active" data-scroll-target="#sec-ahl-4-16">AHL 4.16 — Confidence intervals for the mean of a normal population（正規母集団の平均の信頼区間）</a>
  <ul class="collapse">
  <li><a href="#the-idea" id="toc-the-idea" class="nav-link" data-scroll-target="#the-idea">The idea</a>
  <ul class="collapse">
  <li><a href="#idea" id="toc-idea" class="nav-link" data-scroll-target="#idea">1. <span class="math inline">\(1\)</span> つの数では、確からしさが言えません</a></li>
  <li><a href="#meaning" id="toc-meaning" class="nav-link" data-scroll-target="#meaning">2. 「<span class="math inline">\(95\%\)</span> の信頼区間」とは何か</a></li>
  <li><a href="#form" id="toc-form" class="nav-link" data-scroll-target="#form">3. 区間は、いつも「<span class="math inline">\(\bar{x}\)</span> <span class="math inline">\(\pm\)</span> margin of error」の形です</a></li>
  <li><a href="#assumption" id="toc-assumption" class="nav-link" data-scroll-target="#assumption">4. 母集団が normally distributed であることを確かめます</a></li>
  <li><a href="#which" id="toc-which" class="nav-link" data-scroll-target="#which">5. 計算の前に、<span class="math inline">\(\sigma\)</span> が分かっているか確認する</a></li>
  <li><a href="#t-dist" id="toc-t-dist" class="nav-link" data-scroll-target="#t-dist">6. なぜ <span class="math inline">\(t\)</span>-distribution を使うのか</a></li>
  <li><a href="#width" id="toc-width" class="nav-link" data-scroll-target="#width">7. 区間の幅を決める <span class="math inline">\(3\)</span> つ</a></li>
  <li><a href="#interpret" id="toc-interpret" class="nav-link" data-scroll-target="#interpret">8. 文脈の言葉で書く</a></li>
  <li><a href="#compare" id="toc-compare" class="nav-link" data-scroll-target="#compare">9. 区間が重なっているときに言えること</a></li>
  </ul></li>
  <li><a href="#why-it-works" id="toc-why-it-works" class="nav-link" data-scroll-target="#why-it-works">Why it works</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples">Worked examples</a></li>
  <li><a href="#common-errors" id="toc-common-errors" class="nav-link" data-scroll-target="#common-errors">Common errors</a></li>
  <li><a href="#using-your-gdc-ti-nspire-cx-ii" id="toc-using-your-gdc-ti-nspire-cx-ii" class="nav-link" data-scroll-target="#using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</a>
  <ul class="collapse">
  <li><a href="#gdc-z" id="toc-gdc-z" class="nav-link" data-scroll-target="#gdc-z">1. z Interval — <span class="math inline">\(\sigma\)</span> が分かっているとき</a></li>
  <li><a href="#gdc-t" id="toc-gdc-t" class="nav-link" data-scroll-target="#gdc-t">2. t Interval — <span class="math inline">\(\sigma\)</span> が分からないとき</a></li>
  <li><a href="#gdc-read" id="toc-gdc-read" class="nav-link" data-scroll-target="#gdc-read">3. 結果の読み方</a></li>
  <li><a href="#gdc-check" id="toc-gdc-check" class="nav-link" data-scroll-target="#gdc-check">4. 検算のしかた</a></li>
  <li><a href="#selfcheck" id="toc-selfcheck" class="nav-link" data-scroll-target="#selfcheck">Exercises の前に — セルフチェック</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html">AHL 4.16 — Confidence intervals for the mean of a normal population</a></li></ol></nav></header>




<section id="sec-ahl-4-16" class="level1">
<h1>AHL 4.16 — Confidence intervals for the mean of a normal population（正規母集団の平均の信頼区間）</h1>
<p>標本平均 <span class="math inline">\(\bar{x}\)</span> は、標本を取り直すたびに少しずつ変わります。ですから、<span class="math inline">\(\bar{x}\)</span> だけを使って <strong>population mean</strong>（母平均）<span class="math inline">\(\mu\)</span> をぴったり当てることはできません。このページでは、<span class="math inline">\(\mu\)</span> が入りそうな範囲を <strong>confidence interval</strong>（信頼区間）として求めます。</p>
<p>読む順番は、こうです。</p>
<ol type="1">
<li>なぜ <span class="math inline">\(1\)</span> つの推定値だけでは足りないのか（<a href="#idea">第1節</a>）</li>
<li><span class="math inline">\(95\%\)</span> confidence interval の意味（<a href="#meaning">第2節</a>）</li>
<li>区間の形と、幅を決めるもの（<a href="#form">第3節</a>・<a href="#width">第7節</a>）</li>
<li><span class="math inline">\(z\)</span>-interval と <span class="math inline">\(t\)</span>-interval の使い分け（<a href="#which">第5節</a>）</li>
<li>文脈に合わせた答え方（<a href="#interpret">第8節</a>）</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>What you should be able to do
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>confidence interval</strong>（信頼区間）が何を表しているかを、正しい言い方で説明できる。</li>
<li><strong><span class="math inline">\(\sigma\)</span> が分かっているときは normal distribution、分からないときは <span class="math inline">\(t\)</span>-distribution（<span class="math inline">\(t\)</span> 分布）</strong>を使う、と判断できる。</li>
<li>電卓の <code>z Interval</code> と <code>t Interval</code> に、データからでも統計量からでも入力でき、<strong>母集団が normal であること</strong>が前提だと言える。</li>
<li>区間の<strong>幅を決める <span class="math inline">\(3\)</span> つ</strong>（confidence level・<span class="math inline">\(n\)</span>・ばらつき）を言える。</li>
<li>求めた区間を、<strong>問題の文脈の言葉で</strong>解釈して書ける。</li>
<li><span class="math inline">\(2\)</span> つの区間が<strong>重なっているとき</strong>、何が言えて何が言えないかを述べられる。</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>AHL 4.15 で学んだこと／このページで新しく学ぶこと
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html#xbar">AHL 4.15</a> で学んだのは、<strong><span class="math inline">\(\mu\)</span> が分かっているとき、標本平均 <span class="math inline">\(\bar{X}\)</span> がどのように変動するか</strong>でした。</p>
<p><span class="math display">\[
\bar{X} \sim N\!\left(\mu,\ \frac{\sigma^{2}}{n}\right)
\]</span></p>
<p><strong>このページで新しく学ぶのは、その反対向きの読み方です。</strong> 現実には、分からないのは <span class="math inline">\(\mu\)</span> のほうです。分かるのは、実際にとった標本から計算した <span class="math inline">\(\bar{x}\)</span> だけです。そこで</p>
<blockquote class="blockquote">
<p><strong><span class="math inline">\(\mu\)</span> は、だいたいどのあたりにあると言えそうか。</strong></p>
</blockquote>
<p>を答えます。「標本平均は母平均の近くに出やすい」という AHL 4.15 の性質を逆に使い、<strong><span class="math inline">\(\bar{x}\)</span> のまわりに <span class="math inline">\(\mu\)</span> の候補となる範囲を作る</strong>——これが confidence interval です。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><span class="math inline">\(\bar{X}\)</span> と <span class="math inline">\(\bar{x}\)</span> は、別のものです。</strong> <span class="math inline">\(\bar{X}\)</span> は標本を取る前の「変化する標本平均」を表し、<span class="math inline">\(\bar{x}\)</span> は実際の標本から得られた <span class="math inline">\(1\)</span> つの数値を表します。このページでは、<span class="math inline">\(48.6\)</span> のような<strong>得られた数値</strong>が <span class="math inline">\(\bar{x}\)</span> です。</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>AHL 4.16 専用の新しい公式はありません
</div>
</div>
<div class="callout-body-container callout-body">
<p>AI HL の公式集は <strong>4.14 の次が 4.17</strong> で、4.16 の欄は印刷されていません。使うのは、AHL 4.14 と 4.15 で学んだ <strong>standard error</strong>（標準誤差）と、normal distribution・<span class="math inline">\(t\)</span>-distribution の組み合わせです。</p>
<p>試験では、区間そのものは主に GDC で計算します（<code>z Interval</code> と <code>t Interval</code> の <span class="math inline">\(2\)</span> つがあり、使い分けは<a href="#which">第5節</a>で説明します）。<strong>点になるのは、どちらを使うかを決めることと、出てきた区間を文脈に合わせて説明することです。</strong></p>
<p>シラバスも、そこを名指ししています。</p>
<blockquote class="blockquote">
<p>Students should be able to <strong>interpret the meaning of their results in context.</strong></p>
</blockquote>
</div>
</div>
<section id="the-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-idea">The idea</h2>
<section id="idea" class="level3">
<h3 class="anchored" data-anchor-id="idea">1. <span class="math inline">\(1\)</span> つの数では、確からしさが言えません</h3>
<p>ある工場のチョコレートの重さを調べるとします。<span class="math inline">\(20\)</span> 枚を量って、平均が <span class="math inline">\(48.6\)</span> g でした。</p>
<p><strong>では、<span class="math inline">\(\mu\)</span> は <span class="math inline">\(48.6\)</span> g なのでしょうか。</strong> そうとはかぎりません。別の <span class="math inline">\(20\)</span> 枚を量れば、<span class="math inline">\(48.2\)</span> g かもしれないし <span class="math inline">\(49.1\)</span> g かもしれません（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html#xbar">AHL 4.15</a>）。</p>
<p><span class="math inline">\(\bar{x} = 48.6\)</span> という <strong><span class="math inline">\(1\)</span> つの数</strong>だけでは、<strong>それがどれくらい当てになるのか</strong>が分かりません。そこで、<span class="math inline">\(\mu\)</span> の推定のしかたを <span class="math inline">\(2\)</span> つ並べて考えます。</p>
<ul>
<li><strong>point estimate</strong>（点推定値）… <span class="math inline">\(\mu\)</span> を <span class="math inline">\(1\)</span> つの数 <span class="math inline">\(\bar{x}\)</span> で推定する</li>
<li><strong>interval estimate</strong>（区間推定）… <span class="math inline">\(\mu\)</span> が入りそうな<strong>範囲</strong>で推定する</li>
</ul>
<p>このページで作るのは、<span class="math inline">\(2\)</span> つ目のほうです。形は、いつもこうなります。</p>
<p><span id="eq-ahl416-form"><span class="math display">\[
\text{confidence interval} = \text{point estimate} \ \pm \ \text{margin of error}
\tag{1}\]</span></span></p>
<p><strong>margin of error</strong>（誤差の幅）は、点推定値の左右にとる幅のことです。これが <strong>confidence interval</strong>（信頼区間）で、<span class="math inline">\(47.5 &lt; \mu &lt; 49.7\)</span> のような形で答えます。</p>
<p>この <span class="math inline">\(2\)</span> つの書き方が<strong>同じ区間</strong>であることは、計算で確かめられます。</p>
<p><span class="math display">\[
\text{中心} = \frac{47.5 + 49.7}{2} = 48.6, \qquad \text{margin of error} = 49.7 - 48.6 = 1.1
\]</span></p>
<p>ですから <span class="math inline">\(47.5 &lt; \mu &lt; 49.7\)</span> は、<span class="math inline">\(48.6 \pm 1.1\)</span> と<strong>同じ区間</strong>です。</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>区間には、必ず <span class="math inline">\(2\)</span> つの情報が入っています
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\((47.5,\ 49.7)\)</span> という区間は、<strong><span class="math inline">\(2\)</span> つのこと</strong>を同時に言っています。</p>
<ul>
<li><strong>どこか</strong> … 中心が <span class="math inline">\(48.6\)</span>。これは <span class="math inline">\(\bar{x}\)</span> そのもの、つまり point estimate です</li>
<li><strong>どれくらい確かか</strong> … margin of error が <span class="math inline">\(1.1\)</span>（幅は <span class="math inline">\(2.2\)</span>）。<strong>同じ confidence level で比べたとき</strong>、狭いほどはっきりしたことが言えています</li>
</ul>
<p>「平均は <span class="math inline">\(48.6\)</span> g です」だけでは、<span class="math inline">\(2\)</span> つ目が抜けます。<strong>幅があること</strong>が、point estimate との違いです。</p>
</div>
</div>
</section>
<section id="meaning" class="level3">
<h3 class="anchored" data-anchor-id="meaning">2. 「<span class="math inline">\(95\%\)</span> の信頼区間」とは何か</h3>
<p><strong>答案でいちばん問われるのは、この意味のほうです。</strong> まず、言葉で押さえてください。</p>
<blockquote class="blockquote">
<p><span class="math inline">\(95\%\)</span> confidence interval は、<strong>「同じ方法で標本を取り、同じ方法で区間を作ることを何度もくり返すと、長期的には約 <span class="math inline">\(95\%\)</span> の区間が真の母平均 <span class="math inline">\(\mu\)</span> を含む」</strong>という意味です。</p>
</blockquote>
<p>図で見ると、こうなります。</p>
<div id="fig-ahl416-meaning" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl416-meaning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-16-meaning.svg" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl416-meaning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;1: What a 95% confidence interval means
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl416-meaning" class="quarto-xref">図&nbsp;1</a> は、<span class="math inline">\(\mu = 50\)</span> の母集団から <span class="math inline">\(12\)</span> 個ずつの標本を <strong><span class="math inline">\(100\)</span> 回</strong>とって、そのたびに <span class="math inline">\(95\%\)</span> 区間を作ったものです。次の順に見てください。</p>
<ol type="1">
<li><strong>横線 <span class="math inline">\(1\)</span> 本が、<span class="math inline">\(1\)</span> 回の標本から作った信頼区間</strong>です</li>
<li>標本が変わるので、<strong>区間の中心も両端も、毎回変わります</strong></li>
<li><strong>オレンジ色の縦線</strong>が、動かない真の母平均 <span class="math inline">\(\mu = 50\)</span> です</li>
<li><strong>青い区間は <span class="math inline">\(\mu\)</span> を含み、赤い区間は含んでいません</strong></li>
<li><span class="math inline">\(100\)</span> 本すべてが含むのではなく、<strong>長期的に約 <span class="math inline">\(95\%\)</span> が含みます</strong></li>
</ol>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>「<span class="math inline">\(100\)</span> 回やれば、ちょうど <span class="math inline">\(95\)</span> 回成功する」ではありません
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(95\%\)</span> は<strong>長期的な割合</strong>です。<span class="math inline">\(100\)</span> 回作ったときに <span class="math inline">\(\mu\)</span> を含む本数は、<span class="math inline">\(93\)</span> 本のことも <span class="math inline">\(97\)</span> 本のこともあります。</p>
<p><a href="#fig-ahl416-meaning" class="quarto-xref">図&nbsp;1</a> はその一例で、たまたま <span class="math inline">\(95\)</span> 本が含んでいます。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>「<span class="math inline">\(\mu\)</span> がこの区間に入る確率が <span class="math inline">\(95\%\)</span>」という言い方には、注意が要ります
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>区間を計算した後は、<span class="math inline">\(\mu\)</span> は動かず、区間もすでに決まっています。</strong>「変わる」のは、標本を取り直したときに作られる区間のほうです。</p>
<p>ですから、いま手元にある <span class="math inline">\(1\)</span> つの区間は、<span class="math inline">\(\mu\)</span> を<strong>含んでいるか、含んでいないか</strong>のどちらかです。<a href="#fig-ahl416-meaning" class="quarto-xref">図&nbsp;1</a> の赤い区間は、はじめから外しています。<span class="math inline">\(95\%\)</span> は、その<strong>作り方の成績</strong>を表しています。</p>
<p><strong>答案では、この違いに深入りする必要はありません。</strong> 次の型で書けば、この論点に触れずに済みます（<a href="#interpret">第8節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>We are <span class="math inline">\(95\%\)</span> confident that the population mean mass of a chocolate bar lies between <span class="math inline">\(47.5\)</span> g and <span class="math inline">\(49.7\)</span> g.</em></p>
</div>
<p>（チョコレートバーの母平均質量は <span class="math inline">\(47.5\)</span> g から <span class="math inline">\(49.7\)</span> g のあいだにあると、<span class="math inline">\(95\%\)</span> の信頼度で推定できる、という意味です。）</p>
<p><strong><code>We are 95% confident that ...</code></strong> という書き出しが、そのまま使えます。</p>
</div>
</div>
</section>
<section id="form" class="level3">
<h3 class="anchored" data-anchor-id="form">3. 区間は、いつも「<span class="math inline">\(\bar{x}\)</span> <span class="math inline">\(\pm\)</span> margin of error」の形です</h3>
<p>confidence interval は、<strong>分からない population mean（母平均）<span class="math inline">\(\mu\)</span> を、手元の sample mean（標本平均）<span class="math inline">\(\bar{x}\)</span> から推定する範囲</strong>です。<span class="math inline">\(\bar{x}\)</span> を中心にして、その左右に margin of error を足し引きして作ります。</p>
<p><span id="eq-ahl416-ci"><span class="math display">\[
\bar{x} \ \pm \ (\text{critical value}) \times (\text{standard error})
\tag{2}\]</span></span></p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> … 区間の中心となる <strong>sample mean</strong>（標本平均）</li>
<li><strong>critical value</strong>（臨界値）… <strong>confidence level</strong>（信頼水準）に合わせて、standard error <strong>何個分</strong>まで区間を広げるかを表す数</li>
<li><strong>standard error</strong>（標準誤差）… sample mean が標本ごとに、どれくらいばらつくかを表す値</li>
</ul>
<p>この <span class="math inline">\(2\)</span> つの中身は、<span class="math inline">\(\sigma\)</span> が分かっているかどうかで変わります。</p>
<section id="form-z" class="level4">
<h4 class="anchored" data-anchor-id="form-z"><span class="math inline">\(\sigma\)</span> が分かっている場合</h4>
<p><span id="eq-ahl416-z"><span class="math display">\[
\bar{x} \ \pm \ z^{*} \frac{\sigma}{\sqrt{n}}
\tag{3}\]</span></span></p>
<ul>
<li><span class="math inline">\(\sigma\)</span> … <strong>population standard deviation</strong>（母標準偏差）</li>
<li><span class="math inline">\(n\)</span> … <strong>sample size</strong>（標本の大きさ）</li>
<li><span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span> … sample mean の standard error（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html#narrower">AHL 4.15</a> で出てきた <span class="math inline">\(\bar{X}\)</span> の standard deviation そのものです）</li>
<li><span class="math inline">\(z^{*}\)</span> … normal distribution から決まる critical value</li>
</ul>
<p><span class="math inline">\(95\%\)</span> confidence interval では、<span class="math inline">\(z^{*} = 1.96\)</span> です。</p>
</section>
<section id="form-t" class="level4">
<h4 class="anchored" data-anchor-id="form-t"><span class="math inline">\(\sigma\)</span> が分からない場合</h4>
<p><span id="eq-ahl416-t"><span class="math display">\[
\bar{x} \ \pm \ t^{*} \frac{s}{\sqrt{n}}
\tag{4}\]</span></span></p>
<ul>
<li><span class="math inline">\(s\)</span> … <strong>sample standard deviation</strong>（標本標準偏差）。ここでは、母標準偏差の不偏推定値 <span class="math inline">\(s_{n-1}\)</span>（電卓の <span class="math inline">\(s_x\)</span>）のことです</li>
<li><span class="math inline">\(\dfrac{s}{\sqrt{n}}\)</span> … <span class="math inline">\(\sigma\)</span> を <span class="math inline">\(s\)</span> で置きかえて<strong>推定した</strong> standard error</li>
<li><span class="math inline">\(t^{*}\)</span> … <strong><span class="math inline">\(t\)</span>-distribution</strong> から決まる critical value</li>
</ul>
</section>
<section id="z-vs-t" class="level4">
<h4 class="anchored" data-anchor-id="z-vs-t">なぜ <span class="math inline">\(z\)</span> と <span class="math inline">\(t\)</span> を使い分けるのか</h4>
<ul>
<li><span class="math inline">\(\sigma\)</span> が分かっている場合は、standard error を<strong>正確に</strong>求められます。ですから normal distribution の <span class="math inline">\(z^{*}\)</span> を使います。</li>
<li><span class="math inline">\(\sigma\)</span> が分からない場合は、標本から求めた <span class="math inline">\(s\)</span> で<strong>推定します</strong>。推定による不確かさが加わるので、そのぶんを見こんで、裾が少し広い <span class="math inline">\(t\)</span>-distribution を使います（<a href="#t-dist">第6節</a>）。</li>
<li><span class="math inline">\(t^{*}\)</span> は、confidence level と <strong>degrees of freedom</strong>（自由度）<span class="math inline">\(\text{df} = n - 1\)</span> によって決まります。</li>
</ul>
<p><span id="eq-ahl416-rule"><span class="math display">\[
\boxed{\ \sigma \ \text{が既知} \ \Rightarrow \ z \qquad \sigma \ \text{が未知} \ \Rightarrow \ t\ }
\tag{5}\]</span></span></p>
<p><strong>この判断は、計算より先にします</strong>（<a href="#which">第5節</a>）。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>この式を手で計算する必要はありません。</strong> 電卓が区間の両端を返します。</p>
<p>ただ、<strong>式の形を知っていると、電卓の選び方と入力を確かめられます。</strong> <span class="math inline">\(\sigma\)</span> の欄があるのが <code>z Interval</code>、<code>sx</code> の欄があるのが <code>t Interval</code> です。そして返ってきた <span class="math inline">\(2\)</span> 数の<strong>まん中は、必ず <span class="math inline">\(\bar{x}\)</span></strong> になります。そこがずれていたら、入力を間違えています。</p>
</div>
</div>
</div>
</section>
</section>
<section id="assumption" class="level3">
<h3 class="anchored" data-anchor-id="assumption">4. 母集団が normally distributed であることを確かめます</h3>
<p>シラバスの Content 欄は、こう書かれています。</p>
<blockquote class="blockquote">
<p>Confidence intervals for the mean of <strong>a normal population</strong>.</p>
</blockquote>
<p>この項目では、基本的に<strong>母集団が normally distributed（正規分布にしたがう）と仮定します。</strong> 問題文には <code>normally distributed</code> と書かれます。<strong>このページの問題は、すべてこの前提でできています。</strong></p>
<p>母集団が正規分布でない場合でも、標本が十分に大きければ、<a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html#clt">AHL 4.15 の central limit theorem</a>（中心極限定理）によって標本平均を近似的に正規分布として扱えることがあります。<strong>どちらを使えるかは、問題文の条件を確かめてください。</strong></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>問題文に正規性が明記されていないのに、小さい標本でこの方法を使った場合は、その仮定を答案に書くよう求められることがあります。<code>State the assumption you have made</code>（おいた仮定を述べなさい）と聞かれたら</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>It is assumed that the population is normally distributed.</em></p>
</div>
<p>と書きます。<a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a> の <span class="math inline">\(t\)</span> 検定でも、同じ仮定を書きました。</p>
</div>
</div>
</div>
</section>
<section id="which" class="level3">
<h3 class="anchored" data-anchor-id="which">5. 計算の前に、<span class="math inline">\(\sigma\)</span> が分かっているか確認する</h3>
<p><strong>この項目でいちばん失点するのは、ここです。</strong> そして、計算を始める<strong>前に</strong>決めることです。シラバスの Guidance 欄が、はっきり指定しています。</p>
<blockquote class="blockquote">
<p>Use of the <strong>normal distribution when <span class="math inline">\(\sigma\)</span> is known</strong> and the <strong><span class="math inline">\(t\)</span>-distribution when <span class="math inline">\(\sigma\)</span> is unknown</strong>, <strong>regardless of sample size.</strong></p>
</blockquote>
<p>判断のしかたは <a href="#eq-ahl416-rule" class="quarto-xref">式&nbsp;5</a> のとおりで、<span class="math inline">\(\sigma\)</span> が既知なら <code>z Interval</code>、未知なら <code>t Interval</code> です（<a href="#z-vs-t">第3節</a>）。ここで見るのは、<strong>問題文からその <span class="math inline">\(\sigma\)</span> を読み取る</strong>ところです。</p>
<p>注意が <span class="math inline">\(4\)</span> つあります。</p>
<ul>
<li><strong><span class="math inline">\(n\)</span> の大小だけで <span class="math inline">\(z\)</span> と <span class="math inline">\(t\)</span> を選ばないでください。</strong> 見るのは、<span class="math inline">\(\sigma\)</span> が分かっているかどうかだけです。</li>
<li>問題文に <span class="math inline">\(s\)</span> や <code>sample standard deviation</code> と書かれていても、<strong><span class="math inline">\(\sigma\)</span> が分かったことにはなりません。</strong></li>
<li><code>regardless of sample size</code> は、「標本が大きければ、未知の <span class="math inline">\(\sigma\)</span> を既知としてよい」という意味では<strong>ありません。</strong></li>
<li>このページの範囲では、<strong><span class="math inline">\(\sigma\)</span> が未知なら、標本が大きくても <span class="math inline">\(t\)</span>-interval</strong> を選びます。</li>
</ul>
<p>問題文の書き方で読み分けます。</p>
<div id="tbl-ahl416-which" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-which-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;1: <span class="math inline">\(z\)</span> と <span class="math inline">\(t\)</span> の読み分け
</figcaption>
<div aria-describedby="tbl-ahl416-which-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>問題文の表現</th>
<th>分かっているもの</th>
<th>使う分布</th>
<th>GDC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>the population standard deviation is ...</code></td>
<td><span class="math inline">\(\sigma\)</span></td>
<td>normal</td>
<td><code>z Interval</code></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma = 2.5\)</span> のように直接示される</td>
<td><span class="math inline">\(\sigma\)</span></td>
<td>normal</td>
<td><code>z Interval</code></td>
</tr>
<tr class="odd">
<td><code>the sample standard deviation is ...</code></td>
<td><span class="math inline">\(s\)</span></td>
<td><strong><span class="math inline">\(t\)</span></strong></td>
<td><code>t Interval</code></td>
</tr>
<tr class="even">
<td>データの列だけが与えられる</td>
<td>GDC が <span class="math inline">\(s\)</span> を計算する</td>
<td><strong><span class="math inline">\(t\)</span></strong></td>
<td><code>t Interval</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><code>sample variance</code> が与えられたときは、そのまま入れられません
</div>
</div>
<div class="callout-body-container callout-body">
<p>問題文が <code>the sample variance is 14.7</code> のように <span class="math inline">\(s_n^{2}\)</span> を与えてくることがあります。この値は <span class="math inline">\(n\)</span> で割ったものなので、<strong>電卓の <code>sx</code> にそのまま入れてはいけません。</strong> <span class="math inline">\(s_{n-1}^{2} = \dfrac{n}{n-1}s_n^{2}\)</span> に直してから使います（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-18b.html">AHL 4.18b</a>）。</p>
<p><code>the unbiased estimate of the population standard deviation is 2.5</code> と書かれていれば、それが <span class="math inline">\(s_{n-1}\)</span> そのものです。</p>
</div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><code>it is known from experience that the standard deviation is 2.5</code> のような書き方もあります。このときは、<strong>何が既知なのか</strong>を読み取ってください。ここで既知なのは母集団の standard deviation、つまり <span class="math inline">\(\sigma\)</span> ですから <code>z Interval</code> です。</p>
<p><strong><code>population</code> と書いてあるか、<code>sample</code> と書いてあるか。</strong> そこに丸を付けてから始めてください（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#calculator">AHL 4.14</a>）。</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>AHL 4.15 の <span class="math inline">\(n &gt; 30\)</span> とは、別の話です
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html#n30">AHL 4.15</a> の <span class="math inline">\(n &gt; 30\)</span> という目安は、<strong>central limit theorem が使えるかどうか</strong>の話でした。</p>
<p>こちらは、<strong><span class="math inline">\(\sigma\)</span> が分かっているかどうか</strong>の話です。<strong>混ぜないでください。</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>試験で多いのは、<span class="math inline">\(t\)</span> のほうです
</div>
</div>
<div class="callout-body-container callout-body">
<p>現実には、<span class="math inline">\(\mu\)</span> が分からないのに <span class="math inline">\(\sigma\)</span> だけ分かる、という状況はまれです。ですから <strong><code>t Interval</code> を使う問題のほうがよく出ます。</strong></p>
<p><code>z Interval</code> が出るのは、「長年の記録から <span class="math inline">\(\sigma\)</span> が分かっている」という設定のときです。</p>
</div>
</div>
</section>
<section id="t-dist" class="level3">
<h3 class="anchored" data-anchor-id="t-dist">6. なぜ <span class="math inline">\(t\)</span>-distribution を使うのか</h3>
<p><a href="#z-vs-t">第3節</a>で見たとおり、<span class="math inline">\(\sigma\)</span> が未知のときは、<span class="math inline">\(s\)</span> で standard error を<strong>推定する</strong>ぶん不確かさが増えます。それを埋め合わせるのが <strong><span class="math inline">\(t\)</span>-distribution</strong>（<span class="math inline">\(t\)</span> 分布）です。ここでは、その中身を数で見ます。</p>
<p><span class="math inline">\(t\)</span>-distribution は、<a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a> の <span class="math inline">\(t\)</span> 検定で一度出てきています。この項目でも<strong>電卓が使うだけ</strong>なので、形を細かく知る必要はありません。知っておくとよいのは、<span class="math inline">\(2\)</span> つです。</p>
<p><strong><span class="math inline">\(1\)</span> つ目。<span class="math inline">\(t\)</span>-distribution は normal distribution より裾が広いので、同じ confidence level なら critical value が大きくなります。</strong></p>
<div id="tbl-ahl416-critical" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-critical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;2: critical value の比べ方
</figcaption>
<div aria-describedby="tbl-ahl416-critical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>confidence level</th>
<th>normal の critical value</th>
<th><span class="math inline">\(t\)</span> の critical value（<span class="math inline">\(n = 8\)</span>、<span class="math inline">\(\text{df} = 7\)</span>）</th>
<th><span class="math inline">\(t\)</span> の critical value（<span class="math inline">\(n = 20\)</span>、<span class="math inline">\(\text{df} = 19\)</span>）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(90\%\)</span></td>
<td><span class="math inline">\(1.645\)</span></td>
<td><span class="math inline">\(1.895\)</span></td>
<td><span class="math inline">\(1.729\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(95\%\)</span></td>
<td><span class="math inline">\(1.960\)</span></td>
<td><span class="math inline">\(2.365\)</span></td>
<td><span class="math inline">\(2.093\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(99\%\)</span></td>
<td><span class="math inline">\(2.576\)</span></td>
<td><span class="math inline">\(3.499\)</span></td>
<td><span class="math inline">\(2.861\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>この表は、比べるためのものです。</strong> 試験で critical value を表から引く必要はありません。電卓が区間そのものを返します。</p>
<p><strong><span class="math inline">\(2\)</span> つ目。<span class="math inline">\(n\)</span> が大きくなると <span class="math inline">\(s\)</span> による推定が安定するので、<span class="math inline">\(t\)</span>-distribution は normal distribution に近づきます。</strong> <a href="#tbl-ahl416-critical" class="quarto-xref">表&nbsp;2</a> で、<span class="math inline">\(n = 8\)</span> の <span class="math inline">\(2.365\)</span> より <span class="math inline">\(n = 20\)</span> の <span class="math inline">\(2.093\)</span> のほうが <span class="math inline">\(1.960\)</span> に近いことを見てください。</p>
<p>ただし、<strong>どこまでいっても normal より少し大きいまま</strong>です。これが <code>regardless of sample size</code> の背景にある事実です。</p>
<section id="df" class="level4">
<h4 class="anchored" data-anchor-id="df">degrees of freedom は <span class="math inline">\(n - 1\)</span> です</h4>
<p><span class="math inline">\(t\)</span>-distribution は、<strong>degrees of freedom</strong>（自由度）によって形が変わります。<span class="math inline">\(1\)</span> 標本の平均の <span class="math inline">\(t\)</span>-interval では</p>
<p><span id="eq-ahl416-df"><span class="math display">\[
\text{degrees of freedom} = n - 1
\tag{6}\]</span></span></p>
<p>です。理由は、<strong>標本平均を決めてしまうと、<span class="math inline">\(n\)</span> 個の偏差のうち自由に決められるのは <span class="math inline">\(n - 1\)</span> 個になる</strong>からです（<span class="math inline">\(n-1\)</span> で割った <span class="math inline">\(s_{n-1}\)</span> を使うのも、同じ事情です。<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#s2">AHL 4.14</a>）。</p>
<p>たとえば <span class="math inline">\(n = 8\)</span> なら、<span class="math inline">\(\text{df} = 8 - 1 = 7\)</span> です。</p>
<p><strong>電卓は自動で計算します。</strong> <span class="math inline">\(n\)</span> を入力すれば自由度は勝手に決まるので、試験で複雑な理論を覚える必要はありません。</p>
</section>
</section>
<section id="width" class="level3">
<h3 class="anchored" data-anchor-id="width">7. 区間の幅を決める <span class="math inline">\(3\)</span> つ</h3>
<p><strong>以下は、表に書かれている要素以外の条件が同じ場合の比較です。</strong></p>
<div id="fig-ahl416-width" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl416-width-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-16-width.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl416-width-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;2: What makes a confidence interval wider or narrower
</figcaption>
</figure>
</div>
<div id="tbl-ahl416-width" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-width-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;3: 幅を決める <span class="math inline">\(3\)</span> つ（ほかの条件は同じとして）
</figcaption>
<div aria-describedby="tbl-ahl416-width-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>変えるもの</th>
<th>幅への影響</th>
<th>なぜ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>confidence level</strong> を上げる（<span class="math inline">\(95\% \to 99\%\)</span>）</td>
<td><strong>広くなる</strong></td>
<td>critical value が大きくなる</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(n\)</span> を増やす</strong></td>
<td><strong>狭くなる</strong></td>
<td>standard error が小さくなる</td>
</tr>
<tr class="odd">
<td>データの<strong>ばらつき</strong>が大きくなる</td>
<td><strong>広くなる</strong></td>
<td>standard error が大きくなる</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>それぞれ、次のようにつながっています。</p>
<ul>
<li><strong>confidence level を上げる</strong> → より多くの場合に <span class="math inline">\(\mu\)</span> を含みたい → critical value が大きくなる → 区間が広くなる</li>
<li><strong><span class="math inline">\(n\)</span> を増やす</strong> → standard error <span class="math inline">\(\dfrac{s}{\sqrt{n}}\)</span> または <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span> が小さくなる → 区間が狭くなる</li>
<li><strong>データのばらつきが大きくなる</strong> → <span class="math inline">\(s\)</span> または <span class="math inline">\(\sigma\)</span> が大きくなる → standard error が大きくなる → 区間が広くなる</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>「確かさ」と「細かさ」は、取り引きの関係です
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>confidence level を高くすると、同じ方法をくり返したときに <span class="math inline">\(\mu\)</span> を含む割合は高くなります。その代わり、推定できる範囲は広くなり、精度は低くなります。</strong></p>
<p><a href="#fig-ahl416-width" class="quarto-xref">図&nbsp;2</a> の左で、<span class="math inline">\(4.02 \to 4.87 \to 6.65\)</span> と広がっているとおりです。</p>
<p>「<span class="math inline">\(\mu\)</span> は <span class="math inline">\(0\)</span> から <span class="math inline">\(1000\)</span> のあいだ」と言えば、まず外しません。しかし、<strong>何も言っていないのと同じ</strong>です。</p>
<p><span class="math inline">\(95\%\)</span> という水準は、この <span class="math inline">\(2\)</span> つの折り合いとして、よく使われている値です。</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>「<span class="math inline">\(n\)</span> を <span class="math inline">\(4\)</span> 倍にすると幅が半分」は、critical value が変わらないときの話です
</div>
</div>
<div class="callout-body-container callout-body">
<p>standard error は <span class="math inline">\(\dfrac{s}{\sqrt{n}}\)</span> なので、<span class="math inline">\(n\)</span> を <span class="math inline">\(4\)</span> 倍にすると <strong>standard error はちょうど半分</strong>になります。</p>
<p><strong>幅がちょうど半分になるのは、critical value と standard deviation が同じままのとき</strong>です。<span class="math inline">\(\sigma\)</span> が既知で normal を使うときは、critical value が動かないので<strong>ちょうど半分</strong>です。</p>
<p><span class="math inline">\(t\)</span> を使うときは、<span class="math inline">\(n\)</span> が増えると <strong>critical value も一緒に小さくなります</strong>（<a href="#t-dist">第6節</a>）。ですから幅は、半分より<strong>もう少し縮みます。</strong></p>
</div>
</div>
</section>
<section id="interpret" class="level3">
<h3 class="anchored" data-anchor-id="interpret">8. 文脈の言葉で書く</h3>
<p>シラバスが名指ししている、<strong>この項目の答案での中心</strong>です。</p>
<blockquote class="blockquote">
<p>Students should be able to <strong>interpret the meaning of their results in context.</strong></p>
</blockquote>
<p>書き方は、いつも同じ型です。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>答案の型（空欄に当てはめる）
</div>
</div>
<div class="callout-body-container callout-body">
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>We are [confidence level]% confident that the population mean [quantity] lies between [lower bound] and [upper bound] [unit].</em></p>
</div>
<p>空欄に入れるものは、次のとおりです。</p>
<ul>
<li><strong>confidence level</strong> … <span class="math inline">\(90\)</span>、<span class="math inline">\(95\)</span>、<span class="math inline">\(99\)</span> など</li>
<li><strong>population mean quantity</strong> … <strong>何の母平均か</strong>を、その問題の言葉で</li>
<li><strong>lower and upper bounds</strong> … GDC で得た区間の下限・上限</li>
<li><strong>unit</strong> … g、hours、mg per litre など</li>
</ul>
<p>チョコレートの例なら、こうなります。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>We are <span class="math inline">\(95\%\)</span> confident that the population mean mass of a chocolate bar lies between <span class="math inline">\(47.5\)</span> g and <span class="math inline">\(49.7\)</span> g.</em></p>
</div>
<p><strong>「何の母平均か」が抜けている答案が、いちばん多い</strong>です。次の答案では足りません。</p>
<p><em>We are <span class="math inline">\(95\%\)</span> confident that <span class="math inline">\(\mu\)</span> is between <span class="math inline">\(47.5\)</span> and <span class="math inline">\(49.7\)</span>.</em></p>
<p>足りない理由は <span class="math inline">\(3\)</span> つです。</p>
<ul>
<li><span class="math inline">\(\mu\)</span> が<strong>何の平均か</strong>が分からない</li>
<li><strong>単位</strong>がない</li>
<li><strong><code>population mean</code></strong> という意味が、文章に出ていない</li>
</ul>
<p><strong><code>the population mean</code></strong> と書いておけば確実です。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(1\)</span> つ <span class="math inline">\(1\)</span> つの値について書いてしまう
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>“<span class="math inline">\(95\%\)</span> of the chocolate bars weigh between <span class="math inline">\(47.5\)</span> g and <span class="math inline">\(49.7\)</span> g”</em> は<strong>誤り</strong>です。</p>
<p>confidence interval が言っているのは、<strong>population mean <span class="math inline">\(\mu\)</span> がどこにあるか</strong>であって、<span class="math inline">\(1\)</span> 枚ずつの重さの話ではありません。</p>
</div>
</div>
</section>
<section id="compare" class="level3">
<h3 class="anchored" data-anchor-id="compare">9. 区間が重なっているときに言えること</h3>
<p>シラバスの Connections 欄に、こう書かれています。</p>
<blockquote class="blockquote">
<p>Claiming brand A is “better” on average than brand B <strong>can mean very little if there is a large overlap</strong> between the confidence intervals of the two means.</p>
</blockquote>
<div id="fig-ahl416-overlap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl416-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-16-overlap.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl416-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;3: Comparing two confidence intervals
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl416-overlap" class="quarto-xref">図&nbsp;3</a> の左では、<span class="math inline">\(2\)</span> つの区間が<strong>重なっています</strong>（図のピンク色の部分です）。brand B の <span class="math inline">\(\bar{x}\)</span> のほうが大きくても、<strong>「B のほうが母平均が大きい」とは言い切れません。</strong></p>
<p>ここで、<strong>言えることと言えないこと</strong>を分けてください。</p>
<ul>
<li><span class="math inline">\(2\)</span> つの区間が重なっていることは、<strong><span class="math inline">\(2\)</span> つの母平均が等しいことの証明ではありません。</strong></li>
<li>ただし、<strong>この <span class="math inline">\(2\)</span> つの区間だけを根拠として</strong>、「一方の母平均がもう一方より大きい」と<strong>断定することはできません。</strong></li>
<li>差を正式に検討するには、<a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a> の <span class="math inline">\(2\)</span> 標本の <span class="math inline">\(t\)</span> 検定のような、別の推測統計の方法が必要になります。</li>
</ul>
<p>右のように<strong>重なっていなければ</strong>、話は変わります。<strong>区間に含まれる値</strong>については、A 側のどの値も B 側のどの値より小さくなっているので、<strong>言えることがずっと強くなります。</strong></p>
<p>ただし、信頼区間は「<span class="math inline">\(\mu\)</span> としてありうる値をすべて集めたもの」ではありません。<strong>区間の外の値が不可能だと証明されたわけではない</strong>ことは、頭に置いておいてください。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>重なりを見て、答案に書けること
</div>
</div>
<div class="callout-body-container callout-body">
<div class="model-answer">
<p><strong>試験ではこう書く（重なっているとき）</strong></p>
<p><em>The two confidence intervals overlap between <span class="math inline">\(54.1\)</span> and <span class="math inline">\(55.8\)</span> hundred hours, so these intervals do not provide sufficient evidence that the population mean lifetime for brand B is larger than that for brand A. The two population means could be equal.</em></p>
</div>
<p>（<span class="math inline">\(2\)</span> つの区間は <span class="math inline">\(54.1\)</span> から <span class="math inline">\(55.8\)</span> で重なっているので、この <span class="math inline">\(2\)</span> つの区間だけでは、B の母平均のほうが大きいと言う根拠にならない、という意味です。<span class="math inline">\(2\)</span> つの母平均が等しい可能性も残ります。）</p>
<p><strong><code>overlap</code>（重なる）という語を使う</strong>のが、この型の目印です。</p>
</div>
</div>
</section>
</section>
<section id="why-it-works" class="level2">
<h2 class="anchored" data-anchor-id="why-it-works">Why it works</h2>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>クリックすると開きます
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>ここで説明するのは <span class="math inline">\(1\)</span> つです。<strong>なぜ「<span class="math inline">\(\bar{x}\)</span> <span class="math inline">\(\pm\)</span> margin of error」という形になるのか。</strong></p>
<p><a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html#xbar">AHL 4.15</a> から、<span class="math inline">\(\sigma\)</span> が分かっているとき</p>
<p><span class="math display">\[
\bar{X} \sim N\!\left(\mu,\ \frac{\sigma^{2}}{n}\right)
\]</span></p>
<p>でした。この分布で、<strong>まん中の <span class="math inline">\(95\%\)</span></strong> に入る範囲を考えます。critical value を <span class="math inline">\(1.96\)</span> とすると</p>
<p><span class="math display">\[
\mu - 1.96\frac{\sigma}{\sqrt{n}} \ &lt; \ \bar{X} \ &lt; \ \mu + 1.96\frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>が、確率 <span class="math inline">\(0.95\)</span> で成り立ちます。<strong>「<span class="math inline">\(\bar{X}\)</span> は <span class="math inline">\(\mu\)</span> の近くに来る」</strong>と読める式です。</p>
<p>ここで、<strong><span class="math inline">\(\mu\)</span> と <span class="math inline">\(\bar{X}\)</span> を入れかえます。</strong> 上の式を <span class="math inline">\(\mu\)</span> について解きます。</p>
<p><span class="math display">\[
\bar{X} - 1.96\frac{\sigma}{\sqrt{n}} \ &lt; \ \mu \ &lt; \ \bar{X} + 1.96\frac{\sigma}{\sqrt{n}}
\]</span></p>
<p><strong>同じ不等式です。</strong> 移項しただけで、成り立つ確率も <span class="math inline">\(0.95\)</span> のままです。</p>
<p>そして、この形は「<strong><span class="math inline">\(\mu\)</span> は <span class="math inline">\(\bar{X}\)</span> の近くにある</strong>」と読めます。<strong><span class="math inline">\(\bar{X}\)</span> が <span class="math inline">\(\mu\)</span> の近くに来るなら、<span class="math inline">\(\mu\)</span> も <span class="math inline">\(\bar{X}\)</span> の近くにある</strong>——言いかえただけのようですが、これが信頼区間の作り方そのものです。</p>
<p>実際に標本をとって <span class="math inline">\(\bar{X}\)</span> の値 <span class="math inline">\(\bar{x}\)</span> が決まると、これが <a href="#eq-ahl416-ci" class="quarto-xref">式&nbsp;2</a> の区間になります。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>「確率 <span class="math inline">\(0.95\)</span>」が、どこに掛かっているか</strong>に注意してください。</p>
<p><span class="math inline">\(\bar{X}\)</span> が<strong>大文字</strong>のあいだは、まだ標本をとっていません。動くのは <span class="math inline">\(\bar{X}\)</span> のほうで、確率はそこに掛かっています。</p>
<p>標本をとって <span class="math inline">\(\bar{x} = 48.6\)</span> と決まったあとは、<span class="math inline">\(\mu\)</span> もその区間も動きません。だから<a href="#meaning">第2節</a>のような言い方になるのです。</p>
<p><span class="math inline">\(\sigma\)</span> が分からないときは、<span class="math inline">\(\sigma\)</span> の代わりに <span class="math inline">\(s_{n-1}\)</span> を入れます。<strong>推定値で置きかえたぶん不確かさが増える</strong>ので、<span class="math inline">\(1.96\)</span> ではなく <span class="math inline">\(t\)</span> の critical value（もう少し大きい値）を使います。</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="worked-examples" class="level2">
<h2 class="anchored" data-anchor-id="worked-examples">Worked examples</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>問題文は英語です。意味が理解できなかったら、問題文の下の「<strong>日本語訳</strong>」を開いてください。解説は日本語です。</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>どの問題でも、この <span class="math inline">\(4\)</span> 段階で進みます
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Parameter</strong> … 求める母平均 <span class="math inline">\(\mu\)</span> が<strong>何の平均か</strong>と、その<strong>単位</strong>を確かめる</li>
<li><strong>Conditions</strong> … 母集団が normally distributed であることを確かめる（<a href="#assumption">第4節</a>）</li>
<li><strong>Method</strong> … <span class="math inline">\(\sigma\)</span> が既知なら <span class="math inline">\(z\)</span>-interval、未知なら <span class="math inline">\(t\)</span>-interval（<a href="#which">第5節</a>）</li>
<li><strong>Interpret</strong> … 区間を、<strong>文脈と単位を含む文</strong>で答える（<a href="#interpret">第8節</a>）</li>
</ol>
<p>計算を始める前に、<span class="math inline">\(3\)</span> の判断を答案に <span class="math inline">\(1\)</span> 行で書いてください。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Method: <span class="math inline">\(\sigma\)</span> is known, so a <span class="math inline">\(z\)</span>-interval is used.</em></p>
<p><em>Method: <span class="math inline">\(\sigma\)</span> is unknown and only <span class="math inline">\(s\)</span> is available, so a <span class="math inline">\(t\)</span>-interval is used.</em></p>
</div>
</div>
</div>
<div id="exm-ahl416-z" class="theorem example">
<p><span class="theorem-title"><strong>例題 1</strong></span> <span class="q-en">The mass of a chocolate bar produced by a machine is normally distributed. From long experience, the population standard deviation is known to be <span class="math inline">\(2.5\)</span> g.</span></p>
<p><span class="q-en">A random sample of <span class="math inline">\(20\)</span> bars has a mean mass of <span class="math inline">\(48.6\)</span> g.</span></p>
<p><strong>(a)</strong> <span class="q-en">State, with a reason, whether a normal distribution or a <span class="math inline">\(t\)</span>-distribution should be used.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find a <span class="math inline">\(95\%\)</span> confidence interval for the mean mass of a chocolate bar.</span></p>
<p><strong>(c)</strong> <span class="q-en">Interpret your answer to part (b) in context.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある機械が作るチョコレートの重さは、正規分布にしたがいます。長年の記録から、母標準偏差は <span class="math inline">\(2.5\)</span> g と分かっています。</p>
<p><code>from long experience</code> は「長年の記録から」、<code>population standard deviation</code> は「母標準偏差」という意味です。</p>
<p>無作為にとった <span class="math inline">\(20\)</span> 枚の標本の平均の重さは <span class="math inline">\(48.6\)</span> g でした。</p>
<p><strong>(a)</strong> 正規分布と <span class="math inline">\(t\)</span> 分布のどちらを使うべきかを、理由を示して述べなさい。</p>
<p><strong>(b)</strong> チョコレート <span class="math inline">\(1\)</span> 枚の平均の重さについて、<span class="math inline">\(95\%\)</span> 信頼区間を求めなさい。</p>
<p><strong>(c)</strong> (b) の答えを、文脈の中で解釈しなさい。</p>
</details>
<hr>
<p><strong>Parameter.</strong> 求めるのは、チョコレート <span class="math inline">\(1\)</span> 枚の<strong>母平均の質量</strong>（単位は g）です。</p>
<p><strong>Conditions.</strong> 問題文に <code>normally distributed</code> とあります ✓（<a href="#assumption">第4節</a>）</p>
<p><strong>(a)</strong> 問題文に <code>population standard deviation is known to be 2.5</code> とあります。<strong><span class="math inline">\(\sigma\)</span> が与えられている</strong>ので、normal です（<a href="#which">第5節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The population standard deviation <span class="math inline">\(\sigma = 2.5\)</span> is known, so the normal distribution (a <span class="math inline">\(z\)</span>-interval) should be used.</em></p>
</div>
<p><strong>(b)</strong> <em>Method: <span class="math inline">\(\sigma\)</span> is known, so a <span class="math inline">\(z\)</span>-interval is used.</em></p>
<p><code>z Interval</code> に入れます（<a href="#gdc-z">GDC 第1節</a>）。</p>
<pre><code>σ: 2.5      x̄: 48.6      n: 20      C Level: 0.95</code></pre>
<p><span class="math display">\[
47.5 &lt; \mu &lt; 49.7 \quad (\text{g})
\]</span></p>
<p><strong>検算。</strong> 区間のまん中は <span class="math inline">\(\dfrac{47.5 + 49.7}{2} = 48.6 = \bar{x}\)</span> ✓（<a href="#form">第3節</a>）</p>
<p><a href="#eq-ahl416-z" class="quarto-xref">式&nbsp;3</a> の形と対応させると、こうなります。</p>
<p><span class="math display">\[
\text{standard error} = \frac{2.5}{\sqrt{20}} = 0.559, \qquad \text{margin of error} = 1.96 \times 0.559 = 1.10
\]</span></p>
<p><span class="math display">\[
48.6 \pm 1.10 \quad \Longrightarrow \quad 47.5 &lt; \mu &lt; 49.7
\]</span></p>
<p><strong>point estimate は <span class="math inline">\(48.6\)</span>、margin of error は <span class="math inline">\(1.10\)</span></strong> です。</p>
<p><strong>(c)</strong> <a href="#interpret">第8節</a>の型で書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>We are <span class="math inline">\(95\%\)</span> confident that the population mean mass of a chocolate bar produced by this machine lies between <span class="math inline">\(47.5\)</span> g and <span class="math inline">\(49.7\)</span> g.</em></p>
</div>
<p>（この機械が作るチョコレート <span class="math inline">\(1\)</span> 枚の<strong>平均</strong>の重さは、<span class="math inline">\(47.5\)</span> g から <span class="math inline">\(49.7\)</span> g のあいだにあると <span class="math inline">\(95\%\)</span> の確信をもって言える、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em><span class="math inline">\(\sigma = 2.5\)</span> is the known population standard deviation, so the normal distribution is used.</em></p>
<p><strong>(b)</strong> <span class="math display">\[
47.5 &lt; \mu &lt; 49.7 \quad (\text{g})
\]</span></p>
<p><strong>(c)</strong> <em>We are <span class="math inline">\(95\%\)</span> confident that the population mean mass of a chocolate bar lies between <span class="math inline">\(47.5\)</span> g and <span class="math inline">\(49.7\)</span> g.</em></p>
</div>
</div>
</div>
<div id="exm-ahl416-t" class="theorem example">
<p><span class="theorem-title"><strong>例題 2</strong></span> <span class="q-en">A laboratory measures the concentration, in mg per litre, of a chemical in eight samples of water taken from a lake. The concentration is normally distributed.</span></p>
<div id="tbl-ahl416-we2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-we2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;4: Concentration (mg per litre)
</figcaption>
<div aria-describedby="tbl-ahl416-we2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(12.1\)</span></td>
<td><span class="math inline">\(11.8\)</span></td>
<td><span class="math inline">\(12.4\)</span></td>
<td><span class="math inline">\(12.0\)</span></td>
<td><span class="math inline">\(11.6\)</span></td>
<td><span class="math inline">\(12.3\)</span></td>
<td><span class="math inline">\(12.1\)</span></td>
<td><span class="math inline">\(11.7\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">Find the sample mean and an unbiased estimate of the population standard deviation.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find a <span class="math inline">\(95\%\)</span> confidence interval for the mean concentration.</span></p>
<p><strong>(c)</strong> <span class="q-en">A scientist claims that the mean concentration is <span class="math inline">\(12.5\)</span> mg per litre. Comment on this claim.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある研究室が、湖から採った <span class="math inline">\(8\)</span> 個の水の標本について、化学物質の濃度（<span class="math inline">\(1\)</span> リットルあたり mg）を測りました。濃度は正規分布にしたがいます。</p>
<p>表の見出しは <code>Concentration (mg per litre)</code> で「濃度（<span class="math inline">\(1\)</span> リットルあたり mg）」です。</p>
<p><strong>(a)</strong> 標本平均と、母標準偏差の不偏推定値を求めなさい。</p>
<p><strong>(b)</strong> 平均濃度について、<span class="math inline">\(95\%\)</span> 信頼区間を求めなさい。</p>
<p><strong>(c)</strong> ある科学者が、平均濃度は <span class="math inline">\(12.5\)</span> mg/L だと主張しています。この主張について述べなさい。</p>
</details>
<hr>
<p><strong>Parameter.</strong> 求めるのは、水中の化学物質の<strong>母平均の濃度</strong>（単位は mg per litre）です。</p>
<p><strong>Conditions.</strong> 問題文に <code>The concentration is normally distributed.</code> とあります ✓</p>
<p><strong>(a)</strong> データを電卓の列に入れて <code>One-Variable Statistics</code> を走らせます。</p>
<p><span class="math display">\[
\bar{x} = 12.0, \qquad s_{n-1} = 0.283
\]</span></p>
<p><strong>読むのは <span class="math inline">\(s_x\)</span> のほうです</strong>（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#calculator">AHL 4.14</a>）。<span class="math inline">\(\sigma_x = 0.265\)</span> は不偏推定値ではありません。</p>
<p><strong>(b)</strong> <em>Method: <span class="math inline">\(\sigma\)</span> is unknown and only <span class="math inline">\(s\)</span> is available, so a <span class="math inline">\(t\)</span>-interval is used.</em></p>
<p><span class="math inline">\(\sigma\)</span> は与えられていません。データから <span class="math inline">\(s\)</span> を出したので、<strong><span class="math inline">\(t\)</span>-interval</strong> です（<a href="#which">第5節</a>）。</p>
<p>データがそのまま与えられているので、<code>t Interval</code> の <code>Data</code> を選べば、<span class="math inline">\(\bar{x}\)</span> も <span class="math inline">\(s\)</span> も電卓が計算します。</p>
<pre><code>Data Input Method: Data      List: (データの列)      C Level: 0.95</code></pre>
<p>電卓が返すのは <span class="math inline">\((11.7635,\ 12.2365)\)</span> です。<strong><span class="math inline">\(3\)</span> 桁</strong>に丸めると、次のようになります（この問題では小数第1位までです）。</p>
<p><span class="math display">\[
11.8 &lt; \mu &lt; 12.2 \quad (\text{mg per litre})
\]</span></p>
<p><a href="#eq-ahl416-t" class="quarto-xref">式&nbsp;4</a> の形と対応させると、<span class="math inline">\(\text{df} = 8 - 1 = 7\)</span>、<span class="math inline">\(t^{*} = 2.365\)</span>、standard error は <span class="math inline">\(\dfrac{0.283}{\sqrt{8}} = 0.100\)</span> なので</p>
<p><span class="math display">\[
12.0 \pm 2.365 \times 0.100 = 12.0 \pm 0.237
\]</span></p>
<p>です。<strong>検算。</strong> まん中は <span class="math inline">\(12.0 = \bar{x}\)</span> ✓</p>
<p><strong>(c)</strong> 次の <span class="math inline">\(3\)</span> 段階で書きます。</p>
<ol type="1">
<li>得られた <span class="math inline">\(95\%\)</span> confidence interval は <span class="math inline">\(11.8 &lt; \mu &lt; 12.2\)</span> mg per litre</li>
<li>主張された <span class="math inline">\(12.5\)</span> mg per litre は、上限 <span class="math inline">\(12.2\)</span> より<strong>大きい</strong></li>
<li>したがって、この標本はその主張を<strong>支持しない</strong></li>
</ol>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The value <span class="math inline">\(12.5\)</span> lies outside the <span class="math inline">\(95\%\)</span> confidence interval <span class="math inline">\(11.8 &lt; \mu &lt; 12.2\)</span>, so the data does not support the scientist’s claim.</em></p>
</div>
<p>（<span class="math inline">\(12.5\)</span> は <span class="math inline">\(95\%\)</span> 信頼区間の外にあるので、このデータはその主張を支持しない、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\bar{x} = 12.0, \qquad s_{n-1} = 0.283
\]</span></p>
<p><strong>(b)</strong> <em>Method: <span class="math inline">\(\sigma\)</span> is unknown, so a <span class="math inline">\(t\)</span>-interval is used.</em> <span class="math display">\[
11.8 &lt; \mu &lt; 12.2 \quad (\text{mg per litre})
\]</span></p>
<p><strong>(c)</strong> <em><span class="math inline">\(12.5\)</span> lies outside the interval <span class="math inline">\(11.8 &lt; \mu &lt; 12.2\)</span>, so the data does not support the claim.</em></p>
</div>
</div>
</div>
<div id="exm-ahl416-summary" class="theorem example">
<p><span class="theorem-title"><strong>例題 3</strong></span> <span class="q-en">Test scores are normally distributed. A random sample of <span class="math inline">\(20\)</span> students sat a test. The sample mean score was <span class="math inline">\(68.4\)</span> and the unbiased estimate of the population standard deviation was <span class="math inline">\(5.2\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find a <span class="math inline">\(90\%\)</span> confidence interval for the mean score of all students.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find a <span class="math inline">\(99\%\)</span> confidence interval for the mean score.</span></p>
<p><strong>(c)</strong> <span class="q-en">Comment on how the two intervals differ, and explain why.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>テストの得点は正規分布にしたがいます。無作為に選んだ <span class="math inline">\(20\)</span> 人の生徒がテストを受けました。標本平均の得点は <span class="math inline">\(68.4\)</span>、母標準偏差の不偏推定値は <span class="math inline">\(5.2\)</span> でした。</p>
<p><strong>(a)</strong> すべての生徒の平均点について、<span class="math inline">\(90\%\)</span> 信頼区間を求めなさい。</p>
<p><strong>(b)</strong> 平均点について、<span class="math inline">\(99\%\)</span> 信頼区間を求めなさい。</p>
<p><strong>(c)</strong> <span class="math inline">\(2\)</span> つの区間がどう違うかを述べ、その理由を説明しなさい。</p>
</details>
<hr>
<p><strong>Parameter.</strong> 求めるのは、すべての生徒の<strong>母平均の得点</strong>です。</p>
<p><strong>Conditions.</strong> 問題文に <code>Test scores are normally distributed.</code> とあります ✓</p>
<p><strong>(a)</strong> <em>Method: <span class="math inline">\(\sigma\)</span> is unknown and only <span class="math inline">\(s\)</span> is available, so a <span class="math inline">\(t\)</span>-interval is used.</em></p>
<p><span class="math inline">\(\sigma\)</span> ではなく<strong>不偏推定値</strong>（<span class="math inline">\(s\)</span>）が与えられています。ですから <strong><span class="math inline">\(t\)</span>-interval</strong> です（<a href="#which">第5節</a>）。</p>
<p>データの列はないので、<code>t Interval</code> の <strong><code>Stats</code></strong> を選びます（<a href="#gdc-t">GDC 第2節</a>）。</p>
<pre><code>Data Input Method: Stats      x̄: 68.4      sx: 5.2      n: 20      C Level: 0.90</code></pre>
<p><span class="math display">\[
66.4 &lt; \mu &lt; 70.4
\]</span></p>
<p><strong>(b)</strong> <code>C Level</code> を <span class="math inline">\(0.99\)</span> に変えるだけです。</p>
<p><span class="math display">\[
65.1 &lt; \mu &lt; 71.7
\]</span></p>
<p><strong>(c)</strong> <span class="math inline">\(99\%\)</span> のほうが<strong>広く</strong>なっています。</p>
<p>生の値は <span class="math inline">\((66.3894,\ 70.4106)\)</span> と <span class="math inline">\((65.0734,\ 71.7266)\)</span> です。<strong>幅は、丸める前の値から出します。</strong></p>
<p><span class="math display">\[
\text{幅} \quad 4.02 \ \to \ 6.65
\]</span></p>
<p>数値だけで終わらせず、<strong>理由</strong>まで書きます。<span class="math inline">\(99\%\)</span> 区間は、より高い割合で母平均を含むように作るため、<span class="math inline">\(90\%\)</span> 区間より広くなります。<strong>confidence level を上げると、母平均を含む確信は高まりますが、推定できる範囲は広くなります</strong>（<a href="#width">第7節</a>）。</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><code>more confident</code> と <code>more precise</code> は、別のことです。</strong></p>
<ul>
<li><strong>higher confidence</strong> … confidence level が高い（<span class="math inline">\(99\% &gt; 90\%\)</span>）</li>
<li><strong>more precise</strong> … 区間が狭い（<span class="math inline">\(4.02 &lt; 6.65\)</span> なので、<span class="math inline">\(90\%\)</span> 区間のほうが precise）</li>
</ul>
<p><span class="math inline">\(99\%\)</span> 区間は higher confidence ですが、more precise ではありません。</p>
</div>
</div>
</div>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The <span class="math inline">\(99\%\)</span> interval is wider than the <span class="math inline">\(90\%\)</span> interval (<span class="math inline">\(6.65\)</span> compared with <span class="math inline">\(4.02\)</span>). A higher confidence level means that a larger proportion of such intervals contain the population mean, so a wider range of values must be included. The <span class="math inline">\(99\%\)</span> interval therefore gives higher confidence but a less precise estimate.</em></p>
</div>
<p>（confidence level が高いほど、<span class="math inline">\(\mu\)</span> を含む区間の割合は高くなるので、より広い範囲を含めなければならない。<span class="math inline">\(99\%\)</span> 区間は確信は高いが、precise ではない、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Method: <span class="math inline">\(\sigma\)</span> is unknown, so a <span class="math inline">\(t\)</span>-interval is used.</em> <span class="math display">\[
66.4 &lt; \mu &lt; 70.4
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
65.1 &lt; \mu &lt; 71.7
\]</span></p>
<p><strong>(c)</strong> <em>The <span class="math inline">\(99\%\)</span> interval is wider. A higher confidence level requires a wider interval, so the estimate has higher confidence but is less precise.</em></p>
</div>
</div>
</div>
<div id="exm-ahl416-overlap" class="theorem example">
<p><span class="theorem-title"><strong>例題 4</strong></span> <span class="q-en">Two brands of light bulb are tested. For brand A, a <span class="math inline">\(95\%\)</span> confidence interval for the mean lifetime, in hundreds of hours, is <span class="math inline">\(51.2 &lt; \mu_A &lt; 55.8\)</span>. For brand B, a <span class="math inline">\(95\%\)</span> confidence interval is <span class="math inline">\(54.1 &lt; \mu_B &lt; 58.9\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write down the sample mean lifetime for each brand.</span></p>
<p><strong>(b)</strong> <span class="q-en">A shop advertises that brand B lasts longer on average than brand A. Comment on this claim.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つのブランドの電球を調べました。ブランド A について、平均寿命（<span class="math inline">\(100\)</span> 時間単位）の <span class="math inline">\(95\%\)</span> 信頼区間は <span class="math inline">\(51.2 &lt; \mu_A &lt; 55.8\)</span> です。ブランド B については <span class="math inline">\(54.1 &lt; \mu_B &lt; 58.9\)</span> です。</p>
<p><code>light bulb</code> は「電球」、<code>lifetime</code> は「寿命」、<code>in hundreds of hours</code> は「<span class="math inline">\(100\)</span> 時間を単位として」、<code>advertises</code> は「宣伝する」という意味です。</p>
<p><strong>(a)</strong> 各ブランドの標本平均の寿命を書きなさい。</p>
<p><strong>(b)</strong> ある店が、ブランド B のほうが平均寿命が長いと宣伝しています。この主張について述べなさい。</p>
</details>
<hr>
<p><strong>Method.</strong> この問題では、区間そのものが与えられています。ですから <code>z Interval</code> も <code>t Interval</code> も使いません。読み取るだけです。</p>
<p><strong>(a)</strong> 区間の<strong>まん中が <span class="math inline">\(\bar{x}\)</span></strong> です（<a href="#form">第3節</a>）。</p>
<p><span class="math display">\[
\bar{x}_A = \frac{51.2 + 55.8}{2} = 53.5, \qquad \bar{x}_B = \frac{54.1 + 58.9}{2} = 56.5
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(\bar{x}_B = 56.5\)</span> のほうが大きいのは確かです。しかし、<strong><span class="math inline">\(2\)</span> つの区間は重なっています</strong>（<a href="#compare">第9節</a>）。</p>
<p>重なっているのは、<span class="math inline">\(54.1\)</span> から <span class="math inline">\(55.8\)</span> までです。この範囲の値は、<strong>両方の <span class="math inline">\(\mu\)</span> になりえます。</strong> ですから、<strong>この <span class="math inline">\(2\)</span> つの区間だけを根拠に「B の母平均のほうが大きい」と断定することはできません。</strong> <span class="math inline">\(\mu_A = \mu_B\)</span> という可能性も残ります。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Although the sample mean for brand B (<span class="math inline">\(56.5\)</span>) is larger than for brand A (<span class="math inline">\(53.5\)</span>), the two confidence intervals overlap between <span class="math inline">\(54.1\)</span> and <span class="math inline">\(55.8\)</span> hundred hours. These intervals do not provide sufficient evidence that the population mean lifetime for brand B is larger than that for brand A; the two population means could be equal.</em></p>
</div>
<p>（B の標本平均のほうが大きいが、<span class="math inline">\(2\)</span> つの信頼区間は重なっており、両方の平均が重なりの中にある可能性がある。したがって主張を支持するだけの根拠はない、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\bar{x}_A = 53.5, \qquad \bar{x}_B = 56.5 \quad (\text{hundreds of hours})
\]</span></p>
<p><strong>(b)</strong> <em>The intervals overlap between <span class="math inline">\(54.1\)</span> and <span class="math inline">\(55.8\)</span> hundred hours, so these intervals do not provide sufficient evidence that brand B has the larger population mean lifetime. The two population means could be equal.</em></p>
</div>
</div>
</div>
</section>
<section id="common-errors" class="level2">
<h2 class="anchored" data-anchor-id="common-errors">Common errors</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(\sigma\)</span> と <span class="math inline">\(s\)</span> を読みちがえる
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<code>the sample standard deviation is 2.5</code> を見て、<span class="math inline">\(\sigma\)</span> が与えられたと考える。</p>
<p><span class="math inline">\(\sigma\)</span> と言えるのは、<code>population</code> か「長年の記録から分かっている」という言い方があるときだけです。</p>
<p><strong>正しい判断</strong>：<code>sample</code> としか書かれていなければ <span class="math inline">\(s\)</span>。電卓でも <span class="math inline">\(\sigma_x\)</span> ではなく <span class="math inline">\(s_x\)</span> を読みます（<a href="#which">第5節</a>・<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#calculator">AHL 4.14</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(n\)</span> の大きさで <span class="math inline">\(z\)</span> と <span class="math inline">\(t\)</span> を選ぶ
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<span class="math inline">\(n = 200\)</span> と大きいから <span class="math inline">\(z\)</span>-interval でよい、とする。</p>
<p>シラバスは <code>regardless of sample size</code> と書いています。<span class="math inline">\(n\)</span> の大きさは、選択に関係しません。</p>
<p><strong>正しい判断</strong>：<span class="math inline">\(\sigma\)</span> が未知なら、<span class="math inline">\(n = 200\)</span> でも <span class="math inline">\(t\)</span>-interval です（<a href="#which">第5節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><code>df</code> を確かめない
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<code>t Interval</code> の結果に出た <code>df</code> を見ずに答えを写す。</p>
<p><span class="math inline">\(1\)</span> 標本の <span class="math inline">\(t\)</span>-interval では <span class="math inline">\(\text{df} = n - 1\)</span> なので、ここが合っていなければ <span class="math inline">\(n\)</span> の入力が違っています。</p>
<p><strong>正しい判断</strong>：<span class="math inline">\(n = 8\)</span> なら <code>df</code> は <span class="math inline">\(7\)</span> だと、その場で確かめます（<a href="#df">第6節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><code>C Level</code> に <span class="math inline">\(95\)</span> と入れる
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<code>C Level</code> の欄に <span class="math inline">\(95\)</span> と入力する。</p>
<p>TI-Nspire の <code>C Level</code> は、<strong>小数</strong>で入れる欄です。</p>
<p><strong>正しい判断</strong>：<span class="math inline">\(95\%\)</span> なら <span class="math inline">\(0.95\)</span>、<span class="math inline">\(99\%\)</span> なら <span class="math inline">\(0.99\)</span> と入れます。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>「<span class="math inline">\(\mu\)</span> がこの区間に入る確率は <span class="math inline">\(95\%\)</span>」と書く
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<em>“There is a <span class="math inline">\(95\%\)</span> probability that <span class="math inline">\(\mu\)</span> lies between <span class="math inline">\(47.5\)</span> and <span class="math inline">\(49.7\)</span>.”</em></p>
<p>計算した後は <span class="math inline">\(\mu\)</span> も区間も動かず、変わるのは新しい標本から作られる区間のほうです（<a href="#meaning">第2節</a>）。</p>
<p><strong>正しい判断</strong>：<strong><code>We are 95% confident that ...</code></strong> の型で書きます。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>母平均ではなく、<span class="math inline">\(1\)</span> つ <span class="math inline">\(1\)</span> つの値の区間だと解釈する
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<em>“<span class="math inline">\(95\%\)</span> of the chocolate bars weigh between <span class="math inline">\(47.5\)</span> g and <span class="math inline">\(49.7\)</span> g.”</em></p>
<p>confidence interval は <strong>population mean <span class="math inline">\(\mu\)</span> の居場所</strong>についての区間で、<span class="math inline">\(1\)</span> 枚ずつの重さの散らばりではありません。</p>
<p><strong>正しい判断</strong>：<strong><code>the population mean ...</code></strong> という語を必ず入れます（<a href="#interpret">第8節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>文脈の言葉と単位を書かない
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<em>“We are <span class="math inline">\(95\%\)</span> confident that <span class="math inline">\(\mu\)</span> is between <span class="math inline">\(47.5\)</span> and <span class="math inline">\(49.7\)</span>.”</em></p>
<p>これでは、<span class="math inline">\(\mu\)</span> が<strong>何の母平均か</strong>が分からず、<strong>単位</strong>もありません。</p>
<p><strong>正しい判断</strong>：<em>the population mean mass of a chocolate bar</em> のように、問題の言葉と単位で書きます（<a href="#interpret">第8節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>区間が重なっているのに、「こちらが大きい」と結論する
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：標本平均に差があるから、<span class="math inline">\(\mu_B &gt; \mu_A\)</span> だと断定する。</p>
<p>区間が重なっていれば、<span class="math inline">\(\mu_A = \mu_B\)</span> という可能性が残ります。</p>
<p><strong>正しい判断</strong>：<strong><code>overlap</code></strong> という語を使い、「これらの区間だけでは十分な根拠にならない」と書きます（<a href="#compare">第9節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>confidence level を上げれば、よい答えになると思う
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：<span class="math inline">\(99\%\)</span> の区間のほうが <span class="math inline">\(95\%\)</span> より狭く、精度が高いと考える。</p>
<p>confidence level を上げると critical value が大きくなるので、区間は<strong>広く</strong>なります。</p>
<p><strong>正しい判断</strong>：higher confidence と more precise は別のことです（<a href="#width">第7節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>区間を、<span class="math inline">\(1\)</span> つの数で答える
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>誤り</strong>：「margin of error は <span class="math inline">\(1.10\)</span>」だけを書いて終わる。</p>
<p>答えは<strong>区間</strong>で、両端の <span class="math inline">\(2\)</span> つの数が必要です。</p>
<p><strong>正しい判断</strong>：<span class="math inline">\(47.5 &lt; \mu &lt; 49.7\)</span> のように、<strong>両端を書きます。</strong></p>
</div>
</div>
</section>
<section id="using-your-gdc-ti-nspire-cx-ii" class="level2">
<h2 class="anchored" data-anchor-id="using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</h2>
<p>この項目は、<strong>電卓の操作そのものが中身</strong>です。使うのは <span class="math inline">\(2\)</span> つのメニューだけです。</p>
<pre><code>menu → Statistics → Confidence Intervals</code></pre>
<p>ここに <code>z Interval</code> と <code>t Interval</code> が並んでいます。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>電卓を開く前に、<span class="math inline">\(2\)</span> つ決めます
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>母標準偏差 <span class="math inline">\(\sigma\)</span> が与えられていますか。</strong></p>
<ul>
<li>はい → <strong><code>z Interval</code></strong></li>
<li>いいえ → <strong><code>t Interval</code></strong></li>
</ul>
<p><strong>生データ（数値の列）が与えられていますか。</strong></p>
<ul>
<li>はい → <strong><code>Data</code></strong> を選ぶ</li>
<li>いいえ → <strong><code>Stats</code></strong> を選ぶ</li>
</ul>
</div>
</div>
<section id="gdc-z" class="level3">
<h3 class="anchored" data-anchor-id="gdc-z">1. z Interval — <span class="math inline">\(\sigma\)</span> が分かっているとき</h3>
<pre><code>menu → Statistics → Confidence Intervals → z Interval</code></pre>
<p><code>Data Input Method</code> には <strong><code>Data</code></strong> と <strong><code>Stats</code></strong> があります。<span class="math inline">\(\bar{x}\)</span> と <span class="math inline">\(n\)</span> が与えられている問題では <strong><code>Stats</code></strong> を選びます。次の欄が出ます。</p>
<div id="tbl-ahl416-gdc-z" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-gdc-z-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;5: z Interval の欄
</figcaption>
<div aria-describedby="tbl-ahl416-gdc-z-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>欄</th>
<th>意味</th>
<th>入力例（例題1）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>σ</code></td>
<td>population standard deviation（母標準偏差）</td>
<td><span class="math inline">\(2.5\)</span></td>
</tr>
<tr class="even">
<td><code>x̄</code></td>
<td>標本平均</td>
<td><span class="math inline">\(48.6\)</span></td>
</tr>
<tr class="odd">
<td><code>n</code></td>
<td>標本の大きさ</td>
<td><span class="math inline">\(20\)</span></td>
</tr>
<tr class="even">
<td><code>C Level</code></td>
<td>confidence level（信頼水準）。<strong>小数で</strong></td>
<td><span class="math inline">\(0.95\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>結果の <code>CLower</code> と <code>CUpper</code> が、区間の両端です。</p>
</section>
<section id="gdc-t" class="level3">
<h3 class="anchored" data-anchor-id="gdc-t">2. t Interval — <span class="math inline">\(\sigma\)</span> が分からないとき</h3>
<pre><code>menu → Statistics → Confidence Intervals → t Interval</code></pre>
<p><strong><code>Data Input Method</code> は、<code>z Interval</code> と同じく <code>Data</code> と <code>Stats</code> の <span class="math inline">\(2\)</span> 通り</strong>です。ただし、データの列がそのまま与えられる問題は <code>t Interval</code> のほうによく出ます。</p>
<div id="tbl-ahl416-gdc-t" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-gdc-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;6: t Interval の <span class="math inline">\(2\)</span> つの入れ方
</figcaption>
<div aria-describedby="tbl-ahl416-gdc-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>問題の与えられ方</th>
<th>選ぶもの</th>
<th>入れるもの</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>データの列がある</td>
<td><strong><code>Data</code></strong></td>
<td>列の名前と <code>C Level</code></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{x}\)</span>、<span class="math inline">\(s\)</span>、<span class="math inline">\(n\)</span> だけがある</td>
<td><strong><code>Stats</code></strong></td>
<td><span class="math inline">\(\bar{x}\)</span>、<code>sx</code>、<span class="math inline">\(n\)</span>、<code>C Level</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>データがあるなら <code>Data</code> を選んでください。</strong> 電卓が <span class="math inline">\(\bar{x}\)</span> と <span class="math inline">\(s\)</span> を計算するので、書き写す手間も、丸め誤差も入りません。</p>
<p><code>Stats</code> を選んだときの欄は、こうです。</p>
<div id="tbl-ahl416-gdc-tstats" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-gdc-tstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;7: t Interval（Stats）の欄
</figcaption>
<div aria-describedby="tbl-ahl416-gdc-tstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>欄</th>
<th>意味</th>
<th>入力例（例題3）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>x̄</code></td>
<td>標本平均</td>
<td><span class="math inline">\(68.4\)</span></td>
</tr>
<tr class="even">
<td><code>sx</code></td>
<td>sample standard deviation（標本標準偏差）<span class="math inline">\(s_{n-1}\)</span></td>
<td><span class="math inline">\(5.2\)</span></td>
</tr>
<tr class="odd">
<td><code>n</code></td>
<td>標本の大きさ</td>
<td><span class="math inline">\(20\)</span></td>
</tr>
<tr class="even">
<td><code>C Level</code></td>
<td>confidence level（信頼水準）。<strong>小数で</strong></td>
<td><span class="math inline">\(0.90\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>sx</code> に入れるのは <strong><span class="math inline">\(s_{n-1}\)</span></strong>（電卓の <span class="math inline">\(s_x\)</span>）です。<span class="math inline">\(\sigma_x\)</span> ではありません。</p>
<p>結果には <strong><code>df</code></strong> も表示されます。これは <strong>degrees of freedom</strong>（自由度）で、<span class="math inline">\(1\)</span> 標本の <span class="math inline">\(t\)</span>-interval では <span class="math inline">\(n - 1\)</span> です。<span class="math inline">\(n = 20\)</span> なら <code>df</code> は <span class="math inline">\(19\)</span> になります（<a href="#df">第6節</a>）。</p>
</section>
<section id="gdc-read" class="level3">
<h3 class="anchored" data-anchor-id="gdc-read">3. 結果の読み方</h3>
<p>どちらの機能でも、返ってくる画面には次が並びます。</p>
<div id="tbl-ahl416-gdc-read" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl416-gdc-read-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;8: Confidence Interval の結果
</figcaption>
<div aria-describedby="tbl-ahl416-gdc-read-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>表示</th>
<th>意味</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>CLower</code></td>
<td>区間の下端</td>
</tr>
<tr class="even">
<td><code>CUpper</code></td>
<td>区間の上端</td>
</tr>
<tr class="odd">
<td><code>x̄</code></td>
<td>標本平均。<strong>区間のまん中</strong>になっているか確かめる</td>
</tr>
<tr class="even">
<td><code>ME</code></td>
<td>margin of error（誤差の幅）</td>
</tr>
<tr class="odd">
<td><code>df</code></td>
<td>自由度。<code>t Interval</code> のときだけ出る。<span class="math inline">\(n-1\)</span> になっているか確かめる</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>答案には <code>CLower</code> と <code>CUpper</code> を書きます。</strong> 答えは <strong><span class="math inline">\(3\)</span> 桁</strong>で書きます。丸めるときは、<strong>画面の値から</strong>丸めてください。</p>
</section>
<section id="gdc-check" class="level3">
<h3 class="anchored" data-anchor-id="gdc-check">4. 検算のしかた</h3>
<p><span class="math inline">\(2\)</span> つ、その場でできる確認があります。</p>
<ul>
<li><strong>まん中が <span class="math inline">\(\bar{x}\)</span> か。</strong> <span class="math inline">\(\dfrac{\text{CLower} + \text{CUpper}}{2}\)</span> が <span class="math inline">\(\bar{x}\)</span> になっていなければ、入力が違います</li>
<li><strong><code>df</code> が <span class="math inline">\(n - 1\)</span> か。</strong> <code>t Interval</code> で <span class="math inline">\(n\)</span> を入れ間違えると、ここに出ます</li>
</ul>
</section>
<section id="selfcheck" class="level3">
<h3 class="anchored" data-anchor-id="selfcheck">Exercises の前に — セルフチェック</h3>
<p>Exercises に進む前に、<span class="math inline">\(3\)</span> つだけ確かめてください。</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>1. <span class="math inline">\(\sigma\)</span> が与えられているとき、<span class="math inline">\(z\)</span> と <span class="math inline">\(t\)</span> のどちらを使いますか
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong><span class="math inline">\(z\)</span>-interval</strong> です。<span class="math inline">\(\sigma\)</span> が既知なら normal distribution を使います。<span class="math inline">\(n\)</span> の大きさは関係しません（<a href="#which">第5節</a>）。</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>2. <span class="math inline">\(95\%\)</span> confidence interval は「<span class="math inline">\(\mu\)</span> が <span class="math inline">\(95\%\)</span> の確率で入る」という意味ですか
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>その意味ではありません。</strong> 同じ方法でくり返し作った区間の約 <span class="math inline">\(95\%\)</span> が <span class="math inline">\(\mu\)</span> を含む、という意味です（<a href="#meaning">第2節</a>）。</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>3. <span class="math inline">\(n\)</span> を大きくすると、区間の幅はどうなりますか
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>ほかの条件が同じなら、<strong>狭くなります。</strong> standard error <span class="math inline">\(\dfrac{s}{\sqrt{n}}\)</span> が小さくなるからです（<a href="#width">第7節</a>）。</p>
</div>
</div>
</div>
</section>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>各問題に、折りたたみが3つ付いています。<strong>日本語訳</strong>、<strong>解答例</strong>（答案用紙に書くべきこと。英語です）、<strong>解説</strong>（なぜそうなるか。日本語です）。</p>
<p>まず自分で解いて、次に解答例と見くらべてください。<strong>解説は、合わなかったときだけ開けば十分です。</strong></p>
</div>
</div>
</div>
<div class="exercise-block">
<p><span class="ex-no">1</span> <span class="q-en">A population is normally distributed with known standard deviation <span class="math inline">\(\sigma = 6\)</span>. A random sample of <span class="math inline">\(36\)</span> observations has mean <span class="math inline">\(82\)</span>. Find a <span class="math inline">\(95\%\)</span> confidence interval for the population mean.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある母集団は正規分布にしたがい、母標準偏差は <span class="math inline">\(\sigma = 6\)</span> と分かっています。<span class="math inline">\(36\)</span> 個の観測値からなる無作為標本の平均は <span class="math inline">\(82\)</span> でした。母平均の <span class="math inline">\(95\%\)</span> 信頼区間を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>Method: <span class="math inline">\(\sigma\)</span> is known, so a <span class="math inline">\(z\)</span>-interval is used.</em> <span class="math display">\[
80.0 &lt; \mu &lt; 84.0
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>known standard deviation σ = 6</code> とあるので <strong>normal</strong> です（<a href="#which">第5節</a>）。</p>
<pre><code>z Interval → Stats:   σ: 6   x̄: 82   n: 36   C Level: 0.95</code></pre>
<p><strong>検算。</strong> standard error は <span class="math inline">\(\dfrac{6}{\sqrt{36}} = 1\)</span>。critical value が <span class="math inline">\(1.96\)</span> なので margin of error は <span class="math inline">\(1.96\)</span>。まん中の <span class="math inline">\(82\)</span> から <span class="math inline">\(\pm 1.96\)</span> で、<span class="math inline">\((80.04,\ 83.96)\)</span> です ✓</p>
<p><span class="math inline">\(3\)</span> 桁に丸めて <span class="math inline">\(80.0\)</span> と <span class="math inline">\(84.0\)</span> ですが、<strong><span class="math inline">\(0\)</span> を落として <span class="math inline">\(80\)</span>、<span class="math inline">\(84\)</span> と書かないでください。</strong> 有効数字が変わります。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">2</span> <span class="q-en">A normally distributed population is sampled. A random sample of <span class="math inline">\(12\)</span> items has mean <span class="math inline">\(45.2\)</span> and an unbiased estimate of the population standard deviation of <span class="math inline">\(3.8\)</span>. Find a <span class="math inline">\(95\%\)</span> confidence interval for the population mean.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある正規母集団から標本をとります。<span class="math inline">\(12\)</span> 個の品物からなる無作為標本の平均は <span class="math inline">\(45.2\)</span>、母標準偏差の不偏推定値は <span class="math inline">\(3.8\)</span> でした。母平均の <span class="math inline">\(95\%\)</span> 信頼区間を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>Method: <span class="math inline">\(\sigma\)</span> is unknown, so a <span class="math inline">\(t\)</span>-interval is used.</em> <span class="math display">\[
42.8 &lt; \mu &lt; 47.6
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>unbiased estimate of the population standard deviation</code> は <span class="math inline">\(s_{n-1}\)</span> です。<strong><span class="math inline">\(\sigma\)</span> ではありません。</strong> ですから <strong><span class="math inline">\(t\)</span></strong> を使います（<a href="#which">第5節</a>）。</p>
<pre><code>t Interval → Stats:   x̄: 45.2   sx: 3.8   n: 12   C Level: 0.95</code></pre>
<p><code>df</code> は <span class="math inline">\(12 - 1 = 11\)</span> で、critical value は <span class="math inline">\(2.20\)</span> です。</p>
<p><strong>検算。</strong> まん中は <span class="math inline">\(\dfrac{42.8 + 47.6}{2} = 45.2 = \bar{x}\)</span> ✓</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">3</span> <span class="q-en">The mass of an apple is normally distributed. The masses, in grams, of ten randomly chosen apples are</span></p>
<p><span class="math display">\[
203, \quad 198, \quad 207, \quad 201, \quad 199, \quad 204, \quad 202, \quad 196, \quad 205, \quad 200
\]</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the sample mean and an unbiased estimate of the population standard deviation.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find a <span class="math inline">\(99\%\)</span> confidence interval for the mean mass of an apple.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>りんご <span class="math inline">\(1\)</span> 個の重さは正規分布にしたがいます。無作為に選んだ <span class="math inline">\(10\)</span> 個のりんごの重さ（グラム）は、上のとおりです。</p>
<p><strong>(a)</strong> 標本平均と、母標準偏差の不偏推定値を求めなさい。</p>
<p><strong>(b)</strong> りんご <span class="math inline">\(1\)</span> 個の平均の重さについて、<span class="math inline">\(99\%\)</span> 信頼区間を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\bar{x} = 201.5, \qquad s_{n-1} = 3.37
\]</span></p>
<p><strong>(b)</strong> <em>Method: <span class="math inline">\(\sigma\)</span> is unknown, so a <span class="math inline">\(t\)</span>-interval is used.</em> <span class="math display">\[
198 &lt; \mu &lt; 205 \quad (\text{g})
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 合計は <span class="math inline">\(2015\)</span> なので <span class="math inline">\(\bar{x} = 201.5\)</span>。<span class="math inline">\(s_x\)</span> のほうを読みます（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html#calculator">AHL 4.14</a>）。</p>
<p><strong>(b)</strong> データの列があるので、<code>t Interval</code> の <strong><code>Data</code></strong> を選べます（<a href="#gdc-t">GDC 第2節</a>）。<span class="math inline">\(\bar{x}\)</span> と <span class="math inline">\(s\)</span> を書き写す必要がありません。</p>
<p><code>df</code> <span class="math inline">\(= 9\)</span>、critical value は <span class="math inline">\(3.25\)</span> です。<strong><span class="math inline">\(99\%\)</span> なので、critical value がかなり大きくなっています。</strong></p>
<p>生の値は <span class="math inline">\((198.03,\ 204.97)\)</span> で、<span class="math inline">\(3\)</span> 桁だと <span class="math inline">\(198\)</span> と <span class="math inline">\(205\)</span> です。</p>
<p><strong>検算。</strong> まん中は <span class="math inline">\(201.5 = \bar{x}\)</span> ✓</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">4</span> <span class="q-en">For each of the following, state whether a <span class="math inline">\(z\)</span>-interval or a <span class="math inline">\(t\)</span>-interval should be used, and give a reason.</span></p>
<p><strong>(a)</strong> <span class="q-en">A sample of <span class="math inline">\(8\)</span> measurements, where the population standard deviation is known to be <span class="math inline">\(1.2\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">A sample of <span class="math inline">\(200\)</span> measurements, where the sample standard deviation is <span class="math inline">\(4.7\)</span> and the population standard deviation is not known.</span></p>
<p><strong>(c)</strong> <span class="q-en">A list of <span class="math inline">\(15\)</span> data values, with no other information given.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>次のそれぞれについて、<span class="math inline">\(z\)</span> 区間と <span class="math inline">\(t\)</span> 区間のどちらを使うべきかを述べ、理由を書きなさい。</p>
<p><strong>(a)</strong> <span class="math inline">\(8\)</span> 個の測定値からなる標本で、母標準偏差が <span class="math inline">\(1.2\)</span> と分かっている場合。</p>
<p><strong>(b)</strong> <span class="math inline">\(200\)</span> 個の測定値からなる標本で、標本標準偏差が <span class="math inline">\(4.7\)</span>、母標準偏差は分かっていない場合。</p>
<p><strong>(c)</strong> <span class="math inline">\(15\)</span> 個のデータの値の列だけが与えられ、ほかに情報がない場合。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em><span class="math inline">\(z\)</span>-interval. The population standard deviation is known, so the normal distribution is used.</em></p>
<p><strong>(b)</strong> <em><span class="math inline">\(t\)</span>-interval. The population standard deviation is unknown, so the <span class="math inline">\(t\)</span>-distribution is used regardless of the sample size, even though <span class="math inline">\(n = 200\)</span> is large.</em></p>
<p><strong>(c)</strong> <em><span class="math inline">\(t\)</span>-interval. Only sample data is given, so the population standard deviation is unknown.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><a href="#tbl-ahl416-which">第5節の表</a>が、そのまま答えになる問題です。</p>
<p><strong>(a)</strong> <span class="math inline">\(n = 8\)</span> と小さくても、<strong><span class="math inline">\(\sigma\)</span> が分かっていれば normal</strong> です。<span class="math inline">\(n\)</span> の大きさは関係しません。</p>
<p><strong>(b)</strong> ここが狙いです。<strong><span class="math inline">\(n = 200\)</span> でも <span class="math inline">\(t\)</span></strong> です。シラバスの <code>regardless of sample size</code> がそのまま出ています。</p>
<p><strong>(c)</strong> データしかないなら、<span class="math inline">\(s\)</span> は標本から出すしかありません。ですから <span class="math inline">\(t\)</span> です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>(a) <span class="math inline">\(z\)</span>-interval, because <span class="math inline">\(\sigma\)</span> is known.</em></p>
<p><em>(b) <span class="math inline">\(t\)</span>-interval, because <span class="math inline">\(\sigma\)</span> is unknown. The size of the sample does not matter: a <span class="math inline">\(t\)</span>-interval is used regardless of sample size.</em></p>
<p><em>(c) <span class="math inline">\(t\)</span>-interval, because only sample data is available and so <span class="math inline">\(\sigma\)</span> is unknown.</em></p>
</div>
<p><strong>(b) で <code>regardless of sample size</code> に触れているかどうか</strong>が、読まれるところです。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">5</span> <span class="q-en">A normally distributed population has known standard deviation <span class="math inline">\(\sigma = 9\)</span>. A sample of <span class="math inline">\(16\)</span> observations gives a <span class="math inline">\(95\%\)</span> confidence interval of width <span class="math inline">\(8.82\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the width of a <span class="math inline">\(95\%\)</span> confidence interval if the sample size is increased to <span class="math inline">\(64\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">Explain why increasing the sample size makes the interval narrower.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある正規母集団の母標準偏差は <span class="math inline">\(\sigma = 9\)</span> と分かっています。<span class="math inline">\(16\)</span> 個の観測値からなる標本から作った <span class="math inline">\(95\%\)</span> 信頼区間の幅は <span class="math inline">\(8.82\)</span> でした。</p>
<p><strong>(a)</strong> 標本の大きさを <span class="math inline">\(64\)</span> に増やしたとき、<span class="math inline">\(95\%\)</span> 信頼区間の幅を求めなさい。</p>
<p><strong>(b)</strong> 標本を大きくすると区間が狭くなる理由を説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\text{width} = \frac{8.82}{2} = 4.41
\]</span></p>
<p><strong>(b)</strong> <em>The width depends on the standard error <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span>. Multiplying <span class="math inline">\(n\)</span> by <span class="math inline">\(4\)</span> multiplies <span class="math inline">\(\sqrt{n}\)</span> by <span class="math inline">\(2\)</span>, so the standard error, and therefore the width, is halved. A larger sample gives a more precise estimate of the mean.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-44-contents" aria-controls="callout-44" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-44" class="callout-44-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(\sigma\)</span> が既知なので、critical value は <span class="math inline">\(1.96\)</span> のまま<strong>動きません。</strong> 変わるのは standard error だけです。</p>
<p><span class="math display">\[
\frac{9}{\sqrt{16}} = 2.25 \qquad \to \qquad \frac{9}{\sqrt{64}} = 1.125
\]</span></p>
<p><span class="math inline">\(n\)</span> が <span class="math inline">\(4\)</span> 倍になると <span class="math inline">\(\sqrt{n}\)</span> は <span class="math inline">\(2\)</span> 倍なので、<strong>ちょうど半分</strong>です。</p>
<p><strong><span class="math inline">\(t\)</span> を使うときは、ちょうど半分にはなりません。</strong> critical value も一緒に小さくなるので、半分より少し狭くなります（<a href="#width">第7節</a>）。</p>
<p><strong>(b)</strong> <code>Explain why</code> なので、<strong>式と言葉の両方</strong>を書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The half-width of the interval is the critical value multiplied by the standard error <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span>. Increasing <span class="math inline">\(n\)</span> decreases <span class="math inline">\(\dfrac{\sigma}{\sqrt{n}}\)</span>, so the interval becomes narrower. Intuitively, a larger sample gives more information about the population, so the mean can be pinned down more precisely.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">6</span> <span class="q-en">A <span class="math inline">\(95\%\)</span> confidence interval for the mean time, in minutes, taken to complete a task is <span class="math inline">\(23.4 &lt; \mu &lt; 26.6\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write down the sample mean.</span></p>
<p><strong>(b)</strong> <span class="q-en">Write down the margin of error.</span></p>
<p><strong>(c)</strong> <span class="q-en">Interpret the confidence interval in context.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある作業を終えるのにかかる平均時間（分）についての <span class="math inline">\(95\%\)</span> 信頼区間は <span class="math inline">\(23.4 &lt; \mu &lt; 26.6\)</span> です。</p>
<p><code>margin of error</code> は「誤差の幅」という意味です。</p>
<p><strong>(a)</strong> 標本平均を書きなさい。</p>
<p><strong>(b)</strong> 誤差の幅を書きなさい。</p>
<p><strong>(c)</strong> この信頼区間を、文脈の中で解釈しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\bar{x} = \frac{23.4 + 26.6}{2} = 25.0 \text{ minutes}
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
\text{margin of error} = \frac{26.6 - 23.4}{2} = 1.6 \text{ minutes}
\]</span></p>
<p><strong>(c)</strong> <em>We are <span class="math inline">\(95\%\)</span> confident that the population mean time taken to complete the task lies between <span class="math inline">\(23.4\)</span> and <span class="math inline">\(26.6\)</span> minutes.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-46-contents" aria-controls="callout-46" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-46" class="callout-46-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)(b)</strong> 区間は「<strong><span class="math inline">\(\bar{x}\)</span> <span class="math inline">\(\pm\)</span> margin of error</strong>」の形でした（<a href="#form">第3節</a>）。ですから中心は<strong>まん中</strong>、margin of error は<strong>幅の半分</strong>です。</p>
<p>幅そのものは <span class="math inline">\(3.2\)</span> 分ですが、margin of error はその<strong>半分</strong>の <span class="math inline">\(1.6\)</span> 分です。ここを取りちがえないでください。</p>
<p><strong>(c)</strong> <code>Interpret</code> なので、<strong>文脈の言葉で</strong>書きます（<a href="#interpret">第8節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>We are <span class="math inline">\(95\%\)</span> confident that the population mean time taken to complete the task lies between <span class="math inline">\(23.4\)</span> and <span class="math inline">\(26.6\)</span> minutes.</em></p>
</div>
<p><strong><code>the population mean time</code></strong> と書くこと、<strong><code>minutes</code></strong> という単位を入れることの <span class="math inline">\(2\)</span> つが、点になるところです。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">7</span> <span class="q-en">Using the confidence interval <span class="math inline">\(23.4 &lt; \mu &lt; 26.6\)</span> from question 6, comment on each of the following claims.</span></p>
<p><strong>(a)</strong> <span class="q-en">A manager claims that the mean time is <span class="math inline">\(27\)</span> minutes.</span></p>
<p><strong>(b)</strong> <span class="q-en">A worker claims that the mean time is <span class="math inline">\(24\)</span> minutes.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>問題 6 の信頼区間 <span class="math inline">\(23.4 &lt; \mu &lt; 26.6\)</span> を使って、次のそれぞれの主張について述べなさい。</p>
<p><strong>(a)</strong> ある管理者は、平均時間は <span class="math inline">\(27\)</span> 分だと主張しています。</p>
<p><strong>(b)</strong> ある作業者は、平均時間は <span class="math inline">\(24\)</span> 分だと主張しています。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em><span class="math inline">\(27\)</span> lies outside the interval <span class="math inline">\(23.4 &lt; \mu &lt; 26.6\)</span>, so the data does not support the manager’s claim.</em></p>
<p><strong>(b)</strong> <em><span class="math inline">\(24\)</span> lies inside the interval, so the data is consistent with the worker’s claim. However, this does not prove that the mean is exactly <span class="math inline">\(24\)</span> minutes: every other value in the interval is also consistent with the data.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-48-contents" aria-controls="callout-48" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-48" class="callout-48-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(27 &gt; 26.6\)</span> なので、区間の<strong>外</strong>です。</p>
<p><strong>(b)</strong> <span class="math inline">\(24\)</span> は区間の中です。ただし、ここで<strong>言い過ぎないこと</strong>が大事です。</p>
<p>区間の中にある値は、<strong>どれもこのデータと矛盾しません。</strong> <span class="math inline">\(24\)</span> も <span class="math inline">\(25\)</span> も <span class="math inline">\(26\)</span> も、この区間の中です。<strong>「平均は <span class="math inline">\(24\)</span> 分だと証明された」わけではありません。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>(a) <span class="math inline">\(27\)</span> minutes lies outside the confidence interval, so the data does not support this claim.</em></p>
<p><em>(b) <span class="math inline">\(24\)</span> minutes lies inside the confidence interval, so the claim is consistent with the data. However, every other value in the interval is also consistent with the data, so this does not show that the mean is exactly <span class="math inline">\(24\)</span> minutes.</em></p>
</div>
<p><code>comment on</code> なので、<strong>言えることと言えないことの両方</strong>を書くと強い答案になります。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">8</span> <span class="q-en">Two teaching methods are compared. Test scores are normally distributed. A <span class="math inline">\(95\%\)</span> confidence interval for the mean score using method A is <span class="math inline">\(51.0 &lt; \mu_A &lt; 54.0\)</span>, and for method B is <span class="math inline">\(56.0 &lt; \mu_B &lt; 59.0\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write down the sample mean score for each method.</span></p>
<p><strong>(b)</strong> <span class="q-en">A school decides to use method B. Comment on whether the data supports this decision.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(2\)</span> つの指導法を比べました。得点は正規分布にしたがいます。指導法 A を使ったときの平均点の <span class="math inline">\(95\%\)</span> 信頼区間は <span class="math inline">\(51.0 &lt; \mu_A &lt; 54.0\)</span>、指導法 B については <span class="math inline">\(56.0 &lt; \mu_B &lt; 59.0\)</span> です。</p>
<p><strong>(a)</strong> 各指導法の標本平均の得点を書きなさい。</p>
<p><strong>(b)</strong> ある学校が指導法 B を使うことに決めました。データがこの決定を支持しているかどうかを述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-49-contents" aria-controls="callout-49" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-49" class="callout-49-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\bar{x}_A = 52.5, \qquad \bar{x}_B = 57.5
\]</span></p>
<p><strong>(b)</strong> <em>The two confidence intervals do not overlap: the whole of the interval for method A lies below the whole of the interval for method B. Every value in the interval for <span class="math inline">\(\mu_A\)</span> is smaller than every value in the interval for <span class="math inline">\(\mu_B\)</span>, so the data does support the claim that method B gives a higher mean score. This is a stronger conclusion than in the overlapping case, where the two means could have been equal.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-50-contents" aria-controls="callout-50" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-50" class="callout-50-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>例題4 と対になる問題</strong>です。あちらは区間が<strong>重なって</strong>いて、こちらは<strong>重なっていません。</strong></p>
<p><strong>(a)</strong> 中点をとります。<span class="math inline">\(\dfrac{51.0 + 54.0}{2} = 52.5\)</span>、<span class="math inline">\(\dfrac{56.0 + 59.0}{2} = 57.5\)</span>。</p>
<p><strong>(b)</strong> 例題4 では「言えない」でしたが、ここでは<strong>言えます。</strong></p>
<p>区間に入っている値は、<span class="math inline">\(\mu_A\)</span> 側が <span class="math inline">\(54.0\)</span> まで、<span class="math inline">\(\mu_B\)</span> 側が <span class="math inline">\(56.0\)</span> から。<strong>この <span class="math inline">\(2\)</span> つが重ならない</strong>ので、<span class="math inline">\(\mu_A = \mu_B\)</span> は考えにくくなります。</p>
<p>ただし、<span class="math inline">\(2\)</span> つの区間はどちらも「外すことがある」作り方で作ったものです（<a href="#meaning">第2節</a>）。<strong><span class="math inline">\(\mu_A = \mu_B\)</span> があり得ないと証明された</strong>わけではありません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The intervals do not overlap, since <span class="math inline">\(54.0 &lt; 56.0\)</span>. Every value in the interval for <span class="math inline">\(\mu_A\)</span> is below every value in the interval for <span class="math inline">\(\mu_B\)</span>, so the data supports the claim that method B has the higher population mean score.</em></p>
</div>
<p><strong>重なっているかいないかで、書ける結論がまったく変わります</strong>（<a href="#compare">第9節</a>）。答案では、まず<strong>重なりを確かめてから</strong>書き始めてください。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">9</span> <span class="q-en">A machine fills packets. The mass of the contents is normally distributed, and the population standard deviation is known to be <span class="math inline">\(15\)</span> g. A sample of <span class="math inline">\(25\)</span> packets has mean <span class="math inline">\(500\)</span> g.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find a <span class="math inline">\(90\%\)</span> confidence interval for the mean mass of the contents.</span></p>
<p><strong>(b)</strong> <span class="q-en">Find a <span class="math inline">\(99\%\)</span> confidence interval.</span></p>
<p><strong>(c)</strong> <span class="q-en">State which interval a quality inspector should prefer, and give a reason.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある機械が袋づめをします。中身の重さは正規分布にしたがい、母標準偏差は <span class="math inline">\(15\)</span> g と分かっています。<span class="math inline">\(25\)</span> 袋の標本の平均は <span class="math inline">\(500\)</span> g でした。</p>
<p><code>quality inspector</code> は「品質検査官」という意味です。</p>
<p><strong>(a)</strong> 中身の平均の重さについて、<span class="math inline">\(90\%\)</span> 信頼区間を求めなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(99\%\)</span> 信頼区間を求めなさい。</p>
<p><strong>(c)</strong> 品質検査官はどちらの区間を選ぶべきかを述べ、理由を書きなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-51-contents" aria-controls="callout-51" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-51" class="callout-51-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Method: <span class="math inline">\(\sigma\)</span> is known, so a <span class="math inline">\(z\)</span>-interval is used.</em> <span class="math display">\[
495 &lt; \mu &lt; 505 \quad (\text{g})
\]</span></p>
<p><strong>(b)</strong> <span class="math display">\[
492 &lt; \mu &lt; 508 \quad (\text{g})
\]</span></p>
<p><strong>(c)</strong> <em>The inspector should prefer the <span class="math inline">\(99\%\)</span> interval. It is wider (<span class="math inline">\(15.5\)</span> g against <span class="math inline">\(9.87\)</span> g) and so gives a less precise estimate, but it is much less likely to miss the true mean, and in quality control the cost of an undetected error is high.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-52-contents" aria-controls="callout-52" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-52" class="callout-52-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)(b)</strong> <span class="math inline">\(\sigma\)</span> が既知なので <code>z Interval</code> です。standard error は <span class="math inline">\(\dfrac{15}{\sqrt{25}} = 3\)</span>。</p>
<p>生の値は <span class="math inline">\((495.07,\ 504.93)\)</span> と <span class="math inline">\((492.27,\ 507.73)\)</span> です。<span class="math inline">\(3\)</span> 桁で <span class="math inline">\(495\)</span> と <span class="math inline">\(505\)</span>、<span class="math inline">\(492\)</span> と <span class="math inline">\(508\)</span>。</p>
<p><strong>(c)</strong> <code>give a reason</code> なので理由が要ります。<strong>どちらを選んでも、理由が通っていれば正解</strong>になる問題です。</p>
<p>大事なのは、<strong>取り引きの関係</strong>（<a href="#width">第7節</a>）に触れることです。<span class="math inline">\(99\%\)</span> は当たりやすいが大ざっぱ、<span class="math inline">\(90\%\)</span> は細かいが外しやすい。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The inspector should prefer the <span class="math inline">\(99\%\)</span> interval. It is wider (<span class="math inline">\(15.5\)</span> g compared with <span class="math inline">\(9.87\)</span> g) and so less precise, but it is much less likely to miss the true mean. In quality control, the cost of failing to detect a problem is usually higher than the cost of a less precise estimate.</em></p>
</div>
<p><strong>「どちらか一方が正しい」という問題ではありません。</strong> 両方の性質を比べて書けているかが読まれます。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">10</span> <span class="q-en">Explain why a <span class="math inline">\(95\%\)</span> confidence interval calculated from a sample does not mean that <span class="math inline">\(95\%\)</span> of the population lies within that interval.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>標本から計算した <span class="math inline">\(95\%\)</span> 信頼区間について、それが「母集団の <span class="math inline">\(95\%\)</span> がその区間に入る」という意味ではない理由を説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-53-contents" aria-controls="callout-53" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-53" class="callout-53-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>A confidence interval is an interval for the population <strong>mean</strong> <span class="math inline">\(\mu\)</span>, not for individual values. It is built from the standard error <span class="math inline">\(\dfrac{s}{\sqrt{n}}\)</span>, which measures how much the sample mean varies, not how much individual data values vary. Individual values are spread out by about <span class="math inline">\(s\)</span>, which is <span class="math inline">\(\sqrt{n}\)</span> times the standard error, so they are spread over a much wider range than the confidence interval.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-54-contents" aria-controls="callout-54" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-54" class="callout-54-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>Explain why</code> なので、<strong>何と何を取りちがえているのか</strong>をはっきり書きます。</p>
<p>区間の幅を決めているのは <span class="math inline">\(\dfrac{s}{\sqrt{n}}\)</span> です。これは<strong>標本平均のばらつき</strong>であって、<strong><span class="math inline">\(1\)</span> つ <span class="math inline">\(1\)</span> つの値のばらつき</strong>ではありません（<a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html#narrower">AHL 4.15</a>）。</p>
<p><span class="math inline">\(1\)</span> つ <span class="math inline">\(1\)</span> つの値は、<span class="math inline">\(s\)</span> くらいの幅で散らばっています。これは <strong>standard error の <span class="math inline">\(\sqrt{n}\)</span> 倍</strong>です。<span class="math inline">\(n = 25\)</span> なら <span class="math inline">\(5\)</span> 倍になります。</p>
<p>ですから、信頼区間の中に母集団の <span class="math inline">\(95\%\)</span> が入る、ということはまずありません。<strong>もっと狭い区間</strong>です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The confidence interval estimates the population mean, not individual values. Its width comes from the standard error <span class="math inline">\(\dfrac{s}{\sqrt{n}}\)</span>, which describes the variability of the sample mean. Individual values vary by about <span class="math inline">\(s\)</span>, which is <span class="math inline">\(\sqrt{n}\)</span> times the standard error, so they are spread over a far wider range than the interval.</em></p>
</div>
<p><a href="#interpret">第8節</a>の Common error と、同じ論点です。</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>このページの要点
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>confidence interval（信頼区間）は、母平均 <span class="math inline">\(\mu\)</span> を <span class="math inline">\(1\)</span> つの数ではなく<strong>範囲</strong>で推定する方法です。</li>
<li><strong><span class="math inline">\(\sigma\)</span> が既知なら <span class="math inline">\(z\)</span>-interval、未知なら <span class="math inline">\(t\)</span>-interval</strong> を使います。<span class="math inline">\(n\)</span> の大きさでは決めません。</li>
<li>区間は、いつも <strong><span class="math inline">\(\bar{x}\)</span> <span class="math inline">\(\pm\)</span> margin of error</strong> の形になります。</li>
<li>答案では、<strong>confidence level・何の母平均か・区間・単位</strong>を文章で書きます。</li>
</ul>
</div>
</div>
<p>信頼区間で「もっともらしい母平均の範囲」を求められるようになりました。この考え方をさらに進めて、<strong>特定の値についての主張がデータと矛盾しないか</strong>を判断するのが、<a href="../../ai-hl/04-statistics-and-probability/ahl-4-18b.html">AHL 4.18b</a> の hypothesis testing（仮説検定）です。</p>


</section>
</section>

</main> <!-- /main -->
<!--
  Cookie 同意バナーの本文を差しかえるスクリプト。

  Quarto の cookie-consent は termsfeed のライブラリを使っていて、
  lang: ja のおかげで表示は日本語になります。ただし既定の本文が

    「…パーソナライズされたコンテンツやターゲット広告を表示するため…」

  となっていて、広告を出さないこのサイトの実態と合いません。
  ライブラリ側に文面を差しかえる設定が無いので、バナーが出たあとに
  #cc-nb-text の中身だけを書きかえています。

  ★ 文面を変えるときは、下の NB の中身だけを直してください。
  ★ 読み込みは _quarto.yml の format.html.include-after-body です。
-->
<script>
(function () {
  var NB = "このサイトでは、どのページがどれくらい読まれているかを知るために、"
         + "Google アナリティクスの Cookie を使っています。"
         + "広告の配信や、個人を特定する目的には使いません。";

  function fix() {
    var el = document.getElementById("cc-nb-text");
    if (!el) { return false; }
    if (el.textContent !== NB) { el.textContent = NB; }
    return true;
  }

  // バナーはページ読み込みのあとに差し込まれるので、出てくるまで待つ。
  if (!fix()) {
    var mo = new MutationObserver(function () { if (fix()) { mo.disconnect(); } });
    mo.observe(document.body, { childList: true, subtree: true });
    setTimeout(function () { mo.disconnect(); }, 10000);
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "コピーしました");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "コピーしました");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/edusalonself\.github\.io\/ib-math-ai-sl-jp\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html" class="pagination-link" aria-label="AHL 4.15 — Linear combinations of normal variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">AHL 4.15 — Linear combinations of normal variables</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../ai-hl/04-statistics-and-probability/ahl-4-17.html" class="pagination-link" aria-label="AHL 4.17 — The Poisson distribution">
        <span class="nav-page-text">AHL 4.17 — The Poisson distribution</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 学習サロン SELF</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/">
<p>学習サロン SELF</p>
</a>
  </li>  
</ul>
    <div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie の設定</a></div></div>
    <div class="nav-footer-right">
<p>IB（国際バカロレア機構）とは関係のない独立した教材です</p>
</div>
  </div>
</footer>




</body></html>