<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ahl-4-12 – 日本語で読む IB数学</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html" rel="next">
<link href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-16.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3d27ed94b0b15b9bda3c32201c09d63a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "一致なし",
    "search-matching-documents-text": "一致した文書",
    "search-copy-link-title": "検索へのリンクをコピー",
    "search-hide-matches-text": "追加の検索結果を非表示",
    "search-more-match-text": "追加の検索結果",
    "search-more-matches-text": "追加の検索結果",
    "search-clear-button-title": "消去",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "検索",
    "search-label": "サーチ"
  }
}</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"ja"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">日本語で読む IB数学</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="サーチ"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="ナビゲーションを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../ai-sl/index.html"> 
<span class="menu-text">AI SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../glossary-ai.html"> 
<span class="menu-text">英日対訳表（AI）</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../ai-hl/index.html" aria-current="page"> 
<span class="menu-text">AI HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-sl/index.html"> 
<span class="menu-text">AA SL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../aa-hl/index.html"> 
<span class="menu-text">AA HL</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../which-course.html"> 
<span class="menu-text">AI と AA、どちらを取るか</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/"> 
<span class="menu-text">学習サロン SELF</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">AHL 4.12 — Data collection and χ² categorisation</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="サイドバーを切り替える" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IB数学 AI HL</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 1 — Number and algebra</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.9 — Laws of logarithms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.14 — Matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/01-number-and-algebra/ahl-1-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 1.15 — Eigenvalues and eigenvectors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 3 — Geometry and trigonometry</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.9 — Geometric transformations in two dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.14 — Graph theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.15 — Adjacency matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 3.16 — Tree and cycle algorithms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Topic 4 — Statistics and probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">AHL 4.12 — Data collection and χ² categorisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.13 — Non-linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.14 — Linear transformation of a single random variable</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.15 — Linear combinations of normal variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.16 — Confidence intervals for the mean of a normal population</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.17 — The Poisson distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18a — Critical values and critical regions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18b — Tests for a mean, a proportion and ρ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-18c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.18c — Type I and Type II errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/04-statistics-and-probability/ahl-4-19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 4.19 — Transition matrices</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Topic 5 — Calculus</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="セクションを切り替え">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.14 — Setting up a differential equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.15 — Slope fields</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16a — Euler’s method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-16b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.16b — Euler’s method for coupled systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17a — Phase portraits: real eigenvalues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ai-hl/05-calculus/ahl-5-17b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AHL 5.17b — Phase portraits: complex eigenvalues</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">このページの内容</h2>
   
  <ul>
  <li><a href="#sec-ahl-4-12" id="toc-sec-ahl-4-12" class="nav-link active" data-scroll-target="#sec-ahl-4-12">AHL 4.12 — Data collection and χ² categorisation（データの集め方と χ² のカテゴリ分け）</a>
  <ul class="collapse">
  <li><a href="#the-idea" id="toc-the-idea" class="nav-link" data-scroll-target="#the-idea">The idea</a>
  <ul class="collapse">
  <li><a href="#idea" id="toc-idea" class="nav-link" data-scroll-target="#idea">1. データを「作る側」に回ります</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">2. 質問のしかたで、答えが変わります</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">3. たくさんの変数から、調べるものを選びます</a></li>
  <li><a href="#rel-val" id="toc-rel-val" class="nav-link" data-scroll-target="#rel-val">4. reliability と validity は、別のことです</a></li>
  <li><a href="#categorise" id="toc-categorise" class="nav-link" data-scroll-target="#categorise">5. 数値データを、カテゴリに区切ります</a></li>
  <li><a href="#df" id="toc-df" class="nav-link" data-scroll-target="#df">6. 自由度は、推定した母数の数だけ減ります</a></li>
  </ul></li>
  <li><a href="#why-it-works" id="toc-why-it-works" class="nav-link" data-scroll-target="#why-it-works">Why it works</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples">Worked examples</a></li>
  <li><a href="#common-errors" id="toc-common-errors" class="nav-link" data-scroll-target="#common-errors">Common errors</a></li>
  <li><a href="#using-your-gdc-ti-nspire-cx-ii" id="toc-using-your-gdc-ti-nspire-cx-ii" class="nav-link" data-scroll-target="#using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</a>
  <ul class="collapse">
  <li><a href="#gdc-normcdf" id="toc-gdc-normcdf" class="nav-link" data-scroll-target="#gdc-normcdf">1. normal の期待度数を作る</a></li>
  <li><a href="#gdc-gof" id="toc-gdc-gof" class="nav-link" data-scroll-target="#gdc-gof">2. goodness of fit を走らせる</a></li>
  <li><a href="#gdc-onevar" id="toc-gdc-onevar" class="nav-link" data-scroll-target="#gdc-onevar">3. 平均と標準偏差を、表から出す</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">Topic 4 — Statistics and probability</a></li><li class="breadcrumb-item"><a href="../../ai-hl/04-statistics-and-probability/ahl-4-12.html">AHL 4.12 — Data collection and χ² categorisation</a></li></ol></nav></header>




<section id="sec-ahl-4-12" class="level1">
<h1>AHL 4.12 — Data collection and χ² categorisation（データの集め方と χ² のカテゴリ分け）</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>What you should be able to do
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>survey</strong>（調査）や <strong>questionnaire</strong>（アンケート）の質問を見て、<strong>biased</strong>（かたよった）・<strong>personal</strong>（個人的な）・<strong>unstructured</strong>（選択肢のない）・<strong>imprecise</strong>（あいまいな）ところを指摘し、直せる。</li>
<li>たくさんある変数の中から、<strong>調べたい問いに関係する変数を選べる</strong>。</li>
<li><strong>reliability</strong>（信頼性）と <strong>validity</strong>（妥当性）のちがいを説明し、<strong>test-retest</strong>（再テスト法）・<strong>parallel forms</strong>（平行検査法）・<strong>content</strong>・<strong>criterion-related</strong> の <span class="math inline">\(4\)</span> つを使い分けられる。</li>
<li>数値データを <span class="math inline">\(\chi^2\)</span> の表の<strong>カテゴリに区切り</strong>、その区切り方を<strong>説明できる</strong>。</li>
<li><strong>expected frequency</strong>（期待度数）が <span class="math inline">\(5\)</span> より大きくなるように、<strong>カテゴリをまとめられる</strong>。</li>
<li>goodness of fit で、<strong>データから推定した母数の数だけ自由度が減る</strong>ことを使える。</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>SL 4.1 と SL 4.11 の続きです
</div>
</div>
<div class="callout-body-container callout-body">
<p>このページは、<span class="math inline">\(2\)</span> つのページの上に立っています。</p>
<div id="tbl-ahl412-place" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-place-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;1: このページの位置
</figcaption>
<div aria-describedby="tbl-ahl412-place-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>ページ</th>
<th>そこでやったこと</th>
<th>ここで足すこと</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="../../ai-sl/04-statistics-and-probability/sl-4-1.html">SL 4.1</a></td>
<td>標本の<strong>取り方</strong>（<span class="math inline">\(5\)</span> つの sampling technique と bias）</td>
<td><strong>質問のしかた</strong>そのものを設計する</td>
</tr>
<tr class="even">
<td><a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a></td>
<td><span class="math inline">\(\chi^2\)</span> 検定の<strong>手順</strong>（<span class="math inline">\(5\)</span> ステップと <span class="math inline">\(3\)</span> つの検定）</td>
<td><strong>カテゴリの作り方</strong>と、<strong>自由度の数え方</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math inline">\(\chi^2\)</span> の値も <span class="math inline">\(p\)</span>-value も、電卓が出してくれます（<a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html#gdc-gof">SL 4.11 の GDC の節</a>）。新しく手を動かすのは、<strong>期待度数を作るところ</strong>だけです。</p>
<p>そのかわり、<strong>電卓に渡す前と、受け取ったあとの判断</strong>が増えます。どう区切るか、自由度に何を入れるか、そしてその選択を<strong>言葉で説明できるか</strong>。</p>
<p>なお、この項目にも公式集の欄はありません。覚える式は自由度の <span class="math inline">\(1\)</span> 本だけです。その形の意味は<a href="#why-it-works">あとで説明します</a>。</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>この項目は、計算ではなく「記述」で点が決まります
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a> と同じです。シラバスの言葉を見てください。</p>
<blockquote class="blockquote">
<p>Categorizing numerical data in a <span class="math inline">\(\chi^2\)</span> table and <strong>justifying the choice of categorisation</strong></p>
</blockquote>
<p><code>justifying</code>——つまり、<strong>なぜその区切り方にしたのかを書く</strong>ところまでが問題です。表を作って終わりではありません。</p>
<p>質問の設計も、reliability と validity も、<strong>英語の文を書いて答える</strong>設問です。このページでは、その文の型を毎回示します。</p>
</div>
</div>
<section id="the-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-idea">The idea</h2>
<section id="idea" class="level3">
<h3 class="anchored" data-anchor-id="idea">1. データを「作る側」に回ります</h3>
<p>SL の Topic 4 では、データは<strong>すでにそこにありました</strong>。表が与えられ、それを整理し、検定にかけていました。</p>
<p>この項目では、その手前に立ちます。</p>
<p><span class="math display">\[
\underbrace{\text{何を知りたいか}}_{\text{問い}} \ \to \ \underbrace{\text{どう聞くか}}_{\text{質問の設計}} \ \to \ \underbrace{\text{何を記録するか}}_{\text{変数の選択}} \ \to \ \underbrace{\text{どう区切るか}}_{\text{カテゴリ分け}} \ \to \ \chi^2
\]</span></p>
<p><strong>この <span class="math inline">\(4\)</span> 段のどこかで失敗すると、<span class="math inline">\(\chi^2\)</span> をどれだけ正しく計算しても、答えに意味がありません。</strong> シラバスがこの項目を置いているのは、そのためです。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>Exploration（探究課題・IA）でも、ここが効きます
</div>
</div>
<div class="callout-body-container callout-body">
<p>自分でデータを集めて <span class="math inline">\(\chi^2\)</span> を使うなら、<strong>その集め方を説明する部分</strong>が評価されます。この項目の言葉は、そのまま IA で使えます。</p>
</div>
</div>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">2. 質問のしかたで、答えが変わります</h3>
<p>シラバスは、質問の設計で見るべき点をこう並べています。</p>
<blockquote class="blockquote">
<p>Biased and unbiased, personal, unstructured and structured (with consistent answer choices), and precise questioning.</p>
</blockquote>
<p><span class="math inline">\(4\)</span> つあります。<span class="math inline">\(1\)</span> つずつ見ます。</p>
<div id="fig-ahl412-questions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl412-questions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-12-questions.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl412-questions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;1: Three bad questions, and how to fix them
</figcaption>
</figure>
</div>
<section id="biased" class="level4">
<h4 class="anchored" data-anchor-id="biased">biased と unbiased</h4>
<p><strong>biased question</strong>（かたよった質問）は、<strong>答えを一方に誘導する</strong>質問です。<strong>leading question</strong>（誘導質問）ともいいます。</p>
<p><a href="#fig-ahl412-questions" class="quarto-xref">図&nbsp;1</a> の左を見てください。</p>
<blockquote class="blockquote">
<p>✗ <em>Don’t you agree that the new bus route is good?</em></p>
</blockquote>
<p><code>Don't you agree</code> と言われると、<code>No</code> と答えにくくなります。<strong>質問そのものが、答えを押しています。</strong></p>
<blockquote class="blockquote">
<p>✓ <em>How would you rate the new bus route?</em></p>
</blockquote>
<p>こちらは、どちらへも答えられます。<strong>unbiased</strong>（かたよっていない）質問です。</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>「よい」「便利な」のような語が入っていたら、疑ってください
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>the good new route</code>、<code>this convenient service</code>、<code>the problem of ...</code> のような言い方は、<strong>答える前に評価を与えています。</strong></p>
<p>質問文から、<strong>評価を表す形容詞を抜く</strong>——これが直し方です。</p>
</div>
</div>
</section>
<section id="personal" class="level4">
<h4 class="anchored" data-anchor-id="personal">personal</h4>
<p><strong>personal question</strong>（個人的な質問）は、年齢・収入・成績・健康など、<strong>正直に答えにくい</strong>質問です。</p>
<p>聞いてはいけないわけではありません。ただし、</p>
<ul>
<li>答えたくない人が<strong>答えないまま返す</strong>（missing data が増える）</li>
<li>答えても、<strong>本当のことを書かない</strong></li>
</ul>
<p>ということが起こります。<strong>集まったデータが、その分だけかたよります。</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>直し方は <span class="math inline">\(2\)</span> つあります
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>範囲で聞く。</strong> <code>What is your income?</code> ではなく、<code>Which band is your income in?</code> として、幅のある選択肢を出します</li>
<li><strong>匿名にする。</strong> <code>The questionnaire is anonymous</code> と最初に書いておきます</li>
</ul>
<p>答案では、<strong>「なぜ答えにくいのか」と「どう直すのか」の両方</strong>を書いてください。</p>
</div>
</div>
</section>
<section id="structured" class="level4">
<h4 class="anchored" data-anchor-id="structured">unstructured と structured</h4>
<p><strong>unstructured question</strong>（自由回答の質問）は、答えを自由に書かせる質問です。<strong>structured question</strong>（選択式の質問）は、<strong>選択肢から選ばせる</strong>質問です。</p>
<p><a href="#fig-ahl412-questions" class="quarto-xref">図&nbsp;1</a> の真ん中です。</p>
<blockquote class="blockquote">
<p>✗ <em>What do you think of the canteen?</em></p>
<p>✓ <em>Rate the canteen: very poor / poor / fair / good / very good</em></p>
</blockquote>
<p>シラバスは structured に <strong>(with consistent answer choices)</strong> と付けています。<strong>選択肢がそろっていること</strong>が条件です。</p>
<p><strong><span class="math inline">\(\chi^2\)</span> にかけるなら、structured でなければなりません。</strong> 自由に書かれた文章は、そのままでは度数に数えられないからです。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>選択肢は、重ならず、もれなく
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\chi^2\)</span> の表は、<strong><span class="math inline">\(1\)</span> つの回答が、ちょうど <span class="math inline">\(1\)</span> つのマスに入る</strong>ことを前提にしています。ですから選択肢は</p>
<ul>
<li><strong>重ならない</strong>（<code>0–10</code>、<code>10–20</code> は <span class="math inline">\(10\)</span> がどちらか分かりません。<code>0–9</code>、<code>10–19</code> にします）</li>
<li><strong>もれがない</strong>（<code>0–9</code>、<code>10–19</code> だけでは、<span class="math inline">\(20\)</span> 以上の人が入れません。<code>20 or more</code> を足します）</li>
</ul>
<p>の <span class="math inline">\(2\)</span> つをみたす必要があります。<strong>この <span class="math inline">\(2\)</span> つは、<a href="#categorise">第5節</a>のカテゴリ分けとまったく同じ条件</strong>です。</p>
</div>
</div>
</section>
<section id="precise" class="level4">
<h4 class="anchored" data-anchor-id="precise">precise questioning</h4>
<p><strong>precise question</strong>（正確な質問）は、<strong>誰が読んでも同じ意味になる</strong>質問です。そうでないものを <strong>imprecise</strong>（あいまいな）といいます。</p>
<p><a href="#fig-ahl412-questions" class="quarto-xref">図&nbsp;1</a> の右です。</p>
<blockquote class="blockquote">
<p>✗ <em>Do you exercise often?</em></p>
<p>✓ <em>How many days last week did you exercise for 30 minutes or more?</em></p>
</blockquote>
<p><code>often</code>（よく）は、人によって意味が違います。週 <span class="math inline">\(1\)</span> 回を <code>often</code> と思う人もいれば、毎日でなければ <code>often</code> ではないと思う人もいます。<strong>同じ人の同じ生活について、答えがばらついてしまいます。</strong></p>
<p>直し方は、<strong>期間・量・単位を入れる</strong>ことです。「先週」「<span class="math inline">\(30\)</span> 分以上」「何日」と決めれば、解釈の幅がなくなります。</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>あいまいな語のリスト
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>often</code>、<code>regularly</code>、<code>a lot</code>、<code>good</code>、<code>young</code>、<code>nearby</code>、<code>recently</code>——どれも人によって意味が変わります。</p>
<p>問題文でこれらを見つけたら、<strong>それが指摘すべき点</strong>です。</p>
</div>
</div>
</section>
</section>
<section id="variables" class="level3">
<h3 class="anchored" data-anchor-id="variables">3. たくさんの変数から、調べるものを選びます</h3>
<p>シラバスは <span class="math inline">\(2\)</span> 行だけです。</p>
<blockquote class="blockquote">
<p>Selecting relevant variables from many variables.</p>
<p>Choosing relevant and appropriate data to analyse.</p>
</blockquote>
<p>現実のデータには、<strong>必要のない列がたくさん入っています。</strong> アンケートを取れば <span class="math inline">\(20\)</span> 問ぶんの答えが集まりますが、<span class="math inline">\(1\)</span> つの問いに答えるのに <span class="math inline">\(20\)</span> 個すべては要りません。</p>
<p>選ぶ基準は <span class="math inline">\(2\)</span> つです。</p>
<div id="tbl-ahl412-variables" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;2: 変数を選ぶ <span class="math inline">\(2\)</span> つの基準
</figcaption>
<div aria-describedby="tbl-ahl412-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>基準</th>
<th>中身</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>relevant</strong>（関係がある）</td>
<td>その変数が、<strong>立てた問いに直接かかわる</strong>か</td>
</tr>
<tr class="even">
<td><strong>appropriate</strong>（扱いに合っている）</td>
<td>その変数が、<strong>使いたい検定に合った型</strong>か</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span><span class="math inline">\(\chi^2\)</span> にかけるなら、カテゴリでなければなりません
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\chi^2\)</span> の表に入るのは <strong>度数</strong>です。ですから、変数は<strong>カテゴリになっていること</strong>が必要です。</p>
<ul>
<li>はじめからカテゴリのもの（性別、学年、好きな科目）… そのまま使えます</li>
<li>数値のもの（身長、点数、時間）… <strong>区切ってカテゴリにします</strong>（<a href="#categorise">第5節</a>）</li>
</ul>
<p>数値のまま <span class="math inline">\(\chi^2\)</span> に入れることはできません。<strong>「<span class="math inline">\(168.3\)</span> cm の人が何人」では、どのマスにも <span class="math inline">\(1\)</span> 人ずつしか入らない</strong>からです。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>「関係がありそうだから全部入れる」は、選択ではありません
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>Explain which variables you would use</code> と問われたら、<strong>選んだ理由</strong>を書きます。「多いほうがよい」ではありません。</p>
<p>関係のない変数を混ぜると、表のマスが増え、<span class="math inline">\(1\)</span> マスあたりの度数が小さくなります。<strong><a href="#five">第5節</a>の「<span class="math inline">\(5\)</span> より大きい」がみたせなくなる</strong>——これが、余分な変数の実害です。</p>
</div>
</div>
</section>
<section id="rel-val" class="level3">
<h3 class="anchored" data-anchor-id="rel-val">4. reliability と validity は、別のことです</h3>
<p>シラバスが名指ししている、この項目のもう <span class="math inline">\(1\)</span> つの柱です。</p>
<blockquote class="blockquote">
<p>Definition of reliability and validity. Reliability tests. Validity tests.</p>
</blockquote>
<p>言葉の意味は、<span class="math inline">\(1\)</span> 行ずつです。</p>
<div id="tbl-ahl412-relval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-relval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;3: reliability と validity
</figcaption>
<div aria-describedby="tbl-ahl412-relval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>語</th>
<th>意味</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>reliability</strong>（信頼性）</td>
<td>同じことを<strong>もう一度測ったら、同じ結果になる</strong>か</td>
</tr>
<tr class="even">
<td><strong>validity</strong>（妥当性）</td>
<td>それが<strong>測りたかったものを、本当に測っている</strong>か</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-ahl412-target" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl412-target-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-12-target.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl412-target-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;2: Reliability and validity are different things
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl412-target" class="quarto-xref">図&nbsp;2</a> が、この <span class="math inline">\(2\)</span> つの関係です。的の中心が「本当の値」、点が「測った値」です。</p>
<ul>
<li><strong>reliable</strong> … 点どうしが<strong>まとまっている</strong>（何度やっても同じ）</li>
<li><strong>valid</strong> … 点が<strong>中心を向いている</strong>（正しいものを測っている）</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>reliable でも valid でないことがあります
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="#fig-ahl412-target" class="quarto-xref">図&nbsp;2</a> の <span class="math inline">\(2\)</span> 番目を見てください。<span class="math inline">\(5\)</span> 発とも同じところに当たっていますが、<strong>中心から外れています。</strong></p>
<p>体重計が、いつも <span class="math inline">\(3\)</span> kg 多く出るとします。何度乗っても同じ値が出るので <strong>reliable</strong> ですが、<strong>体重を正しく測っていないので valid ではありません。</strong></p>
<p><strong>この <span class="math inline">\(2\)</span> つは別々に確かめる必要があります。</strong> 「同じ結果が出たから正しい」とは言えません。</p>
</div>
</div>
<section id="reliability-tests" class="level4">
<h4 class="anchored" data-anchor-id="reliability-tests">reliability tests</h4>
<p>シラバスが挙げているのは <span class="math inline">\(2\)</span> つです。</p>
<div id="tbl-ahl412-reliability" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-reliability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;4: <span class="math inline">\(2\)</span> つの reliability test
</figcaption>
<div aria-describedby="tbl-ahl412-reliability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>方法</th>
<th>やること</th>
<th>何が分かるか</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>test-retest</strong></td>
<td><strong>同じ人</strong>に、<strong>同じテスト</strong>を、<strong>時間をおいて</strong>もう一度受けてもらう</td>
<td><span class="math inline">\(2\)</span> 回の結果が近ければ reliable</td>
</tr>
<tr class="even">
<td><strong>parallel forms</strong></td>
<td><strong>同じ内容</strong>の<strong>別の問題</strong>（<span class="math inline">\(2\)</span> つの版）を作り、両方受けてもらう</td>
<td><span class="math inline">\(2\)</span> つの版の結果が近ければ reliable</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span><span class="math inline">\(2\)</span> つの使い分け
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>test-retest</strong> … 同じテストをもう一度。ただし、<strong>覚えてしまう</strong>という問題があります。<span class="math inline">\(2\)</span> 回目のほうが点が上がるなら、それは reliability ではなく記憶です。だから<strong>時間をあけます</strong></li>
<li><strong>parallel forms</strong> … 別の問題なので、覚える問題は起きません。ただし、<strong><span class="math inline">\(2\)</span> つの版が本当に同じ難しさか</strong>を確かめるのが難しくなります</li>
</ul>
<p>どちらを選んでも構いませんが、<code>Give a reason</code> と問われたら、<strong>この長所と短所のどちらかにふれてください。</strong></p>
</div>
</div>
<p>どちらの方法でも、確かめるのは<strong><span class="math inline">\(2\)</span> 回の結果がどれだけ一致しているか</strong>です。実際には、<span class="math inline">\(2\)</span> 組の値の相関係数（<a href="../../ai-sl/04-statistics-and-probability/sl-4-4.html#pearson-r">SL 4.4</a>）を見ます。</p>
</section>
<section id="validity-tests" class="level4">
<h4 class="anchored" data-anchor-id="validity-tests">validity tests</h4>
<p>こちらも <span class="math inline">\(2\)</span> つです。</p>
<div id="tbl-ahl412-validity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-validity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;5: <span class="math inline">\(2\)</span> つの validity test
</figcaption>
<div aria-describedby="tbl-ahl412-validity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>方法</th>
<th>やること</th>
<th>何が分かるか</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>content validity</strong>（内容的妥当性）</td>
<td>測りたい<strong>内容が、もれなく入っている</strong>かを確かめる</td>
<td>範囲がそろっていれば valid</td>
</tr>
<tr class="even">
<td><strong>criterion-related validity</strong>（基準関連妥当性）</td>
<td><strong>すでに信用されている別のものさし</strong>と比べる</td>
<td>よく一致していれば valid</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>例で見ます。</p>
<ul>
<li><strong>content</strong> … 学期の数学のテストが、<strong>その学期に習った全部の単元から出ている</strong>か。<span class="math inline">\(1\)</span> 単元だけから出ていたら、content validity は低いです</li>
<li><strong>criterion-related</strong> … 新しく作った短い体力テストの結果を、<strong>きちんとした測定機器で測った値</strong>と比べる。近ければ criterion-related validity が高いです</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span><span class="math inline">\(4\)</span> つの名前は、そのまま書けるようにしてください
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>test-retest</code>、<code>parallel forms</code>、<code>content</code>、<code>criterion-related</code>。シラバスが名指ししている <span class="math inline">\(4\)</span> つです。</p>
<p>答案では、<strong>名前だけでなく「何をするのか」を <span class="math inline">\(1\)</span> 行添えて</strong>ください。名前だけでは点になりません。</p>
</div>
</div>
</section>
</section>
<section id="categorise" class="level3">
<h3 class="anchored" data-anchor-id="categorise">5. 数値データを、カテゴリに区切ります</h3>
<p>ここから、この項目の計算に近い部分です。</p>
<blockquote class="blockquote">
<p>Categorizing numerical data in a <span class="math inline">\(\chi^2\)</span> table and justifying the choice of categorisation.</p>
</blockquote>
<p>身長・点数・時間のような<strong>数値データ</strong>を <span class="math inline">\(\chi^2\)</span> にかけるには、まず<strong>区間に区切って、度数を数えられる形</strong>にします。区切ってできた <span class="math inline">\(1\)</span> つ <span class="math inline">\(1\)</span> つを <strong>class</strong>（階級）といいます（<a href="../../ai-sl/04-statistics-and-probability/sl-4-2.html#class-interval">SL 4.2</a>）。</p>
<p>区切り方は <span class="math inline">\(1\)</span> 通りではありません。<strong>そこが問われます。</strong></p>
<section id="three-conditions" class="level4">
<h4 class="anchored" data-anchor-id="three-conditions">区切り方の <span class="math inline">\(3\)</span> つの条件</h4>
<div id="tbl-ahl412-conditions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-conditions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;6: 区切り方の条件
</figcaption>
<div aria-describedby="tbl-ahl412-conditions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>条件</th>
<th>中身</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>重ならない</strong></td>
<td><span class="math inline">\(1\)</span> つの値が、<span class="math inline">\(2\)</span> つの class に入らない</td>
</tr>
<tr class="even">
<td><strong>もれがない</strong></td>
<td>どの値も、どこかの class に入る</td>
</tr>
<tr class="odd">
<td><strong>期待度数が <span class="math inline">\(5\)</span> より大きい</strong></td>
<td>これが、この項目の中心です</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="five" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>期待度数は <span class="math inline">\(5\)</span> より大きく
</div>
</div>
<div class="callout-body-container callout-body">
<p>シラバスの指定は、はっきりしています。</p>
<blockquote class="blockquote">
<p>Appropriate categories should be chosen with <strong>expected frequencies greater than 5</strong>.</p>
</blockquote>
<p>見るのは <strong>expected frequency</strong>（期待度数）であって、<strong>observed frequency（観測度数）ではありません。</strong> 実際に <span class="math inline">\(2\)</span> 人しかいない class でも、期待度数が <span class="math inline">\(8\)</span> なら構いません。</p>
<p><span class="math inline">\(5\)</span> を下回る class があったら、<strong>隣とまとめます</strong>（<a href="#combine">次の節</a>）。</p>
<p>なぜ <span class="math inline">\(5\)</span> なのかは <a href="#why-it-works">Why it works</a> で説明します。</p>
</div>
</div>
</section>
<section id="combine" class="level4">
<h4 class="anchored" data-anchor-id="combine"><span class="math inline">\(5\)</span> 以下の class は、隣とまとめます</h4>
<div id="fig-ahl412-combine" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl412-combine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-12-combine.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl412-combine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;3: Combining the tail classes
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl412-combine" class="quarto-xref">図&nbsp;3</a> の左は、身長を <span class="math inline">\(8\)</span> つの class に区切ったときの期待度数です。両端の <span class="math inline">\(2\)</span> つが <span class="math inline">\(3.41\)</span> で、<strong><span class="math inline">\(5\)</span> を下回っています。</strong></p>
<p>そこで、両端をそれぞれ隣とまとめます。</p>
<p><span class="math display">\[
3.413 + 10.27 = 13.68, \qquad 10.27 + 3.413 = 13.68
\]</span></p>
<p>右がその結果です。class は <span class="math inline">\(8\)</span> つから <strong><span class="math inline">\(6\)</span> つ</strong>になり、どれも <span class="math inline">\(5\)</span> を超えました。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>まとめるのは、<strong>隣どうし</strong>だけです
</div>
</div>
<div class="callout-body-container callout-body">
<p>いちばん下の class といちばん上の class をまとめてはいけません。<strong>区間としてつながっていないから</strong>です。</p>
<p>数値データの class には<strong>順序があります。</strong> まとめてよいのは、その順序で隣り合っているものだけです。</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>両端は「未満」「以上」の形にします
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="#fig-ahl412-combine" class="quarto-xref">図&nbsp;3</a> の右では、いちばん下が <code>under 16</code>、いちばん上が <code>32 and over</code> になっています。</p>
<p><strong>normal distribution のような連続分布を当てはめるときは、この形が必要</strong>です。<span class="math inline">\(8\)</span> より小さい値や <span class="math inline">\(40\)</span> より大きい値にも、モデルは確率を与えているからです。両端を開いておけば、<strong>確率の合計がちょうど <span class="math inline">\(1\)</span></strong> になります。</p>
</div>
</div>
</section>
<section id="justify" class="level4">
<h4 class="anchored" data-anchor-id="justify">区切り方を説明する</h4>
<p><code>justify</code> と問われたら、<strong>上の条件のどれを使ったか</strong>を書きます。型は決まっています。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The classes do not overlap and cover all the data. The two end classes had expected frequencies below <span class="math inline">\(5\)</span>, so each was combined with the class next to it. All six remaining classes now have an expected frequency greater than <span class="math inline">\(5\)</span>.</em></p>
</div>
<p>（重ならず、もれもないこと。両端の期待度数が <span class="math inline">\(5\)</span> 未満だったのでまとめたこと。まとめたあとは全部 <span class="math inline">\(5\)</span> を超えていること——この <span class="math inline">\(3\)</span> 点です。）</p>
</section>
</section>
<section id="df" class="level3">
<h3 class="anchored" data-anchor-id="df">6. 自由度は、推定した母数の数だけ減ります</h3>
<p><span class="math inline">\(\chi^2\)</span> goodness of fit の自由度は、SL では<strong>いつも <span class="math inline">\(n-1\)</span></strong> でした。SL 4.11 の試験についての注意書きは、こうなっています。</p>
<blockquote class="blockquote">
<p>the degrees of freedom will always be greater than one. At SL the degrees of freedom for the goodness of fit test will always be <span class="math inline">\(n-1\)</span></p>
</blockquote>
<p><strong>前半の「<span class="math inline">\(1\)</span> より大きい」は、HL でも生きています。</strong> 試験で <span class="math inline">\(\nu = 1\)</span> になる問題は出ません。後半が、HL では変わります。</p>
<blockquote class="blockquote">
<p>Choosing an appropriate number of degrees of freedom when <strong>estimating parameters from data</strong> when carrying out the <span class="math inline">\(\chi^2\)</span> goodness of fit test.</p>
</blockquote>
<p><span id="eq-ahl412-df"><span class="math display">\[
\nu = k - 1 - q
\tag{1}\]</span></span></p>
<ul>
<li><span class="math inline">\(k\)</span> … <strong>検定に使う class の数</strong>（<a href="#combine">まとめたあと</a>の数です）</li>
<li><span class="math inline">\(q\)</span> … <strong>データから推定した parameter（母数）の数</strong></li>
</ul>
<div id="fig-ahl412-df" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ahl412-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ahl-4-12-df.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ahl412-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
図&nbsp;4: Counting the degrees of freedom
</figcaption>
</figure>
</div>
<p><a href="#fig-ahl412-df" class="quarto-xref">図&nbsp;4</a> は、<a href="#combine">第5節</a>の例に当てはめたものです。<span class="math inline">\(8\)</span> つを <span class="math inline">\(6\)</span> つにまとめ、<span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> を推定したので <span class="math inline">\(\nu = 6 - 1 - 2 = 3\)</span> です。</p>
<section id="count-q" class="level4">
<h4 class="anchored" data-anchor-id="count-q"><span class="math inline">\(q\)</span> は、どう数えるか</h4>
<p><strong>問題文が値を教えてくれたら <span class="math inline">\(0\)</span>、データから計算したら <span class="math inline">\(1\)</span> つにつき <span class="math inline">\(1\)</span></strong> です。</p>
<div id="tbl-ahl412-q" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;7: <span class="math inline">\(q\)</span> の数え方
</figcaption>
<div aria-describedby="tbl-ahl412-q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>当てはめる分布</th>
<th>データから推定するもの</th>
<th><span class="math inline">\(q\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>割合が問題文で与えられている（サイコロが公平、<span class="math inline">\(2:3:5\)</span> など）</td>
<td>なし</td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td><strong>binomial</strong> <span class="math inline">\(B(n,\ p)\)</span> で、<span class="math inline">\(p\)</span> をデータから出す</td>
<td><span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
<tr class="odd">
<td><strong>Poisson</strong>（ポアソン分布）で、<span class="math inline">\(m\)</span>（平均）をデータから出す</td>
<td><span class="math inline">\(m\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td><strong>normal</strong> <span class="math inline">\(N(\mu,\ \sigma^{2})\)</span> で、<span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> をデータから出す</td>
<td><span class="math inline">\(\mu\)</span>、<span class="math inline">\(\sigma\)</span></td>
<td><span class="math inline">\(2\)</span></td>
</tr>
<tr class="odd">
<td><strong>normal</strong> で、<span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> が<strong>問題文に書いてある</strong></td>
<td>なし</td>
<td><span class="math inline">\(0\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>最後の <span class="math inline">\(2\)</span> 行を、見くらべてください
</div>
</div>
<div class="callout-body-container callout-body">
<p>同じ normal でも、<strong><span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> をどこから持ってきたか</strong>で <span class="math inline">\(q\)</span> が変わります。</p>
<ul>
<li>「この工場の製品は <span class="math inline">\(N(50,\ 4)\)</span> に従うと言われている。合うか」→ <strong>与えられている</strong> → <span class="math inline">\(q = 0\)</span></li>
<li>「このデータは normal に従うか」→ <strong>データから <span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> を出すしかない</strong> → <span class="math inline">\(q = 2\)</span></li>
</ul>
<p><strong>問題文に数が書いてあるかどうか</strong>を、先に確かめてください。</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>independence の自由度は、変わりません
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a> の <span class="math inline">\(\chi^2\)</span> test for independence は、いままでどおり</p>
<p><span class="math display">\[
\nu = (r-1)(c-1)
\]</span></p>
<p>です。<span class="math inline">\(r\)</span> は行の数、<span class="math inline">\(c\)</span> は列の数。<strong><a href="#eq-ahl412-df" class="quarto-xref">式&nbsp;1</a> を使うのは goodness of fit だけ</strong>です。</p>
<p>（independence でも期待度数を推定してはいますが、その分はすでに <span class="math inline">\((r-1)(c-1)\)</span> の形に織り込まれています。）</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>GOF では、自由度を自分で電卓に入れます
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>χ² GOF</code> は <code>Deg of Freedom</code> を聞いてきます（<a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html#gdc-gof">SL 4.11 の GDC の節</a>）。</p>
<p><strong>電卓は、class をいくつまとめたかも、parameter を何個推定したかも知りません。</strong> ここは自分で数えて入れるところです。</p>
<p><a href="#exm-ahl412-normal" class="quarto-xref">例&nbsp;4</a> では、<span class="math inline">\(\nu\)</span> を <span class="math inline">\(3\)</span> にするか <span class="math inline">\(5\)</span> にするかで、<strong><span class="math inline">\(p\)</span>-value が <span class="math inline">\(5\)</span> 倍変わります。</strong></p>
</div>
</div>
</section>
</section>
</section>
<section id="why-it-works" class="level2">
<h2 class="anchored" data-anchor-id="why-it-works">Why it works</h2>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>クリックすると開きます
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>ここで説明するのは <span class="math inline">\(2\)</span> つです。<strong>なぜ推定するたびに自由度が <span class="math inline">\(1\)</span> 減るのか</strong>と、<strong>なぜ期待度数が <span class="math inline">\(5\)</span> より大きくないといけないのか</strong>。</p>
<section id="why-df" class="level3">
<h3 class="anchored" data-anchor-id="why-df">なぜ、推定すると自由度が減るのか</h3>
<p>「自由度」は、<strong>自由に決められる数がいくつあるか</strong>という意味です。</p>
<p>class が <span class="math inline">\(k\)</span> 個あって、観測度数を <span class="math inline">\(O_1, O_2, \ldots, O_k\)</span> とします。合計は <span class="math inline">\(n\)</span> で決まっているので、</p>
<p><span class="math display">\[
O_1 + O_2 + \cdots + O_k = n
\]</span></p>
<p><span class="math inline">\(k-1\)</span> 個まで自由に決めれば、<strong>最後の <span class="math inline">\(1\)</span> 個は自動的に決まります。</strong> これが <span class="math inline">\(-1\)</span> の意味です。</p>
<p>つぎに、<span class="math inline">\(\mu\)</span> をデータから推定したとします。推定するというのは、<strong>「モデルの平均が、データの平均と一致するように <span class="math inline">\(\mu\)</span> を選ぶ」</strong>ということです。つまり</p>
<p><span class="math display">\[
(\text{モデルの平均}) = (\text{データの平均})
\]</span></p>
<p>という<strong>式が <span class="math inline">\(1\)</span> 本増えます。<span class="math inline">\(\mu\)</span> を自由に動かせなくなった</strong>、ということです。</p>
<p><strong>厳密な理由は、この課程の範囲を越えます。</strong> ただ、向きだけは上の <span class="math inline">\(2\)</span> 行で見えます。IB では「<strong>データから決めた parameter <span class="math inline">\(1\)</span> つにつき、自由度が <span class="math inline">\(1\)</span> 減る</strong>」として使います。</p>
<p><span class="math inline">\(\sigma\)</span> も同じように推定すれば、さらに <span class="math inline">\(1\)</span> つ減ります。だから normal では <span class="math inline">\(q = 2\)</span> です。</p>
<p><span class="math display">\[
\nu = \underbrace{k}_{\text{class の数}} - \underbrace{1}_{\text{合計が $n$}} - \underbrace{q}_{\text{推定した母数}}
\]</span></p>
<p><strong>自由度が減ると、同じ <span class="math inline">\(\chi^2\)</span> の値でも <span class="math inline">\(p\)</span>-value が小さくなります。</strong> 推定した分だけモデルがデータに寄せてあるので、「ずれが小さくて当たり前」——その分、厳しく見るわけです。</p>
</section>
<section id="why-five" class="level3">
<h3 class="anchored" data-anchor-id="why-five">なぜ、期待度数が <span class="math inline">\(5\)</span> より大きくないといけないのか</h3>
<p><span class="math inline">\(\chi^2\)</span> 統計量は</p>
<p><span class="math display">\[
\chi^2 = \sum \frac{(O - E)^2}{E}
\]</span></p>
<p>でした（<a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a>）。<span class="math inline">\(p\)</span>-value は、この値が <strong><span class="math inline">\(\chi^2\)</span> 分布に従うとみなして</strong>出しています。</p>
<p>ところが、これは<strong>近似</strong>です。<span class="math inline">\(O\)</span> は整数しか取れないとびとびの値なのに、<span class="math inline">\(\chi^2\)</span> 分布はなめらかな曲線だからです。</p>
<p><span class="math inline">\(E\)</span> が小さいと、この近似がくずれます。理由は分母を見れば分かります。</p>
<p><span class="math display">\[
E = 2 \ \text{のとき、} \ O \ \text{が} \ 1 \ \text{ずれるだけで} \ \frac{1^2}{2} = 0.5
\]</span></p>
<p><span class="math display">\[
E = 20 \ \text{のとき、} \ O \ \text{が} \ 1 \ \text{ずれても} \ \frac{1^2}{20} = 0.05
\]</span></p>
<p><strong><span class="math inline">\(E\)</span> が小さい class は、<span class="math inline">\(1\)</span> 人ずれただけで、その項が大きく動きます。</strong> そうなると、<span class="math inline">\(\chi^2\)</span> の値のばらつき方が、なめらかな <span class="math inline">\(\chi^2\)</span> 分布からずれてしまいます。</p>
<p><strong>困るのは、電卓が返す <span class="math inline">\(p\)</span>-value が当てにならなくなること</strong>です。棄却しやすくなるとはかぎらず、逆に棄却しにくくなることもあります。どちらに転ぶかは、表の形によります。</p>
<p><span class="math inline">\(5\)</span> という数字そのものに深い意味はありません。<strong>近似が実用に耐える目安</strong>として広く使われている値で、シラバスもそれを採っています。</p>
</section>
</div>
</div>
</div>
</section>
<section id="worked-examples" class="level2">
<h2 class="anchored" data-anchor-id="worked-examples">Worked examples</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>問題文は英語です。意味が理解できなかったら、問題文の下の「<strong>日本語訳</strong>」を開いてください。解説は日本語です。</p>
</div>
</div>
</div>
<div id="exm-ahl412-survey" class="theorem example">
<p><span class="theorem-title"><strong>例題 1</strong></span> <span class="q-en">A student wants to find out whether the members of her school use the new library. She plans to ask students the following question.</span></p>
<blockquote class="blockquote">
<p><em>Don’t you think the excellent new library is often useful?</em></p>
</blockquote>
<p><strong>(a)</strong> <span class="q-en">State two reasons why this question is not well designed.</span></p>
<p><strong>(b)</strong> <span class="q-en">Write an improved question that could be used in a <span class="math inline">\(\chi^2\)</span> test for independence.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある生徒が、学校の生徒が新しい図書館を使っているかどうかを調べようとしています。次の質問を生徒にする予定です。</p>
<blockquote class="blockquote">
<p><em>Don’t you think the excellent new library is often useful?</em></p>
<p>（すばらしい新図書館は、よく役に立つと思いませんか。）</p>
</blockquote>
<p><strong>(a)</strong> この質問がうまく設計されていない理由を <span class="math inline">\(2\)</span> つ述べなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(\chi^2\)</span> の独立性の検定に使えるような、改善した質問を書きなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> この <span class="math inline">\(1\)</span> 文には、<a href="#questions">第2節</a>で見た問題が <span class="math inline">\(3\)</span> つ入っています。</p>
<div id="tbl-ahl412-we1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;8: この質問の問題点
</figcaption>
<div aria-describedby="tbl-ahl412-we1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>問題</th>
<th>どこに出ているか</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>biased</strong>（誘導的）</td>
<td><code>Don't you think ...?</code> と <code>excellent</code></td>
</tr>
<tr class="even">
<td><strong>imprecise</strong>（あいまい）</td>
<td><code>often</code>——人によって意味が違う</td>
</tr>
<tr class="odd">
<td><strong>unstructured</strong>（選択肢がない）</td>
<td><code>useful</code> かどうかを、どう答えればよいか決まっていない</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>two reasons</code> なので、<span class="math inline">\(2\)</span> つ書けば足ります。<strong>どこが悪いのかを、質問文の言葉を引いて示してください。</strong></p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The question is biased: “Don’t you think” and “excellent” both push the student towards agreeing.</em></p>
<p><em>The question is imprecise: “often” means different things to different students, so their answers cannot be compared.</em></p>
</div>
<p>（誘導的であること、あいまいであること——それぞれ、質問文のどの語がそうさせているかを示しています。）</p>
<p><strong>(b)</strong> <span class="math inline">\(\chi^2\)</span> test for independence にかけるので、答えが<strong>カテゴリ</strong>になる必要があります（<a href="#variables">第3節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>How many times did you use the library last week?</em></p>
<p><em><span class="math inline">\(0\)</span> / <span class="math inline">\(1\)</span>–<span class="math inline">\(2\)</span> / <span class="math inline">\(3\)</span>–<span class="math inline">\(4\)</span> / <span class="math inline">\(5\)</span> or more</em></p>
</div>
<p>（<span class="math inline">\(3\)</span> つとも直っています。評価を表す語がなく <strong>unbiased</strong>、「先週」「何回」と決めてあって <strong>precise</strong>、選択肢が重ならず、もれもない <strong>structured</strong>。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>It is biased: “Don’t you think” and “excellent” lead the student towards a positive answer.</em></p>
<p><em>It is imprecise: “often” is not defined, so different students will interpret it differently.</em></p>
<p><strong>(b)</strong> <em>How many times did you use the library last week? <span class="math inline">\(0\)</span> / <span class="math inline">\(1\)</span>–<span class="math inline">\(2\)</span> / <span class="math inline">\(3\)</span>–<span class="math inline">\(4\)</span> / <span class="math inline">\(5\)</span> or more.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span><code>two reasons</code> に <span class="math inline">\(3\)</span> つ書いても、点は増えません
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(3\)</span> つ目を書いて時間を使うより、<strong><span class="math inline">\(2\)</span> つを <span class="math inline">\(1\)</span> 行ずつ、根拠つきで</strong>書くほうが確実です。</p>
<p>「biased です」だけでは足りません。<strong>どの語がそうさせているか</strong>を引いてください。</p>
</div>
</div>
</div>
<div id="exm-ahl412-relval" class="theorem example">
<p><span class="theorem-title"><strong>例題 2</strong></span> <span class="q-en">A teacher designs a new <span class="math inline">\(20\)</span>-minute test to measure students’ arithmetic skill.</span></p>
<p><strong>(a)</strong> <span class="q-en">Describe how the teacher could use a test-retest method to check the reliability of the test.</span></p>
<p><strong>(b)</strong> <span class="q-en">The results of the new test agree closely with the results of a well-established arithmetic test taken by the same students. State which type of validity this supports, and explain your answer.</span></p>
<p><strong>(c)</strong> <span class="q-en">The new test contains only addition questions. Comment on the validity of the test.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある教師が、生徒の計算力を測る新しい <span class="math inline">\(20\)</span> 分のテストを作りました。</p>
<p><strong>(a)</strong> このテストの reliability を確かめるために、test-retest の方法をどう使えばよいかを説明しなさい。</p>
<p><strong>(b)</strong> 新しいテストの結果が、同じ生徒が受けた、すでに定評のある計算テストの結果とよく一致しました。これはどの種類の validity を支持するかを述べ、理由を説明しなさい。</p>
<p><strong>(c)</strong> 新しいテストには足し算の問題しか入っていません。このテストの validity について述べなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> test-retest は「<strong>同じ人に、同じテストを、時間をおいて</strong>」でした（<a href="#reliability-tests">第4節</a>）。</p>
<p><code>Describe</code> なので、<strong>やることを順に書きます。</strong> 「時間をおく」理由まで書けると、答案が強くなります。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Give the same test to the same group of students a second time, after an interval long enough that they do not simply remember their answers. If the two sets of scores agree closely, the test is reliable.</em></p>
</div>
<p>（同じ生徒に、覚えていない程度の間隔をあけて、同じテストをもう一度。<span class="math inline">\(2\)</span> 回の得点が近ければ reliable、という意味です。）</p>
<p><strong>(b)</strong> 「<strong>すでに信用されている別のものさしと比べる</strong>」——これが criterion-related validity です（<a href="#validity-tests">第4節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Criterion-related validity. The new test is being compared with an established test that is already accepted as a measure of arithmetic skill, and the close agreement suggests that the new test measures the same thing.</em></p>
</div>
<p>（すでに認められているものさしと比べていて、よく一致しているから、という意味です。）</p>
<p><strong>(c)</strong> 足し算だけでは、<strong>計算力の一部しか測っていません。</strong> 引き算・かけ算・わり算が入っていないからです。これは content validity の問題です。</p>
<p><code>Comment on</code> と言われているので、<strong>どの validity が、なぜ低いのか</strong>を書きます。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The test has low content validity. Arithmetic skill also includes subtraction, multiplication and division, but the test covers only addition, so it does not cover the whole of what it claims to measure.</em></p>
</div>
<p>（内容が全体をおおっていないので content validity が低い、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Give the same test to the same students again after a suitable interval, and compare the two sets of scores. Close agreement indicates reliability.</em></p>
<p><strong>(b)</strong> <em>Criterion-related validity: the new test agrees with an established test that is already accepted as measuring arithmetic skill.</em></p>
<p><strong>(c)</strong> <em>Low content validity: only addition is tested, so the test does not cover the whole of arithmetic skill.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>(c) で「reliable ではない」と書かない
</div>
</div>
<div class="callout-body-container callout-body">
<p>足し算だけのテストでも、<strong>何度受けても同じ点が出るなら reliable です。</strong> 問題は、測っているものが違うこと——つまり validity です（<a href="#fig-ahl412-target" class="quarto-xref">図&nbsp;2</a> の <span class="math inline">\(2\)</span> 番目）。</p>
<p><strong>この取りちがえが、この項目でいちばん多い失点</strong>です。</p>
</div>
</div>
</div>
<div id="exm-ahl412-categorise" class="theorem example">
<p><span class="theorem-title"><strong>例題 3</strong></span> <span class="q-en">The times, in minutes, taken by <span class="math inline">\(60\)</span> students to complete a puzzle are to be tested against a proposed model using a <span class="math inline">\(\chi^2\)</span> goodness of fit test. Under the model, the expected frequencies for six equal classes would be</span></p>
<div id="tbl-ahl412-we3q" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we3q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;9: Expected frequencies under the model
</figcaption>
<div aria-describedby="tbl-ahl412-we3q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>class</th>
<th><span class="math inline">\(0 \le t &lt; 4\)</span></th>
<th><span class="math inline">\(4 \le t &lt; 8\)</span></th>
<th><span class="math inline">\(8 \le t &lt; 12\)</span></th>
<th><span class="math inline">\(12 \le t &lt; 16\)</span></th>
<th><span class="math inline">\(16 \le t &lt; 20\)</span></th>
<th><span class="math inline">\(t \ge 20\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>expected frequency</td>
<td><span class="math inline">\(3.1\)</span></td>
<td><span class="math inline">\(18.4\)</span></td>
<td><span class="math inline">\(21.7\)</span></td>
<td><span class="math inline">\(11.6\)</span></td>
<td><span class="math inline">\(4.2\)</span></td>
<td><span class="math inline">\(1.0\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">State which classes must be combined, and give a reason.</span></p>
<p><strong>(b)</strong> <span class="q-en">Write down the expected frequencies after combining.</span></p>
<p><strong>(c)</strong> <span class="q-en">The model has no parameters estimated from the data. Write down the number of degrees of freedom.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(60\)</span> 人の生徒がパズルを解くのにかかった時間（分）を、<span class="math inline">\(\chi^2\)</span> 適合度検定で、ある提案されたモデルと比べます。そのモデルのもとでは、<span class="math inline">\(6\)</span> つの等しい階級の期待度数は上の表のようになります。</p>
<p>表の見出しは、<code>class</code> が「階級」、<code>expected frequency</code> が「期待度数」、<code>20 or more</code> が「<span class="math inline">\(20\)</span> 以上」です。</p>
<p><strong>(a)</strong> まとめなければならない階級を述べ、理由を書きなさい。</p>
<p><strong>(b)</strong> まとめたあとの期待度数を書きなさい。</p>
<p><strong>(c)</strong> このモデルでは、データから推定した母数はありません。自由度を書きなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> <a href="#five">第5節</a>の条件を使います。<span class="math inline">\(5\)</span> より大きくない class を探します。</p>
<p><span class="math display">\[
3.1 \ (&lt; 5), \qquad 4.2 \ (&lt; 5), \qquad 1.0 \ (&lt; 5)
\]</span></p>
<p><span class="math inline">\(3\)</span> つあります。まとめるのは<strong>隣どうし</strong>だけでした（<a href="#combine">第5節</a>）。</p>
<ul>
<li><span class="math inline">\(0 \le t &lt; 4\)</span>（<span class="math inline">\(3.1\)</span>）は、隣の <span class="math inline">\(4 \le t &lt; 8\)</span> とまとめます</li>
<li><span class="math inline">\(16 \le t &lt; 20\)</span>（<span class="math inline">\(4.2\)</span>）と <span class="math inline">\(t \ge 20\)</span>（<span class="math inline">\(1.0\)</span>）は<strong>隣どうし</strong>なので、この <span class="math inline">\(2\)</span> つをまとめます。<span class="math inline">\(4.2 + 1.0 = 5.2\)</span> で、<span class="math inline">\(5\)</span> を超えます</li>
</ul>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Combine <span class="math inline">\(0 \le t &lt; 4\)</span> with <span class="math inline">\(4 \le t &lt; 8\)</span>, and combine <span class="math inline">\(16 \le t &lt; 20\)</span> with <span class="math inline">\(t \ge 20\)</span>. Each of these classes has an expected frequency less than <span class="math inline">\(5\)</span>, and every class used in a <span class="math inline">\(\chi^2\)</span> test must have an expected frequency greater than <span class="math inline">\(5\)</span>.</em></p>
</div>
<p>（どれをまとめるかと、その理由（期待度数が <span class="math inline">\(5\)</span> 未満）を書いています。）</p>
<p><strong>(b)</strong> 足します。</p>
<p><span class="math display">\[
3.1 + 18.4 = 21.5, \qquad 4.2 + 1.0 = 5.2
\]</span></p>
<div id="tbl-ahl412-we3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;10: まとめたあと
</figcaption>
<div aria-describedby="tbl-ahl412-we3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>class</th>
<th><span class="math inline">\(0 \le t &lt; 8\)</span></th>
<th><span class="math inline">\(8 \le t &lt; 12\)</span></th>
<th><span class="math inline">\(12 \le t &lt; 16\)</span></th>
<th><span class="math inline">\(t \ge 16\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>expected frequency</td>
<td><span class="math inline">\(21.5\)</span></td>
<td><span class="math inline">\(21.7\)</span></td>
<td><span class="math inline">\(11.6\)</span></td>
<td><span class="math inline">\(5.2\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>検算。</strong> <span class="math inline">\(21.5 + 21.7 + 11.6 + 5.2 = 60\)</span> ✓ もとの合計と同じです。</p>
<p>全部 <span class="math inline">\(5\)</span> を超えました ✓</p>
<p><strong>(c)</strong> class は <span class="math inline">\(4\)</span> つ、推定した母数は <span class="math inline">\(0\)</span> 個です（<a href="#eq-ahl412-df" class="quarto-xref">式&nbsp;1</a>）。</p>
<p><span class="math display">\[
\nu = 4 - 1 - 0 = 3
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Combine <span class="math inline">\(0 \le t &lt; 4\)</span> with <span class="math inline">\(4 \le t &lt; 8\)</span>, and <span class="math inline">\(16 \le t &lt; 20\)</span> with <span class="math inline">\(t \ge 20\)</span>, because each has an expected frequency less than <span class="math inline">\(5\)</span>.</em></p>
<p><strong>(b)</strong></p>
<div id="tbl-ahl412-we3ans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we3ans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;11: まとめたあと
</figcaption>
<div aria-describedby="tbl-ahl412-we3ans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>class</th>
<th><span class="math inline">\(0 \le t &lt; 8\)</span></th>
<th><span class="math inline">\(8 \le t &lt; 12\)</span></th>
<th><span class="math inline">\(12 \le t &lt; 16\)</span></th>
<th><span class="math inline">\(t \ge 16\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(E\)</span></td>
<td><span class="math inline">\(21.5\)</span></td>
<td><span class="math inline">\(21.7\)</span></td>
<td><span class="math inline">\(11.6\)</span></td>
<td><span class="math inline">\(5.2\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(c)</strong> <span class="math inline">\(\nu = 4 - 1 - 0 = 3\)</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>まとめたあと、合計が変わっていないことを見てください
</div>
</div>
<div class="callout-body-container callout-body">
<p>期待度数の合計は、いつもデータの個数（ここでは <span class="math inline">\(60\)</span>）です。まとめても、<strong>足し合わせているだけなので合計は変わりません。</strong></p>
<p><span class="math inline">\(60\)</span> にならなかったら、足し間違いか、写し間違いです。<strong><span class="math inline">\(5\)</span> 秒の検算</strong>です。</p>
</div>
</div>
</div>
<div id="exm-ahl412-normal" class="theorem example">
<p><span class="theorem-title"><strong>例題 4</strong></span> <span class="q-en">The heights, in centimetres, of <span class="math inline">\(150\)</span> plants are shown in the table.</span></p>
<div id="tbl-ahl412-we4q" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we4q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;12: Heights of <span class="math inline">\(150\)</span> plants
</figcaption>
<div aria-describedby="tbl-ahl412-we4q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>height <span class="math inline">\(h\)</span></th>
<th><span class="math inline">\(8 \le h &lt; 12\)</span></th>
<th><span class="math inline">\(12 \le h &lt; 16\)</span></th>
<th><span class="math inline">\(16 \le h &lt; 20\)</span></th>
<th><span class="math inline">\(20 \le h &lt; 24\)</span></th>
<th><span class="math inline">\(24 \le h &lt; 28\)</span></th>
<th><span class="math inline">\(28 \le h &lt; 32\)</span></th>
<th><span class="math inline">\(32 \le h &lt; 36\)</span></th>
<th><span class="math inline">\(36 \le h &lt; 40\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>frequency</td>
<td><span class="math inline">\(3\)</span></td>
<td><span class="math inline">\(7\)</span></td>
<td><span class="math inline">\(35\)</span></td>
<td><span class="math inline">\(30\)</span></td>
<td><span class="math inline">\(31\)</span></td>
<td><span class="math inline">\(34\)</span></td>
<td><span class="math inline">\(6\)</span></td>
<td><span class="math inline">\(4\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="q-en">Using mid-interval values, the mean of the data is <span class="math inline">\(24.0\)</span> cm and the standard deviation is <span class="math inline">\(6.0\)</span> cm.</span></p>
<p><span class="q-en">A researcher wishes to test, at the <span class="math inline">\(5\%\)</span> significance level, whether these heights can be modelled by a normal distribution.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the expected frequencies under the normal model, treating the lowest class as “less than <span class="math inline">\(12\)</span>” and the highest as “<span class="math inline">\(36\)</span> or more”.</span></p>
<p><strong>(b)</strong> <span class="q-en">State which classes must be combined, and justify your choice of categorisation.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the number of degrees of freedom.</span></p>
<p><strong>(d)</strong> <span class="q-en">Carry out the test and state your conclusion in context.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(150\)</span> 本の植物の高さ（cm）が表に示されています。</p>
<p>表の見出しは、<code>height</code> が「高さ」、<code>frequency</code> が「度数」です。</p>
<p>階級値を使うと、データの平均は <span class="math inline">\(24.0\)</span> cm、標準偏差は <span class="math inline">\(6.0\)</span> cm です。</p>
<p>研究者は、これらの高さが正規分布でモデル化できるかどうかを、有意水準 <span class="math inline">\(5\%\)</span> で検定したいと考えています。</p>
<p><strong>(a)</strong> 正規分布モデルのもとでの期待度数を求めなさい。ただし、いちばん下の階級は「<span class="math inline">\(12\)</span> 未満」、いちばん上は「<span class="math inline">\(36\)</span> 以上」として扱いなさい。</p>
<p><strong>(b)</strong> まとめなければならない階級を述べ、階級の選び方の理由を書きなさい。</p>
<p><strong>(c)</strong> 自由度を求めなさい。</p>
<p><strong>(d)</strong> 検定を行い、文脈に沿って結論を述べなさい。</p>
</details>
<hr>
<p><strong>(a)</strong> 高さを表す確率変数を <span class="math inline">\(H\)</span> とします。<span class="math inline">\(\mu = 24.0\)</span>、<span class="math inline">\(\sigma = 6.0\)</span> の normal distribution で、各区間の確率を出します（<a href="../../ai-sl/04-statistics-and-probability/sl-4-9.html#area">SL 4.9</a>）。それに <span class="math inline">\(150\)</span> を掛けたものが期待度数です。</p>
<p>いちばん下は <span class="math inline">\(-\infty\)</span> から <span class="math inline">\(12\)</span>、いちばん上は <span class="math inline">\(36\)</span> から <span class="math inline">\(\infty\)</span> とします。<strong>そうしないと、確率の合計が <span class="math inline">\(1\)</span> になりません</strong>（<a href="#combine">第5節</a>）。</p>
<p><span class="math display">\[
P(H &lt; 12) = 0.0228 \quad \Rightarrow \quad E = 150 \times 0.0228 = 3.413
\]</span></p>
<p>同じように残りも出します。</p>
<div id="tbl-ahl412-we4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;13: 期待度数（<span class="math inline">\(4\)</span> 有効数字）
</figcaption>
<div aria-describedby="tbl-ahl412-we4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>class</th>
<th><span class="math inline">\(&lt; 12\)</span></th>
<th><span class="math inline">\(12\)</span>–<span class="math inline">\(16\)</span></th>
<th><span class="math inline">\(16\)</span>–<span class="math inline">\(20\)</span></th>
<th><span class="math inline">\(20\)</span>–<span class="math inline">\(24\)</span></th>
<th><span class="math inline">\(24\)</span>–<span class="math inline">\(28\)</span></th>
<th><span class="math inline">\(28\)</span>–<span class="math inline">\(32\)</span></th>
<th><span class="math inline">\(32\)</span>–<span class="math inline">\(36\)</span></th>
<th><span class="math inline">\(\ge 36\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(O\)</span></td>
<td><span class="math inline">\(3\)</span></td>
<td><span class="math inline">\(7\)</span></td>
<td><span class="math inline">\(35\)</span></td>
<td><span class="math inline">\(30\)</span></td>
<td><span class="math inline">\(31\)</span></td>
<td><span class="math inline">\(34\)</span></td>
<td><span class="math inline">\(6\)</span></td>
<td><span class="math inline">\(4\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(E\)</span></td>
<td><span class="math inline">\(3.413\)</span></td>
<td><span class="math inline">\(10.27\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(10.27\)</span></td>
<td><span class="math inline">\(3.413\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>検算。</strong> <span class="math inline">\(E\)</span> の合計は <span class="math inline">\(150\)</span> です ✓ <span class="math inline">\(O\)</span> の合計も <span class="math inline">\(150\)</span> ✓</p>
<p><strong>(b)</strong> 両端が <span class="math inline">\(3.413\)</span> で、<strong><span class="math inline">\(5\)</span> を下回っています</strong>（<a href="#five">第5節</a>）。それぞれ隣とまとめます。</p>
<p><span class="math display">\[
3.413 + 10.27 = 13.68
\]</span></p>
<div id="tbl-ahl412-we4b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we4b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;14: まとめたあと
</figcaption>
<div aria-describedby="tbl-ahl412-we4b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>class</th>
<th><span class="math inline">\(&lt; 16\)</span></th>
<th><span class="math inline">\(16\)</span>–<span class="math inline">\(20\)</span></th>
<th><span class="math inline">\(20\)</span>–<span class="math inline">\(24\)</span></th>
<th><span class="math inline">\(24\)</span>–<span class="math inline">\(28\)</span></th>
<th><span class="math inline">\(28\)</span>–<span class="math inline">\(32\)</span></th>
<th><span class="math inline">\(\ge 32\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(O\)</span></td>
<td><span class="math inline">\(10\)</span></td>
<td><span class="math inline">\(35\)</span></td>
<td><span class="math inline">\(30\)</span></td>
<td><span class="math inline">\(31\)</span></td>
<td><span class="math inline">\(34\)</span></td>
<td><span class="math inline">\(10\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(E\)</span></td>
<td><span class="math inline">\(13.68\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(13.68\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>検算。</strong> まとめても合計は <span class="math inline">\(150\)</span> のままです ✓</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The classes below <span class="math inline">\(12\)</span> and <span class="math inline">\(36\)</span> or more have expected frequencies of <span class="math inline">\(3.41\)</span>, which is less than <span class="math inline">\(5\)</span>, so each is combined with the class next to it. The six remaining classes do not overlap, cover all the data, and every expected frequency is now greater than <span class="math inline">\(5\)</span>.</em></p>
</div>
<p>（両端の期待度数が <span class="math inline">\(5\)</span> 未満なので隣とまとめたこと、まとめたあとは重なりもなく、もれもなく、全部 <span class="math inline">\(5\)</span> を超えていること——<a href="#justify">第5節</a>の <span class="math inline">\(3\)</span> 点です。）</p>
<p><strong>(c)</strong> class は <span class="math inline">\(6\)</span> つ。データから推定した parameter は <strong><span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> の <span class="math inline">\(2\)</span> 個</strong>です。問題文が「平均は <span class="math inline">\(24.0\)</span>、標準偏差は <span class="math inline">\(6.0\)</span>」と書いていますが、<strong>それはデータから計算した値</strong>であって、与えられたモデルの値ではありません（<a href="#count-q">第6節</a>）。</p>
<p><span class="math display">\[
\nu = 6 - 1 - 2 = 3
\]</span></p>
<p><strong>(d)</strong> <a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html#tbl-5-steps">SL 4.11 の <span class="math inline">\(5\)</span> ステップ</a>どおりに進めます。</p>
<p><span class="math inline">\(H_0\)</span>: <em>The heights can be modelled by a normal distribution.</em></p>
<p><span class="math inline">\(H_1\)</span>: <em>The heights cannot be modelled by a normal distribution.</em></p>
<p><span class="math inline">\(\chi^2\)</span> を組み立てます。</p>
<p><span class="math display">\[
\chi^2 = \frac{(10-13.68)^2}{13.68} + \frac{(35-24.19)^2}{24.19} + \frac{(30-37.13)^2}{37.13} + \cdots
\]</span></p>
<p><span class="math display">\[
= 0.991 + 4.83 + 1.37 + 1.01 + 3.98 + 0.991 = 13.2
\]</span></p>
<p><span class="math inline">\(\nu = 3\)</span> を電卓に入れて（<a href="#gdc-gof">GDC 第2節</a>）、</p>
<p><span class="math display">\[
p = 0.00429
\]</span></p>
<p><span class="math inline">\(p &lt; 0.05\)</span> なので、<span class="math inline">\(H_0\)</span> を <strong>reject</strong> します。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(\chi^2 = 13.2\)</span>, <span class="math inline">\(\nu = 3\)</span>, <span class="math inline">\(p = 0.00429\)</span>. Since <span class="math inline">\(p &lt; 0.05\)</span>, reject <span class="math inline">\(H_0\)</span>. There is sufficient evidence at the <span class="math inline">\(5\%\)</span> level that the heights of these plants are not well modelled by a normal distribution.</em></p>
</div>
<p>（<span class="math inline">\(p\)</span> が <span class="math inline">\(0.05\)</span> より小さいので <span class="math inline">\(H_0\)</span> を棄却し、これらの植物の高さは正規分布ではうまく表せない、という意味です。）</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙にはこう書く）
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>(a)</strong></p>
<div id="tbl-ahl412-we4ans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we4ans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;15: 期待度数
</figcaption>
<div aria-describedby="tbl-ahl412-we4ans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>class</th>
<th><span class="math inline">\(&lt; 12\)</span></th>
<th><span class="math inline">\(12\)</span>–<span class="math inline">\(16\)</span></th>
<th><span class="math inline">\(16\)</span>–<span class="math inline">\(20\)</span></th>
<th><span class="math inline">\(20\)</span>–<span class="math inline">\(24\)</span></th>
<th><span class="math inline">\(24\)</span>–<span class="math inline">\(28\)</span></th>
<th><span class="math inline">\(28\)</span>–<span class="math inline">\(32\)</span></th>
<th><span class="math inline">\(32\)</span>–<span class="math inline">\(36\)</span></th>
<th><span class="math inline">\(\ge 36\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(E\)</span></td>
<td><span class="math inline">\(3.413\)</span></td>
<td><span class="math inline">\(10.27\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(10.27\)</span></td>
<td><span class="math inline">\(3.413\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(b)</strong> <em>The two end classes have <span class="math inline">\(E = 3.41 &lt; 5\)</span>, so each is combined with its neighbour. All six remaining classes then have <span class="math inline">\(E &gt; 5\)</span>.</em></p>
<div id="tbl-ahl412-we4bans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-we4bans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;16: まとめたあと
</figcaption>
<div aria-describedby="tbl-ahl412-we4bans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>class</th>
<th><span class="math inline">\(&lt; 16\)</span></th>
<th><span class="math inline">\(16\)</span>–<span class="math inline">\(20\)</span></th>
<th><span class="math inline">\(20\)</span>–<span class="math inline">\(24\)</span></th>
<th><span class="math inline">\(24\)</span>–<span class="math inline">\(28\)</span></th>
<th><span class="math inline">\(28\)</span>–<span class="math inline">\(32\)</span></th>
<th><span class="math inline">\(\ge 32\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(E\)</span></td>
<td><span class="math inline">\(13.68\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(37.13\)</span></td>
<td><span class="math inline">\(24.19\)</span></td>
<td><span class="math inline">\(13.68\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(c)</strong> <span class="math display">\[
\nu = 6 - 1 - 2 = 3
\]</span></p>
<p><strong>(d)</strong> <span class="math display">\[
\chi^2 = 13.2, \qquad p = 0.00429 &lt; 0.05
\]</span></p>
<p><em>Reject <span class="math inline">\(H_0\)</span>: there is sufficient evidence at the <span class="math inline">\(5\%\)</span> level that the heights are not normally distributed.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>自由度とまとめ方で、<span class="math inline">\(p\)</span> が大きく変わります
</div>
</div>
<div class="callout-body-container callout-body">
<div id="tbl-ahl412-dfcompare" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-dfcompare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;17: 自由度で <span class="math inline">\(p\)</span> が変わる
</figcaption>
<div aria-describedby="tbl-ahl412-dfcompare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\nu\)</span></th>
<th>どこを間違えたか</th>
<th><span class="math inline">\(\chi^2\)</span></th>
<th><span class="math inline">\(p\)</span></th>
<th><span class="math inline">\(5\%\)</span> での結論</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(3\)</span></strong></td>
<td><strong>正しい</strong></td>
<td><strong><span class="math inline">\(13.2\)</span></strong></td>
<td><strong><span class="math inline">\(0.00429\)</span></strong></td>
<td><strong>reject</strong> ✓</td>
</tr>
<tr class="even">
<td><span class="math inline">\(5\)</span></td>
<td>まとめたが、<span class="math inline">\(-2\)</span> を忘れた</td>
<td><span class="math inline">\(13.2\)</span></td>
<td><span class="math inline">\(0.0219\)</span></td>
<td>reject（同じ結論だが <span class="math inline">\(p\)</span> が <span class="math inline">\(5\)</span> 倍）</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(7\)</span></td>
<td>まとめなかった（<span class="math inline">\(\chi^2\)</span> も変わる）</td>
<td><span class="math inline">\(14.1\)</span></td>
<td><span class="math inline">\(0.0486\)</span></td>
<td>かろうじて reject</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>この問題では、<span class="math inline">\(5\%\)</span> ならどれも reject になります。</strong> ただし <span class="math inline">\(1\%\)</span> で検定すると、正しい <span class="math inline">\(0.00429\)</span> は reject、<span class="math inline">\(0.0486\)</span> は reject しない——<strong>結論が分かれます。</strong></p>
<p><span class="math inline">\(p\)</span> が有意水準の近くに落ちる問題では、<strong>自由度の数え方が答えそのものを決めます。</strong> そして、どれが正しいかは <span class="math inline">\(p\)</span>-value を見ても分かりません。<strong>数える段階でしか防げません。</strong></p>
</div>
</div>
</div>
</section>
<section id="common-errors" class="level2">
<h2 class="anchored" data-anchor-id="common-errors">Common errors</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>自由度から、推定した母数の分を引き忘れる
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>この項目でいちばん多い失点です。</strong> SL では <span class="math inline">\(\nu = n-1\)</span> でしたが、HL では <a href="#eq-ahl412-df" class="quarto-xref">式&nbsp;1</a> です。</p>
<p><code>the mean and standard deviation of the data</code> という言葉が問題文にあったら、<strong>その <span class="math inline">\(2\)</span> つはデータから推定したもの</strong>です。<span class="math inline">\(q = 2\)</span> になります。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>まとめる前の class の数で、自由度を数える
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(k\)</span> は「<strong>検定に使う</strong> class の数」です（<a href="#df">第6節</a>）。<span class="math inline">\(6\)</span> つを <span class="math inline">\(4\)</span> つにまとめたなら、<span class="math inline">\(k = 4\)</span> です。</p>
<p>まとめたら、<strong>その場で <span class="math inline">\(k\)</span> を書き直してください。</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span> が与えられているのに、<span class="math inline">\(2\)</span> を引く
</div>
</div>
<div class="callout-body-container callout-body">
<p>逆の間違いです。<strong>問題文に数が書いてあれば、推定していません。</strong> <span class="math inline">\(q = 0\)</span> です（<a href="#tbl-ahl412-q" class="quarto-xref">表&nbsp;7</a>）。</p>
<p>「どこから来た数か」を、そのつど確かめてください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>観測度数を見て、まとめるかどうかを決める
</div>
</div>
<div class="callout-body-container callout-body">
<p>条件は <strong>expected frequency</strong> についてのものです（<a href="#five">第5節</a>）。観測度数が <span class="math inline">\(1\)</span> でも、期待度数が <span class="math inline">\(8\)</span> ならまとめません。</p>
<p><strong><span class="math inline">\(E\)</span> の行を見てください。<span class="math inline">\(O\)</span> の行ではありません。</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>隣り合っていない class をまとめる
</div>
</div>
<div class="callout-body-container callout-body">
<p>いちばん下といちばん上をまとめると、<strong>区間としてつながらない</strong>ものができます。</p>
<p>数値データの class には順序があります。<strong>まとめてよいのは隣どうしだけ</strong>です（<a href="#combine">第5節</a>）。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>連続分布を当てはめるとき、両端を閉じたままにする
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(12 \le h &lt; 16\)</span> のままだと、<span class="math inline">\(12\)</span> より小さい値の確率が抜けます。<strong>確率の合計が <span class="math inline">\(1\)</span> にならず、期待度数の合計もデータの個数に合いません。</strong></p>
<p>いちばん下は「未満」、いちばん上は「以上」にしてください（<a href="#combine">第5節</a>）。<strong>合計が合うかどうかで、その場で気づけます。</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>reliability と validity を取りちがえる
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>reliability</strong> … もう一度測っても同じか</li>
<li><strong>validity</strong> … 測りたいものを測っているか</li>
</ul>
<p><strong>いつも同じ値が出る、ずれた体重計</strong>は reliable ですが valid ではありません（<a href="#fig-ahl412-target" class="quarto-xref">図&nbsp;2</a>）。</p>
<p>「同じ結果が出たから正しい」とは書かないでください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(4\)</span> つの test の名前を、中身なしで書く
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>test-retest</code> とだけ書いても点になりません。<strong>何をするのかを <span class="math inline">\(1\)</span> 行</strong>添えてください（<a href="#reliability-tests">第4節</a>）。</p>
<p><code>Describe</code> や <code>Explain</code> が付いていれば、なおさらです。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>質問の直し方で、選択肢を作らない
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\chi^2\)</span> にかけるなら、答えは<strong>カテゴリ</strong>でなければなりません（<a href="#variables">第3節</a>）。</p>
<p><code>How would you rate the library?</code> だけでは、まだ自由回答です。<strong>選択肢を並べる</strong>ところまで書いてください。</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>選択肢が重なっている、またはもれている
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>0–10</code>、<code>10–20</code> は <span class="math inline">\(10\)</span> がどちらか決まりません。<code>0–9</code>、<code>10–19</code> とします。</p>
<p>上の端も、<code>20 or more</code> のように<strong>開いておく</strong>必要があります（<a href="#structured">第2節</a>）。</p>
</div>
</div>
</section>
<section id="using-your-gdc-ti-nspire-cx-ii" class="level2">
<h2 class="anchored" data-anchor-id="using-your-gdc-ti-nspire-cx-ii">Using your GDC (TI-Nspire CX II)</h2>
<p>この項目で電卓が要るのは、<strong>期待度数を作るところ</strong>と、<strong>検定を走らせるところ</strong>の <span class="math inline">\(2\)</span> か所です。</p>
<section id="gdc-normcdf" class="level3">
<h3 class="anchored" data-anchor-id="gdc-normcdf">1. normal の期待度数を作る</h3>
<p>区間ごとの確率は <code>normCdf</code> で出します（<a href="../../ai-sl/04-statistics-and-probability/sl-4-9.html#area">SL 4.9</a>）。</p>
<pre><code>menu → Statistics → Distributions → Normal Cdf</code></pre>
<p><span class="math inline">\(\mu = 24\)</span>、<span class="math inline">\(\sigma = 6\)</span> として、</p>
<pre><code>normCdf(20, 24, 24, 6)        → 0.24751
normCdf(−9999, 12, 24, 6)     → 0.022750
normCdf(36, 9999, 24, 6)      → 0.022750</code></pre>
<p><span class="math inline">\(150\)</span> を掛ければ期待度数です。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span>両端は <span class="math inline">\(\pm 9999\)</span> を使ってください
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>normCdf(8, 12, 24, 6)</code> と打つと、<span class="math inline">\(8\)</span> より小さいぶんが抜けます。<strong>下端は <span class="math inline">\(-9999\)</span>、上端は <span class="math inline">\(9999\)</span></strong> と入れてください。</p>
<p><strong>検算。</strong> 期待度数を全部足して、データの個数になるかを見ます。合わなければ、両端の入れ方を間違えています。</p>
</div>
</div>
</section>
<section id="gdc-gof" class="level3">
<h3 class="anchored" data-anchor-id="gdc-gof">2. goodness of fit を走らせる</h3>
<p><a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html#gdc-gof">SL 4.11 と同じ手順</a>です。Lists &amp; Spreadsheet に <span class="math inline">\(2\)</span> 列を作ります。</p>
<ul>
<li>列 A（<code>obs</code>）… <strong>まとめたあと</strong>の観測度数 <span class="math inline">\(10, 35, 30, 31, 34, 10\)</span></li>
<li>列 B（<code>exp</code>）… <strong>まとめたあと</strong>の期待度数 <span class="math inline">\(13.68, 24.19, 37.13, 37.13, 24.19, 13.68\)</span></li>
</ul>
<pre><code>menu → Statistics → Stat Tests → χ² GOF</code></pre>
<p><code>Deg of Freedom</code> に、<strong>自分で数えた <span class="math inline">\(\nu\)</span></strong> を入れます。</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>電卓に入れるのは、まとめたあとのリストです
</div>
</div>
<div class="callout-body-container callout-body">
<p>まとめる前の <span class="math inline">\(8\)</span> 個を入れてしまうと、<strong><span class="math inline">\(\chi^2\)</span> の値も自由度も変わります</strong>（<a href="#tbl-ahl412-dfcompare" class="quarto-xref">表&nbsp;17</a>）。</p>
<p>紙の上でまとめてから、<strong>その <span class="math inline">\(6\)</span> 個だけ</strong>を打ちこんでください。</p>
</div>
</div>
</section>
<section id="gdc-onevar" class="level3">
<h3 class="anchored" data-anchor-id="gdc-onevar">3. 平均と標準偏差を、表から出す</h3>
<p><a href="#exm-ahl412-normal" class="quarto-xref">例&nbsp;4</a> のように階級と度数で与えられたときは、One-Variable Statistics を使います（<a href="../../ai-sl/04-statistics-and-probability/sl-4-3.html#grouped-mean">SL 4.3</a>）。</p>
<ul>
<li>列 A に <strong>mid-interval value</strong>（<span class="math inline">\(10, 14, 18, 22, 26, 30, 34, 38\)</span>）</li>
<li>列 B に <strong>frequency</strong>（<span class="math inline">\(3, 7, 35, 30, 31, 34, 6, 4\)</span>）</li>
</ul>
<pre><code>menu → Statistics → Stat Calculations → One-Variable Statistics</code></pre>
<p><code>Frequency List</code> に列 B を指定するのを忘れないでください。<span class="math inline">\(\bar{x} = 24\)</span>、<span class="math inline">\(\sigma_x = 6\)</span> が返ります。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>使うのは <span class="math inline">\(\sigma_x\)</span> のほうです
</div>
</div>
<div class="callout-body-container callout-body">
<p>出力には <span class="math inline">\(s_x\)</span> と <span class="math inline">\(\sigma_x\)</span> が並びます。当てはめるモデルの <span class="math inline">\(\sigma\)</span> は、<strong>データそのものの標準偏差</strong>から決めるので、<strong><span class="math inline">\(\sigma_x\)</span></strong> を読みます（<a href="../../ai-sl/04-statistics-and-probability/sl-4-3.html#grouped-mean">SL 4.3</a>）。</p>
<p><strong>そして、この <span class="math inline">\(2\)</span> つを電卓から読んだ時点で、<span class="math inline">\(q = 2\)</span> が確定します。</strong></p>
</div>
</div>
</section>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>各問題に、折りたたみが3つ付いています。<strong>日本語訳</strong>、<strong>解答例</strong>（答案用紙に書くべきこと。英語です）、<strong>解説</strong>（なぜそうなるか。日本語です）。</p>
<p>まず自分で解いて、次に解答例と見くらべてください。<strong>解説は、合わなかったときだけ開けば十分です。</strong></p>
</div>
</div>
</div>
<div class="exercise-block">
<p><span class="ex-no">1</span> <span class="q-en">A shop owner writes the following question for a customer survey.</span></p>
<blockquote class="blockquote">
<p><em>How much do you usually spend here?</em></p>
</blockquote>
<p><strong>(a)</strong> <span class="q-en">Explain why this question is not precise.</span></p>
<p><strong>(b)</strong> <span class="q-en">Write an improved version with four answer choices.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある店主が、客への調査のために次の質問を書きました。</p>
<blockquote class="blockquote">
<p><em>How much do you usually spend here?</em></p>
<p>（ここでふだんいくら使いますか。）</p>
</blockquote>
<p><strong>(a)</strong> この質問が precise でない理由を説明しなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(4\)</span> つの選択肢を付けた、改善した質問を書きなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>“Usually” is not defined: it could mean each visit, each week or each month, so different customers will answer about different things and their answers cannot be compared.</em></p>
<p><strong>(b)</strong> <em>How much did you spend here today? Under $10 / $10 to under $20 / $20 to under $30 / $30 or more.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <code>usually</code> と <code>how much</code> の両方があいまいです（<a href="#precise">第2節</a>）。<span class="math inline">\(1\)</span> 回あたりなのか、<span class="math inline">\(1\)</span> か月あたりなのかが決まっていません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>“Usually” does not say over what period, so one customer may answer for a single visit and another for a whole month. The answers would not be comparable.</em></p>
</div>
<p><strong>(b)</strong> 直すところは <span class="math inline">\(2\)</span> つです。<strong>期間を決める</strong>（<code>today</code>）と、<strong>選択肢を出す</strong>（<a href="#structured">第2節</a>）。</p>
<p>選択肢は、<strong>重ならず、もれがない</strong>ようにします。<code>Under \$10</code>、<code>\$10 to under \$20</code>、<code>\$20 to under \$30</code>、<code>\$30 or more</code> なら、どの金額もちょうど <span class="math inline">\(1\)</span> か所に入ります。</p>
<p><strong>金額は整数とはかぎりません。</strong> <code>\$10–\$19</code>、<code>\$20–\$29</code> と書くと、<code>\$19.50</code> の人がどこにも入りません。<strong>連続な量では「◯以上、△未満」の形</strong>にしてください。</p>
<p>いちばん上を <code>\$30 or more</code> と開いておくのも要点です。<code>\$30 to under \$40</code> で止めると、<span class="math inline">\(40\)</span> ドル使った人が入れません。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">2</span> <span class="q-en">A researcher wants to know whether students at a large school prefer to study in the library or at home. She stands outside the library at lunchtime and asks the first <span class="math inline">\(50\)</span> students who come out.</span></p>
<p><strong>(a)</strong> <span class="q-en">State the sampling technique she has used.</span></p>
<p><strong>(b)</strong> <span class="q-en">Explain why this method will produce biased data for her question.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある研究者が、大きな学校の生徒が図書館で勉強するのが好きか、家で勉強するのが好きかを知りたいと考えています。彼女は昼休みに図書館の外に立ち、出てきた最初の <span class="math inline">\(50\)</span> 人の生徒に質問します。</p>
<p><strong>(a)</strong> 彼女が使った標本の取り方を述べなさい。</p>
<p><strong>(b)</strong> この方法が、彼女の問いに対してかたよったデータを生む理由を説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-44-contents" aria-controls="callout-44" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-44" class="callout-44-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Convenience sampling.</em></p>
<p><strong>(b)</strong> <em>Everyone she asks has just been in the library, so students who prefer to study at home are much less likely to be included. The sample is not representative of all students at the school, and the proportion preferring the library will be overestimated.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> ここは <a href="../../ai-sl/04-statistics-and-probability/sl-4-1.html#sampling-methods">SL 4.1</a> の復習です。「手近な人に聞く」なので <strong>convenience sampling</strong> です。</p>
<p><strong>(b)</strong> ここが、この項目の考え方です。<strong>調べたい問いと、標本の取り方がかみ合っていません。</strong></p>
<p>図書館から出てきた人は、<strong>すでに図書館を使うと決めた人</strong>です。家で勉強する生徒は、そもそも図書館の外を通りません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>All the students asked have just used the library, so students who prefer to study at home are unlikely to be in the sample. The sample is not representative, and the proportion who prefer the library will be too high.</em></p>
</div>
<p><code>Explain why</code> なので、<strong>「かたよっている」だけでは足りません。</strong> どちらの向きにかたよるか（図書館派が多く出る）まで書いてください。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">3</span> <span class="q-en">A school wants to check the reliability of a new reading test.</span></p>
<p><strong>(a)</strong> <span class="q-en">Describe the parallel forms method.</span></p>
<p><strong>(b)</strong> <span class="q-en">Give one advantage of using parallel forms rather than test-retest.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある学校が、新しい読解テストの reliability を確かめたいと考えています。</p>
<p><strong>(a)</strong> parallel forms の方法を説明しなさい。</p>
<p><strong>(b)</strong> test-retest ではなく parallel forms を使うことの利点を <span class="math inline">\(1\)</span> つ挙げなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-46-contents" aria-controls="callout-46" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-46" class="callout-46-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Write two versions of the test that cover the same content and are of the same difficulty. Give both versions to the same students, and compare the two sets of scores. If they agree closely, the test is reliable.</em></p>
<p><strong>(b)</strong> <em>The students see different questions, so they cannot simply remember their earlier answers; this problem does affect the test-retest method.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> parallel forms は「<strong>同じ内容の別の問題</strong>を <span class="math inline">\(2\)</span> 版作って、両方受けてもらう」でした（<a href="#reliability-tests">第4節</a>）。</p>
<p><strong>「同じ内容・同じ難しさ」</strong>という条件を落とさないでください。難しさが違えば、結果が違っても reliability を測ったことになりません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Write two versions of the test that cover the same content and are of the same difficulty. Give both versions to the same students and compare the two sets of scores. If the two sets agree closely, the test is reliable.</em></p>
</div>
<p><strong>(b)</strong> test-retest の弱点は、<strong><span class="math inline">\(2\)</span> 回目に前の答えを覚えている</strong>ことでした。別の問題ならそれが起きません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>With parallel forms the students answer different questions, so their second set of scores cannot be improved simply by remembering their answers from the first test.</em></p>
</div>
<p>「<span class="math inline">\(1\)</span> つ挙げなさい」なので、<span class="math inline">\(1\)</span> つで足ります。<strong>その <span class="math inline">\(1\)</span> つを、理由まで書いてください。</strong></p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">4</span> <span class="q-en">A driving school claims that its written test measures how safely a person will drive.</span></p>
<p><strong>(a)</strong> <span class="q-en">State how criterion-related validity could be investigated for this test.</span></p>
<p><strong>(b)</strong> <span class="q-en">The written test contains questions only about road signs. Explain what this suggests about the content validity of the test.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある自動車教習所は、その筆記試験が「その人がどれだけ安全に運転するか」を測っていると主張しています。</p>
<p><strong>(a)</strong> このテストについて criterion-related validity をどう調べられるかを述べなさい。</p>
<p><strong>(b)</strong> 筆記試験には道路標識についての問題しか入っていません。これがこのテストの content validity について何を示すかを説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-48-contents" aria-controls="callout-48" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-48" class="callout-48-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Compare the written test scores with an accepted measure of safe driving, such as the number of accidents each driver has in the following year, or an examiner’s score from a practical driving test. Close agreement would support criterion-related validity.</em></p>
<p><strong>(b)</strong> <em>The content validity is low. Safe driving also involves speed control, awareness of other road users and reacting to hazards, but the test covers only road signs, so it does not cover the whole of what it claims to measure.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-49-contents" aria-controls="callout-49" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-49" class="callout-49-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> criterion-related は「<strong>すでに信用されている別のものさしと比べる</strong>」でした（<a href="#validity-tests">第4節</a>）。</p>
<p>このテストが測ろうとしているのは「安全な運転」なので、比べる相手も<strong>安全な運転を測っているもの</strong>でなければなりません。実技試験の点数や、その後の事故件数がそれにあたります。</p>
<p><strong>筆記試験どうしを比べても意味がありません。</strong> 比べる相手を何にするかが、この設問の中身です。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Compare the written test scores with an accepted measure of safe driving, such as an examiner’s score from a practical driving test, or the number of accidents each driver has in the following year. Close agreement would support criterion-related validity.</em></p>
</div>
<p><strong>(b)</strong> 標識だけでは、<strong>測りたいものの一部しかおおっていません</strong>（<a href="#validity-tests">第4節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Safe driving involves much more than knowing road signs, so a test made only of road-sign questions does not cover the whole of what it claims to measure. Its content validity is low.</em></p>
</div>
<p><strong>「reliable ではない」と書かないでください。</strong> 何度受けても同じ点が出るなら、このテストは reliable です。問題は validity です。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">5</span> <span class="q-en">A questionnaire records, for each student: name, age in years, class, number of hours of sleep last night, favourite colour, distance from home to school, and score in a concentration test.</span></p>
<p><span class="q-en">A researcher wants to test whether the number of hours of sleep is independent of the score in the concentration test.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write down the two variables that should be selected.</span></p>
<p><strong>(b)</strong> <span class="q-en">Explain why these two variables must be put into classes before a <span class="math inline">\(\chi^2\)</span> test for independence can be carried out.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>あるアンケートは、生徒ごとに次の項目を記録しています。氏名、年齢（歳）、クラス、昨夜の睡眠時間、好きな色、家から学校までの距離、集中力テストの得点。</p>
<p>研究者は、睡眠時間が集中力テストの得点と独立かどうかを検定したいと考えています。</p>
<p><strong>(a)</strong> 選ぶべき <span class="math inline">\(2\)</span> つの変数を書きなさい。</p>
<p><strong>(b)</strong> <span class="math inline">\(\chi^2\)</span> の独立性の検定を行う前に、この <span class="math inline">\(2\)</span> つの変数を階級に分けなければならない理由を説明しなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-50-contents" aria-controls="callout-50" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-50" class="callout-50-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>The number of hours of sleep last night, and the score in the concentration test.</em></p>
<p><strong>(b)</strong> <em>Both variables are numerical, so almost every student would have a different value and each cell of the table would contain only one or two students. A <span class="math inline">\(\chi^2\)</span> test needs frequencies in categories, with expected frequencies greater than <span class="math inline">\(5\)</span>, so the values must first be grouped into classes.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-51-contents" aria-controls="callout-51" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-51" class="callout-51-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 立てた問いに<strong>直接かかわる</strong>変数だけを選びます（<a href="#variables">第3節</a>）。名前・クラス・好きな色・距離・年齢は、この問いには関係しません。</p>
<p><strong>「関係がありそうだから全部入れる」ではありません。</strong></p>
<p><strong>(b)</strong> ここがこの設問の中身です。<span class="math inline">\(\chi^2\)</span> の表に入るのは<strong>度数</strong>でした。</p>
<p>睡眠時間を <span class="math inline">\(6.5\)</span> 時間、<span class="math inline">\(7.25\)</span> 時間……とそのまま使うと、<strong>ほとんどの生徒が別のマスに入ってしまいます。</strong> <span class="math inline">\(1\)</span> マスに <span class="math inline">\(1\)</span> 人ずつでは、期待度数が <span class="math inline">\(5\)</span> を超えません（<a href="#five">第5節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Both variables are numerical, so nearly every student would fall in a different cell and the expected frequencies would be far below <span class="math inline">\(5\)</span>. Grouping the values into classes gives cells with enough students for the test to be valid.</em></p>
</div>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">6</span> <span class="q-en">In a <span class="math inline">\(\chi^2\)</span> goodness of fit test with <span class="math inline">\(80\)</span> observations, the expected frequencies for seven classes are</span></p>
<div id="tbl-ahl412-ex6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-ex6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;18: Expected frequencies for seven classes
</figcaption>
<div aria-describedby="tbl-ahl412-ex6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>class</th>
<th>A</th>
<th>B</th>
<th>C</th>
<th>D</th>
<th>E</th>
<th>F</th>
<th>G</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(E\)</span></td>
<td><span class="math inline">\(2.4\)</span></td>
<td><span class="math inline">\(9.6\)</span></td>
<td><span class="math inline">\(21.0\)</span></td>
<td><span class="math inline">\(24.8\)</span></td>
<td><span class="math inline">\(14.2\)</span></td>
<td><span class="math inline">\(4.8\)</span></td>
<td><span class="math inline">\(3.2\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>(a)</strong> <span class="q-en">State which classes must be combined, and give a reason.</span></p>
<p><strong>(b)</strong> <span class="q-en">Write down the number of classes used in the test.</span></p>
<p><strong>(c)</strong> <span class="q-en">The model has one parameter estimated from the data. Find the number of degrees of freedom.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p><span class="math inline">\(80\)</span> 個の観測値による <span class="math inline">\(\chi^2\)</span> 適合度検定で、<span class="math inline">\(7\)</span> つの階級の期待度数が上のとおりです。</p>
<p><strong>(a)</strong> まとめなければならない階級を述べ、理由を書きなさい。</p>
<p><strong>(b)</strong> 検定に使う階級の数を書きなさい。</p>
<p><strong>(c)</strong> このモデルでは、データから推定した母数が <span class="math inline">\(1\)</span> つあります。自由度を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-52-contents" aria-controls="callout-52" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-52" class="callout-52-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>Combine A with B, and combine F with G. Each of A, F and G has an expected frequency less than <span class="math inline">\(5\)</span>.</em></p>
<p><span class="math display">\[
2.4 + 9.6 = 12.0, \qquad 4.8 + 3.2 = 8.0
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(5\)</span></p>
<p><strong>(c)</strong> <span class="math display">\[
\nu = 5 - 1 - 1 = 3
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-53-contents" aria-controls="callout-53" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-53" class="callout-53-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(5\)</span> より大きくないのは A（<span class="math inline">\(2.4\)</span>）、F（<span class="math inline">\(4.8\)</span>）、G（<span class="math inline">\(3.2\)</span>）の <span class="math inline">\(3\)</span> つです。</p>
<ul>
<li>A は端なので、隣の B とまとめます。<span class="math inline">\(2.4 + 9.6 = 12.0\)</span> ✓</li>
<li>F と G は<strong>隣どうし</strong>なので、この <span class="math inline">\(2\)</span> つでまとめます。<span class="math inline">\(4.8 + 3.2 = 8.0\)</span> ✓</li>
</ul>
<p><strong>F を E とまとめる必要はありません。</strong> F と G をまとめただけで <span class="math inline">\(5\)</span> を超えるからです。<strong>必要な分だけまとめる</strong>のが原則です。</p>
<p><strong>検算。</strong> 新しい期待度数は <span class="math inline">\(12.0,\ 21.0,\ 24.8,\ 14.2,\ 8.0\)</span>。合計は <span class="math inline">\(80\)</span> ✓</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Combine A with B, and combine F with G. A, F and G each have an expected frequency less than <span class="math inline">\(5\)</span>, and every class used in a <span class="math inline">\(\chi^2\)</span> test must have an expected frequency greater than <span class="math inline">\(5\)</span>.</em></p>
</div>
<p><strong>(b)</strong> <span class="math inline">\(7\)</span> つが <span class="math inline">\(5\)</span> つになりました。</p>
<p><strong>(c)</strong> <a href="#eq-ahl412-df" class="quarto-xref">式&nbsp;1</a> に <span class="math inline">\(k = 5\)</span>、<span class="math inline">\(q = 1\)</span> を入れます。</p>
<p><span class="math display">\[
\nu = 5 - 1 - 1 = 3
\]</span></p>
<p><strong><span class="math inline">\(k\)</span> は「まとめたあと」の数</strong>です（<a href="#df">第6節</a>）。<span class="math inline">\(7\)</span> を使うと <span class="math inline">\(\nu = 5\)</span> になり、<span class="math inline">\(p\)</span>-value が変わります。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">7</span> <span class="q-en">For each of the following <span class="math inline">\(\chi^2\)</span> tests, write down the number of degrees of freedom.</span></p>
<p><strong>(a)</strong> <span class="q-en">A goodness of fit test with <span class="math inline">\(6\)</span> classes, testing whether a die is fair.</span></p>
<p><strong>(b)</strong> <span class="q-en">A goodness of fit test with <span class="math inline">\(8\)</span> classes reduced to <span class="math inline">\(5\)</span> after combining, fitting a normal distribution whose mean and standard deviation are calculated from the data.</span></p>
<p><strong>(c)</strong> <span class="q-en">A goodness of fit test with <span class="math inline">\(7\)</span> classes reduced to <span class="math inline">\(6\)</span> after combining, fitting a Poisson distribution whose mean is calculated from the data.</span></p>
<p><strong>(d)</strong> <span class="q-en">A test for independence on a <span class="math inline">\(3 \times 4\)</span> contingency table.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>次のそれぞれの <span class="math inline">\(\chi^2\)</span> 検定について、自由度を書きなさい。</p>
<p><strong>(a)</strong> <span class="math inline">\(6\)</span> つの階級による適合度検定で、さいころが公平かどうかを調べるもの。</p>
<p><strong>(b)</strong> <span class="math inline">\(8\)</span> つの階級がまとめたあと <span class="math inline">\(5\)</span> つになった適合度検定で、平均と標準偏差をデータから計算した正規分布を当てはめるもの。</p>
<p><strong>(c)</strong> <span class="math inline">\(7\)</span> つの階級がまとめたあと <span class="math inline">\(6\)</span> つになった適合度検定で、平均をデータから計算したポアソン分布を当てはめるもの。</p>
<p><strong>(d)</strong> <span class="math inline">\(3 \times 4\)</span> の分割表による独立性の検定。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-54-contents" aria-controls="callout-54" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-54" class="callout-54-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(\nu = 6 - 1 = 5\)</span></p>
<p><strong>(b)</strong> <span class="math inline">\(\nu = 5 - 1 - 2 = 2\)</span></p>
<p><strong>(c)</strong> <span class="math inline">\(\nu = 6 - 1 - 1 = 4\)</span></p>
<p><strong>(d)</strong> <span class="math inline">\(\nu = (3-1)(4-1) = 6\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-55-contents" aria-controls="callout-55" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-55" class="callout-55-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 「公平」なら確率はどれも <span class="math inline">\(\frac{1}{6}\)</span> と<strong>決まっています。</strong> データから推定するものはありません。<span class="math inline">\(q = 0\)</span> です。</p>
<p><strong>(b)</strong> <span class="math inline">\(k = 5\)</span>（まとめたあと）、<span class="math inline">\(q = 2\)</span>（<span class="math inline">\(\mu\)</span> と <span class="math inline">\(\sigma\)</span>）。</p>
<p><strong>(c)</strong> <span class="math inline">\(k = 6\)</span>（まとめたあと）、<span class="math inline">\(q = 1\)</span>。Poisson の母数は <span class="math inline">\(m\)</span> の <span class="math inline">\(1\)</span> つだけです（公式集では <span class="math inline">\(X \sim \mathrm{Po}(m)\)</span> と書かれます。<strong>AHL 4.17</strong>）。</p>
<p><strong>(d)</strong> independence は <a href="#eq-ahl412-df" class="quarto-xref">式&nbsp;1</a> を<strong>使いません</strong>（<a href="#df">第6節</a>）。行が <span class="math inline">\(3\)</span>、列が <span class="math inline">\(4\)</span> なので <span class="math inline">\((3-1)(4-1) = 6\)</span> です。</p>
<p><strong>(a) と (d) は SL のままです。</strong> 変わるのは (b) と (c)、つまり<strong>データから母数を推定したとき</strong>だけです。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">8</span> <span class="q-en">A factory takes <span class="math inline">\(200\)</span> samples of four items each and records the number of defective items in each sample.</span></p>
<div id="tbl-ahl412-ex8" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ahl412-ex8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;19: Defective items in <span class="math inline">\(200\)</span> samples
</figcaption>
<div aria-describedby="tbl-ahl412-ex8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>number defective</th>
<th><span class="math inline">\(0\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3\)</span></th>
<th><span class="math inline">\(4\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>frequency</td>
<td><span class="math inline">\(81\)</span></td>
<td><span class="math inline">\(88\)</span></td>
<td><span class="math inline">\(26\)</span></td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="q-en">It is proposed that the number of defective items follows a binomial distribution <span class="math inline">\(B(4,\ p)\)</span>.</span></p>
<p><strong>(a)</strong> <span class="q-en">Show that the value of <span class="math inline">\(p\)</span> estimated from the data is <span class="math inline">\(0.195\)</span>.</span></p>
<p><strong>(b)</strong> <span class="q-en">The expected frequencies under this model are <span class="math inline">\(83.99\)</span>, <span class="math inline">\(81.38\)</span>, <span class="math inline">\(29.57\)</span>, <span class="math inline">\(4.775\)</span> and <span class="math inline">\(0.2892\)</span>. State which classes must be combined, and give a reason.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the number of degrees of freedom.</span></p>
<p><strong>(d)</strong> <span class="q-en">Given that <span class="math inline">\(\chi^2 = 1.08\)</span>, find the <span class="math inline">\(p\)</span>-value and state the conclusion at the <span class="math inline">\(5\%\)</span> level.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある工場が、<span class="math inline">\(4\)</span> 個ずつの標本を <span class="math inline">\(200\)</span> 組取り、それぞれの組に含まれる不良品の数を記録しました。</p>
<p>表の見出しは、<code>number defective</code> が「不良品の数」、<code>frequency</code> が「度数」です。</p>
<p>不良品の数は二項分布 <span class="math inline">\(B(4,\ p)\)</span> に従うと提案されています。</p>
<p><strong>(a)</strong> データから推定した <span class="math inline">\(p\)</span> の値が <span class="math inline">\(0.195\)</span> であることを示しなさい。</p>
<p><strong>(b)</strong> このモデルのもとでの期待度数は <span class="math inline">\(83.99\)</span>、<span class="math inline">\(81.38\)</span>、<span class="math inline">\(29.57\)</span>、<span class="math inline">\(4.775\)</span>、<span class="math inline">\(0.2892\)</span> です。まとめなければならない階級を述べ、理由を書きなさい。</p>
<p><strong>(c)</strong> 自由度を求めなさい。</p>
<p><strong>(d)</strong> <span class="math inline">\(\chi^2 = 1.08\)</span> であるとき、<span class="math inline">\(p\)</span> 値を求め、<span class="math inline">\(5\%\)</span> での結論を述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-56-contents" aria-controls="callout-56" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-56" class="callout-56-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\text{total defectives} = 0(81) + 1(88) + 2(26) + 3(4) + 4(1) = 156
\]</span> <span class="math display">\[
\text{total items} = 4 \times 200 = 800
\]</span> <span class="math display">\[
p = \frac{156}{800} = 0.195
\]</span></p>
<p><strong>(b)</strong> <em>Combine “<span class="math inline">\(3\)</span>” with “<span class="math inline">\(4\)</span>”: their expected frequencies are <span class="math inline">\(4.775\)</span> and <span class="math inline">\(0.2892\)</span>, both less than <span class="math inline">\(5\)</span>. Together they give <span class="math inline">\(5.06 &gt; 5\)</span>.</em></p>
<p><strong>(c)</strong> <span class="math display">\[
\nu = 4 - 1 - 1 = 2
\]</span></p>
<p><strong>(d)</strong> <em><span class="math inline">\(p = 0.583 &gt; 0.05\)</span>, so do not reject <span class="math inline">\(H_0\)</span>. There is insufficient evidence at the <span class="math inline">\(5\%\)</span> level that the number of defective items does not follow a binomial distribution.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-57-contents" aria-controls="callout-57" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-57" class="callout-57-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(p\)</span> は「<span class="math inline">\(1\)</span> 個が不良品である確率」です。<strong>不良品の総数を、品物の総数で割ります。</strong></p>
<p><span class="math inline">\(4\)</span> 個ずつ <span class="math inline">\(200\)</span> 組なので、品物は <span class="math inline">\(800\)</span> 個。不良品は <span class="math inline">\(156\)</span> 個。</p>
<p><span class="math display">\[
p = \frac{156}{800} = 0.195
\]</span></p>
<p><strong>(b)</strong> <span class="math inline">\(5\)</span> より大きくないのは <span class="math inline">\(3\)</span>（<span class="math inline">\(4.775\)</span>）と <span class="math inline">\(4\)</span>（<span class="math inline">\(0.2892\)</span>）です。<strong>隣どうし</strong>なので、この <span class="math inline">\(2\)</span> つをまとめます。</p>
<p><span class="math display">\[
4.775 + 0.2892 = 5.06 &gt; 5 \quad ✓
\]</span></p>
<p><strong>検算。</strong> 期待度数の合計は <span class="math inline">\(83.99 + 81.38 + 29.57 + 5.06 = 200\)</span> ✓</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Combine “<span class="math inline">\(3\)</span>” with “<span class="math inline">\(4\)</span>”. Their expected frequencies, <span class="math inline">\(4.775\)</span> and <span class="math inline">\(0.2892\)</span>, are both less than <span class="math inline">\(5\)</span>; combined they give <span class="math inline">\(5.06\)</span>, which is greater than <span class="math inline">\(5\)</span>.</em></p>
</div>
<p><strong>(c)</strong> <span class="math inline">\(k = 4\)</span>（まとめたあと）、<span class="math inline">\(q = 1\)</span>（<span class="math inline">\(p\)</span> をデータから推定した）。</p>
<p><span class="math display">\[
\nu = 4 - 1 - 1 = 2
\]</span></p>
<p><strong>この <span class="math inline">\(-1\)</span> を忘れると <span class="math inline">\(\nu = 3\)</span> になります。</strong> (a) で <span class="math inline">\(p\)</span> を計算したこと自体が、<span class="math inline">\(q = 1\)</span> の証拠です。</p>
<p><strong>(d)</strong> 電卓で <span class="math inline">\(\chi^2 = 1.08\)</span>、<span class="math inline">\(\nu = 2\)</span> の <span class="math inline">\(p\)</span>-value を出します。<span class="math inline">\(0.583\)</span> です。</p>
<p>（丸めていない <span class="math inline">\(\chi^2 = 1.0766\)</span> から出すと <span class="math inline">\(0.584\)</span> になります。<strong>問題文が <span class="math inline">\(1.08\)</span> と与えているので、<span class="math inline">\(0.583\)</span> で構いません。</strong> どちらでも結論は同じです。）</p>
<p><span class="math inline">\(p &gt; 0.05\)</span> なので reject しません。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em><span class="math inline">\(p = 0.583 &gt; 0.05\)</span>, so do not reject <span class="math inline">\(H_0\)</span>. There is insufficient evidence at the <span class="math inline">\(5\%\)</span> level that the number of defective items in a sample of four does not follow a binomial distribution.</em></p>
</div>
<p><code>accept $H_0$</code> とは書きません（<a href="../../ai-sl/04-statistics-and-probability/sl-4-11.html">SL 4.11</a>）。<strong>「合っていると分かった」ではなく「合っていないとは言えない」</strong>です。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">9</span> <span class="q-en">A student has <span class="math inline">\(30\)</span> measurements of a continuous variable and wants to carry out a <span class="math inline">\(\chi^2\)</span> goodness of fit test. She proposes to use <span class="math inline">\(10\)</span> classes, chosen so that each class would have the same expected frequency.</span></p>
<p><strong>(a)</strong> <span class="q-en">Find the expected frequency in each class under her proposal.</span></p>
<p><strong>(b)</strong> <span class="q-en">Explain why her choice of categorisation is not appropriate.</span></p>
<p><strong>(c)</strong> <span class="q-en">Find the greatest number of equally likely classes she could use.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある生徒が、連続な変量の測定値を <span class="math inline">\(30\)</span> 個もっていて、<span class="math inline">\(\chi^2\)</span> 適合度検定を行いたいと考えています。彼女は、どの階級の期待度数も等しくなるように選んだ <span class="math inline">\(10\)</span> の階級を使おうとしています。</p>
<p><strong>(a)</strong> この案での各階級の期待度数を求めなさい。</p>
<p><strong>(b)</strong> 彼女の階級の選び方が適切でない理由を説明しなさい。</p>
<p><strong>(c)</strong> 期待度数が等しくなるように選べる階級の数の最大値を求めなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-58-contents" aria-controls="callout-58" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-58" class="callout-58-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math display">\[
\frac{30}{10} = 3
\]</span></p>
<p><strong>(b)</strong> <em>Each expected frequency would be <span class="math inline">\(3\)</span>, which is less than <span class="math inline">\(5\)</span>. Every class in a <span class="math inline">\(\chi^2\)</span> test must have an expected frequency greater than <span class="math inline">\(5\)</span>, so this categorisation is not appropriate.</em></p>
<p><strong>(c)</strong> <span class="math display">\[
\frac{30}{k} &gt; 5 \quad \Rightarrow \quad k &lt; 6
\]</span></p>
<p><em>So the greatest number of equally likely classes is <span class="math inline">\(5\)</span>.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-60-contents" aria-controls="callout-60" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-60" class="callout-60-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 期待度数が等しいので、全体を階級の数で割るだけです。<span class="math inline">\(\dfrac{30}{10} = 3\)</span>。</p>
<p><strong>(b)</strong> <span class="math inline">\(3 &lt; 5\)</span> です（<a href="#five">第5節</a>）。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>With <span class="math inline">\(10\)</span> equally likely classes each expected frequency is <span class="math inline">\(30 \div 10 = 3\)</span>, which is less than <span class="math inline">\(5\)</span>. A <span class="math inline">\(\chi^2\)</span> test requires every expected frequency to be greater than <span class="math inline">\(5\)</span>, so <span class="math inline">\(10\)</span> classes is too many for only <span class="math inline">\(30\)</span> measurements.</em></p>
</div>
<p><strong>(c)</strong> 条件は <span class="math inline">\(\dfrac{30}{k} &gt; 5\)</span>、つまり <span class="math inline">\(k &lt; 6\)</span> です。<span class="math inline">\(k\)</span> は整数なので、<strong>いちばん大きいのは <span class="math inline">\(5\)</span></strong> です。</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">警告</span><span class="math inline">\(k = 6\)</span> は使えません
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\dfrac{30}{6} = 5\)</span> ちょうどです。シラバスの条件は <code>greater than 5</code> なので、<strong>ちょうど <span class="math inline">\(5\)</span> では足りません</strong>。</p>
<p>不等号が <span class="math inline">\(&gt;\)</span> か <span class="math inline">\(\ge\)</span> かで、答えが <span class="math inline">\(5\)</span> か <span class="math inline">\(6\)</span> かに分かれます。<strong>問題文とシラバスの言葉を、そのまま読んでください。</strong></p>
</div>
</div>
<p><strong>データが少ないほど、使える階級は少なくなります。</strong> <span class="math inline">\(\chi^2\)</span> で細かく区切れないのは、そのためです。</p>
</div>
</div>
</div>
<div class="ex-sep">

</div>
<p><span class="ex-no">10</span> <span class="q-en">A student plans an Exploration on whether the time secondary students spend on social media is independent of their year group. She will collect data with an online questionnaire.</span></p>
<p><strong>(a)</strong> <span class="q-en">Write a suitable structured question for measuring the time spent on social media.</span></p>
<p><strong>(b)</strong> <span class="q-en">Explain how she could check the reliability of her questionnaire.</span></p>
<p><strong>(c)</strong> <span class="q-en">She receives <span class="math inline">\(45\)</span> responses and plans a <span class="math inline">\(3 \times 5\)</span> contingency table. Comment on whether this table is appropriate.</span></p>
<details class="jp-trans">
<summary>
日本語訳
</summary>
<p>ある生徒が、中高生がソーシャルメディアに費やす時間が学年と独立かどうかについて Exploration を計画しています。彼女はオンラインのアンケートでデータを集めます。</p>
<p><strong>(a)</strong> ソーシャルメディアに費やす時間を測るのに適した、選択式の質問を書きなさい。</p>
<p><strong>(b)</strong> アンケートの reliability をどう確かめられるかを説明しなさい。</p>
<p><strong>(c)</strong> 回答が <span class="math inline">\(45\)</span> 件集まり、彼女は <span class="math inline">\(3 \times 5\)</span> の分割表を作ろうとしています。この表が適切かどうかについて述べなさい。</p>
</details>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-61-contents" aria-controls="callout-61" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ノート</span>解答例（答案用紙に書くこと）
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-61" class="callout-61-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <em>How many hours did you spend on social media yesterday? Under <span class="math inline">\(1\)</span> / <span class="math inline">\(1\)</span> to under <span class="math inline">\(2\)</span> / <span class="math inline">\(2\)</span> to under <span class="math inline">\(4\)</span> / <span class="math inline">\(4\)</span> or more.</em></p>
<p><strong>(b)</strong> <em>Use test-retest: ask the same students to complete the same questionnaire again after a short interval, and compare the two sets of answers. If most students give the same answers both times, the questionnaire is reliable.</em></p>
<p><strong>(c)</strong> <em>A <span class="math inline">\(3 \times 5\)</span> table has <span class="math inline">\(15\)</span> cells, so with <span class="math inline">\(45\)</span> responses the average frequency per cell is only <span class="math inline">\(3\)</span>. Many expected frequencies would be less than <span class="math inline">\(5\)</span>, so the table is not appropriate. She should use fewer categories, for example a <span class="math inline">\(3 \times 2\)</span> table (<span class="math inline">\(45 \div 6 = 7.5\)</span> per cell), or collect more responses.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-62-contents" aria-controls="callout-62" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">ヒント</span>解説
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-62" class="callout-62-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> 直すところは <span class="math inline">\(3\)</span> つでした（<a href="#questions">第2節</a>）。<strong>期間を決める</strong>（<code>yesterday</code>）、<strong>選択肢を出す</strong>、<strong>選択肢を重ねず、もれなく</strong>。</p>
<p>いちばん上を <code>4 or more</code> と開いておくのを忘れないでください。</p>
<p><strong>(b)</strong> reliability を確かめる方法は <span class="math inline">\(2\)</span> つでした（<a href="#reliability-tests">第4節</a>）。アンケートなら test-retest が自然です。<strong>parallel forms（別の版を作る）でも構いません。</strong> 選んだほうを説明してください。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>Use a test-retest method: ask the same students to complete the same questionnaire again after a short interval, and compare the two sets of answers. If most students give the same answers both times, the questionnaire is reliable.</em></p>
</div>
<p><strong>(c)</strong> ここがこの問題の中心です。</p>
<p><span class="math display">\[
3 \times 5 = 15 \ \text{マス}, \qquad \frac{45}{15} = 3
\]</span></p>
<p><span class="math inline">\(1\)</span> マスあたり平均 <span class="math inline">\(3\)</span> です。<strong>期待度数が <span class="math inline">\(5\)</span> を超えるマスは、ほとんどありません</strong>（<a href="#five">第5節</a>）。</p>
<p><span class="math inline">\(3 \times 3\)</span> でも足りません。<span class="math inline">\(\dfrac{45}{9} = 5\)</span> <strong>ちょうど</strong>で、<code>greater than 5</code> をみたさないからです（演習 <span class="math inline">\(9\)</span> と同じところです）。時間帯を <span class="math inline">\(2\)</span> つに減らして <span class="math inline">\(3 \times 2\)</span> にすれば、<span class="math inline">\(\dfrac{45}{6} = 7.5\)</span> になります。</p>
<div class="model-answer">
<p><strong>試験ではこう書く</strong></p>
<p><em>The <span class="math inline">\(3 \times 5\)</span> table has <span class="math inline">\(15\)</span> cells but only <span class="math inline">\(45\)</span> responses, so the average frequency per cell is <span class="math inline">\(3\)</span>. Many expected frequencies would be below <span class="math inline">\(5\)</span> and the <span class="math inline">\(\chi^2\)</span> test would not be valid. She should either combine categories to make a smaller table, such as <span class="math inline">\(3 \times 2\)</span> with only two time bands, giving <span class="math inline">\(45 \div 6 = 7.5\)</span> per cell, or collect more responses.</em></p>
</div>
<p><code>Comment on</code> なので、<strong>「適切でない」だけでは足りません。</strong> 数で示し、<strong>どうすればよいか</strong>まで書いてください（<a href="#variables">第3節</a>）。</p>
</div>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<!--
  Cookie 同意バナーの本文を差しかえるスクリプト。

  Quarto の cookie-consent は termsfeed のライブラリを使っていて、
  lang: ja のおかげで表示は日本語になります。ただし既定の本文が

    「…パーソナライズされたコンテンツやターゲット広告を表示するため…」

  となっていて、広告を出さないこのサイトの実態と合いません。
  ライブラリ側に文面を差しかえる設定が無いので、バナーが出たあとに
  #cc-nb-text の中身だけを書きかえています。

  ★ 文面を変えるときは、下の NB の中身だけを直してください。
  ★ 読み込みは _quarto.yml の format.html.include-after-body です。
-->
<script>
(function () {
  var NB = "このサイトでは、どのページがどれくらい読まれているかを知るために、"
         + "Google アナリティクスの Cookie を使っています。"
         + "広告の配信や、個人を特定する目的には使いません。";

  function fix() {
    var el = document.getElementById("cc-nb-text");
    if (!el) { return false; }
    if (el.textContent !== NB) { el.textContent = NB; }
    return true;
  }

  // バナーはページ読み込みのあとに差し込まれるので、出てくるまで待つ。
  if (!fix()) {
    var mo = new MutationObserver(function () { if (fix()) { mo.disconnect(); } });
    mo.observe(document.body, { childList: true, subtree: true });
    setTimeout(function () { mo.disconnect(); }, 10000);
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "コピーしました");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "コピーしました");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/edusalonself\.github\.io\/ib-math-ai-sl-jp\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../ai-hl/03-geometry-and-trigonometry/ahl-3-16.html" class="pagination-link" aria-label="AHL 3.16 — Tree and cycle algorithms">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">AHL 3.16 — Tree and cycle algorithms</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../ai-hl/04-statistics-and-probability/ahl-4-13.html" class="pagination-link" aria-label="AHL 4.13 — Non-linear regression">
        <span class="nav-page-text">AHL 4.13 — Non-linear regression</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 学習サロン SELF</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.selfsg.com/">
<p>学習サロン SELF</p>
</a>
  </li>  
</ul>
    <div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie の設定</a></div></div>
    <div class="nav-footer-right">
<p>IB（国際バカロレア機構）とは関係のない独立した教材です</p>
</div>
  </div>
</footer>




</body></html>